### ISSUE TITLE
Printing or storing intermediate values inside a cost function produces ArrayBox objects

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1001]
#### Issue description

When using with the `step_and_cost` function to optimize a cost function that involves computing probabilities with `qml.probs`, the output values of the QNode are stored as `ArrayBox` objects.

```python
import pennylane as qml
from pennylane import numpy as np

wires = 6
dev = qml.device("default.qubit", wires=wires, shots=1000, analytic=False)

def global_cost_simple(rotations):
    for i in range(wires):
        qml.RX(rotations[0][i], wires=i)
    return qml.probs(wires=range(wires))

global_circuit = qml.QNode(global_cost_simple, dev)

def cost_global(rotations):
    probs = global_circuit(rotations)
    print(probs)   # <----- Outputs Autograd ArrayBox objects
    return 1 - probs[0]

params_global = np.array([[3.] * len(range(wires))])
opt = qml.GradientDescentOptimizer(stepsize=0.2)
steps = 5

for i in range(steps):
    params_global, c = opt.step_and_cost(cost_global, params_global)
```

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:*
We can store the values that are not `ArrayBox` objects.

* *Actual behavior:* (What actually happens)
We are storing `ArrayBox` objects.

* *Reproduces how often:*
Everytime.

* *System information:*
```
Name: PennyLane
Version: 0.14.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/antalszava/xanadu/pennylane
Requires: numpy, scipy, networkx, autograd, toml, appdirs, semantic-version
Required-by: PennyLane-Orquestra
Platform info:           Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.10
Python version:          3.8.5
Numpy version:           1.19.2
Scipy version:           1.4.1
Installed devices:
- orquestra.forest (PennyLane-Orquestra-0.13.1)
- orquestra.ibmq (PennyLane-Orquestra-0.13.1)
- orquestra.qiskit (PennyLane-Orquestra-0.13.1)
- orquestra.qulacs (PennyLane-Orquestra-0.13.1)
- default.gaussian (PennyLane-0.14.0.dev0)
- default.mixed (PennyLane-0.14.0.dev0)
- default.qubit (PennyLane-0.14.0.dev0)
- default.qubit.autograd (PennyLane-0.14.0.dev0)
- default.qubit.jax (PennyLane-0.14.0.dev0)
- default.qubit.tf (PennyLane-0.14.0.dev0)
- default.tensor (PennyLane-0.14.0.dev0)
- default.tensor.tf (PennyLane-0.14.0.dev0)
```

#### Additional information
A solution can be to store the output of `dev.probability(wires=dev.wires)` (`dev` is the PennyLane device) which does involves computations using the statevector/samples without executing the QNode again.

**Comment by josh146** [comment]
@antalszava, this might be expected behaviour (unfortunately).

The new `step_and_cost` method takes advantage of the fact that when you backpropagate with Autograd via `qml.grad()`, two things happen:

* Autograd wraps the function input as `ArrayBox` objects, and passes them through the function, computing the function output.

* Autograd then reverses through the function from input to output, accumulating the gradient.

So `step_and_cost` allows you to step the parameters _and_ retrieve the cost function with minimal overhead, but we might not be able to avoid the introduction of ArrayBox objects. Let me think about this.

**Comment by josh146** [comment]
For example, consider the following pure Autograd code:

```python
import autograd
from autograd import numpy as np

from autograd.core import make_vjp as _make_vjp
from autograd.wrap_util import unary_to_nary
from autograd.extend import vspace

make_vjp = unary_to_nary(_make_vjp)


@unary_to_nary
def grad(fun, x):
    """This function is a replica of autograd.grad
    modified to also return the function output"""
    vjp, fn_output = _make_vjp(fun, x)

    if not vspace(fn_output).size == 1:
        raise TypeError(
            "Grad only applies to real scalar-output functions. "
            "Try jacobian, elementwise_grad or holomorphic_grad."
        )

    grad_value = vjp(vspace(fn_output).ones())
    return grad_value, fn_output


def function(x):
    intermediate = x ** 2
    print("This intermediate value will be an ArrayBox:", intermediate)
    return 1 - intermediate

grad_fn = grad(function, argnum=0)
grad_value, cost_value = grad_fn(0.5)

print("Gradient value is not an ArrayBox:", grad_value)
print("Function output is not an ArrayBox:", cost_value)
```

This has output:
```
This intermediate value will be an ArrayBox: Autograd ArrayBox with value 0.25
Gradient value is not an ArrayBox: -1.0
Function output is not an ArrayBox: 0.75
```

**Comment by Francesco-Benfenati** [comment]
So using `step_and_cost` I won't be able to have the probabilities as numbers, and the two possible solutions would be accessing `dev.probability(wires=dev.wires)` or splitting `step_and_cost` into `step` and `cost`, both of which would require twice the number of executions of the qnode, right? The most important thing for me would be to avoid measuring the same circuit twice, that's why I thought that I should use `step_and_cost`.

Would this be the case even with real QPUs? Because for example I think that IBMQ is outputting the probabilities of all the states as numbers, so it should be possible to print them and use them to calculate the cost without repeating the experiment.

**Comment by josh146** [comment]
Hi @Francesco-Benfenati,

> splitting `step_and_cost` into `step` and `cost`, both of which would require twice the number of executions of the qnode, right?

Yes, exactly right - `step_and_cost` computes the gradient and extracts the corresponding forward pass value at the same time. Calling `step` and `cost` separately would instead result in two executions.

> accessing `dev.probability(wires=dev.wires)`

This approach actually _doesn't_ result in an extra evaluation. The device always stores the result of the last computation, so calling `dev.probability` just extracts the last execution probabilities 🙂 

> Would this be the case even with real QPUs? Because for example I think that IBMQ is outputting the probabilities of all the states as numbers, so it should be possible to print them and use them to calculate the cost without repeating the experiment.

Unfortunately yes, the issue currently stems from how Autograd works, which is the default backend PennyLane uses for autodifferentiation. If you compute the gradient in Autograd, the cost function value is _always_ computed implicitly at the same time, and all intermediate values of the computation will be Autograd `ArrayBox` objects.

I think your solution of using `_value` is actually quite a neat one:

```python
from autograd import numpy as np

from autograd.core import make_vjp
from autograd.wrap_util import unary_to_nary
from autograd.extend import vspace


@unary_to_nary
def grad(fun, x):
    """This function is a replica of autograd.grad
    modified to also return the function output"""
    vjp, fn_output = make_vjp(fun, x)

    if not vspace(fn_output).size == 1:
        raise TypeError(
            "Grad only applies to real scalar-output functions. "
            "Try jacobian, elementwise_grad or holomorphic_grad."
        )

    grad_value = vjp(vspace(fn_output).ones())
    return grad_value, fn_output


def function(x):
    intermediate = x ** 2
    print("This intermediate value will be an ArrayBox:", intermediate)
    print("Calling ._value extracts the NumPy array:", intermediate._value)
    return 1 - intermediate

grad_fn = grad(function, argnum=0)
grad_value, cost_value = grad_fn(0.5)

print("Gradient value is not an ArrayBox:", grad_value)
print("Function output is not an ArrayBox:", cost_value)
```

This gives output

```
This intermediate value will be an ArrayBox: Autograd ArrayBox with value 0.25
Calling ._value extracts the NumPy array: 0.25
Gradient value is not an ArrayBox: -1.0
Function output is not an ArrayBox: 0.75
```

**Comment by Francesco-Benfenati** [comment]
Thank you @josh146 and @antalszava !
I'll experiment with that
