### ISSUE TITLE
Replace tape.inv() with a transform.

### ISSUE THREAD

**Issue by Thenerdstation** [PennyLaneAI/pennylane#1044]
We should replace `tape.inv()` with a transform `inv_tape = inv(tape)`. This will help our codebase be more functional.

Context: https://github.com/PennyLaneAI/pennylane/pull/1040#discussion_r564464649

**Comment by josh146** [comment]
:+1:

**Comment by josh146** [comment]
@Thenerdstation would this be relatively trivial to do now?

**Comment by josh146** [comment]
I believe this is closed via #1111

**Comment by josh146** [comment]
Nevermind, I misread the issue title!

**Comment by Thenerdstation** [comment]
I would consider this fixed by #1111
