### ISSUE TITLE
KeyError when printing Hamiltonian with a `Hermitian` term

### ISSUE THREAD

**Issue by co9olguy** [PennyLaneAI/pennylane#1068]
#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* printing a Hamiltonian should not raise any errors

* *Actual behavior:* a `KeyError` is raised when trying to print a Hamiltonian which has a term created with `qml.Hermitian`

* *Reproduces how often:* whenever I try :wink: 

* *System information:* 
```
Name: PennyLane
Version: 0.13.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/nathan/anaconda3/lib/python3.7/site-packages
Requires: numpy, networkx, semantic-version, toml, appdirs, autograd, scipy
Required-by: PennyLane-SF, PennyLane-Cirq, PennyLane-Orquestra
Platform info:           Linux-5.4.0-62-generic-x86_64-with-debian-bullseye-sid
Python version:          3.7.6
Numpy version:           1.18.1
Scipy version:           1.4.1
Installed devices:
- default.gaussian (PennyLane-0.13.0)
- default.mixed (PennyLane-0.13.0)
- default.qubit (PennyLane-0.13.0)
- default.qubit.autograd (PennyLane-0.13.0)
- default.qubit.tf (PennyLane-0.13.0)
- default.tensor (PennyLane-0.13.0)
- default.tensor.tf (PennyLane-0.13.0)
- strawberryfields.fock (PennyLane-SF-0.12.0)
- strawberryfields.gaussian (PennyLane-SF-0.12.0)
- strawberryfields.gbs (PennyLane-SF-0.12.0)
- strawberryfields.remote (PennyLane-SF-0.12.0)
- strawberryfields.tf (PennyLane-SF-0.12.0)
- cirq.mixedsimulator (PennyLane-Cirq-0.10.0.dev0)
- cirq.pasqal (PennyLane-Cirq-0.10.0.dev0)
- cirq.simulator (PennyLane-Cirq-0.10.0.dev0)
- orquestra.forest (PennyLane-Orquestra-0.13.0.dev0)
- orquestra.ibmq (PennyLane-Orquestra-0.13.0.dev0)
- orquestra.qiskit (PennyLane-Orquestra-0.13.0.dev0)
- orquestra.qulacs (PennyLane-Orquestra-0.13.0.dev0)
```

#### Source code and tracebacks

This error can be generated by duplicating the example text in the docstring of qml.Hamiltonian:
```
>>> obs_matrix = np.array([[0.5, 1.0j, 0.0, -3j],
                           [-1.0j, -1.1, 0.0, -0.1],
                           [0.0, 0.0, -0.9, 12.0],
                           [3j, -0.1, 12.0, 0.0]])
>>> obs = qml.Hermitian(obs_matrix, wires=[0, 1])
>>> H = qml.Hamiltonian((0.8, ), (obs, ))
>>> print(H)
>>> KeyError: 'Hermitian'
```

**Comment by co9olguy** [comment]
Note: I uncovered this bug when exploring the cryptic print statement output:
`(0.8) [Hermitian0'1]`. What is `0'1` supposed to mean?

**Comment by josh146** [comment]
It seems this change was introduced in another bugfix, #987

**Comment by albi3ro** [comment]
I tried this out myself, and am not getting a key error.

Can you try:

```python
OBS_MAP = {"PauliX": "X", "PauliY": "Y", "PauliZ": "Z", "Hadamard": "H", "Identity": "I"}
OBS_MAP.get("somestring","somestring")
```
and tell me if that complains?

`0'1` indicates the operation acts on the `0` and `1` wires. 

If you have suggestions for a better way to write out multiple wire labels, I would be very happy.  That choice was a "best of bad options" type of situation.

**Comment by co9olguy** [comment]
why not the same way it would be written when creating the gate? e.g., `Hermitian [0,1]`?

**Comment by albi3ro** [comment]
We wanted to generalize the OpenFermion way of printing: for example 'coeff [X1 Y2]'. 

But if we throw out that syntax for the simple gates we have more flexibility to try something like 'coeff GateName [0,1]'.

**Comment by josh146** [comment]
How about just `(0.8) [Hermitian0,1,2]`?

**Comment by josh146** [comment]
@albi3ro has there been work on fixing this bug?

**Comment by albi3ro** [comment]
I don't get a KeyError when calling the above code. As you said above, the KeyError was probably an older version pre-fix thing.

  Are we switching `0'1` to `0,1`?

**Comment by antalszava** [comment]
This is indeed solved with the latest version of PennyLane.

> How about just (0.8) [Hermitian0,1,2]?

It seems, that using a comma is more intuitive to us when extending the OpenFermion convention to Hermitian.

*Current convention*
```
  (0.8) [Z0]
+ (0.8) [Z0 Hermitian1'3 Z2]
```
*With a comma as separator*
```
  (0.8) [Z0]
+ (0.8) [Z0 Hermitian1,3 Z2]
```

Produced by
```python
obs_matrix = np.array([[0.5, 1.0j, 0.0, -3j],
                           [-1.0j, -1.1, 0.0, -0.1],
                           [0.0, 0.0, -0.9, 12.0],
                           [3j, -0.1, 12.0, 0.0]])
obs = qml.Hermitian(obs_matrix, wires=[1,3])
H = qml.Hamiltonian((0.8,0.8, ), (qml.PauliZ(0) @ obs @ qml.PauliZ(2), qml.PauliZ(0), ))
print(H)
```
> Are we switching 0'1 to 0,1?

I think it's worth doing that, yes.

**Comment by antalszava** [comment]
Opened #1465, but can close/refine if there are any objections to this change.
