### ISSUE TITLE
Gate decompositions are limited to indentation level 2

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1073]
When trying to use gates with nested decompositions of order higher than 2, the `default.qubit.autograd` device does not execute because it does not find the decomposition. Take the following dummy copies of the `RX` gate:

```python
class Copy1RX(qml.operation.Operation):
    num_params = 1
    num_wires = 1
    par_domain = "R"
    grad_method = "A"

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = [
            qml.RX(theta, wires=wires),
        ]
        return decomp_ops

class Copy2RX(qml.operation.Operation):
    num_params = 1
    num_wires = 1
    par_domain = "R"
    grad_method = "A"

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = [
            Copy1RX(theta, wires=wires),
        ]
        return decomp_ops

class Copy3RX(qml.operation.Operation):
    num_params = 1
    num_wires = 1
    par_domain = "R"
    grad_method = "A"

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = [
            Copy2RX(theta, wires=wires),
        ]
        return decomp_ops
```
A circuit containing `Copy1RX` and `Copy2RX` will work, a circuit containing `Copy3RX` will complain about `Copy1RX` not being implemented, which shows that it is a decomposition issue (as `Copy1RX` itself works).
I found the currently hardcoded `max_expansions` parameter in tape/qnode.py and changed it to 10, but unfortunately that did not resolve the issue.

**Comment by dwierichs** [comment]
Sorry, my bad! I actually failed at setting the `max_expansion` depth. So it's not a bug but maybe it would be nice to expose this parameter to the user?

**Comment by josh146** [comment]
Hi @dwierichs thanks for catching this! Definitely something that is worth exposing.

In either case though, a max expansion of 2 seems two small. Since the tape expansion is recursive, this parameter can be thought of as akin to the `max_recursion` variable that is set in Python. 

It's current value of 2 is biased because `default.qubit` supports all PL operations to within 1-2 tape expansions. In your current use-case, would 10 be a more suitable default?

**Comment by dwierichs** [comment]
Yes, 10 should be a reasonable expansion depth. Is there a fundamental necessity to cap the recursion? It seems to me like by default it should not be capped and optionally the user could decide to do so, but presumably I'm not aware of use cases where capping it is reasonable by default.

**Comment by josh146** [comment]
The capping is a protection against accidental recursion I believe. E.g., gate1 -> decomposes into gate 2 -> decomposes back into gate 1.

**Comment by cvjjm** [comment]
Won't Pyhton's max_recursion kick in anyway in case there is a runaway decomposition?

**Comment by josh146** [comment]
> Won't Pyhton's max_recursion kick in anyway in case there is a runaway decomposition?

I assume so yes, but I haven't tested a case yet where it does!
