### ISSUE TITLE
Allow sympy Symbols during Operation construction?

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1086]
Operations with sympy symbols are probably of very limited use for computation, but they can be very useful when analyzing circuits and gate decompositions.

A minimal change such as adding
```
        try:
            from sympy.core.symbol import Symbol
            from sympy.core.mul import Mul
            print(type(p))
            if isinstance(p, (Symbol, Mul)):
                return p
        except ImportError:
            pass
```
in line 506 of `operation.py` makes it possible to instantiate operations with a sympy symbol as paramter.

Is that something you would consider adding?

**Comment by josh146** [comment]
Hi @cvjjm, this is a check we are in the process of disabling 🙂 the operation class will therefore be able to accept *any* input types as arguments, including TF tensors, sympy symbols, etc.

In fact, this check is already disabled in tape mode, I believe.

**Comment by cvjjm** [comment]
OK then we can close this :-)
