### ISSUE TITLE
Clear up unintuitive behaviour for adjoint differentiation with finite number of shots

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#1092]
The `adjoint` and `reversible` differentiation methods, due to their implementations, will *always* return analytic/exact gradients, even when the device it is running on is instantiated with `analytic=False` and with a finite number of shots.

Due to their implementation (they calculate the gradient directly from the quantum statevector), this is unavoidable. However, this will likely be confusing to users; when using a finite number of shots to estimate expectation values, you would expect gradients to also be estimated!

Two changes to help fix this include:

* if `diff_method="best"` and `analytic=False`, modify the QNode logic to reject `adjoint`/`reversible` and instead use `parameter-shift`. This way gradients will be estimated with a finite number of shots.

* If `diff_method="adjoint"` or `diff_method="reversible"` and `analytic=False`, raise an error with a useful error message.

**Comment by mariaschuld** [comment]
I am wondering if we should tackle this after the shots refactor #1079, where the `analytic` argument will be discontinued...

**Comment by josh146** [comment]
Makes sense!

**Comment by josh146** [comment]
@mariaschuld is this change to the QNode logic already made in #1079? Or will it still need to be made?

**Comment by mariaschuld** [comment]
No, I think it still has to be made. Maybe best to make a separate PR to track this change after.

**Comment by albi3ro** [comment]
I'd like to say that neither adjoint nor reversible are on the list of things that can be possible selected if the user provides "best".

It goes:
* device
* backprop
* parameter shift
* numeric

Adjoint is only a semi-device method. It goes not count in this situation.

**Comment by josh146** [comment]
@albi3ro yes, you're right - `adjoint` is not yet chosen by the 'best' logic, since it is not up to feature parity. However, it will be included in the 'best' logic at some future point.

Just an update for those reading this issue: more discussion has taken place in #1406, and I suggest we instead _allow_ finite-shots within the adjoint method, by sampling the statevector inner-products computed by the adjoint method. However, care will need to be taken to ensure that the shots statistics match the parameter-shift shot statistics!

**Comment by antalszava** [comment]
Closing this as the original bug was resolved, but opened another one dedicated to the last point.
