### ISSUE TITLE
Problem on importing pennylane as qml.

### ISSUE THREAD

**Issue by yusharth** [PennyLaneAI/pennylane#1098]
I wrote a simple QML code to work on quantum computational circuits but it doesn't work. And gives value error.

When I debugged, It's pointing towards importing pennylane as qml.

Traceback (most recent call last):
  File "simple_circuits_20_template.py", line 40, in <module>
    angle = float(angle_str)
ValueError: could not convert string to float: ''

My Code:
[pennylane error.zip](https://github.com/PennyLaneAI/pennylane/files/6014762/pennylane.error.zip)

**Comment by co9olguy** [comment]
Hi @yusharth! This is a perfect question for our [discussion forum](discuss.pennylane.ai). I will close this issue and encourage you to post your question there (and please be mindful of not sharing code from the QHack challenges at the moment). If it is indeed uncovered that this is a bug, we can reopen this issue :slightly_smiling_face:
