### ISSUE TITLE
Add flaky as a dependency to Software tests page

### ISSUE THREAD

**Issue by PritishSehzpaul** [PennyLaneAI/pennylane#1099]
#### Issue description
I was following the installation guide for pennylane from https://pennylane.readthedocs.io/en/stable/development/guide/installation.html. I installed all the dependencies as mentioned on this page and moved on to the next page which talks about running the test suite to check the installation. I encountered an issue with it as attached below. 

In the list of dependencies in the file https://github.com/PennyLaneAI/pennylane/blob/master/doc/development/guide/tests.rst, [flaky](https://github.com/box/flaky) should be added as a dependency. This is because when you run `make test` and flaky is not installed, an error is thrown as attached below.
![pennylane_image](https://user-images.githubusercontent.com/15370938/108606669-5a9ce680-73e1-11eb-993b-6bd8a978ed63.png)

As I understand, the flag `--no-flaky-report` is provided by flaky.

* *Expected behavior:* When `make test` is run the tests should be run without any error.

* *Actual behavior:* I get the above error.

* *Reproduces how often:* Everytime if flaky as a dependency is not installed.
 
* *System information:*  
   - Windows x64 bit.
   - Using Anaconda3 and pennylane has a separate environment. in conda 
   - Installed dependency versions
       Dependency | Version
       -------------- | --------  
       python | 3.7.9
       numpy | 1.19.2
       scipy | 1.6.0
       networkx | 2.5
       autograd | 1.3
       toml | 0.10.1
       appdirs | 1.4.4
       semantic_version | 2.6.0     
   - Output of `import pennylane as qml; qml.about()` -
```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: PennyLane
Version: 0.15.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: e:\code\pennylane
Requires: numpy, scipy, networkx, autograd, toml, appdirs, semantic-version
Required-by:
Platform info:           Windows-10-10.0.19041-SP0
Python version:          3.7.9
Numpy version:           1.19.2
Scipy version:           1.6.0
Installed devices:
- default.gaussian (PennyLane-0.15.0.dev0)
- default.mixed (PennyLane-0.15.0.dev0)
- default.qubit (PennyLane-0.15.0.dev0)
- default.qubit.autograd (PennyLane-0.15.0.dev0)
- default.qubit.jax (PennyLane-0.15.0.dev0)
- default.qubit.tf (PennyLane-0.15.0.dev0)
- default.tensor (PennyLane-0.15.0.dev0)
- default.tensor.tf (PennyLane-0.15.0.dev0)
```

**Comment by josh146** [comment]
Hi @PritishSehzpaul! Good catch, this should definitely be added.

**Comment by josh146** [comment]
Would you be interested in making a contribution to update the file https://github.com/PennyLaneAI/pennylane/blob/master/doc/development/guide/tests.rst?

**Comment by PritishSehzpaul** [comment]
> Would you be interested in making a contribution to update the file https://github.com/PennyLaneAI/pennylane/blob/master/doc/development/guide/tests.rst?

Hi @josh146, sure. I will raise a PR shortly after going through the contributing guidelines.

**Comment by josh146** [comment]
Thanks @PritishSehzpaul! Feel free to open a WIP (work in progress) PR if you have any questions.
