### ISSUE TITLE
[BUG] qml.ExpvalCost() calculation mistake for variance

### ISSUE THREAD

**Issue by exAClior** [PennyLaneAI/pennylane#1105]
-------------------------------------------------------------------------------------------------------------

#### Issue description

For a hamiltonian H= 1/2 XX + 1/2 ZZ + 1/3 YY , I want to calculate the variance of it using qml.ExpvalCost(ansatz,H,dev,measure='var')

* *Expected behavior:* it calculates the variance taken into account of the coefficients for each Pauli String.

* *Actual behavior:* Coefficients like 1/2, 1/3  is not squared when calculating the variance, resulting in incorrect variance being calculated

* *Reproduces how often:* every time

* *System information:* Name: PennyLane
Version: 0.14.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/myname/anaconda3/envs/QHack/lib/python3.9/site-packages
Requires: numpy, autograd, appdirs, toml, networkx, scipy, semantic-version
Required-by: PennyLane-qiskit, PennyLane-Cirq, amazon-braket-pennylane-plugin
Platform info:           Linux-5.10.15-1-MANJARO-x86_64-with-glibc2.33
Python version:          3.9.1
Numpy version:           1.20.1
Scipy version:           1.6.0
Installed devices:
- default.gaussian (PennyLane-0.14.1)
- default.mixed (PennyLane-0.14.1)
- default.qubit (PennyLane-0.14.1)
- default.qubit.autograd (PennyLane-0.14.1)
- default.qubit.jax (PennyLane-0.14.1)
- default.qubit.tf (PennyLane-0.14.1)
- default.tensor (PennyLane-0.14.1)
- default.tensor.tf (PennyLane-0.14.1)
- qiskit.aer (PennyLane-qiskit-0.14.0)
- qiskit.basicaer (PennyLane-qiskit-0.14.0)
- qiskit.ibmq (PennyLane-qiskit-0.14.0)
- cirq.mixedsimulator (PennyLane-Cirq-0.13.0)
- cirq.pasqal (PennyLane-Cirq-0.13.0)
- cirq.qsim (PennyLane-Cirq-0.13.0)
- cirq.qsimh (PennyLane-Cirq-0.13.0)
- cirq.simulator (PennyLane-Cirq-0.13.0)
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.1.0)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.1.0)

**Comment by josh146** [comment]
Thanks for catching this @exAClior! I'll look into this.

**Comment by josh146** [comment]
Hi @exAClior, I've just had a look, and unfortunately I don't think it's possible to use `qml.ExpvalCost` to return variances of Hamiltonians. This function was designed to only return expectation values, and this assumption flows through the entire function.

However, it is relatively easy to do what you want using `qml.dot` and `qml.map`! For example, see below:

```python
import pennylane as qml
from pennylane import numpy as np

dev = qml.device("default.qubit", wires=2)

obs = [
    qml.PauliX(0) @ qml.PauliX(1),
    qml.PauliY(0) @ qml.PauliY(1),
    qml.PauliZ(0) @ qml.PauliZ(1)
]

coeffs = np.array([0.5, 0.5, 1/3])
qnodes = qml.map(qml.templates.StronglyEntanglingLayers, obs, dev, measure="var")
cost_fn = qml.dot(coeffs ** 2, qnodes)

weights = qml.init.strong_ent_layers_normal(n_layers=5, n_wires=2)
cost_fn(weights)
```

I'll close this issue for now, but let me know if that works for you.
