### ISSUE TITLE
Device jacobian is not called when QNode contains gates that need to be decomposed

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1115]
When a QNode contains gates that are not natively supported on a device they are decomposed by PennyLane (which is great!). 

Unfortunately (for some reason I do not understand) `diff_method='device'` does no longer work for QNodes containing such gates as is demonstrated by the following example:
```python
import pennylane as qml
from pennylane.devices import DefaultQubit
from pennylane.operation import Operation
import numpy as np

class MyDev(DefaultQubit):
    @classmethod
    def capabilities(cls):
        capabilities = super().capabilities().copy()
        capabilities.update(
            provides_jacobian=True,
        )
        return capabilities

    def jacobian(self, operations_or_tape, observables=None, parameters=None):
        raise Exception("This exception signals that the device jacobian() was called")

class RYZ(Operation):
    num_params = 2
    num_wires = 1
    par_domain = "R"
    grad_method = "A"

    @staticmethod
    def _matrix(*params):
        theta, phi = params
        return qml.RZ._matrix(phi + np.pi) @ qml.RY._matrix(theta + np.pi / 2)

    @staticmethod
    def decomposition(theta, phi, wires):
        decomp_ops = [
            qml.RY(np.pi / 2, wires=wires),
            qml.RY(theta, wires=wires),
            qml.RZ(phi, wires=wires),
            qml.RZ(np.pi, wires=wires),
        ]
        return decomp_ops

@qml.qnode(MyDev(wires=2), diff_method='device')
def circuit(params):
    RYZ(params[0], params[1], wires=0) # with this commented the device jacobian is called also with PennyLane master
    qml.RY(params[0], wires=0)
    return qml.expval(qml.Hermitian(np.array([[1, 0], [0, 0]]), wires=0))

params = np.array([0.75916255, -2.16921113])
qml.jacobian(circuit)(params)
raise Exception("This line should not be reached as device jacobian() should have been called")
```
With PL 0.13.0 `MyDev.jacobian()` is called, as is expected. With master `MyDev.jacobian()` is not called and PL computes the jacobian in some other way. By commenting out the `RYZ(params[0], params[1], wires=0)`, and thereby removing the only gate that needs to be decomposed, the device `jacobian()` is called again.

**Comment by antalszava** [comment]
Hi @cvjjm, this will likely be due to a change in the order of differentiation methods. As `MyDev` inherits from `DefaultQubit`, it prioritizes `backprop` over the device jacobian.

In PL `0.13.0`, the behaviour of master can be reproduced by using `qml.enable_tape()`.

For further details on the change, see the point in the `Improvements` section of the [Release notes of `v0.14.0`](https://pennylane.readthedocs.io/en/latest/development/release_notes.html#release-0-14-0) starting with
> The logic for choosing the ‘best’ differentiation method has been altered to improve performance.

**Comment by josh146** [comment]
Thanks for catching this @cvjjm! This is definitely a bug - I have created a bugfix PR #1117.

**Comment by antalszava** [comment]
Indeed, sorry for the previous misleading comment!

**Comment by cvjjm** [comment]
One more question related this:

There are gates composed of many "elementary" gates which nevertheless satisfy relatively simple shift rules, such as the four term rule. In case such a gate is differentiated on a device that does not natively support the composite gate but only the elementary gates and `diff_method="parameter-shift"`, how does PennyLane shift-differentiate the gate?

What it should do, I think, is apply the shift rule of the composite gate and then do the decomposition when executing circuits with the shift.
What it should not do (in my opinion) is decompose first and then differentiate all the elementary gates with their respective shift rules. Doing the latter can lead to significantly more circuit evaluations.
If the composite gate does not define a shift rule, I think it should decompose the gate and then try to use the shift rules of the elementary gates and chain rule.

What is PL doing at the moment? Is that behavior tested? If not it may be worth taking this into account when moving the decomposition to the device.

**Comment by josh146** [comment]
> What it should do, I think, is apply the shift rule of the composite gate and then do the decomposition when executing circuits with the shift. What it should not do (in my opinion) is decompose first and then differentiate all the elementary gates with their respective shift rules. Doing the latter can lead to significantly more circuit evaluations.

Yep, I agree 100%

> What is PL doing at the moment? Is that behavior tested? If not it may be worth taking this into account when moving the decomposition to the device.

Currently, it is doing the latter --- decomposing _before_ the gradient rules are applied. This is not ideal at all, and one of the driving reasons why we are moving the decompositions to the device. 

By the next release, we aim to have the following behaviour:

* A 'gradient' decomposition, that decomposes any gate without gradient rules.
* A 'apply' decomposition within the device, that decomposes any gate not supported.

**Comment by cvjjm** [comment]
Ok, great!
