### ISSUE TITLE
qml.adjoint breaks when combined with .inv()

### ISSUE THREAD

**Issue by Thenerdstation** [PennyLaneAI/pennylane#1119]
Currently, operations that use `gate.inv()` will not be correctly inverted when transformed by `qml.adjoint`. This also affects some gates when nested with multiple `adjoint` transforms, as some gates have their adjoint defined with `inv()`. (See gate SX). 

Ideally, in the future we would want to completely remove `inv()` and only ever use `qml.adjoint` transforms. That way, devices no longer have to keep track of inverting gates themselves.

**Comment by josh146** [comment]
Would it be possible to keep `.inv()` purely as a UI shortcut to `qml.adjoint`?

**Comment by Thenerdstation** [comment]
I would highly discourage that.

**Comment by albi3ro** [comment]
`qml.adjoint` now works with `.inv`, and we are getting rid of `.inv()` soon anyway.  Issue is no longer an issue.
