### ISSUE TITLE
Allow representing arbitrary operators with the Operator class

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1120]
*This issue has been tagged for contributions during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)*

#### Issue description

We would like to allow the representation of arbitrary non-Hermitian operators in PennyLane using the `Operator` class. This would be required for extending the definition of the `@` where the result of multiplying `Observable` instances might not necessarily Hermitian (see #715 and #1107 for further details).

This can be achieved by allowing arbitrary matrices to represent an `Operator` by redefining the [`_matrix` class method](https://github.com/PennyLaneAI/pennylane/blob/c8673eb45d9b3d435867f04b9943a5c4b53322be/pennylane/operation.py#L314). This would likely be similar to how it is done at the moment for [`Hermitian._matrix`](https://github.com/PennyLaneAI/pennylane/blob/8031ba9738f6264c5d56b9fbe18c1bcbec3b4d53/pennylane/ops/qubit.py#L1889).

**Comment by brs96** [comment]
Hi, reading through I don't see anything in Operator class _matrix method which prevents a non-self-adjoint matrix to be defined...? Did I miss sth?

**Comment by antalszava** [comment]
Hi @brs96, the Operator._matrix method raises a NotImplementedError, as certain subclasses define this method for more specific cases. We would like to remove this error and allow creating Operator objects that are not necessarily an instance of other special classes (like Operation or Observable).

To give a basic idea, we'd like something like
```python
op = Operator(matrix=mx, wires=wires)
```
to work well, where we do not pose any constraints on `matrix`.

**Comment by brs96** [comment]
Got it, thanks, will give it a try.

**Comment by albi3ro** [comment]
No longer really relevant.  We no longer check the unitarity of `QubitUnitary`, and `@` is defined for all Operators.
