### ISSUE TITLE
Too many circuit executions when computing parameter-shift Jacobians using Autograd

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1133]
I do believe that PennyLane is doing too many device executions when computing gradients with the parameter shift rule. This can impact performance when running on simulators but can hurt really badly when running on hardware.

Consider the following example: 

```
import pennylane as qml
import numpy as np
qml.enable_tape()

num_wires = 4
dev = qml.device('default.qubit', wires=num_wires)

@qml.qnode(dev, diff_method='parameter-shift')
def circuit(params, wires=range(num_wires)):
    qml.templates.layers.BasicEntanglerLayers(params, wires=wires)
    return [qml.expval(qml.PauliZ(wires=[wire])) for wire in wires]

params = np.random.randn(2, num_wires)

qml.jacobian(circuit)(params)

print("dev.num_executions", dev.num_executions)
print("expected number of executions 2*number of parameters =", 2*params.size)

print(circuit(params))
print(circuit.draw()) # drawig directly after qml.jacobian(circuit)(params) results in a TypeError: unsupported format string passed to ArrayBox.__format__
``` 
When executing this with the current `master` I get the following output:

```
>>> dev.num_executions 65
>>> expected number of executions 2*number of parameters = 16
>>> [-0.00324111 -0.02142108  0.28389244 -0.01313385]
 0: ──RX(0.5)────╭C──────────────────────────────╭X──RX(-0.266)──╭C──────────╭X──┤ ⟨Z⟩
 1: ──RX(0.919)──╰X──╭C───RX(-1.13)──────────────│───────────────╰X──╭C──────│───┤ ⟨Z⟩
 2: ──RX(-1.32)──────╰X──╭C──────────RX(-0.538)──│───────────────────╰X──╭C──│───┤ ⟨Z⟩
 3: ──RX(0.212)──────────╰X──────────────────────╰C──RX(-1.02)───────────╰X──╰C──┤ ⟨Z⟩
```

I am expecting 2 * number of parameters many executions when computing the jacobian of a circuit with parametrized `RX` gates because they are 2-shift differentiable, and so the circuit needs to be executed exactly two times to get a single component of the gradient of all simultaneously measurable quantities.

I think I know why the number of actual executions is odd: Autograd has the stupid(?) tendency to evaluate the function that we want to differentiate and pass the result of that evaluation to the vector jacobian product (vjp) function of the differentiated function even if the function value at the paramters is neither needed nor used during the computation of the vjp (as is the case here). I know how this can be fixed in principle, let me know if you want to know.

But why does PL do 65 instead of just 17 circuit evaluations? Is it doing parameter shift gradients for each simultaneously measurable quantity independently instead of computing the first entry of the jacobian for all PauliZs, then the second for all PauliZs, ...

**Comment by josh146** [comment]
Hey @cvjjm!

I actually came across this exact same issue yesterday, while adding Hessian support to Autograd. I _think_ the cause here is that `autograd.jacobian` is a bit stupid in how it computes the Jacobian (see https://stackoverflow.com/questions/54488875/improve-performance-of-autograd-jacobian).

I have a (maybe not optimal) working fix to the issue I found in #1131, let me run your code on that branch and see if it is resolved.

**Comment by josh146** [comment]
Ooh, it's close! In branch #1131, running your example, I get an output of:

```python
dev.num_executions 17
expected number of executions 2*number of parameters = 16
```

I think this is to be expected though, since autograd will always perform a forward pass prior to the backward pass.

**Comment by cvjjm** [comment]
I will probably be able to provide a solution for how to bring down 17 to 16 on Monday :-)

**Comment by josh146** [comment]
> I will probably be able to provide a solution for how to bring down 17 to 16 on Monday :-)

🤯 

Very much looking forward to it! Curious to see how you've done it.

I remember looking at the `autograd.grad` source code, and the forward pass was explicitly invoked in order to cache intermediate values for backprop.

**Comment by cvjjm** [comment]
Let me know what you think of the proposed solution to this in #1137 .

**Comment by josh146** [comment]
Thanks @cvjjm!
