### ISSUE TITLE
Drawing QNodes without executing them

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1136]
I used to be able to draw QNodes without having to execute them by calling their protected `_constuct()` method. I know this was a hack and this method now seems to be gone.

Is there an “official” way to draw QNodes with PL without having to execute them? I guess in an ideal world draw() would accept the parameters of a Qnode as an optional argument and if provided draw the Qnode with those parameters instead of those from the last execution.

I also noticed that drawing a QNode after a jacobian evaluation currently leads to a `TypeError: unsupported format string passed to ArrayBox.__format__`.

**Comment by josh146** [comment]
Hey @cvjjm! We're in the process of replacing a draw method with a new `qml.draw` function: https://pennylane.readthedocs.io/en/stable/code/api/pennylane.draw.html

Which from my reading of your comment above, behaves as you would prefer! It matches the behaviour of `qml.grad`, and no longer draws the last construction.

**Comment by josh146** [comment]
In particular:

```python
>>> drawer = qml.draw(circuit)
>>> drawer(a=2.3, w=[1.2, 3.2, 0.7])
0: ──H──╭C────────────────────────────╭C─────────╭┤ ⟨Z ⊗ Z⟩
1: ─────╰RX(2.3)──Rot(1.2, 3.2, 0.7)──╰RX(-2.3)──╰┤ ⟨Z ⊗ Z⟩
```

**Comment by cvjjm** [comment]
Awesome!
