### ISSUE TITLE
Relax pennylane-qchem dependence on PySCF version?

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1145]
PennyLane-QChem currently depends on pyscf==1.7.2 (I think this was because of [the bug mentioned here](https://github.com/PennyLaneAI/pennylane/pull/700#issuecomment-647500768)). From a few superficial tests it seems that this can now be relaxed to pyscf>=1.7.2 or pyscf==1.7.

Exact pinning to minor versions takes away a lot of flexibility.

**Comment by cvjjm** [comment]
This is certainly not a bug :-)

**Comment by josh146** [comment]
I think the bot saw that you used the word 'bug' and got excited 😆

**Comment by josh146** [comment]
@cvjjm regarding the comment you link to:

> @antalszava @agran2018: I also have a feeling that the pyscf bug that required pinning pyscf to version <=1.7.1 is now fixed, as of May 20: pyscf/pyscf#618. Was wondering if either of you know if this is the case?

At the time, we discovered the bug was still not fixed, and pyscf>1.7.2 would not install alongside SciPy (or something along those lines). It might be fixed now though, so worth giving another try!

**Comment by glassnotes** [comment]
I think we should revisit this as it causes issues in Python 3.9(.4). Specifying `pyscf==1.7.2` yields a BLAS linking error and the message
```
ERROR: Could not find a version that satisfies the requirement pyscf==1.7.2
ERROR: No matching distribution found for pyscf==1.7.2
```
For Python 3.9 one needs to specify at least version 1.7.6. (In Python 3.8, 1.7.2 it installs without issues. Both cases verified for Python 3.8 and 3.9 on both a Mac and Linux).

**Comment by antalszava** [comment]
Indeed, fails on Ubuntu too. On the bright side, this indeed seems to [have been solved in PySCF](https://github.com/pyscf/pyscf/commit/88aa846aff5ed6696dce2028b1855360c810412f) after we've done the [strict pinning](https://github.com/PennyLaneAI/pennylane/pull/926).

Opening a PR that will ease the requirement.
