### ISSUE TITLE
[unitaryhack] Add the ZZ operation

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1148]
*This issue has been tagged for contributions during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)*

**Context**

We would like to define a new diagonal operation called `ZZ`, as [defined in the PennyLane-Braket plugin](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/257eb99d62122e3a83c380ab240d6e166b2b9257/src/braket/pennylane_plugin/ops.py#L504).

**Steps to take**

*A. Adding the operation*

1. Adding the `ZZ` class and its attributes to `pennylane/ops/qubit.py`. This class would inherit from `DiagonalOperation`. Complete its docstring in a similar fashion as for other operations. Make sure the class is accessible through `qml.ZZ`.
2. Add its decomposition: a definition for how the operation could be decomposed into elementary operations (see note below),
3. Add its matrix, eigenvalues, adjoint and generator,
4. *Test:* include tests for the operation in the `tests/ops/test_qubit_ops.py` file,

*Note:* `ZZ` is a special case for [`PauliRot`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.PauliRot.html?highlight=paulirot#pennylane.PauliRot) for the `"ZZ"` Pauli word. Therefore, the decomposition of `ZZ` can directly depend on using `PauliRot`, which further decomposes into elementary gates. Inheriting from `PauliRot` could also be considered.

*B. Adding `default.qubit` support*

5. Add support for the operation in the `default.qubit` device,
6. *Test:* test the operation with `default.qubit` in the `tests/devices/test_default_qubit.py` file.

*Bonus:* Add support to the interface-specific `default.qubit` devices too: `default.qubit.autograd` and `default.qubit.tf`. This will require the operation to be defined in a framework-specific way. These devices inherit the supported operations from `default.qubit`, so if this step is not tackled, the `ZZ` can be removed from the `operations` dictionary for `default.qubit.autograd` and `default.qubit.tf`.

**Comment by Miru19** [comment]
Hello! I would like to solve this issue :) Thank you

**Comment by antalszava** [comment]
Hi @Miru19, that's great to hear! :) Feel free to start with it and open up a draft PR that's work in progress if you'd like. Don't hesitate to post any questions here.
