### ISSUE TITLE
Outdated interface introduction

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1155]
*This issue has been tagged for contributions during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)*

In the [interface introduction](https://pennylane.readthedocs.io/en/stable/introduction/interfaces/torch.html), the section on [converting an existing QNode](https://pennylane.readthedocs.io/en/stable/introduction/interfaces/torch.html#converting-an-existing-qnode) shows the function `to_torch()` , or respectively `to_tf()` etc., returning a new QNode instead of altering that QNode in place.  

What exists now:
```
qnode1_torch = qnode1.to_torch()
```

What should exist:
```
qnode1.to_torch()
```

This should be checked for all interface options.  

We should also update each interface's introduction to show creating a QNode with an interface via the class constructor:

```
qnode = qml.QNode(circuit, dev, interface='torch')
```

You can find the introduction source at [doc/introduction/interfaces/torch](https://github.com/PennyLaneAI/pennylane/blob/master/doc/introduction/interfaces/torch.rst#converting-an-existing-qnode).

**Comment by ryanhill1** [comment]
Hey there, I just started working on this issue. I'm getting an error trying to use the `forest.wavefunction` device:

```
import pennylane as qml

dev_wfun = qml.device('forest.wavefunction', wires=2)
---------------------------------------------------------------------------
DeviceError                               Traceback (most recent call last)
<ipython-input-1-40259941cb81> in <module>
      1 import pennylane as qml
      2 
----> 3 dev_wfun = qml.device('forest.wavefunction', wires=2)

~/opt/anaconda3/envs/qml/lib/python3.8/site-packages/pennylane/__init__.py in device(name, *args, **kwargs)
    253         return plugin_device_class(*args, **options)
    254 
--> 255     raise DeviceError("Device does not exist. Make sure the required plugin is installed.")
    256 
    257 

DeviceError: Device does not exist. Make sure the required plugin is installed.
```
But my `pennylane` installation seems to be working fine. For example, running
```
dev = qml.device('default.qubit', wires=2)
```
raises no errors. Do you have an idea why this is?

**Comment by albi3ro** [comment]
Thanks for taking a look :)

It looks like you don't have the [`"forest.wavefunction"`](https://pennylane-forest.readthedocs.io/en/latest/) device installed.  We should either:
* add a note that the forest plugin needs to be installed for that device
* switch `dev2` to another in-built simulator, like maybe `default.mixed`

Other "in-built" devices technically still require additional dependencies like jax or tensorflow that aren't required by default.

I favour switching `dev2` to `"default.mixed"` so all code examples can run without any additional installation.

Think you could do that too?

**Comment by co9olguy** [comment]
Agreed @albi3ro, the forest device is notoriously hard to install, so probably not the best example to use

**Comment by ryanhill1** [comment]
@albi3ro @co9olguy thanks for your input! I'll go ahead and switch `dev2` to `"default.mixed"` as you suggested.

**Comment by ryanhill1** [comment]
I have a quick question regarding line 28 of [docs/introduction/interfaces/torch](https://github.com/PennyLaneAI/pennylane/blob/master/doc/introduction/interfaces/torch.rst):

"The :ref:`QNode decorator <intro_vcirc_decorator>` is the recommended way for creating..."

On the [webpage](https://pennylane.readthedocs.io/en/stable/introduction/interfaces/torch.html#construction-via-the-decorator), this ref hyperlinks to [The QNode decorator](https://pennylane.readthedocs.io/en/stable/introduction/interfaces/torch.html#construction-via-the-decorator) section of the [Quantum Circuits](https://pennylane.readthedocs.io/en/stable/introduction/interfaces/torch.html#construction-via-the-decorator) docs page, but on GitHub, the link points nowhere. So my question is, where did this tag come from and what is it pointing to, exactly? For instance, if I wanted to create another ref that linked to the [Creating a quantum node](https://pennylane.readthedocs.io/en/stable/introduction/circuits.html#creating-a-quantum-node) section just above that, where would I find the equivalent to the "<intro_vcirc_decorator>" tag? Sorry if it's an obvious question, it's my first time working with `.rst` files!

**Comment by albi3ro** [comment]
I'm not the best at rst files either, so take what I say with a grain of salt and check the documentation build when you make a PR.

Looks like the reference for "Creating a quantum node" is `_intro_vcirc_qnode`, so a link would be `:ref: Creating a QNode (or some other text) <intro_vcirc_qnode>`.  Check [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-arbitrary-locations) for more information on `:ref:`

This way of creating links is much more dynamic, allowing sections to get moved around without destroying links.   If you look around the github pages, that's not the only link not going anywhere, just by nature of how sphinx and rst works.

**Comment by ryanhill1** [comment]
Ok, gotcha. In general where I can find those references? I see for this one it was used at the top of [doc/introduction/circuits.rst](https://github.com/PennyLaneAI/pennylane/blob/master/doc/introduction/circuits.rst#quantum-circuits), but if it hadn't previously been used where could I find it?

**Comment by josh146** [comment]
Hey @ryanhill1! Just a bit more context for internal linking with ReST files.

### Cross-references

Cross references are created by adding a label above section headings, like so:

```rest
.. _my-reference-label:

Section to cross-reference
--------------------------
```

So in order to create a cross-referenced link elsewhere, a label must first be created at the target location.
A link can then be created that points towards this section heading as follows:

```rest
See here: :ref:`my-reference-label`.
```

By default, this link will be displayed with the name of the section it links to ("Section to cross-reference"). If you want to provide custom link text, the following syntax is used:

```rest
See the :ref:`cross referencing section <my-reference-label>` for more details.
```

### Internal page links

However, that's not the only type of internal linking! There is also internal page links. For example, say that you want to link to the page `doc/introduction/circuits.rst`; you can do so like this:

```rest
For more details, see the :doc:`quantum circuit quickstart </introduction/circuits.rst>`.
```

Note the leading forward slash in the filepath -- this means that the file path is always relative to the `doc/` directory.

Note that, unless you want to link to a specific subsection of a page, **internal page links are always preferred to cross references where possible**.

**Comment by co9olguy** [comment]
Hi @ryanhill1 just wondering if you're still working on this issue?

We've flagged it for [unitaryHACK](https://unitaryfund.github.io/unitaryhack/), which means you'll be eligible for swag if you register and it is merged during next two weeks. (but it also means someone could scoop the issue sooner :wink:)

**Comment by ryanhill1** [comment]
Hey! Yeah I saw that I got caught up with some other work for a minute there but I'll be submitting a pull request for this sometime tomorrow!

**Comment by ryanhill1** [comment]
@albi3ro @co9olguy, yesterday I started a draft that addresses this issue. I made revisions to the PyTorch and TensorFlow introductions but held off on the Jax introduction for now until I know the first two look ok. I just had a few questions about some links/references and top-level outputs that were previously there, which I pointed out with a few comments. Could you take a look when you have a chance?

**Comment by josh146** [comment]
thanks @ryanhill1!
