### ISSUE TITLE
Standardize transform return types.

### ISSUE THREAD

**Issue by Thenerdstation** [PennyLaneAI/pennylane#1161]
We currently have 3 methods that could be considered transforms on `Operations`: `decompose`, `adjoint` and `_controlled`. `decompose` returns a list of operators and always queues to the tape context, `adjoint` returns a single operator with an optional `do_queue` argument, and `_controlled` doesn't return anything, and instead queues it's controlled ops to the tape context.

While not a big deal, we should consider having all of these transforms behave the same and have the same return types.

**Comment by josh146** [comment]
👍 

Note that `decompose` is deprecated, and being (slowly) replaced with `expand`, which instead returns a tape containing the operations (and iirc doesn't require queuing).
