### ISSUE TITLE
Please expose device._shot_vector via public property

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1164]
This is a features request: Please expose the shot vector via some public and documented property of the device. Thank you!

This is inspired by me needing to predict the output shape of certain QNodes and in case of a non trivial shot vector and all observables being owned by an `expval` the shape is 
```
(sum([shot_tuple.copies for shot_tuple in self.device._shot_vector]), len(self.measurements))
```
(where self is a tape).

**Comment by josh146** [comment]
Thanks @cvjjm!

> This is inspired by me needing to predict the output shape of certain QNodes and in case of a non trivial shot vector and all observables being owned by an expval the shape is

We should also update the `tape` logic to better predict the output shape.

**Comment by Thenerdstation** [comment]
> This is inspired by me needing to predict the output shape

Are you doing something with JAX? I'd be interested in hearing more about it.

**Comment by cvjjm** [comment]
No, this was independent of JAX. #1168 looks good to me. Thanks!
