### ISSUE TITLE
Create a hash property of the `QuantumTape` by using the `_ops` attribute

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1187]
A quantum circuit represented by a `QuantumTape` can have a hash computed. This is used for features like circuit caching and parametric compilation, where quantum circuits are compared (see the discussion in #1180). The hash is created by building the circuit graph of a `QuantumTape`, serializing this circuit graph and using the built-in `hash` function.

Instead of this approach, we would like to create a hash simply by using the recorded operations of a `QuantumTape`, kept in the `_ops` attribute. This will help with faster hash creation at the cost of finding two circuits equivalent if and only if they have identical recorded operations.

The `QubitDevice` specific test cases removed in https://github.com/PennyLaneAI/pennylane/pull/1182 should be re-added targeting the `QuantumTape` class.

**Comment by trbromley** [comment]
Note that #1180 contains some useful discussion on efficient hashing.

**Comment by josh146** [comment]
@antalszava what is the status of this PR? Has it since been updated?

**Comment by antalszava** [comment]
This specific issue has not been updated or addressed by a PR since it's been opened.

**Comment by josh146** [comment]
I think we can close this now that `tape.hash` is defined
