### ISSUE TITLE
`num_wires` attribute for a general qml.Hermitian object

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1188]
When creating a new arbitrary `Hermitian` observable, 

```python
h = qml.Hermitian(np.array([[0, 1], [1,0]]), 0)
```

the attribute `num_wires` isn't automatically calculated and defaults to this:

```
>>> h.num_wires
<WiresEnum.AnyWires: -1>
```
even though `num_wires` is a required attribute for both `Observable` and `Operator`.

I see one of two solutions:
1) use a different way to create a new generic Hermitian operator
2) automatically calculate `num_wires` in the `__init__` method of either `Operator`, `Observable` or `Hermitian`.

**Comment by josh146** [comment]
Thanks @albi3ro! Can I ask how you caught this -- was this causing an exception during other logic?

**Comment by albi3ro** [comment]
I was finally going back to the Hamiltonian printing to try and clear it from my backlog I had been ignoring.  

The test uses operators created with `qml.Hermitian(matrix, wires)`, but these terms weren't getting sorted according to how many wires they were using.  In that situation, I could just use `op.wires.__len__()` instead.

**Comment by albi3ro** [comment]
Given I used a workaround where this was causing an issue, I'm going to close this issue.
