### ISSUE TITLE
[unitaryhack] update docstring for permute template

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1193]
*This issue has been tagged for contributions during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)*

In the [permute template](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/templates/subroutines/permute.py), the example code chunks use initial `qml.RZ` gates to ensure `tape.draw()` uses the correct ordering of wires.  

One case:

```python
import pennylane as qml
from pennylane.templates import Permute
with qml.tape.QuantumTape() as tape:
    # RZs added to ensure numerical ordering in drawing
    for wire in range(5):
        qml.RZ(0, wires=wire)
    Permute([4, 2, 0, 1, 3], wires=[0, 1, 2, 3, 4])
```

[The draw method](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.tape.draw.html) now supports a `wire_order` keyword.  The docstring should use this method instead of initial gates to control how wires get ordered when drawn.

So the corresponding drawing should be created using:
```python
print(tape.draw(wire_order=[0,1,2,3,4]))
```

Solving this issue involves:
* identifying each place in `permute.py` (or even beyond) where this needs to get fixed
* checking the new code works as expected
* changing each location

**Comment by tgag17** [comment]
Hi! Is this issue still open? I am not sure but I think a relevant PR has already been merged which solves this issue.

**Comment by co9olguy** [comment]
Hi @tgag17, good catch! I had a quick look and it does seem that that PR already solved the issue, but it was forgotten to close the issue. I guess this one is off the table then :slightly_smiling_face:
