### ISSUE TITLE
[unitaryhack] Deprecate `qml.inv`

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#1195]
*This issue has been tagged for contributions during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)*

Currently, PennyLane has two functions for inverting quantum operations:

* [`qml.inv()`](https://github.com/PennyLaneAI/pennylane/blob/4ece39acb42dacafd5b5cc566c4d3f0512dfa6fb/pennylane/utils.py#L236) accepts a list of operations, unqueues them from the tape, inverts them, and re-queues.

* [`qml.adjoint()`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/transforms/adjoint.py) transforms a function that queues operations to one that queues the inverse.

While both have very different internal implementations, for end users, they provide pretty much the same functionality; `qml.adjoint()`, however, is more general and `qml.inv()` has been marked for removal.

Further, the term `adjoint` is already in use for the adjoint differentiation method, and could be confusing to have two independent concepts share the same term.

So we can kill two birds with one stone:

- Remove `qml.inv()`
- Rename the `qml.adjoint()` transform to `qml.inv()`.

This has the advantage that existing users code that uses `qml.inv()` should continue to work as is.

**Comment by tgag17** [comment]
Hi! Is this issue an open issue or has it already been assigned?

**Comment by antalszava** [comment]
Hi @tgag17, it's still an open issue. :slightly_smiling_face: (The assignment was from a while back.)

**Comment by tgag17** [comment]
Hi! I have been working on this issue. An integral part of the issue is to rename the qml.adjoint() transform to qml.inv(). I had some doubts about the same. 
- Shouldn't the data type of the argument change too when the renaming is done as qml.adjoint() takes a function while qml.inv() takes an operation list.
- There would be a drawback as the existing codes that use qml.adjoint() will become redundant

Thanks!

**Comment by josh146** [comment]
Hi @tgag17 this is a great point, thanks for pointing it out. Perhaps we should modify this issue --- instead, we could keep `qml.adjoint` as is, and mark `qml.inv()` for deprecation (with a deprecation message that informs users to switch to `qml.adjoint`).

**Comment by tgag17** [comment]
Yes! That seems like a good option 👍

**Comment by josh146** [comment]
@tgag17 feel free to tackle this --- I will edit the title of this issue 🙂
