### ISSUE TITLE
drawing operations on tapes

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1230]
PennyLane supports drawing tapes, like 
```python
with qml.tape.QuantumTape() as tape:
    qml.RX(0.1, wires=0)

print(tape.draw())
```
```
 0: ──RX(0.1)──┤  
```

But if such a tape includes non-fundamental operations, like templates,

```python
with qml.tape.QuantumTape() as tape:
    qml.templates.Permute([4,2,0,1,3], wires=[0,1,2,3,4])

print(tape.draw())
```
Attempting to draw fails.  The above example raises 

```
TypeError: can't multiply sequence by non-int of type 'float'
```

The particular issue is at [pennylane/circuit_drawer/representation_resolver.py#L421](https://github.com/PennyLaneAI/pennylane/blob/a3def612368879169cbc7c8e318375901ab681e7/pennylane/circuit_drawer/representation_resolver.py#L421)

Once the tape has been expanded, it draws fine:

```
tape2 = qml.tape.tape.expand_tape(tape)
print(tape2.draw())
```

If we wish to invest in fixing this issue, I see two possible solutions:
A) Perform tape expansion before drawing
B) Expand circuit drawer support

Solution A) will be the easiest to implement, but Solution B) will allow drawing more complicated circuits in the long run.

**Comment by josh146** [comment]
@albi3ro this is a good catch, and a relatively important bug now that templates do not expand by default.

Note that this however doesn't affect *QNode* drawing, since when drawing a QNode, the bound device is always taken into account:

```pycon
>>> import torch
>>> import pennylane as qml
>>> dev = qml.device("default.qubit", wires=2)
>>> @qml.qnode(dev, interface="torch")
... def circuit(weights):
...     qml.templates.BasicEntanglerLayers(weights, wires=range(2))
...     return qml.expval(qml.PauliZ(wires=0))
>>> weights = torch.ones((3, 2))
>>> print(qml.draw(qnode)(weights))
 0: ──RX(1)──╭C──RX(1)──╭C──RX(1)──╭C──┤ ⟨Z⟩
 1: ──RX(1)──╰X──RX(1)──╰X──RX(1)──╰X──┤
```

So since this isn't very user-facing, I suggest we go with the long-term solution:

>  B) Expand circuit drawer support

A nice approach would be to support drawing 'unknown' operations, by having a box with the gate name within it. This is also quite future proof.

**Comment by mariaschuld** [comment]
Seconded...in the long term it would be nice if a user had control over what gates to expand in the drawer, for example by passing a list of gates to expand.

**Comment by dime10** [comment]
This was fixed in https://github.com/PennyLaneAI/pennylane/pull/1994
