### ISSUE TITLE
Executing a `QNodeCollection`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1231]
In the documentation for [`QNodeCollection`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/collections/qnode_collection.py), the docstring gives the example of executing multiple qnodes at the same time:

```python
dev1 = qml.device("default.qubit", wires=1)
dev2 = qml.device("default.qubit", wires=2)

@qml.qnode(dev1)
def qnode1(x, y):
    qml.RX(x, wires=0)
    qml.RY(y, wires=0)
    return qml.expval(qml.PauliZ(0))

@qml.qnode(dev2)
def qnode2(x, y):
    qml.Hadamard(wires=0)
    qml.RX(x, wires=0)
    qml.RY(y, wires=1)
    qml.CNOT(wires=[0, 1])
    return qml.expval(qml.PauliZ(0)), qml.var(qml.PauliZ(1))

qnodes = qml.QNodeCollection([qnode1, qnode2])

qnodes(0.5643, -0.45)
```

I get ```ValueError: all input arrays must have the same shape```.

In the docstring, this is supposed to return 
```
[ 7.60844651e-01 -5.55111512e-17  1.00000000e+00]
```

**Comment by mariaschuld** [comment]
@albi3ro has this been fixed? I cannot find the code in the [docstring](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.QNodeCollection.html?highlight=qnodecollection#pennylane.QNodeCollection)...

**Comment by albi3ro** [comment]
Oh, yeah... This still needs to be fixed.  I just temporarily edited the docstring to an example that wasn't broken.
