### ISSUE TITLE
`tape.inv` execution contradicts documentation

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1240]
Local execution of the docstring for [`tape.inv`](https://github.com/PennyLaneAI/pennylane/blob/6c5868b5232e80166684ae75871c99edda7e65e3/pennylane/tape/tape.py#L563) gives different behaviour.

```python
import pennylane as qml

with qml.tape.JacobianTape() as tape:
    qml.BasisState(np.array([1, 1]), wires=[0, 'a'])
    qml.RX(0.432, wires=0)
    qml.Rot(0.543, 0.1, 0.4, wires=0).inv()
    qml.CNOT(wires=[0, 'a'])
    qml.probs(wires=0), qml.probs(wires='a')
```
Here when we ask for the parameters, we get them in this order:
```pycon
>>> tape.get_parameters()
[array([1, 1]), 0.432, 0.543, 0.1, 0.4]
```
After inverting the tape:
```python
tape.inv()
```

The gate parameters should be shifted in location according to the new order of operations of the tape:
```pycon
>>> tape.get_parameters()
 [array([1, 1]), 0.543, 0.1, 0.4, 0.432]
```

but I do not get that inverted order.  I instead get the same order of parameters:

```pycon
>>> tape.get_parameters()
[tensor([1, 1], requires_grad=True), 0.432, 0.543, 0.1, 0.4]
```

**Comment by josh146** [comment]
Hey @albi3ro, strangely I'm not able to reproduce this 🤔 

```python
>>> tape.operations
[BasisState(array([1, 1]), wires=[0, 'a']),
 RX(0.432, wires=[0]),
 Rot.inv(0.543, 0.1, 0.4, wires=[0]),
 CNOT(wires=[0, 'a'])]
>>> tape.get_parameters()
[array([1, 1]), 0.432, 0.543, 0.1, 0.4]
```

After inverting it:

```python
>>> tape.inv()
>>> tape.operations
[BasisState(array([1, 1]), wires=[0, 'a']),
 CNOT.inv(wires=[0, 'a']),
 Rot(0.543, 0.1, 0.4, wires=[0]),
 RX.inv(0.432, wires=[0])]
>>> tape.get_parameters()
[array([1, 1]), 0.543, 0.1, 0.4, 0.432]
```

**Comment by albi3ro** [comment]
When I tried it again this morning I got very confused, as the above code was working as expected!

But it still doesn't work, I just didn't write all the steps, because I didn't think the step would have changed anything.  The problem occurs when the trainable parameters are set.  Here's the actual example:

```python
import pennylane as qml
from pennylane import numpy as np

with qml.tape.JacobianTape() as tape:
    qml.BasisState(np.array([1, 1]), wires=[0, 'a'])
    qml.RX(0.432, wires=0)
    qml.Rot(0.543, 0.1, 0.4, wires=0).inv()
    qml.CNOT(wires=[0, 'a'])
    qml.probs(wires=0), qml.probs(wires='a')

print(tape.get_parameters())

#this causes the problem
tape.trainable_params = {1,2}

print(tape.get_parameters(trainable_only=False))

tape.inv()
print("should be inverted now?")
print(tape.get_parameters(trainable_only=False))
print(tape.trainable_params)
```

**Comment by josh146** [comment]
@albi3ro could you check if this works as expected in v0.14.1? This might be the cause of #1242

**Comment by albi3ro** [comment]
Looks like it's still happening when I checked out v0.14.1, but might still be the source of the problem anyway.

**Comment by josh146** [comment]
Oh, odd. In #1242, the `qml.inv()` buggy behaviour is not present in 0.14.1 --- something else must have changed in-between the two versions 🤔

**Comment by josh146** [comment]
It turns out that this is unrelated to #1242. My guess is that this bug has always existed, but likely does not affect current behaviour (since, I'm guessing, that the edge case of setting the trainable parameters inbetween inversion never occurs in the code base?)
