### ISSUE TITLE
Inverse circuit not computed correctly in pennylane 0.15.0

### ISSUE THREAD

**Issue by EliasCombarro** [PennyLaneAI/pennylane#1242]
#### Issue description

I do not know if it has to do with this other issue https://github.com/PennyLaneAI/pennylane/issues/1240 but it seems that in version 0.15.0 the inverse of a circuit is not computed correctly. I noticed it while executing the kernel classifier from https://pennylane.ai/qml/demos/tutorial_kernel_based_training.html

In fact, when executing 

```python
kernel(X_train[0], X_train[0])
```

I obtain 0.15190944036912452

and when printing the circuit I get 
```
[ 0.35866332  2.73124718 -0.94364311 -0.68644165]
 0: ──RX(0.359)───RX(0.359)───╭┤ ⟨H0⟩ 
 1: ──RX(2.73)────RX(2.73)────├┤ ⟨H0⟩ 
 2: ──RX(-0.944)──RX(-0.944)──├┤ ⟨H0⟩ 
 3: ──RX(-0.686)──RX(-0.686)──╰┤ ⟨H0⟩ 
```
with not inverse in the second column of rotations)

* *Expected behavior:* (What you expect to happen)

This works correctly with pennylane 0.14.1, with which I obtain 
```
0.9999999999999998
[ 0.35866332  2.73124718 -0.94364311 -0.68644165]
 0: ──RX(0.359)───RX(0.359)⁻¹───╭┤ ⟨H0⟩ 
 1: ──RX(2.73)────RX(2.73)⁻¹────├┤ ⟨H0⟩ 
 2: ──RX(-0.944)──RX(-0.944)⁻¹──├┤ ⟨H0⟩ 
 3: ──RX(-0.686)──RX(-0.686)⁻¹──╰┤ ⟨H0⟩ 
```
* *Actual behavior:* (What actually happens)

The one described above

* *Reproduces how often:* (What percentage of the time does it reproduce?)

100%

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

Name: PennyLane
Version: 0.15.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: scipy, toml, appdirs, numpy, semantic-version, autograd, networkx
Required-by: 
Platform info:           Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python version:          3.7.10
Numpy version:           1.19.5
Scipy version:           1.4.1
Installed devices:

**Comment by josh146** [comment]
Thanks for catching this @EliasCombarro! This is certainly a concerning bug, we'll look into this and see if we can uncover what is happening.

**Comment by EliasCombarro** [comment]
My pleasure

**Comment by josh146** [comment]
@EliasCombarro, a quick update: I believe I have found the issue and fixed it in #1243

**Comment by EliasCombarro** [comment]
Thanks! Just a quick question: what should I use instead of qml.inv()?

**Comment by josh146** [comment]
Hey @EliasCombarro!

If you install PennyLane from the branch in the PR, 

```python
pip install git+https://github.com/PennyLaneAI/pennylane.git@fix-inv
```

then you should be able to use either `qml.inv()` or the new `qml.adjoint()` function to invert your templates 🙂 

Note that, while `qml.inv()` is still present, it has been *deprecated*, and will long-term be replaced with `qml.adjoint()`.

**Comment by josh146** [comment]
no worries @EliasCombarro!

**Comment by EliasCombarro** [comment]
Thank you!

**Comment by josh146** [comment]
Hi @EliasCombarro - we just realized a bugfix version of PennyLane, v0.15.1, that fixes this bug 🙂 The kernel demo on the website should now also be returning the correct result

**Comment by EliasCombarro** [comment]
Great! Thanks so much
