### ISSUE TITLE
Superfluous nodes in graph plot when graph built with tensor objects as graph nodes

### ISSUE THREAD

**Issue by anthayes92** [PennyLaneAI/pennylane#1248]
When building a networkx graph with nodes that are tensor objects, the plot of the graph will display double the amount of nodes

* *Expected behavior:* Graph displayed with prescribed number of nodes and edges

* *Actual behavior:* Additional unwanted nodes are displayed around the graph, these additional nodes are not connected by edges.

* *Reproduces how often:* Every time a graph is defined with tensor object nodes. Note that it does not occur when the graph is defined without edge weights.  

* *System information:* 
Name: PennyLane
Version: 0.15.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/ant/.local/lib/python3.8/site-packages
Requires: scipy, numpy, appdirs, networkx, autograd, semantic-version, toml
Required-by: pennylane-qulacs, PennyLane-qiskit, PennyLane-Lightning, PennyLane-Cirq, amazon-braket-pennylane-plugin
Platform info:           Linux-5.8.0-50-generic-x86_64-with-glibc2.29
Python version:          3.8.5
Numpy version:           1.20.2
Scipy version:           1.4.1

#### Source code and tracebacks

```
import networkx as nx
from pennylane import numpy as np

G = nx.Graph()
n_nodes = 3
G.add_nodes_from(np.arange(n_nodes)) # adds tensor object nodes
edge_weights = np.random.uniform(low=0, high=1, size=(n_nodes,))
for i in range(n_nodes):
    for j in range(i+1, n_nodes):
        G.add_edge(i, j, weight=edge_weights[i])
nx.draw(G)
```

#### Additional information

[Original forum post
](https://discuss.pennylane.ai/t/issue-with-pennylane-wrapped-numpy-import/992/4)

**Comment by josh146** [comment]
Hey @anthayes92; this is due to the fact that `edge_weights[i]` returns a PennyLane tensor rather than a NumPy array. As a result, NetworkX treats it like a separate node, since NetworkX hashes nodes based on *object hash*, not object value.

This could be fixed as follows:

```python
import networkx as nx
from pennylane import numpy as np

G = nx.Graph()
n_nodes = 3
G.add_nodes_from(np.arange(n_nodes)) # adds tensor object nodes
edge_weights = np.random.uniform(low=0, high=1, size=(n_nodes,))
for i in range(n_nodes):
    for j in range(i+1, n_nodes):
        G.add_edge(i, j, weight=edge_weights[i].numpy())
nx.draw(G)
```

This is expected behaviour, and not a PennyLane bug. Note that to avoid issues with external frameworks, we recommend using vanilla NumPy with external frameworks, similarly to how JAX works.

**Comment by anthayes92** [comment]
Hey @josh146, thanks for quickly clearing this up! Using the standard numpy import certainly solve this.
