### ISSUE TITLE
Update NumPy random module wrapping

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1252]
Currently, PennyLane wraps the arrays created by `np.random` method, such as `np.random.random`.

But, in current NumPy, that way of creating random arrays is legacy.  NumPy instead [recommends](https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random) creating random arrays by:
```python
rng = np.random.default_rng()
x = rng.standard_normal((4,2))
y = rng.random(4)
```

`rng` is a [`np.random.Generator`](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator) object.  We need to wrap this object's methods as well to keep consistent with NumPy recommendations.

**Comment by josh146** [comment]
Nice catch @albi3ro! In addition, we will need to update demos that use `np.random`.
