### ISSUE TITLE
Two operations named `Interferometer`

### ISSUE THREAD

**Issue by mariaschuld** [PennyLaneAI/pennylane#1256]
*This issue has been tagged for contributions during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)*

The new design of the templates turned them into just another kind of operation. 

This causes an issue for the [Interferometer](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.subroutines.Interferometer.html) template, since it gets mixed up with the [gate](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Interferometer.html) of the same name, but which takes a unitary specifying the beam splitter arrangement instead.

The problem gets picked up when using the `default.gaussian` device, which tries to implement the former template by feeding it a single parameter.

We should rename one of the two in a 1-release-cycle deprecation. But which one?

**Comment by josh146** [comment]
I would say the upcoming release, v0.16 🙂 

Is the plan the following?

- `qml.Interferometer` -> `qml.InterferometerUnitary`
- `qml.templates.Interferometer` remains as is

**Comment by mariaschuld** [comment]
Yes, that was my plan. I'll put it on the todo list.

**Comment by arjundavis** [comment]
Hi, me and @maldoalberto are working on this as our first issue. We found the class interferometer in ops.cv and have changed it's name to InterferometerUnitary along with other parts. 
Which other files are using this interferometer? We assume in the default_gaussian and in representation_resolver.

**Comment by mariaschuld** [comment]
Great that you picked this up!

Actually there are two steps to a deprecation. The first step (or the first PR) would just be to add a deprecation warning (at the moment we use `UserWarning`, you can find them elsewhere in the code`) to the current `ops.cv.Interferometer` class. If someone uses this gate, the warning should tell them that it will be renamed. This change will be there for one release cycle, so people have time to change their code. The warning has to be tested (best where the gate is tested, just add a new test function using `pytest.warns` I think). And you have to add the change to the CHANGELOG file, and add yourselves as contributers of the release.

If you're up to implementing the next step as well (although we will only be able to merge it after the next release), then you can make the second PR, which is the one you already started with. In this PR we need to rename the class as you did, and then search for lines in the code where `Interferometer` is translated to an implementation.

* One would indeed have to check the `default.gaussian` device, and change the name there. More precisely, at the moment when `default.gaussian` encounters a gate called `Interferometer`, it expects it to have a `param` that represents the unitary which defines the interferometer's matrix. This logic should now only be performed when it sees `InterferometerUnitary` (else it uses the decomposition defined in `template.Interferometer`). 

* You are right, there is also `representation_revolver` that needs the same change...

* In addition to the PennyLane code base, the change should also be implemented with a separate PR in the StrawberryFields plugin that is not part of this repo, but in [here](https://github.com/PennyLaneAI/pennylane-sf/blob/master/pennylane_sf). Essentially, [this line ](https://github.com/PennyLaneAI/pennylane-sf/blob/8b98ad1932afe35a8bef08f2d6b13519ca427e42/pennylane_sf/gaussian.py#L91) needs to be changed in every device  from `"Interferometer": Interferometer`  to `"InterferometerUnitary": Interferometer` (which maps the PennyLane `InterferometerUnitary` to StrawberryField's `Interferometer`, which is a bit confusing but should be the right translation). The link above refers to `strawberryfields.gaussian` but there is also `strawberryfields.fock` (in `fock.py`) and the remote device (in `remote.py`).

Finally, there is a third PR, which I am happy to help with once the first two are done. In this one we need to turn the `templates.Interferometer` into an `Operation`. We did this for all other templates (for example [here](https://github.com/PennyLaneAI/pennylane/pull/1156)) but the name conflict prevented the rewrite for this one. 

Let me know if there are any questions :)

**Comment by MaldoAlberto** [comment]
In case I want to support this issue and others independent of unitaryHACK is it possible?

**Comment by josh146** [comment]
Hi @MaldoAlberto, yes any issue tagged [`good first issue`](https://github.com/PennyLaneAI/pennylane/labels/good%20first%20issue%20%3Ahatching_chick%3A) is a good one to open a contributing PR for!

**Comment by antalszava** [comment]
Hi @arjundavis and @MaldoAlberto, any update on this one? :slightly_smiling_face:

**Comment by antalszava** [comment]
As there are many steps to this addition, removing the "good first issue" label and creating separate issues.

**Comment by antalszava** [comment]
Opened https://github.com/PennyLaneAI/pennylane/issues/1709 which would be the next step in the deprecation cycle.

**Comment by josh146** [comment]
@antalszava can we close this issue now?

**Comment by antalszava** [comment]
Yes :tada:
