### ISSUE TITLE
Analytical gradients for excitation operations

### ISSUE THREAD

**Issue by ixfoduap** [PennyLaneAI/pennylane#1264]
The new [SingleExcitation](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.SingleExcitation.html) and [DoubleExcitation](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.DoubleExcitation.html) operations support analytical gradients through a decomposition into a product of two gates that satisfy the usual parameter-shift rule. 

However, since these gates are actually supported in default PennyLane simulators, they are not in fact decomposed when computing gradients. Instead, by specifying that gradients are computed analytically, PennyLane assumes that the excitation gates themselves satisfy the usual parameter-shift rule. This leads to incorrect results when computing gradients using parameter-shift.

During development, gradients were tested across different methods, but unfortunately we have now identified that there was an bug in the tests themselves.

Since gradients are now calculated using backpropagation as default, this is not an issue in the majority of calculations. It will only appear for users that build circuits using these operations and explicitly set the differentiation method to parameter-shift.

This problem can be fixed by removing these operations from the list of supported ones, but this will lead to an unnecessary doubling of gates applied in the forward pass.

**Comment by josh146** [comment]
Thanks @ixfoduap! Note that this will be solved by moving tape expansion to the device. The logical flow will look as follows:

1. The QNode constructs the tape, using `SingleExcitation` and `DoubleExcitation` operations.
2. `default.qubit` is in control of expansion, and understands these operations natively, so does _not_ decompose them for the forward pass/classical backpropagation.
3. The parameter-shift rule will have it's _own_ expansion step. The parameter-shift rule _doesn't_ natively support these two gates, so will decompose them into `SingleExcitationPlus` and `SingleExcitationMinus` (etc.) for gradient computations.

(@trbromley)

**Comment by mariaschuld** [comment]
This will be so clean! :)

**Comment by dwierichs** [comment]
Both excitation gates satisfy the four-term parameter shift rule, so we could use that one :)
I talked to Josh and I am excited about the split up of the differentiation pass, but for these gates we might get away with it.

**Comment by josh146** [comment]
@dwierichs we should probably add the 4-term rules sooner rather than later, as I am struggling to split up the forward and backward expansions 😆 It was not as straightforward as I thought it would be.

**Comment by josh146** [comment]
Closing this, as the 4-term shift rules have been added.
