### ISSUE TITLE
Inconsistent type returned by <class 'pennylane.vqe.vqe.Hamiltonian'>  property ops

### ISSUE THREAD

**Issue by aemccoy** [PennyLaneAI/pennylane#1265]
#### Issue description

When vqe.Hamiltonian contains terms consisting of a single qubit operator, e.g., H=2*Z0,  `H.ops` returns a list of operators whose type depends on whether Hamiltonian is constructed directly from pennlylane pauli operator `2*qml.PauliZ(0)` or if Hamiltonian is converted to vqe.Hamiltonian from openfermion QubitOperator using `qml.qchem.convert_observable`. 

* *Expected behavior:*  Properties of Hamiltonian consistently return same type for the same operator independent of construction 

* *Actual behavior:* See below

* *Reproduces how often:* Always

* *System information:* (post the output of `import pennylane as qml; qml.about()`)
    Name: PennyLane
    Version: 0.16.0.dev0
    Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
    Home-page: https://github.com/XanaduAI/pennylane
    Author: None
    Author-email: None
    License: Apache License 2.0
    Location: /opt/anaconda3/envs/pennylane/lib/python3.9/site-packages
    Requires: toml, semantic-version, networkx, autograd, appdirs, numpy, scipy
    Required-by: PennyLane-qiskit, PennyLane-Qchem
    Platform info:           macOS-10.16-x86_64-i386-64bit
    Python version:          3.9.4
    Numpy version:           1.20.1
    Scipy version:           1.6.1
    Installed devices:
    - default.gaussian (PennyLane-0.16.0.dev0)
    - default.mixed (PennyLane-0.16.0.dev0)
    - default.qubit (PennyLane-0.16.0.dev0)
    - default.qubit.autograd (PennyLane-0.16.0.dev0)
    - default.qubit.jax (PennyLane-0.16.0.dev0)
    - default.qubit.tf (PennyLane-0.16.0.dev0)
    - default.tensor (PennyLane-0.16.0.dev0)
    - default.tensor.tf (PennyLane-0.16.0.dev0)
    - qiskit.aer (PennyLane-qiskit-0.15.0)
    - qiskit.basicaer (PennyLane-qiskit-0.15.0)
    - qiskit.ibmq (PennyLane-qiskit-0.15.0)

#### Source code and tracebacks
If the vqe.Hamiltonian is constructed directly in pennylane
```
A=2*qml.PauliZ(0)
print("A: ",type(A))
print(A)
print("A.ops: ",type(A.ops))
print(A.ops)
print("A.ops[0]: ",type(A.ops[0]))
print(A.ops[0])
print("A.ops[0].name: ",type(A.ops[0].name))
print(A.ops[0].name)
```
Returns
```
A:  <class 'pennylane.vqe.vqe.Hamiltonian'>
  (2) [Z0]
A.ops:  <class 'list'>
[PauliZ(wires=[0])]
A.ops[0]:  <class 'pennylane.ops.qubit.PauliZ'>
PauliZ(wires=[0])
A.ops[0].name:  <class 'str'>
PauliZ
```

If equivalent vqe.Hamiltonian is obtained from openfermion QubitOperator 

```
qubit_op=QubitOperator("Z0",2)
B=qml.qchem.convert_observable(qubit_op)

print("B: ", type(B))
print(B)
print("B.ops: ",type(B.ops))
print(B.ops)
print("B.ops[0]: ",type(B.ops[0]))
print(B.ops[0])
print("B.ops[0].name: ",type(B.ops[0].name))
print(B.ops[0].name)
```
return 
```
B:  <class 'pennylane.vqe.vqe.Hamiltonian'>
  (2) [Z0]
B.ops:  <class 'list'>
[PauliZ(wires=[0])]
B.ops[0]:  <class 'pennylane.operation.Tensor'>
PauliZ(wires=[0])
B.ops[0].name:  <class 'list'>
['PauliZ']
```

**Comment by josh146** [comment]
Thanks for noting this @aemccoy! This is definitely something we can fix to make more consistent.
