### ISSUE TITLE
Allow QNodes to support `diff_method=None` option

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/pennylane#1274]
As discussed in #1271 , add the option for `diff_method=None` to QNodes. This would create QNodes that accept NumPy input, return NumPy output, but cannot be differentiated.

**Comment by ankit27kh** [comment]
Will a simple change which checks if the QNode.diff_method=None and if it is, set QNode.interface=None AND QNode.diff_method="best" work?
This is like a shortcut patch to support diff_method=None with the added benefit of not doing any more changes.

**Comment by glassnotes** [comment]
Hi @ankit27kh , this should work, please feel free to submit a PR!

**Comment by albi3ro** [comment]
I'm looking into fixing some unexpected behaviour with interface devices and finite shots, see Issue #1481 and Pull Request #1588 .  We can't take backpropogation gradients with finite shots.  In that situation, a user might still want to calculate finite shot values from an interface-specific circuit, but just never calculate any derivatives.  In that case, `diff_method=None` might be helpful.

**Comment by antalszava** [comment]
Just catching up with this issue: @glassnotes @josh146 I'm slightly concerned that now we'll have two ways to achieve the same thing here. Both
* `interface=None` and
* `diff_method=None`

would stand for the same thing based on the description.

Could you elaborate on why allowing `diff_method=None` would be preferable? If that's our choice, shall we not deprecate `interface=None`? I think having both options will lead to confusion and ambiguity.

**Comment by josh146** [comment]
@antalszava I'm fine with making minor quality-of-life improvements now, as the upcoming new differentiable pipeline will result in an overhaul of the `diff_method` and `interface` keyword arguments anyway (likely by v0.19). In particular:

- `diff_method` will accept a string (`device`, `backprop`) _or_ a gradient transform directly (`diff_method=qml.gradients.param_shift`).

- `interface` will likely be no longer needed - it is looking very likely that after this new differentiable pipeline is instituted, the interface can be inferred directly.

**Comment by ankit27kh** [comment]
@antalszava @josh146 
As discussed in the original issue, this is meant to be a simple patch to start support for `diff_method=None`, which is more intuitive than providing `interface=None` when we don't need gradient capabilities. 
Concretely, for the same effect, `interface=None` should be deprecated in favour of `diff_method=None`. But, this will require a lot more work than this simple fix. `diff_method=None` is not supported internally and requires numerous changes to work. On the other hand, `interface=None` is already perfectly integrated.

According to @josh146, there is a new pipeline in works that completely overhauls this. I think it best to leave the heavy-lifting for that.
