### ISSUE TITLE
Define decomposition for single and double excitation operations

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1275]
More elementary operations for single and double excitation functions have been added recently #1121 #1123.

These operations are supported by the `default.qubit` device. However, other devices from external plugins may not have support directly for these operations. In such cases, PennyLane turns to the decomposition of operations.

We would like to therefore add decomposition for the following operations:
* SingleExcitationPlus
* SingleExcitationMinus
* DoubleExcitationPlus
* DoubleExcitationMinus

**Comment by glassnotes** [comment]
This can be closed following the merge of #1303! :tada:
