### ISSUE TITLE
Fully parametrized gate

### ISSUE THREAD

**Issue by oumjunior** [PennyLaneAI/pennylane#1281]
Any gate (unitary 2x2 matrix) is fully determined given 4 parameters 
![image](https://user-images.githubusercontent.com/32430632/117337998-5b043400-ae9e-11eb-8a21-66e9cb00050f.png)
This "raw" format is used in qml circuits (for instance https://arxiv.org/pdf/1804.00633.pdf). Although the aforementioned format can be decomposed into RzRyRz with a relative phase, it would be handy to have it especially for qml.

Note that qml.QubitUnitary is general enough but, as far as I know, is not differentiable.

**Comment by josh146** [comment]
Hey @oumjunior! Have you tried using the [`qml.Rot`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Rot.html) gate? This gate is not decomposed on built-in simulators such as `default.qubit` (it is only decomposed when required, such as on hardware devices), and appears equivalent (up to a global phase factor) with the `G` gate above.

In particular, from having a look at the convention used,

```
G(alpha, beta, gamma, phi) = qml.Rot(gamma - beta, 2 * alpha, -gamma - beta)
```

**Comment by co9olguy** [comment]
Note that experimentally extractable outputs do not depend on the global phase, so there would be no observable difference in, e.g., the final expectation values when using `G` and `Rot`. 

One could observe a global phase if looking at `qml.state`. However, we do not enforce self-consistency of global phases in the gate decompositions, so the global phase you would see may not necessarily be the same one if you worked out by hand

**Comment by josh146** [comment]
Hey @oumjunior, did using `qml.Rot` solve this issue for you? Since these gates are equivalent (up to a global phase), I will close this issue for now. Feel free to re-open, or create a new one, if you have any more issues!
