### ISSUE TITLE
Anaconda

### ISSUE THREAD

**Issue by vsrikrishna07** [PennyLaneAI/pennylane#1285]
How to install pennylane in conda environment?? I was not able to install in Conda base packages. Kindly help.

**Comment by josh146** [comment]
HI @vsrikrishna07 - what error message were you receiving?

**Comment by vsrikrishna07** [comment]
Hi, I was not able to add the package on my anaconda base root itself. Can you guide me through it? Is there any command for conda prompt??

**Comment by vsrikrishna07** [comment]
Hi, I solved the issue on my own. Thanks and Cheers.
