### ISSUE TITLE
Calculation of circuit depth

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1293]
I think it would be a nice feature to expose functions to the user to conveniently compute the circuit depth of a `QNode` for a given device (and after PennyLane has done its just in time circuit compilation).

In principle this seems already possible via something like
```
import networkx
import pennylane as qml

dev = qml.device('default.qubit', wires=1)
@qml.qnode(dev)
def qnode(x, y):
    qml.RY(x, wires=0)
    qml.Hadamard(0)
    qml.RZ(y, wires=0)
    return qml.expval(qml.PauliZ(0))

qnode(1., 2.)

networkx.dag_longest_path_length(qnode.qtape.graph.graph)
```
but it would be nice if PennyLane could provide a `QNode` property (maybe `.circuit_depth`) to access this information. Ideally without having to execute the `QNode` first. Maybe the interface could be designed to match `qml.draw()`?

**Comment by josh146** [comment]
@albi3ro, can we close this with the addition of [`qml.specs`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.specs.html)?

**Comment by albi3ro** [comment]
Yep.
