### ISSUE TITLE
[unitaryhack] Define decomposition for `qml.CSWAP`

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1306]
*This issue has been tagged for contributions during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)*

Each PennyLane operation defines a decomposition. The decomposition of an operation is an ordered list of other operations. Applying this list of operations evolves quantum states the same way as applying the operation itself does. In most cases, this list includes elementary gates that are often supported by most quantum devices.

We would like to add the decomposition of the `qml.CSWAP` operation by:
1. Defining the decomposition method for [the `qml.CSWAP` operation](https://github.com/PennyLaneAI/pennylane/blob/1930230dde60112ad90af0951fa9295d374e1adf/pennylane/ops/qubit.py#L580) that has the following signature:
```python
    @staticmethod
    def decomposition(wires):
```
Other operations in the `pennylane/ops/qubit.py` file can serve as an example for defining this method (e.g., [see `qml.Hadamard`](https://github.com/PennyLaneAI/pennylane/blob/1930230dde60112ad90af0951fa9295d374e1adf/pennylane/ops/qubit.py#L87)).
2. Including a test case for the decomposition of `qml.CSWAP` in the `tests/ops/test_qubit_ops.py` file to verify its correctness.

**Comment by charmerDark** [comment]
Hey! I would like to have a crack at this.
What gates can I decompose the CSWAP into? Can I use the Toffoli or would you rather I break it down to Hadamard,CNOT and T gates? Also any tips on writing the tests?
Thanks for the opportunity!

**Comment by josh146** [comment]
Hi @charmerDark - you can have a look at some of the decomposition tests we have in [`test_qubit_ops.py`](https://github.com/PennyLaneAI/pennylane/blob/9687c130b7c4f758238859f2fe0dbb811a07825a/tests/ops/test_qubit_ops.py#L613). Essentially, the idea is to:

1. Decompose the operation
2. Multiply together the matrix representations of each operation in the decomposition
3. Make sure it agrees with the matrix representation of the CSWAP gate

**Comment by co9olguy** [comment]
Another possible landing spot (and reference) for gate tests:

https://github.com/PennyLaneAI/pennylane/blob/7680a48a8a93c5a2f24acd7204b8de83e41bc02e/tests/test_operation.py#L1034

**Comment by MaldoAlberto** [comment]
Hi @antalszava  I send a Pull requests about this issue, but I forgot to add the Unitaryhack label, is there any problem or should I resend it?

**Comment by josh146** [comment]
Hi @MaldoAlberto, I can add the label for you :)
