### ISSUE TITLE
Add the `IsingYY` operation

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1347]
**Context**

We would like to define a new operation called `IsingYY`, with the gradient recipe:
```python
* Gradient recipe: :math:`\frac{d}{d\theta}f(YY(\theta)) = \frac{1}{2}\left[f(YY(\theta +\pi/2)) - f(YY(\theta-\pi/2))\right]`
```
The operation is [defined in the PennyLane-Braket plugin](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/257eb99d62122e3a83c380ab240d6e166b2b9257/src/braket/pennylane_plugin/ops.py#L449).

**Steps to take**

*A. Adding the operation*

1. Adding the `IsingYY` class and its attributes to `pennylane/ops/qubit.py`. Complete its docstring in a similar fashion as for other operations. Make sure the class is accessible through `qml.IsingYY`.
2. Add its decomposition: a definition for how the operation could be decomposed into elementary operations (see note below),
3. Add its matrix, eigenvalues, adjoint and generator,
4. *Test:* include tests for the operation, its decomposition and its matrix in the `tests/ops/test_qubit_ops.py` file,
5. Add the operation to the [list of operations in the introduction docs](https://github.com/PennyLaneAI/pennylane/blame/master/doc/introduction/operations.rst#L77).

*B. Adding `default.qubit` support*

5. Add support for the operation in the `default.qubit` device,
6. *Test:* test the operation with `default.qubit` in the `tests/devices/test_default_qubit.py` file.

See issues for `IsingXX` and `IsingZZ`: #1149 #1148

**Comment by nahumsa** [comment]
Hi! I would like to solve this issue! 😄 

Should I also add `IsingXX` to other devices as well, or just implement for `default.qubit`?

**Comment by paniash** [comment]
Hi! I would like to try my hand at this issue as well. :-)

**Comment by josh146** [comment]
@nahumsa for this issue, adding it to `default.qubit` is sufficient, but feel free to add it to additional devices!

@paniash great to see such enthusiasm 🙂 Definitely feel free to give it a go, or you could also join up with @nahumsa if you would like to tackle it as a team.

**Comment by paniash** [comment]
@josh146 Thanks a lot! @nahumsa Would you like to team up? I've made a draft PR for the same [here](https://github.com/PennyLaneAI/pennylane/pull/1358).

**Comment by nahumsa** [comment]
@paniash sure, that would be awesome! :)
