### ISSUE TITLE
Change order of technical description and list of functions in documentation

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/pennylane#1365]
Three modules, [`kernels`](https://pennylane.readthedocs.io/en/latest/code/qml_kernels.html), [`grouping`](https://pennylane.readthedocs.io/en/latest/code/qml_grouping.html), and [`qaoa`](https://pennylane.readthedocs.io/en/latest/code/qml_qaoa.html) have their module documentation ordered such that there is first a lengthy description of the theory, and the actual list of functions comes after. We should update the docs of these modules so that the functions appear *first*, and the technical details come afterwards (as was recently discussed in #1160). This will improve readability of the documentation and make it easier to find the details of a desired function.

**Comment by n45800** [comment]
Can i help on this ?

**Comment by glassnotes** [comment]
@n45800 absolutely! Please go right ahead, and feel free to let us know if you have any questions :grin:

**Comment by AkashNarayanan** [comment]
Hi! Can I still work on this issue?

**Comment by glassnotes** [comment]
@AkashNarayanan for sure, but perhaps we should check in first with @n45800 to make sure there is not a PR in the works that will be posted soon.

**Comment by n45800** [comment]
Hi , Akash yes you can work, unfortunately i am too busy these days to do
the update

**Comment by AkashNarayanan** [comment]
Sorry for the late response! I will start working on this issue now.

**Comment by antalszava** [comment]
Just tagged this issue for the Code Together event. A successful submission will award swag. :slightly_smiling_face: See the [blog post about the event for more details](https://pennylane.ai/blog/2021/07/pennylane-code-together/).
