### ISSUE TITLE
Matrix-valued parameters, ragged nested sequences, and tapes

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1369]
In attempting to fix a failing test on a PR, I have been bumping up against unexpected behaviour and a deprecation warning.

This code modified from a device test

```python
import pennylane as qml
from pennylane import numpy as np

dev = qml.device('default.qubit', wires=2)

theta = 0.432
phi = 0.123
A_ = np.array(
    [
        [-6, 2 + 1j, -3, -5 + 2j],
        [2 - 1j, 0, 2 - 1j, -5 + 4j],
        [-3, 2 + 1j, 0, -4 + 3j],
        [-5 - 2j, -5 - 4j, -4 - 3j, -6],
    ]
)

@qml.qnode(dev, diff_method='finite-diff')
def circuit(theta, phi):
    qml.RX(theta, wires=[0])
    qml.RX(phi, wires=[1])
    qml.CNOT(wires=[0, 1])
    return qml.expval(qml.Hermitian(A_, wires=[0, 1]))

qml.grad(circuit, argnum=[0,1])(theta, phi)
```
raises 

```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```

due to [a line in `JacobianTape.jacobian`](https://github.com/PennyLaneAI/pennylane/blob/23b194ea61dd4158478ce06ef7f4719105f20b57/pennylane/tape/jacobian_tape.py#L515) that casts the parameters to a numpy array.  The entire `A_` matrix is considered one parameter since it occupies one tape slot.

Should we treat matrix-valued parameters differently in the tape? Or should we just live with the warning?

Context: I want to cast all parameters to `np.float64` before calculating the `"y0"` used for finite-differences.

**Comment by antalszava** [comment]
@albi3ro I'm not so sure we ended up adding support for differentiating `qml.Hermitian`. Historically, with the old core, it was not differentiable. So I'd think we need `requires_grad=False` here, though quite likely @josh146 will be able to verify and extend on this.

**Comment by josh146** [comment]
Yep @antalszava that's correct. Currently, the PennyLane `autograd` interface assumes `requires_grad=True` by default. So that is why the `A` matrix ends up being considered a parameter on the tape.

@albi3ro, this can be fixed for now by simply being explicit and stating `A_ = np.array(..., requires_grad=False)`.

Long term, the best solution here is to change to assuming `requires_grad=False` by default, like how PyTorch does. While making this particular case more intuitive, it also has a lot of other advantages across the stack.

**Comment by albi3ro** [comment]
We could rethink `Hermitian`.  If we don't want `Hermitian` to ever be differentiable, we can set the passed variables as something other than `parameters`, like `op._matrix`.  We would just need to re-write the constructor.

Something like:

```python
class Hermitian(Observable):
    def __init__(self, matrix, wires=None, do_queue=True):
        super().__init__(self, wires=wires, do_queue=do_queue)

        if A.shape[0] != A.shape[1]:
            raise ValueError("Observable must be a square matrix.")
        if not np.allclose(A, A.conj().T):
            raise ValueError("Observable must be Hermitian.")

        self._matrix = matrix
```

**Comment by albi3ro** [comment]
Seems to no longer be an issue with the new return types specification.
