### ISSUE TITLE
[New-Feature]Adding Docker Support to Pennylane

### ISSUE THREAD

**Issue by arshpreetsingh** [PennyLaneAI/pennylane#1372]
#### Issue description
Just wanted to know if Docker-Support is in Check-list, I would be able to add Docker-Support for Pennylane. 

Adding Dockerfile to Build penylane using Docker.

* *Expected behavior:* 
Build and entire system using Docker. 

## To build from source 

``` docker build -t pennylane:docke_build . ``` 

## To Run Python script using pennylane

``` docker run -it --rm -v $PWD:/tmp -w /tmp pennylane/pennylane python ./script.py ```

## To Run pennylane as-Service using jupyter. 

  ``` docker run -it -p 8888:8888 pennylane/pennylane:nightly-jupyter```

#### Additional information

Other Libraries doing it: 

Pytorch: https://github.com/pytorch/pytorch/blob/master/Dockerfile

Tensorflow: https://www.tensorflow.org/install/docker

**Comment by josh146** [comment]
Hi @arshpreetsingh, docker support would be great :)

Do you have docker support for PennyLane already working locally?

**Comment by arshpreetsingh** [comment]
Hi @josh146  This is the dockerfile working for me(Although have not tested thoroughly)
https://github.com/arshpreetsingh/pennylane/blob/docker-support/Dockerfile

To build an Image, keep dockerfile into pennylane root and run following:
``` docker build -t pennylane . ```
to test pennylane after image build run following. 
``` docker run -it --rm pennylane python -c "import pennylane; print(pennylane.__version__)" ```

**Comment by albi3ro** [comment]
We could create dockerfiles for different sets of additional packages, like plain pennylane, pennylane+tensorflow, all interfaces packages, or pennylane-qchem plus all qchem packages.

**Comment by josh146** [comment]
Thanks @arshpreetsingh!

> We could create dockerfiles for different sets of additional packages, like plain pennylane, pennylane+tensorflow, all interfaces packages, or pennylane-qchem plus all qchem packages.

This would be great. Although, would there be a downside to providing a dockerfile with _all_ interfaces/plugins? Akin to the CI environment.

**Comment by albi3ro** [comment]
Size.  Tensorflow and torch can be pretty large.

**Comment by arshpreetsingh** [comment]
@albi3ro  Agree with Size, Will be raising PR shortly for Docker-implementation.
@josh146 
Wanted to confirm one thing before going further, Should docker builds be handled from Makefile? like ``` make build docker-pennylane``` or for TensorFlow, Pytorch etc something like ``` make build docker-pennylane-tf ``` or ``` make build docker-pennylane-torch```

with this docker-builds could be handled from Existing Makefile and end-user will not have to remember docker-commands to Ruild,Run or may be deploy in future. :)

**Comment by josh146** [comment]
Hi @arshpreetsingh, it certainly sounds nice to include in a makefile!

Before jumping straight into the PR, perhaps it might make sense to explore how other open-source projects with similar range of dependencies integrate docker support?

For instance, I had a look at the PyTorch repo, and they have:

- A top level `Dockerfile` that includes all optional dependencies as far as I can tell: https://github.com/pytorch/pytorch/blob/master/Dockerfile
- A file `docker.Makefile` containing the make instructions for building the docker images: https://github.com/pytorch/pytorch/blob/master/docker.Makefile
- A separate directory `docker` containing additional dockerfiles: https://github.com/pytorch/pytorch/tree/master/docker

TensorFlow has an even more complicated process where the dockerfiles are created programmatically! https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dockerfiles

So maybe it makes sense (for now) to have a separate `docker` directory to contain all docker related files/docs?

**Comment by arshpreetsingh** [comment]
Hi @josh146  Thanks for great ideas! I was also thinking about referencing Pytorch's Docker-implementation as guidance, Yes Dockerfiles from TensorFlow are partially generated programmatically (which comes with Broad-Range of GPU and OS support). 
But I feel we can start with Simple implementation first. I was thinking of Following implementations. 

1. **Simple-Pennylane** : Docker build using Official Python3.7 as base image (Alpine or Slim-buster) https://hub.docker.com/_/python/
Usually Alpine has smaller build size but sometimes GPU device support could be limited. 

2. **Pennylane+Pytorch**: Using Official Pytorch_conda_build as base Image (https://hub.docker.com/r/pytorch/conda-builder/tags?page=1&ordering=last_updated)

3. **Pennylane+tensorFlow** : Using Official Tensorflow image based on Ubuntu 18.04 https://hub.docker.com/r/tensorflow/tensorflow  

Somewhat similar approach for other-Plugins like Qiskit, cirq, Pyquil etc if official images will be available. 

Using above approach we can control Build easily from Makefile using following commands.

``` make build pennylane-base ``` # just base image for pennylane (One needed to run it for sure)

```make build pennylane-<Plugin-Name>``` # If someone wants Extra-plugin Support with pennylane-base-image

All required Dockerfiles will be inside /docker directory and docker.Makefile will be on root level (So just like Pytorch)

Looking forward for your views on that.

**Comment by josh146** [comment]
Thanks @arshpreetsingh! I think that sounds like a great plan, especially re-using existing TF and Torch images.

With respect to the interfaces, I think it makes sense to have separate docker files, since in most cases users will only be using a single ML framework, which is their framework of choice.

For plugins, however, it is a little more complicated:

- Build requirements will depend on the external repos
- I can imagine situations where users might want to use *multiple* plugins

So maybe best, for now, to provide docker files for PL + different ML frameworks, and consider device plugins a bit further down the line?

**Comment by albi3ro** [comment]
At some point, we should also consider doing this for `pennylane-qchem` and all the qchem dependencies.

**Comment by arshpreetsingh** [comment]
@albi3ro  Well I have completed pennylane-plain, Pennylane-TF and Pennylane-Torch docker images,  Will be able to share those by tomorrow for review.

As I can see Qchem has script for dependencies installation(https://github.com/PennyLaneAI/pennylane/blob/master/qchem/install-dependencies.sh) which could be easily reused for creation of Dockerfile for   pennylane-Qchem.

**Comment by josh146** [comment]
Nice, I think having qchem dockerfiles is a great idea

**Comment by arshpreetsingh** [comment]
@josh146  @albi3ro  PR is Ready!
Able to create Following builds. 
1. Base-Pennylane
2. Pennylane+Tensorflow
3. Pennylane+torch
4. Pennylane+Jax
5. Pennylane_Tensorflow+GPU support
6. Pennylane_Torch+GPU support
7. Pennylane_Jax+GPU support
8. Qchem! (at last but not least :) )
Looking for reviews on that.

**Comment by trbromley** [comment]
Thanks @arshpreetsingh, we have linked https://github.com/PennyLaneAI/pennylane/pull/1391 so that it will automatically close this issue once merged :smile:
