### ISSUE TITLE
operation adjoint and inverses

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1379]
Right now, we have two separate ways for inverting/ adjoint-ing an operation:

* `op.inv()`: toggle `op._inverse` boolean for `op` instance
* `op.adjoint()`: returns a new class instance determined on a per-op basis

I would expect that these two things should be the same for unitary operations:

```python
op = qml.RY(0.1, wires=0).inv()

op_inv = op.adjoint()
print(op_inv.matrix)

op.inv()
print(op.matrix)
op.inv()
```

For already inverted operations, they are not.  No implementation of `adjoint` takes into account the `op._inverse` attribute.

We could either change the implementation of `op.adjoint` for each type of operation, or we could instead redefine the Base Class `Operation` so that `adjoint` always returns a new class instance with `inv` toggled.

Also, this choice will affect the `operation_derivative` convention.  Currently, these two quantities are not equal, though I intuitively expect them to be:

```python
print(qml.operation.operation_derivative(op_inv))

op.inv()
print(qml.operation.operation_derivative(op))
op.inv()
```

**Comment by josh146** [comment]
Nice catch @albi3ro!

**Comment by albi3ro** [comment]
I wanted to used 'adjoint' mainly for readability and reducing potential for sneaky errors.

When using 'op.inv()', you have to remember to return it to its original form through another application of 'op.inv()'. 

Also, while it's inverted, the name of the op is still just 'op'. For readability, it'd be nice to see, "here i'm using the inverted operation" clearly by having a variable 'op_inv'. 

This came up working with the adjoint methods. I can assume there'd be other cases when someone wants to use 'op' and 'op.inv()' together at the same time.

**Comment by josh146** [comment]
Yes, this is a good point - `op.adjoint()` is definitely advantageous in that it does not modify the device in-place, it just returns a new one. 

> redefine the Base Class Operation so that adjoint always returns a new class instance with inv toggled.

Do you think this suggestion is the way to go?

**Comment by albi3ro** [comment]
I like the idea of having one method edit the op in-place and one method returning a new instance that's inverted. 

I do wonder though about the names for `inv` versus `adjoint`. Those terms don't make clear which one is which.  For most gates, these two will be equivalent. `op.matrix` even calculates an inverted matrix by performing `op_matrix.conj().T`, which is technically taking the adjoint instead of taking the inverse.

I also see that the `Operation` class abstract definition of `adjoint` has the keyword `do_queue` for "Whether to add the adjointed gate to the context queue", but none of the implementations for `adjoint` in `qubit.py` have that keyword.  Try to use the documented keyword with the method, and you get an error.

**Comment by albi3ro** [comment]
Thinking about it more, we could have just one method, `op.inv`, but have a keyword `inplace=True`.  If the user specifies `op.inv(inplace=False)` then it returns a new instance with opposite `op._inverse` value leaving `op` untouched.

**Comment by josh146** [comment]
Oh, cool idea. I have to admit, I'm on the fence:

- On the one hand, I like it; it streamlines everything down to a single access point.
- On the other hand, I'm a bit uneasy having a single method that performs such different logic depending on a keyword argument?

**Comment by albi3ro** [comment]
To me, they seem like they're doing the same thing. The only thing that's different is in place versus return modified copy. 

Most of the time people will probably just continue using the in-place version, but for some special cases, people may just find it easier to work with an inverted copy.  Like how I want an inverted copy for the adjoint method.

**Comment by dwierichs** [comment]
It seems like this issue is closed because `Operator.inv` no longer exists? :thinking: 
@albi3ro

**Comment by albi3ro** [comment]
Thanks for finding this.
