### ISSUE TITLE
More informative QNode `diff_method`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1399]
Currently, QNode's have an attribute `diff_method` that captures the user-provided `diff_method` keyword or the default `"best"`.  

If `diff_method=="best"`, then the class will determine which differentiation method to use based on a combination of various things like device and interface.

But the attribute `diff_method` is not updated with this choice. To find which method actually got used, we need to query `qnode.qtape.jacobian_options['method']`, which is unnecessarily complicated for a fairly central piece of information.

Example:

```python
dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circ(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

print(circ.diff_method)
circ(0.1)
print(circ.qtape.jacobian_options['method'] )
```

```
best
backprop
```

I propose we update `QNode.diff_method` once a differentiation method is chosen. 

----

*List of tasks for completion:*

1. Update the logic of the QNode such that the `diff_method` attribute is updated after tape construction, once the `QNode.qtape.jacobian_options['method']` information is available;
2. Add unit and integration tests that test the new functionality and check multiple differentiation methods.

**Comment by josh146** [comment]
Great idea, this will also help a lot with testing and debugging

**Comment by nahumsa** [comment]
Hi! Can I work on this issue? :)

**Comment by antalszava** [comment]
Hi @nahumsa, sure! :slightly_smiling_face: It looks that @ankit27kh was also giving this a go. If multiple PRs are submitted, then we accept the first that is merge-ready. Alternatively, you could also submit a solution as a team. Let us know if you have any questions!

**Comment by ankit27kh** [comment]
I request the maintainers to have a look at #1568 
It does not do exactly what the issue demands but I think this is what is being intended.

**Comment by ankit27kh** [comment]
```
dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circ(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

print(circ.diff_method)
circ(0.1)
print(circ.qtape.jacobian_options['method'] )
```
`circ.diff_method` and `circ.qtape.jacobian_options['method']` are not same.
It's easier to see it if you try this:
```
dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev, diff_method='parameter-shift')
def circ(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

print(circ.diff_method)
print(circ)
circ(0.1)
print(circ.qtape.jacobian_options['method'])
print(circ)
print(circ.diff_method)
```
This results in:
```
parameter-shift
<QNode: wires=2, device='default.qubit', interface='autograd', diff_method='parameter-shift'>
analytic
<QNode: wires=2, device='default.qubit', interface='autograd', diff_method='parameter-shift'>
parameter-shift
```

**Comment by ankit27kh** [comment]
Even in the original example, if you try `circ.diff_method' after `print(circ.qtape.jacobian_options['method'] )`, you'll still get "best".
