### ISSUE TITLE
Log the number of shots a device used

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1408]
In addition to counting the number of qnode calls/executions of a device via `num_executions`, it would be nice to count the number of shots a device used overall.
While this can easily be obtained via `num_shots=device.num_executions * device.shots` if the same number of shots was used for all executions, it is currently not possible to access the same quantity if `device.shots` was altered at some point since resetting `device.num_executions`.

`num_shots` could be a simple attribute like `num_executions` which is updated with `+= self.shots` instead of `+= 1`.

**Comment by albi3ro** [comment]
I've got a device tracker as a work in progress. In addition to tracking executions and shots, it can track any additional information relevant to a specific device and record the information on a per execution basis. Record being silent, print to console, or logging as the user chooses. 

Stay tuned!

**Comment by dwierichs** [comment]
Amazing, thanks! Sorry, I only checked the issues and not the PRs.
