### ISSUE TITLE
`default.tensor` does not return correlated samples

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#1419]
Consider the following QNode:

```python
def circuit():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return [qml.sample(qml.PauliZ(i)) for i in range(2)]
```

The end state of this device is `|00> + |11>`, so the output samples on each wire should be correlated; either both should be -1, or both should be 1:

```pycon
>>> dev = qml.device("default.qubit", wires=2, shots=10)
>>> qnode = qml.QNode(circuit, dev)
>>> qnode()
array([[ 1, -1,  1, -1,  1,  1, -1, -1,  1,  1],
       [ 1, -1,  1, -1,  1,  1, -1, -1,  1,  1]])
```

However, `default.tensor` currently samples from each wire independently, resulting in no correlation:

```pycon
>>> dev = qml.device("default.tensor", wires=2, shots=10)
>>> qnode = qml.QNode(circuit, dev)
>>> qnode()
array([[ 1., -1., -1.,  1., -1., -1., -1.,  1., -1., -1.],
       [-1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1.]])
```

This issue would be resolved by porting `default.tensor` to `QubitDevice`, which has support for sampling with correlations built-in.

**Comment by antalszava** [comment]
Closing this as `default.tensor` is being removed as of v0.20.0.
