### ISSUE TITLE
Parameter-shift Hessian of multi-observable circuits incorrect

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1424]
#### Issue description

Consider a circuit with an iterable of `qml.expval`s returned and a cost function that sums this iterable (using the PennyLane version of numpy):

```python
dev = qml.device('default.qubit', wires=1)

@qml.qnode(dev, diff_method='parameter-shift')
def _circ(param):
    qml.RX(param[0], wires=0)
    return [qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(0))]

circ = lambda p: np.sum(_circ(p))
```
Now evaluate the second order derivative of this circuit, once via manual finite difference, once via parameter shifts:
```python
param = np.random.random(1)
delta = 1e-5
print(((circ(param+delta)-circ(param))/delta-(circ(param)-circ(param-delta))/delta)/delta)
>>> -1.957101147809226
print(qml.jacobian(qml.jacobian(circ))(param))
>>> -3.91459319
```
We consistently find the latter output to be twice the correct value. When switching to `diff_method='backprop'`, the finite difference and the `qml.jacobian(qml.grad(circ))` results coincide.

For larger parameter spaces, the full Hessian is off by the same factor `2`, i.e. both off-diagonal and diagonal entries are affected likewise.

* *Expected behavior:* (What you expect to happen)
Hessian computed via parameter shifts should match the one computed via backprop/the manually computed value.

* *Actual behavior:* (What actually happens)
The parameter shift Hessian is twice as large as the exact value.

* *Reproduces how often:* (What percentage of the time does it reproduce?)
Always

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

```python
Name: PennyLane
Version: 0.15.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/david/venvs/xanadu/lib/python3.8/site-packages
Requires: autograd, numpy, scipy, networkx, appdirs, semantic-version, toml
Required-by: PennyLane-SF, pennylane-qulacs, PennyLane-qiskit, PennyLane-Qchem, PennyLane-Forest, PennyLane-Cirq
Platform info:           Linux-5.4.0-74-generic-x86_64-with-glibc2.29
Python version:          3.8.5
Numpy version:           1.18.5
Scipy version:           1.6.3
Installed devices:
- default.gaussian (PennyLane-0.15.1)
- default.mixed (PennyLane-0.15.1)
- default.qubit (PennyLane-0.15.1)
- default.qubit.autograd (PennyLane-0.15.1)
- default.qubit.jax (PennyLane-0.15.1)
- default.qubit.tf (PennyLane-0.15.1)
- default.tensor (PennyLane-0.15.1)
- default.tensor.tf (PennyLane-0.15.1)
- strawberryfields.fock (PennyLane-SF-0.15.0)
- strawberryfields.gaussian (PennyLane-SF-0.15.0)
- strawberryfields.gbs (PennyLane-SF-0.15.0)
- strawberryfields.remote (PennyLane-SF-0.15.0)
- strawberryfields.tf (PennyLane-SF-0.15.0)
- qulacs.simulator (pennylane-qulacs-0.15.0)
- qiskit.aer (PennyLane-qiskit-0.15.0)
- qiskit.basicaer (PennyLane-qiskit-0.15.0)
- qiskit.ibmq (PennyLane-qiskit-0.15.0)
- forest.numpy_wavefunction (PennyLane-Forest-0.15.0)
- forest.qvm (PennyLane-Forest-0.15.0)
- forest.wavefunction (PennyLane-Forest-0.15.0)
- cirq.mixedsimulator (PennyLane-Cirq-0.15.0)
- cirq.pasqal (PennyLane-Cirq-0.15.0)
- cirq.qsim (PennyLane-Cirq-0.15.0)
- cirq.qsimh (PennyLane-Cirq-0.15.0)
- cirq.simulator (PennyLane-Cirq-0.15.0)
```

**Comment by albi3ro** [comment]
Taking a look.

**Comment by albi3ro** [comment]
Pretty sure the problem is on [interfaces/autograd.py Line 262](https://github.com/PennyLaneAI/pennylane/blob/25284ed58880fa6658676d2184eff5dd4503d699/pennylane/interfaces/autograd.py#L262).

But I never quite understood that line in the first place, so I'll try and work out what that line is supposed to be.

**Comment by josh146** [comment]
Ah, I can provide some insight, but not all unfortunately.

* In the case that the QNode simply returns a scalar, then `dy == [1]`, and the vector-Hessian product is simply `ddy @ hessian`.

* If the QNode instead returns a _vector_, then this section of the code will be called twice. The first time with `dy = [1, 0]` (I believe), and the second time with `dy = [0, 1]`. Hence why we contract with `dy`: `vhp = dy @ ddy @ hessian @ dy.T`.

I wonder if this line is missing a normalization factor? We have tests where this line passes, so maybe the normalization is `dy`/`ddy`/`ans` dependent?
