### ISSUE TITLE
Feature Request for Additional Ansatzes in Quantum Chemistry

### ISSUE THREAD

**Issue by ChrisW918** [PennyLaneAI/pennylane#1428]
I tried to test VQE algorithm for calculating the ground state energy of an arbitary molecule, using UCCSD as ansatz and existing Optimizer in NumPy interface.

And I would like to apply for additional ansatzes such as _UCCS_, _Hardware efficient_, and _UCCD_ to compare the results with.

Since intuitatively UCCS may contribute to more accurate energy in some Hydro-based models, and it appears these ansatzes provide users more options to test.

**Comment by ixfoduap** [comment]
Hi @ChrisW918, thank you for this suggestion.

Our team has indeed been looking at new templates for quantum chemistry, although we are pursuing different ansatze than the ones you are suggesting.

More recently, we added the [AllSinglesDoubles](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.subroutines.AllSinglesDoubles.html) ansatz, which is similar to UCCSD, but much more efficient. Perhaps you can start there to perform comparisons.

We are also steering our users to implement adaptive circuits, following similar strategies to the one outlined in [this paper](https://www.nature.com/articles/s41467-019-10988-2). Here the idea is to calculate the gradient of single and double excitation operations with respect to the cost function, and keep only those whose gradient is sufficiently large. This is something else you could try. 

Finally, we are planning to implement the circuit architecture introduced in [this paper](https://arxiv.org/abs/2104.05695). We'll keep you posted as we make progress on that front

**Comment by ChrisW918** [comment]
That's great! @ixfoduap Thanks for reply.
