### ISSUE TITLE
Temporarily setting shots for gradient

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1432]
Currently, you can temporarily set the number of shots for a circuit execution by passing in the keyword `shots`:

```
circuit(x, shots=10)
```

We should be able to do the same thing for a parameter-shift gradient calculation:

```
qml.grad(circuit)(x, shots=10)
```

Currently, this only alters the first circuit execution, before reverting to the default for the parameter-shift executions.  It may be useful to alter the shots information for the entirety of the parameter-shift calculation.

**Comment by josh146** [comment]
Good catch, I remember @mariaschuld and I discussing this during the shots refactor!

This is one of those cases where TF/Torch need to be treated more carefully than Autograd and JAX, since the backward pass can be performed independently of the forward pass.

**Comment by albi3ro** [comment]
@josh146  Should we go ahead and close this then?
