### ISSUE TITLE
Update the resolution of the `qml.CY` operation when drawn

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1443]
**Context**

When drawing a circuit that contains a `qml.CY` operation, there is no distinction between the control and target qubits, both qubits are represented with the `CY` string. This is in contrast with how other controlled operations are drawn. As examples, for the `qml.CNOT` and `qml.CZ` operations, a `C` character represents the control qubit and an `X` or `Z` character represents the target qubit respectively.

```python
dev = qml.device('default.qubit', 2)

@qml.qnode(dev)
def my_circuit():
    qml.CNOT(wires=[0,1])
    qml.CY(wires=[0,1])        # <--- the operation for which we'd like to change the representation
    qml.CZ(wires=[0,1])
    return qml.expval(qml.PauliZ(0))

my_circuit()

print(my_circuit.draw())
```
```
 0: ──╭C──╭CY──╭C──┤ ⟨Z⟩ 
 1: ──╰X──╰CY──╰Z──┤     
```
Whereas, we would like this circuit to be resolved as:
```
 0: ──╭C──╭C──╭C──┤ ⟨Z⟩ 
 1: ──╰X──╰Y──╰Z──┤     
```
**Changes to make**

Update the resolving of the `CY` operation such that a `C` character represents the control and a `Y` character represents the target qubit.

**Comment by Zer0points** [comment]
Hi, could I pick up this issue?

**Comment by antalszava** [comment]
Hi @zer0points, sure, thanks for the interest! :slightly_smiling_face: Let us know if you'd have any questions regarding how the circuit drawer is working.
