### ISSUE TITLE
All controlled operations should belong to the class `Controlled`

### ISSUE THREAD

**Issue by rmoyard** [PennyLaneAI/pennylane#1447]
#### Issue description

Most of controlled gates are not in the `ControlledOperation` class, therefore you cannot easily check if an operation is controlled and you cannot access the control wires directly if you don't know the operation. Because of this behavior, it is complicated to write algorithms that use the fact that certain gates are controlled or not. Every controlled operation should be built from a target operation and a set of control wires within the class `ControlledOperation`.

* *Expected behavior:* (What you expect to happen)
A small example of what we should expect from any controlled operation:
```
op = qml.Toffoli(wires=[1,2,0])
print(isinstance(operation, ControlledOperation))
>>> True
print(op.control_wires())
>>> Wires(1,2)
print(op.target_wires())
>>> Wires(0)
print(op.target_operation)
>>> PauliX
```

* *Actual behavior:* (What actually happens)

```
op= qml.Toffoli(wires=[1,2,0])
print(isinstance(operation, ControlledOperation))
>>> False
```

I have started to work on this issue in the commutation DAG PR: https://github.com/PennyLaneAI/pennylane/pull/1446

**Comment by josh146** [comment]
@glassnotes correct me if wrong, but I believe this issue is still open?

**Comment by glassnotes** [comment]
Yes! I didn't expect the PR to close it.

**Comment by albi3ro** [comment]
`ControlledOperation` has been replaced by `qml.ops.op_math.Controlled` and the `Operation` version `ControlledOp`. We have managed to move over `ControlledQubitUnitary` to inherit from `ControlledOp`. 

We could continue to move over all controlled operations to inherit from this class and remove a vast amount of duplicated code, but it is currently not that high of a priority.

**Comment by astralcai** [comment]
Fixed
