### ISSUE TITLE
QFT adjoint operator does not work

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/pennylane#1448]
#### Issue description

When I try to perform the inverse of the QFT operator, it does not include it in the circuit (and no error appears).

#### Source code and tracebacks

```python
@qml.qnode(dev)
def circ():
    qml.PauliX(wires = 1)
    qml.adjoint(qml.QFT)(wires = range(N))
    qml.QFT(wires = range(N))
    return qml.state()

print(qml.draw(circ)())
print(circ())
```
This is the output:

 0: ─────╭QFT──╭┤ State 
 1: ──X──╰QFT──╰┤ State 

[ 5.00000000e-01+0.000000e+00j  3.06161700e-17+5.000000e-01j
 -5.00000000e-01+6.123234e-17j -9.18485099e-17-5.000000e-01j]

**Comment by antalszava** [comment]
Hi @KetpuntoG, thanks for reporting this! :100: We'll take a look. :slightly_smiling_face:
