### ISSUE TITLE
`qml.fourier.coefficients` won't  work with more than one expectation value

### ISSUE THREAD

**Issue by PCesteban** [PennyLaneAI/pennylane#1449]
#### Issue description

When I try to calculate the Fourier coefficients with the new module `qml.fourier` if the circuit has more than one measurement an error appears.

#### Code:
```python
import pennylane as qml
from pennylane import numpy as np
from pennylane.fourier import coefficients

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def simple_circuit(x):
    qml.RX(x[0], wires=0)
    qml.RY(x[0], wires=1)
    qml.CNOT(wires=[1, 0])
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1))


coeffs = coefficients(simple_circuit, 1, 2)
print(np.round(coeffs, decimals=4))
```
#### Output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-111-8c2ae78fdea3> in <module>
     13 
     14 
---> 15 coeffs = coefficients(simple_circuit, 1, 2)
     16 print(np.round(coeffs, decimals=4))

~/.local/lib/python3.8/site-packages/pennylane/fourier/coefficients.py in coefficients(f, n_inputs, degree, lowpass_filter, filter_threshold)
    154     """
    155     if not lowpass_filter:
--> 156         return _coefficients_no_filter(f, n_inputs, degree)
    157 
    158     if filter_threshold is None:

~/.local/lib/python3.8/site-packages/pennylane/fourier/coefficients.py in _coefficients_no_filter(f, n_inputs, degree)
    228 
    229         # fill discretized function array with value of f at inpts
--> 230         f_discrete[tuple(nvec)] = f(sample_points)
    231 
    232     coeffs = np.fft.fftn(f_discrete) / f_discrete.size

ValueError: setting an array element with a sequence.
```

**Comment by antalszava** [comment]
Hi @PCesteban, thank you for posting! We'll have a look at it.

**Comment by mariaschuld** [comment]
@PCesteban I am curious what your use case is here? If I am not mistaken, a Fourier series is only defined for a function (in the mathematical sense), which is a map from inputs to a scalar output. 

I made a PR to be more clear in the docs that a QNode must return a scalar for this to work, which is intended behaviour.

**Comment by PCesteban** [comment]
Hi @mariaschuld,  I was just checking the new features and trying different things, and I thought it would be possible to calculate the coefficients for two expectation values of the same circuit since this can be done separately and the result is different for each case. 

Just to clarify, if I want to see the representation of a complete quantum model in Fourier series, to calculate the coefficients a single expectation value is enough? it doesn't matter if my circuit has measurements in all its qubits?

**Comment by PCesteban** [comment]
> @PCesteban I am curious what your use case is here? If I am not mistaken, a Fourier series is only defined for a function (in the mathematical sense), which is a map from inputs to a scalar output.

Hi @mariaschuld,  I was just checking the new features and trying different things, and I thought it would be possible to calculate the coefficients for two expectation values of the same circuit since this can be done separately and the result is different for each case. 

Just to clarify, if I want to see the representation of a complete quantum model in Fourier series, to calculate the coefficients a single expectation value is enough? it doesn't matter if my circuit has measurements in all its qubits?

**Comment by glassnotes** [comment]
Hi @PCesteban ,

> Just to clarify, if I want to see the representation of a complete quantum model in Fourier series, to calculate the coefficients a single expectation value is enough? it doesn't matter if my circuit has measurements in all its qubits?

Yes that's correct - the expectation value could be something like `qml.expval(qml.PauliZ(0) @ qml.PauliX(1) @ qml.PauliY(2)...)`, the only restriction is that there is just the one. As Maria mentioned this is just a consequence of how the Fourier series/transform is defined; the circuit plays the role of the multi-input function, and the measured expectation value is the scalar output.

**Comment by PCesteban** [comment]
I see... Thank you @glassnotes !! 🙏

**Comment by mariaschuld** [comment]
@PCesteban let us know if you pick up anything else, your feedback is very valuable!

**Comment by PCesteban** [comment]
Sure!, I will.
