### ISSUE TITLE
Parameters in MultiControlledX

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1452]
As I was inspecting the `MultiControlledX` gate, I noticed how it printed out:

```
MultiControlledX(array([[0, 1],
       [1, 0]]), wires=[0, 1, 2, 3])
```

And was quite confused as to where the array came from.  It turns out `MultiControlledX` inherits from `ControlledQubitUnitary` with the Unitary matrix as an X gate. This makes `MultiControlledX` a parametrized gate.  

Worse yet, that gate is trainable:

```
>>> with qml.tape.JacobianTape() as tape:
...    qml.MultiControlledX(control_wires=(0,1,2), wires=(3))
>>> tape.trainable_params
{0}
```

This further indicates to me that how we treat never trainable parameters needs fixing in the long run.

In the short term, we should just remove the inheritance on `ControlledQubitUnitary`.

This would involve duplicating only relevant code in `ControlledQubitUnitary` and changing the inheritance to `Operation`.

----

*List of tasks for completion:*

1. Change the `MultiControlledX` operation such that it doesn't inherit from `ControlledQubitUnitary` anymore;
2. Include logic in `MultiControlledX` that is required for its full functionality;
3. Adjust any tests as required.

**Comment by tgag17** [comment]
Hi! Can I work on this issue?

**Comment by albi3ro** [comment]
Thanks @tgag17 ! 👍

I assigned you the issue.  Feel free to ask any additional questions here or when you open a PR.

**Comment by anushkrishnav** [comment]
It's been 2 weeks already is someone working on it or can I contribute?

**Comment by tgag17** [comment]
Hi @anushkrishnav! I am working on it. Actually I was busy with some exams last week and am planning to make a PR this week.

**Comment by albi3ro** [comment]
Thanks for the update @tgag17 .

@anushkrishnav , we have multiple other [good first issues](https://github.com/PennyLaneAI/pennylane/contribute) and are adding more all the time. If you don't see something promising right now, you can check back later and maybe we'll have added something.

**Comment by albi3ro** [comment]
@tgag17 I'd just like to let you know about the pending reorganizing of the qubit operations in PR #1467 .  Currently, `MultiControlledX` will be moved to the `matrix_ops`.  Once it no longer inherits from `ControlledQubitUnitary`, it can be moved to the `non_parametric_ops.py` file.

**Comment by tgag17** [comment]
Hi @albi3ro! I have been recently facing technical difficulties and thus haven't made a PR yet. I would not like to keep this issue on hold till the problem is fixed and would be happy if the issue is handed over to anyone who is interested in solving it. If the issue remains open after the problem is solved I would make a PR ASAP.
Sorry for the inconvenience.

**Comment by albi3ro** [comment]
No problem @tgag17 . I'm sorry this ended up being more difficult. It's hard to know how difficult a problem is to solve without solving it sometimes.

I just restricted the operations file, which might have made merging with master difficult. Can you tell us anything about the problems you ran into?

**Comment by tgag17** [comment]
Hi @albi3ro. Sorry for the late reply. 
Actually the part to change the __init__ method was a bit confusing for me. I was not a 100% sure what to add and what to remove. Other than that there were some technical issues on my end and thus I wasn't able to proceed with the issue.

**Comment by antalszava** [comment]
Hi @tgag17, no worries there! The issue is now participating in Code Together and it's even a bounty issue to solve.

Due to the call to `super().__init__` in the current implementation, likely the `__init__` method will require additions similar to the ones in `ControlledQubitUnitary.__init__`. Let us know if you have any specific questions. :slightly_smiling_face:

**Comment by tgag17** [comment]
Thank you @antalszava! I will try to tackle the issue and get back if I face any issue.
