### ISSUE TITLE
Divide `qubit.py` into multiple shorter files

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1454]
The [ops/qubit.py](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/ops/qubit.py) file holding all qubit ops is 3412 lines long.  While usually I just search for the operation I want, the file is still too unwieldy.

I propose dividing this file up into multiple files by:
* non-parameterized basic ops
* parameterized basic ops
* Chemistry ops
* Observables
* Arbitrary unitary type operations
* state preparations
* other advanced ops

We can place all these files in a folder named `qubit`.

**Comment by josh146** [comment]
💯

**Comment by glassnotes** [comment]
This would be amazing! We could do it for the tests as well, it'd make things a lot cleaner :star:

**Comment by antalszava** [comment]
Maybe also good to include an `__init__.py` file where the names are imported, so that the `ops.qubit` references across the docs & potentially plugins will continue working.
