### ISSUE TITLE
Add a transform `get_unitary_matrix` to obtain matrix representations of circuits

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/pennylane#1462]
As suggested in #1458, it would be useful to have a transform to obtain the matrix representation of a quantum function. The transform should look and behave like the following pseudocode (similar to the `draw` or `specs` transform):

```python
def get_unitary_matrix(qnode, wire_order=None):

    @wraps(qnode)
    def wrapper(*args, **kwargs):
        qnode.construct(args, kwargs)
     
        mat = qml.math.eye(2 ** num_wires)

        for op in qnode.qtape.operations:
            next_matrix = # construct matrix from op
            mat = qml.math.dot(next_matrix, mat)
    
        return mat

    return wrapper
```

This transform should be able to process *all* operations, including controlled gates on non-adjacent wires or wires in reverse order.

Note: this was written as a QNode transform because wire order is important (and we could extract that from the device). However, it could also be written as a tape or quantum function transform where the wire order must be passed explicitly every time. 

The functions [`compute_matrix_from_ops_one_qubit`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/transforms/test_optimization/utils.py#L21) and [`compute_matrix_from_ops_two_qubit`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/transforms/test_optimization/utils.py#L31) contain some simple starting code. Once the new transform is implemented, usage of these should be replaced by the transform, as well as matrix computation in other parts of the code (such as `SingleExcitation` and `DoubleExcitation` tests).

----

*List of tasks for completion:*

1. Create a quantum function transform that takes the device wires as an argument;
2. Create a QNode transform that calls the quantum function transform;
3. Replace the usage of [`compute_matrix_from_ops_one_qubit`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/transforms/test_optimization/utils.py#L21) and [`compute_matrix_from_ops_two_qubit`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/transforms/test_optimization/utils.py#L31);
4. Update the tests for the decomposition of the following operations to a new transform:
* [`ControlledPhaseShift`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/ops/test_qubit_ops.py#L1634)
* [`SingleExcitationPlus`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/ops/test_qubit_ops.py#L1684)
* [`SingleExcitationMinus`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/ops/test_qubit_ops.py#L1684)
* [`DoubleExcitation`](https://github.com/PennyLaneAI/pennylane/blob/1596b9a84ca6efe40c15ec74a286c3d0ed7b7c53/tests/ops/test_qubit_ops.py#L2044)

**Comment by josh146** [comment]
> However it could also be written as a tape or quantum function transform where the wire order must be passed explicitly every time.

Oh! Actually, should we have both? The QNode function can just call this qfunc transform and pass the device wires as an argument.

This feels more flexible, since then you can use it even if you don't have a device

**Comment by glassnotes** [comment]
Yes, great idea! :100:

**Comment by ingstra** [comment]
I'm interested to look into this :)

**Comment by glassnotes** [comment]
@ingstra fantastic :star2: Please feel free to ask us any questions you might have!

**Comment by ingstra** [comment]
Which file should the transforms be defined in?

**Comment by glassnotes** [comment]
Hi @ingstra ,

> Which file should the transforms be defined in?

You can put it in a new file in the `pennylane/transforms` directory, with the same name as the transform itself.

> Do I need to take into account the possibility of multiqubit gates with an arbitrary number of qubits involved in the gate? 

Yes we'd like to have the transform work for arbitrary-sized gates. All of the existing gates do have matrix representations available regardless of size that you can use as a starting point (for example, you can do `qml.Toffoli(wires=[0, 1, 2]).matrix`, or `qml.MultiControlledX(control_wires=[0, 1, 2, 3, 4, 5, 6], wires=7).matrix`), it's just that the ordering of those matrix representations is fixed, and doesn't take into account the ordering of the wires on the device (which is why `compute_matrix_from_ops_two_qubit` has a `wire_order` argument). 

For non-controlled gates, one way to work around this would be to apply SWAPs (but this could get computationally expensive).  For controlled gates, there is a trick you can use to construct them using the projectors `|0><0| = np.array([[1, 0], [0, 0]])` and `|1><1| = np.array([[0, 0], [0, 1]])`. A CNOT can be written as `|0><0| \otimes I + |1><1| \otimes X`. You can use this representation to compute the matrices for, e.g., `CNOT(wires=[0, 2])` where wires are non-adjacent or in a different order, and it generalizes to arbitrary controlled operations and arbitrary number of controls.

**Comment by ingstra** [comment]
Status update: I now have a quantum function transform that works for (has been tested on) single-qubit gates, two-qubit controlled gates, and Toffoli with adjacent or nonadjacent wires. My first idea was actually using the `|0><0| \otimes I + |1><1| \otimes X` kind of representation for controlled gates, but I ended up just doing SWAPs for everything. Now I need to test with MultiControlledX, and fix the other things on the to-do list. I'm just wondering if you'd like to see what I have so far, before I start editing previously existing code (tasks 3 & 4)? Maybe you can see something I missed or have other suggestions. I actually have one question for you guys (posed in a comment in the code ^_^)

One thing I was briefly thinking about was checking the `is_symmetric_over_all_wires` and `is_symmetric_over_control_wires` to do something to avoid doing superfluous SWAPs, but eh...

**Comment by ingstra** [comment]
I did some more testing today, and it turned out that it was just a fluke everything worked yesterday, but _now_ I think it works (famous last words). Anyway, I started replacing `compute_matrix_from_ops_one_qubit` and `compute_matrix_from_ops_two_qubit`, and found that my method got a different result compared to `compute_matrix_from_ops_two_qubit` in function `test_single_qubit_fusion_multiple_qubits` in `test_single_qubit_fusion.py`. So I manually constructed the operator, and it looks like I'm right and `compute_matrix_from_ops_two_qubit` is wrong o_o

**Comment by ingstra** [comment]
Sry for spamming but here's a question: I now have a quantum function transform named `get_unitary_matrix`. What should the QNode transform be named? Something different? The same? I learned from a quick Google search that Python doesn't support function overloading but I guess some type of workarounds exist.

**Comment by glassnotes** [comment]
Hi @ingstra ,  thanks for all your work on this! 🚀 I think you are correct that there is an issue in the current. `compute_matrix_from_ops_two_qubit` function. I'm pretty sure I know the cause (I added a swap,  but did not swap back! The test cases it was used in must not have been affected). I will confirm tomorrow, and also provide some guidance for your other questions 🙂

BTW you can make a PR whenever you like, happy to quickly review it in an intermediate state (sometimes it's helpful to have just for pointing out where you might have questions).

**Comment by ingstra** [comment]
Thanks! I created a PR. In get_unitary matrix I copied some code from adjoint.py because it felt appropriate, but I don't really know how the tape stuff works so I don't know if all of it it is necessary/appropriate here.

**Comment by glassnotes** [comment]
Thanks @ingstra , I will leave a few comments regarding your questions over in the PR!

**Comment by ingstra** [comment]
Right now this does not work with a circuit containing a controlled op generated by `qml.ctrl`, since it throws a NotImplementedError when get_unitary_matrix() tries to get op.matrix. Is this something I need to be concerned about at this point?

**Comment by ingstra** [comment]
I'm having some problems in `test_qubit_ops.py` for task 4, `test_double_excitation_decomp`: Something makes it not work when looping through the list of decompostitions. As a simple example, the following just prints the identity matrix two times. What is happening?

```
wires= [0,1]

list = [qml.RY(0.5,wires=[0]), qml.PauliX(wires=1)]

for op in list:
    def circ():
        op
        
    get_matrix = get_unitary_matrix(circ, wires)
    matrix = get_matrix()

    print(matrix)
```

**Comment by glassnotes** [comment]
> Right now this does not work with a circuit containing a controlled op generated by `qml.ctrl`, since it throws a NotImplementedError when get_unitary_matrix() tries to get op.matrix. Is this something I need to be concerned about at this point?

In this case since the matrix is legit not available, I'd say don't worry about it. (This should maybe be written up as a separate issue, actually.)

> I'm having some problems in test_qubit_ops.py for task 4, test_double_excitation_decomp: Something makes it not work when looping through the list of decompostitions.

I would need a bit more context, but one thing to note is that PennyLane operators are queued to the underlying tape upon construction, so you cannot apply an already-constructed operation as is done above. You'll need to use the `qml.apply()` function, so:

```
for op in list:
    def circ():
        qml.apply(op)
```

The identity is coming out because unless the operations are manually applied like this, nothing will be queued. This might solve the problem; let me know if it doesn't (seeing the full function would be helpful here).

**Comment by ingstra** [comment]
@glassnotes `qml.apply()` did the trick, thanks!

**Comment by glassnotes** [comment]
Closing as #1609 has been merged in :tada:
