### ISSUE TITLE
Make QFT a template instead of an operation

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1477]
The [QFT operation](https://github.com/PennyLaneAI/pennylane/blob/459b5cd9be57c228c115c9e534aa23e564f582d2/pennylane/ops/qubit/non_parametric_ops.py#L993) fits better as a template rather than a core operation.  It can accept any number of wires and adjusts accordingly.  While it has a matrix, we think of it more as a combination of gates.

Moving it would involve:
* Creating a new file in the [subroutines folder](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/templates/subroutines)
* Moving the [QFT code](https://github.com/PennyLaneAI/pennylane/blob/459b5cd9be57c228c115c9e534aa23e564f582d2/pennylane/ops/qubit/non_parametric_ops.py#L993) to this file
* Adding the new template to [`__init__.py` files](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/templates/subroutines/__init__.py)
* Adding an image of the gate decomposition, similar to other templates.  This can be done with [LaTeX qcircuit](https://www.overleaf.com/latex/templates/drawing-circuits-with-qcircuit/wnmnpmncykjg) and converting the resulting pdf file to an SVG.
* Moving all [current QFT tests](https://github.com/PennyLaneAI/pennylane/blob/459b5cd9be57c228c115c9e534aa23e564f582d2/tests/ops/test_qubit_ops.py#L525) to a new file in the [`test_subroutines` folder](https://github.com/PennyLaneAI/pennylane/tree/master/tests/templates/test_subroutines)
* Add a card to the documentation on `doc/introduction/templates.rst`
* Generally follow the [adding template instructions](https://pennylane.readthedocs.io/en/latest/development/adding_templates.html)

**Comment by anonymousr007** [comment]
Hi! I would like to work on this issue.

**Comment by albi3ro** [comment]
Hi @anonymousr007 .  Thanks for your interest. 

This issue is part of our [Code Together event](https://pennylane.ai/blog/2021/07/pennylane-code-together/) and eligible for extra swag.  Depending on participation numbers, we may have multiple people working on each issue, in which case the first issue to "merge ready" counts.  Participants can also join together into teams if they wish.

Good luck :)

**Comment by anonymousr007** [comment]
Okay @albi3ro .Yes,I know this issue is the part of [Code Together Event](https://pennylane.ai/blog/2021/07/pennylane-code-together/) and I am a participant of this hackathon. 

Finally, I start working on this issue.
 
Thanks 
Best Regards 
Rishabh (@anonymousr007 )

**Comment by anonymousr007** [comment]
Hi! I am new in pennylane open source system,Can you please tell me what branch we used for pull request ? 
It's a lot,I'm little confused

Thanks 
Best Regards
Rishabh (@anonymousr007 )

**Comment by antalszava** [comment]
Hi @anonymousr007, sure, welcome! :slightly_smiling_face: 

You could create a pull request targeting the `master` branch of PennyLane. Let us know if you have any further questions!

**Comment by anonymousr007** [comment]
Hi @antalszava ,Sorry for these silly questions 😅 
From `master-anonymousr007` to `master-pennylane` .

**Comment by antalszava** [comment]
There are no silly questions. :slightly_smiling_face: The `master` branch of PennyLane is the one to make sure of.

From your fork, you could choose any of the branches that contain the changes to be incorporated. Basically, when the pull request is opened, you're initiating a merge of the branch that you specify in your fork to the `master` branch of the PennyLane repository. You could create a branch separate from `master` in your fork just to make sure that the changes are organized nicely, though it's not required.

**Comment by anonymousr007** [comment]
Now, It's Clear. Thank you so much 😄

**Comment by anonymousr007** [comment]
https://github.com/PennyLaneAI/pennylane/pull/1537
Checkout this, this is my first pull request.

**Comment by anonymousr007** [comment]
[#1556 ](https://github.com/PennyLaneAI/pennylane/pull/1556)
Checkout this, this is my second pull request and please tell me my mistake :(.
