### ISSUE TITLE
[BUG] Incorrect shot batching behaviour in ExpvalCost when optimize=True

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#1480]
### Expected behavior

Suppose we want to evaluate the expectation value of a Hamiltonian:
```python
h = qml.Hamiltonian([1, 1], [qml.PauliZ(0), qml.PauliZ(1)])
```
We want to do this using batched-shots
```python
shot_batch = [(100, 10)]
```

To do this in PennyLane, we use `ExpvalCost`. There are options based on the `optimize` flag, which sets whether to group commuting observables:
```python
exp_unoptimized = qml.ExpvalCost(ansatz, h, dev, optimize=False)
exp_optimized = qml.ExpvalCost(ansatz, h, dev, optimize=True)
```

Evaluating the result with `optimize=False` gives the expected output shape:
```pycon
>>> exp_unoptimized(args)
[1.92 1.9  1.98 1.92 1.96 1.92 1.92 1.94 1.86 1.9 ]
```

### Actual behavior

When `optimize=False`, we get an unexpected output shape:
```pycon
>>> exp_optimized(args)
[1.8 2. ]
```

### Additional information

We may decide not to fix this given `ExpvalCost` may soon be replaced, and suggest users set `optimize=False`. On the other hand, `optimize=True` provides some impressive speedups and switching to `optimize=False` will likely prevent users being able to successfully optimize.

Related post: https://discuss.pennylane.ai/t/differentiable-circuit-with-sampling/1190

### Source code

```shell
import pennylane as qml

shot_batch = [(100, 10)]
dev = qml.device("default.qubit", wires=2, shots=shot_batch)
h = qml.Hamiltonian([1, 1], [qml.PauliZ(0), qml.PauliZ(1)])

def ansatz(params, wires):
    qml.RX(params, wires=wires[0])

exp_unoptimized = qml.ExpvalCost(ansatz, h, dev, optimize=False)
exp_optimized = qml.ExpvalCost(ansatz, h, dev, optimize=True)

print(exp_unoptimized(0.4))
print(exp_optimized(0.4))
```

### System information

```shell
Happens on dev branch of PL.
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by trbromley** [comment]
Do we need to edit the template to automatically format to Python? See below:
![image](https://user-images.githubusercontent.com/49409390/127224841-1128d7f7-73a8-424e-884b-061f2f2c565d.png)

Otherwise, template was fun to use! The "System information" felt a bit unnecessary for this post, but I can understand why it's there as a required field.

**Comment by mariaschuld** [comment]
@trbromley we are busy finding a better way to integrate `shot_batch`. Basically, it will always be ambivalent if we set it in the device, but use the device to do all sorts of things. The solution we are exploring is to do the grouping and shot distribution when creating the Hamiltonian (otherwise using a default). 

So I personally suggest fixing this with the new VQE design!

**Comment by rmoyard** [comment]
[sc-8002]
