### ISSUE TITLE
[BUG] WireError in code example from the documentation

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1498]
### Expected behavior

Trying to run the NumPy interface examples from the Gradients and training section of the documentation. The expected behaviour is to get the provided result.

https://pennylane.readthedocs.io/en/stable/introduction/interfaces/numpy.html

### Actual behavior

Code fails with pennylane.wires.WireError

### Additional information

Not doing anything extra. Just trying to run the example.

### Source code

```shell
dev = qml.device('default.qubit', wires=5)

@qml.qnode(dev)
def circuit(weights, data, wires):
    qml.templates.AmplitudeEmbedding(data, wires=wires, normalize=True)
    qml.RX(weights[0], wires=wires[0])
    qml.RY(weights[1], wires=wires[1])
    qml.RZ(weights[2], wires=wires[2])
    qml.CNOT(wires=[wires[0], wires[1]])
    qml.CNOT(wires=[wires[0], wires[2]])
    return qml.expval(qml.PauliZ(wires[0]))

weights = np.array([0.1, 0.2, 0.3])
data = np.random.random([2**3], requires_grad=False)
wires = np.array([2, 0, 1], requires_grad=False)
circuit(weights, data, wires)
grad_fn = qml.grad(circuit)
grad_fn(weights, data, wires)
```

### Tracebacks

```shell
Traceback (most recent call last):
  File "...\lib\site-packages\pennylane\devices\default_qubit.py", line 166, in map_wires
    mapped_wires = [self.wire_map[w] for w in wires]
  File "...\lib\site-packages\pennylane\devices\default_qubit.py", line 166, in <listcomp>
    mapped_wires = [self.wire_map[w] for w in wires]
KeyError: tensor(2, requires_grad=False)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "...\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-2b4e5768a851>", line 16, in <module>
    circuit(weights, data, wires)
  File "...\lib\site-packages\pennylane\qnode.py", line 598, in __call__
    res = self.qtape.execute(device=self.device)
  File "...\lib\site-packages\pennylane\tape\tape.py", line 1323, in execute
    return self._execute(params, device=device)
  File "...\lib\site-packages\pennylane\tape\tape.py", line 1354, in execute_device
    res = device.execute(self)
  File "...\site-packages\pennylane\_qubit_device.py", line 192, in execute
    self.apply(circuit.operations, rotations=circuit.diagonalizing_gates, **kwargs)
  File "...\lib\site-packages\pennylane\devices\default_qubit.py", line 196, in apply
    self._apply_state_vector(operation.parameters[0], operation.wires)
  File "...\lib\site-packages\pennylane\devices\default_qubit.py", line 531, in _apply_state_vector
    device_wires = self.map_wires(device_wires)
  File "...\lib\site-packages\pennylane\devices\default_qubit.py", line 168, in map_wires
    raise WireError(
pennylane.wires.WireError: Did not find some of the wires (tensor(2, requires_grad=False), tensor(0, requires_grad=False), tensor(1, requires_grad=False)) on device with wires (0, 1, 2, 3, 4).
```

### System information

```shell
Name: PennyLane
Version: 0.16.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: ...\lib\site-packages
Requires: toml, numpy, semantic-version, networkx, autoray, scipy, appdirs, autograd
Required-by: PennyLane-Cirq, PennyLane-qiskit
Platform info:           Windows-10-10.0.19043-SP0
Python version:          3.8.10
Numpy version:           1.19.5
Scipy version:           1.6.0
Installed devices:
- cirq.mixedsimulator (PennyLane-Cirq-0.14.0)
- cirq.pasqal (PennyLane-Cirq-0.14.0)
- cirq.qsim (PennyLane-Cirq-0.14.0)
- cirq.qsimh (PennyLane-Cirq-0.14.0)
- cirq.simulator (PennyLane-Cirq-0.14.0)
- default.gaussian (PennyLane-0.16.0)
- default.mixed (PennyLane-0.16.0)
- default.qubit (PennyLane-0.16.0)
- default.qubit.autograd (PennyLane-0.16.0)
- default.qubit.jax (PennyLane-0.16.0)
- default.qubit.tf (PennyLane-0.16.0)
- default.tensor (PennyLane-0.16.0)
- default.tensor.tf (PennyLane-0.16.0)
- qiskit.aer (PennyLane-qiskit-0.16.0)
- qiskit.basicaer (PennyLane-qiskit-0.16.0)
- qiskit.ibmq (PennyLane-qiskit-0.16.0)
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by mariaschuld** [comment]
@ankit27kh thank you for reporting. This is a manifestation of a known problem (see also Issue #1459). 

Basically, you are calling your gates like `qml.RY(weights[1], wires=wires[1])` with wires of the form `wires[i]`. But your wires argument is a numpy tensor. This means that `wires[0]` is a numpy tensor of the form `tensor(2, requires_grad=0)`. PennyLane tries to find a wire `tensor(2, requires_grad=0)` but only sees integer valued wire labels `0,1...`. So it complains. 

A way to fix it if you insist on using wires that are tensors is to create the device using custom wires. You don't pass a number (of wires, such as `5`), but you pass a list of the wire labels:

``` python
dev_wires = [np.array(0, requires_grad=False), np.array(1, requires_grad=False), np.array(2, requires_grad=False),
                     np.array(3, requires_grad=False), np.array(4, requires_grad=False)]
dev = qml.device('default.qubit', wires=dev_wires)
```
This fixes the issue for me! 

There are maybe better ways there though, for example one could use keyword arguments to pass the wires to the qnode, in which case they won't get automatically converted to trainable tensors (which is something we kept for backwards compatibility, but it will be removed soon, so that your issue should never come up!). 

Also, check your gradient: You are trying to differentiate with respect to wires, which does not make sense. Can you maybe use ` `qml.grad(circuit, argnum=[0, 1])` to specify that you only want to differentiate with respect to the first arg?

**Comment by ankit27kh** [comment]
Thanks for your reply. Your workaround does work. 

As I said, this code was directly taken from the pennylane website without modifications. This just makes it look bad as the provided 'official' code meant for learning is not working.

`wires = np.array([2, 0, 1], requires_grad=False)`
`wires` is defined like this stating '`requires_grad=False'`. Shouldn't this mean that no gradient is supposed to be taken wrt wires?

Again, thank you for your solution!

**Comment by mariaschuld** [comment]
Ah, I totally overlooked what you said on where the code is from. 

You are completely right, this is a severe oversight. We try to keep the code examples in the documentation up-to-date, but with PennyLane's fast development cycles we sometimes need feedback like yours to find the bugs. Thanks! 

We will update the documentation accordingly.

**Comment by mariaschuld** [comment]
For your convenience, the updated example (which uses now the recommended way to go about things) is this:

``` python
dev = qml.device('default.qubit', wires=5)

@qml.qnode(dev)
def circuit(weights, data, wires=None):
    qml.templates.AmplitudeEmbedding(data, wires=wires, normalize=True)
    qml.RX(weights[0], wires=wires[0])
    qml.RY(weights[1], wires=wires[1])
    qml.RZ(weights[2], wires=wires[2])
    qml.CNOT(wires=[wires[0], wires[1]])
    qml.CNOT(wires=[wires[0], wires[2]])
    return qml.expval(qml.PauliZ(wires[0]))


np.random.seed(42)  # make the results reproducable
weights = np.array([0.1, 0.2, 0.3], requires_grad=True)
data = np.random.random([2**3], requires_grad=False)
wires = [2, 0, 1]
print(circuit(weights, data, wires=wires))
grad_fn = qml.grad(circuit)
print(grad_fn(weights, data, wires=wires))
```

As you can see, the `wires` argument is passed as a keyword arg everywhere, and it is specified as a list of integers as usual. Hope this makes a lot more sense now!
