### ISSUE TITLE
Validation check for the arguments passed to `qml.operation.Observable`

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1507]
### Feature details

Observables have a logic in that attempts to support a "shorthand" way of construction:

```python
qml.PauliZ(0)
```
This is in contrast with `qml.PauliZ(wires=0)`.

However, when no arguments are passed, an `IndexError` is raised because there's an attempt to access the first argument passed:
```python
qml.PauliZ()
```
```
~/pennylane/pennylane/operation.py in __init__(self, wires, do_queue, id, *params)
   1040         # extract the arguments
   1041         if wires is None:
-> 1042             wires = params[-1]
   1043             params = params[:-1]
   1044 

IndexError: tuple index out of range
```

This feature request aims at adding a validation check for operations when not passing any arguments. Having such a check would ensure that users receive an informative error message.

----

*List of tasks for completion:*

1. Add a validation check mechanism to creating observables such that passing no arguments raises an error that informs users well about.
2. Include unit and integration testing for the changes.

### Implementation

Adding a try-except block to handle `IndexError` could be a good approach.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by ingstra** [comment]
I'll take a crack at this :blush:

**Comment by thisac** [comment]
Thanks @ingstra! There's already a PR up for this one (#1539), but feel free to work on it as well. The first PR to be approved and merge-ready will the the one accepted. Otherwise you can look into one of the many other issues we have as well. 🙂

**Comment by ingstra** [comment]
Thanks for letting me know! I had started so I finished with it anyway.

**Comment by antalszava** [comment]
Hi @ingstra and @mayap24 :slightly_smiling_face: Just letting you know, that both of you submitted a solution to this issue. You could consider teaming up potentially to submit a joint solution. Otherwise, the first PR that's merge-ready will be merged in.
