### ISSUE TITLE
Add matrix form to Grover Operator

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1514]
While the [`GroverOperator` template](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/templates/subroutines/grover.py) is a template and currently only has an expansion in terms of gates, we could define a [`matrix` attribute](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.operation.Operator.html#pennylane.operation.Operator.matrix) for more efficient use of the template on statevector simulators.

Fulfilling this task would involve:
* Determining the matrix form of the Grover Diffusion Operator
* Adding that to the template
* Adding tests

This will require some knowledge of Quantum Computation to determine the matrix, but less extensive programming experience.

**Comment by tgag17** [comment]
Hi! Can I work on this issue?

**Comment by abzsd** [comment]
Can I work on this issue too?

**Comment by ingstra** [comment]
I worked on this as well... I will now put a PR with two different options how to construct the matrix

**Comment by antalszava** [comment]
Hi everyone, thanks for the interest in this! :slightly_smiling_face: It's okay for multiple people to tackle one issue, you could potentially chat and team up to create a single solution! Alternatively, if multiple PRs are opened, then the first one to be merged will get swag. Let us know if you have any questions!

**Comment by tgag17** [comment]
Hi! I had a question.
Should the matrix be a generalized one (which changes which the number and set of wires) or should these parameters be fixed?
I would also be happy to team up if everyone is up for it!
Thank you!

**Comment by antalszava** [comment]
Hi @tgag17, the matrix representation could be defined in the `_matrix` method. When using the `matrix` property, the returned matrix would then depend on the parameters with which `GroverOperator` was created, [see here](https://github.com/PennyLaneAI/pennylane/blob/742f2ff067d969a42e380968f36456c995dee2c9/pennylane/operation.py#L326).

**Comment by antalszava** [comment]
A correction here: the parameters will likely not be used (as there aren't really any gate parameters), so that might become an unused argument when using `_matrix`. Instead, the wires themselves will be significant.
