### ISSUE TITLE
Add function to get grouping indices to grouping module

### ISSUE THREAD

**Issue by mariaschuld** [PennyLaneAI/pennylane#1518]
Given a list of observables, the `grouping` module computes groups of commuting observables:

```python
obs = [qml.PauliZ(0), qml.PauliX(1), qml.PauliX(0)]
grouped_obs = qml.grouping.group_observables(obs)
print(grouped_obs)  # [[PauliZ(wires=[0]), PauliX(wires=[1])], [PauliX(wires=[0])]]
```
Computing which elements of the observable list group together is very costly, and we [are planning to store information](https://github.com/PennyLaneAI/pennylane/pull/1515/files) about groupings in a Hamiltonian observable, so any part of the PennyLane pipeline can (re)use it. 

It would be most useful to store the information not in form of grouped observables, but just as a list of the indices (such as ``[[1, 2], [3]]`` in the above example. These indices can be easily used to pick the right observables from `obs`, and can also be used to pick coefficients corresponding to these observables in a Hamiltonian. 

This issue suggests adding a function or argument to the grouping module that allows the extraction of the grouped indices instead of the grouped observables. 

A wanted side-effect is that this could improve the use of `qml.grouping.group_observables` itself. If coefficients are passed to be grouped along with the observables, the function goes through the ``grouped_obs`` list and tracks the index of each observable in the initial list, and uses the index to pick the right coefficients. If we had the indices in the first place, this reconstruction would be much easier.

**Comment by astralcai** [comment]
The `qml.pauli.grouping.compute_partition_indices` method is now available: https://docs.pennylane.ai/en/stable/code/api/pennylane.pauli.compute_partition_indices.html
