### ISSUE TITLE
Add the `SISWAP` operation

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1527]
### Feature details

We would like to define a new operation called `SISWAP`, that is the square-root of the `qml.ISWAP` operation. See [further details here](https://arxiv.org/pdf/2105.06074.pdf).

### Implementation

*List of tasks for completion:*

*A. Adding the operation*

1. Adding the `SISWAP` new class for the operation to `pennylane/ops/qubit/non_parametric_ops.py`. Complete its docstring in a similar fashion as for other operations. Make sure the class is accessible through `qml.SISWAP`.
2. Add its decomposition: a definition for how the operation could be decomposed into elementary operations ([see candidate decompositions here for example](https://quantumcomputing.stackexchange.com/questions/16139/how-to-implement-sqrtiswap-in-qiskit)),
3. Add its matrix, eigenvalues and adjoint (see `S` or `T` operations as examples of non-Hermitian unitaries),
4. Add the `SQISW` alias of `SISWAP`, by including the `SQISW = SISWAP` in the `tests/ops/test_qubit_ops.py` file after the definition of the `SISWAP` class and making sure that `qml.SQISW` is valid (see the [`CPhase` alias as an example](https://github.com/PennyLaneAI/pennylane/blob/0088704258018171ad955d83238fb08ef94ed88d/pennylane/ops/qubit/parametric_ops.py#L297))
5. Add an entry to the `doc/introduction/operations.rst` file for the new `qml.SISWAP` operation
6. *Test:* include tests for the operation and its alias in the `tests/ops/test_qubit_ops.py` file similar to how other non-parametric operations are tested.

*B. Adding `default.qubit` support*

5. Add support for the operation in the `default.qubit` device,
6. *Test:* test the operation with `default.qubit` in the `tests/devices/test_default_qubit.py` file.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by charmerDark** [comment]
Hey @antalszava Is there a set of basis gates that have to be used to write the decomposition? or prefered ones?

**Comment by antalszava** [comment]
Hi @charmerDark, any should work well.

Preferred gate sets would be single-qubit rotations & an entangler (e.g., CNOT). Overall, most decompositions would be further decomposed implicitly into these elementary gates using PennyLane. Maybe a good approach is to see which decomposition yields the least deep circuit overall when decomposed into elementary gates. Having said that, there's no constraint on the type of decomposition that will be accepted.

**Comment by antalszava** [comment]
Good to see your interest in this issue! :slightly_smiling_face:

**Comment by antalszava** [comment]
@charmerDark for adding support to `default.qubit`, the [PR that added to the `ISWAP` operator to `default.qubit`](https://github.com/PennyLaneAI/pennylane/pull/1298/files) can help along the way. :slightly_smiling_face:
