### ISSUE TITLE
Modify `default.mixed` to use `qml.math` for native autodiff backpropagation support

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1528]
### Feature details

We would like to create a version of the `default.mixed` simulator that can perform computations native to the TensorFlow, PyTorch and Jax autodiff frameworks. This can be achieved by modifying the existing device to use the `qml.math` module. The `qml.math` module supports dispatching to the aforementioned frameworks by using `autoray`. It allows one to write code that would be compatible with multiple auto differentiation frameworks.

There would be two advantages to modifying the `default.mixed` device to use `qml.math`:

- The device would support backpropagation and so diff_method='backprop' should be supported;
- Framework specific features would work with `default.mixed`:
    * TensorFlow: hybrid models using Keras could be supported using backprop
    * Jax: the jax.vmap function for parallelizing the quantum circuit computations would be supported

### Implementation

As pointers, the following code snippets should execute well without any errors raised:

**TensorFlow**

```python
import tensorflow as tf

p = 0.01
dev = qml.device("default.mixed", wires=1)

@qml.qnode(dev, interface="tf", diff_method="backprop")
def circuit(x):
    qml.RX(x[1], wires=0)
    qml.Rot(x[0], x[1], x[2], wires=0)
    qml.DepolarizingChannel(p, wires=0)
    return qml.expval(qml.PauliZ(0))

weights = tf.Variable([0.2, 0.5, 0.1])

with tf.GradientTape() as tape:
    res = circuit(weights)

print(tape.gradient(res, weights))
```

**PyTorch**

```python
dev = qml.device('default.mixed', wires=2)

p = 0.01
@qml.qnode(dev, interface='torch', diff_method='backprop')
def circuit3(phi, theta):
    qml.RX(x[1], wires=0)
    qml.Rot(x[0], x[1], x[2], wires=0)
    qml.DepolarizingChannel(p, wires=0)
    return qml.expval(qml.PauliZ(0))

phi = torch.tensor([0.5, 0.1, 0.4], requires_grad=True)
result = circuit3(phi)

result.backward()
phi.grad
theta.grad
```

**Jax**

```python
from jax import numpy as jnp

dev = qml.device("default.mixed", wires=1)

p = 0.01
@qml.qnode(dev, interface="jax", diff_method="backprop")
def circuit(x):
    qml.RX(x[1], wires=0)
    qml.Rot(x[0], x[1], x[2], wires=0)
    qml.DepolarizingChannel(p, wires=0)
    return qml.expval(qml.PauliZ(0))

weights = jnp.array([0.2, 0.5, 0.1])
grad_fn = jax.grad(circuit)
print(grad_fn(weights))
```

```python
import jax
import networkx as nx
import pennylane as qml

G = nx.Graph()
G.add_nodes_from([0,1,2,3])
G.add_edges_from([(0,3),(1,2),(1,3)])

def noisy_circuit(prob,**kwargs):
    for k in range(len(G.nodes)):
        qml.BitFlip(prob, wires=k)
    return qml.expval(qml.PauliZ(0))

dev = qml.device("default.mixed", wires = len(G.nodes))
qcircuit = qml.QNode(noisy_circuit, dev, interface = "jax")
vcircuit = jax.vmap(qcircuit)

probs = jax.numpy.array([0., 0.05, 0.1])
vcircuit(probs)
```

It is worth noting that this issue is highly exploratory and resolving the issue will likely entail a deeper dive beforehand.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

See the following discussion forum threads:

TensorFlow & Keras with noise models: https://discuss.pennylane.ai/t/adding-noise-to-a-keras-hybrid-nn/1241
Jax `vmap` function: https://discuss.pennylane.ai/t/jax-with-default-mixed-device/1170

**Comment by anonymousr007** [comment]
Hi @antalszava, I would try to solve this issue :)

**Comment by antalszava** [comment]
Hi @anonymousr007, that's great! Feel free to open a PR or a work in progress PR for it. :slightly_smiling_face:

**Comment by shukob** [comment]
Hi, I need this so implementing for my own. Is the suggested method to use `qml.math` different from `default.qubit` version like impelementing `default.qubit.autograd`, etc...? It feels straightforward when go that way.

**Comment by josh146** [comment]
Hey @shukob, the main reason for using `qml.math` is to support _all_ autodiff frameworks at once 🙂 However, I imagine that will be a lot more work and testing, so implementing a subclass (`default.mixed.torch`) should be an okay intermediary step.

**Comment by shukob** [comment]
@josh146 Thanks! While implementing autograd/tf versions, it feels like implementing devices.qml_ops to be used in all qubit/mixed devices will be the way to go when using `qml.math`. Is that what you expect?

**Comment by josh146** [comment]
@shukob yep that is one approach definitely! Ideally, I would like it so that all operations defined in `pennylane/ops` have their `operation.matrix` property implemented using `qml.math`. That way, you would be able to do

```python
>>> x = torch.tensor(0.2)
>>> op = qml.RX(x, wires=0)
>>> op.matrix
tensor([[0.9950+0.0000j, 0.0000-0.0998j],
        [0.0000-0.0998j, 0.9950+0.0000j]], dtype=torch.complex128,
       grad_fn=<AddBackward0>)
```

and ensure the output is differentiable 🙂

**Comment by shukob** [comment]
@josh146 Thank you for the explanation. I am a bit confused because `ops` are defined both in `devices` and in `ops.qubit`. But from that explanation, will current class variables: `_apply_ops` and `parametric_ops` be removed and only `_get_unitary_matrix` part be used for `qubit` devices? It seems we still need to define `staticmethod`s in root device but they will become `qml.math` versions, I guess?

**Comment by josh146** [comment]
> from that explanation, will current class variables: _apply_ops and parametric_ops be removed and only _get_unitary_matrix part be used for qubit devices? It

Yep, exactly :) The plan is to remove all of `tf_ops.py`, `torch_ops.py`, etc.

> It seems we still need to define staticmethods in root device but they will become qml.math versions, I guess?

Ideally, we can remove all the static methods from the devices as well at some point!

> Non parametric ops in ops uses numpy as its variable, and we do not have intuitive way to specify the backend. Is it ok to let them as is? 

If an op is non-parametric, I believe it is okay to use NumPy, since the autodiff frameworks will automatically convert it to a tensor when needed.

**Comment by shukob** [comment]
Hi, is it OK to add some utility methods like `zeros` or something that is used to create an array of the specific backend in `qml.math` module? Current problem is that Kraus operators are given in the list of arrays but for example, ArrayBox seems not working on `_cast` in that case. So am trying to work around it by making it another type.

**Comment by josh146** [comment]
@shukob, this should already be available as we use [autoray](https://github.com/jcmgray/autoray) as a backend 🙂 

For example,

```pycon
>>> import pennylane as qml
>>> qml.math.zeros([2, 3], like="torch")
tensor([[0., 0., 0.],
        [0., 0., 0.]])
```

Most functions in the `qml.math` module accept a `like` argument to force a particular backend.

Let me know if that helps, or if the ArrayBox still causes an issue!

**Comment by shukob** [comment]
Hi, it locally works for all backends by implementing subclasses now,  tests are missing though. Are there any plan for the replacement of the asserts on each framework like `VERSION_SUPPORT = semantic_version.match(">=1.8.1", torch.__version__)` when implementing framework-agnostic version of single device? Thanks.

**Comment by shukob** [comment]
@josh146 Thanks! Will try to implement a single device ignoring those validations for a while.

**Comment by shukob** [comment]
@josh146 Thanks! Will open a PR after cleaning up.

**Comment by shukob** [comment]
Hi, for methods that have different interfaces between backends, e.g. expand_dims, can I create a method in for example `math.util` like this?
```python
try:
    import torch

    VERSION_SUPPORT = semantic_version.match(">=1.8.1", torch.__version__)
    if not VERSION_SUPPORT:
        raise ImportError("default.mixed.torch device requires Torch>=1.8.1")

except ImportError as e:
    pass


def expand_dims(tensor, axes):
    """Adapter for np.expand_dims to allow torch to have same interface as others
    """
    if get_interface(tensor) == "torch":
        return tensor.unsqueeze(axes)
    else:
        return np.expand_dims(tensor, axes)
```

Thanks.

**Comment by josh146** [comment]
Hey @shukob, since `expand_dims` is a single-dispatch function (it only dispatches based on the first argument), then it can be registered in `math/single_dispatch.py` 🙂 

However, it seems that `expand_dims` already seems to work for Torch tensors?

```python
>>> x = torch.tensor([1, 2, 3.])
>>> qml.math.expand_dims(x, 0)
tensor([[1., 2., 3.]])
```

**Comment by shukob** [comment]
@josh146 Thanks! I had tried using autoray itself but hadn't noticed that the line was already added to `single_dispatch`.
```python
ar.register_function("torch", "expand_dims", lambda x, axis: _i("torch").unsqueeze(x, dim=axis))
```
I will consider adding to `single_dispatch` if there are any others that require conditional execution.

**Comment by shukob** [comment]
Hi, since we do not specify backend to the device, initial state preparation by basis state is always generated in NumPy. In the first operation, we should cast _state to lie in the desired backend. I did not find autoray function to do this. We can have a wrapper to do this, or is there any existing solution you can think of? Thank you in advance.

**Comment by shukob** [comment]
Hi, since the device does not know the interface, initial state preparation by basis state is always generated in NumPy. It becomes redundant, but we can add an init argument of the device to specify the backend.  This breaks device-agnostic initialization in qnode if we do not also add the argument to all the devices. Or we can add a post-initialization function to the devices that take interface argument and initialize _state. In this case, adding a do-nothing function to the Device base-class will be sufficient for backward compatibility. May I ask your opinion?

**Comment by josh146** [comment]
Hey @shukob! Perhaps we could use `qml.math.asarray(state, like="torch")` etc. to convert the initial state?

**Comment by shukob** [comment]
@josh146 Thanks. Yes at some point we can do that. I think not every operation is on the target backend, like non-parametric ones. In such a case we cannot always convert _state in `_apply_channel` or `_apply_diagonal`_uniatry based on the argument. So conversion should be one-time. The current implementation does this based on the initializer argument. Other ideas that do not change the initialize will be helpful. For example, when we face a non-NumPy argument the first time? But I am afraid this might cause unexpected results.

**Comment by ankit27kh** [comment]
@antalszava is there any progress on this? Is this issue on the roadmap? I would like to request that this issue priority be increased from Not important!

**Comment by Jaybsoni** [comment]
Hi @ankit27kh, 
Thanks for the comment, this issue is currently being addressed. I am working on a fix that can be found [here](https://github.com/PennyLaneAI/pennylane/pull/1801). Due to some other priorities, I wasn't able to complete the fix this quarter, but it definitely is on the road map, and will be addressed soon. Could I ask, what particular use case you were targeting for this feature? Maybe we can prioritize that use case so that it is not blocking your work/research. Thanks again for your interest in this feature!


> @antalszava is there any progress on this? Is this issue on the roadmap? I would like to request that this issue priority be increased from Not important!

**Comment by ankit27kh** [comment]
Hello @Jaybsoni, thanks for the update.
I am using `default.mixed` for noise simulations which takes a very long time. I did all of my ideal simulations using `default.qubit.jax` so I was hoping to have JAX and JIT support with noise simulations to drastically reduce runtime.
