### ISSUE TITLE
Create `qml.PauliError`

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1529]
### Feature details

As requested in #971, we would like to add a channel for Pauli errors.

See the following references:
* https://arxiv.org/pdf/1907.12976.pdf
* https://arxiv.org/pdf/2101.02109.pdf

See the [addition of a Reset error](https://github.com/PennyLaneAI/pennylane/pull/1321) as an example.

### Implementation

*List of tasks for completion:*

A.
1. Add a new `qml.PauliError` class to `pennylane/ops/channel.py` that inherits from `Channel` and defines the Kraus operators.
2. Add an entry to the `doc/introduction/operations.rst` file for the new operation
3. Add tests for the new channel in the `tests/ops/test_channel_ops.py` file.

B.
1. Add support for `qml.PauliError` in the `default.mixed` device by adding it to the [list of supported operations](https://github.com/PennyLaneAI/pennylane/blob/0088704258018171ad955d83238fb08ef94ed88d/pennylane/devices/default_mixed.py#L92).
2. Add tests for [checking the Kraus operators of the channel](https://github.com/PennyLaneAI/pennylane/blob/0088704258018171ad955d83238fb08ef94ed88d/tests/devices/test_default_mixed.py#L216) and for [applying the new channel](https://github.com/PennyLaneAI/pennylane/blob/0088704258018171ad955d83238fb08ef94ed88d/tests/devices/test_default_mixed.py#L266) using `default.mixed`.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by ingstra** [comment]
Hi! I started looking at this for the _code together_, but I see that Pauli Z (`PhaseFlip`) and Pauli X (`BitFlip`) error channels already exist in `pennylane/ops/channel.py`?

**Comment by antalszava** [comment]
Hi @ingstra, indeed, good find! What we'd like for `qml.PauliError` is to stand for any Pauli error acting on an arbitrary number of qubits. To achieve that, the existing `PhaseFlip` and `BitFlip` classes could be used. It's worth noting, that these classes act on single qubits.

**Comment by MoritzWillmann** [comment]
Hey @antalszava and @ingstra, If help is still needed I can pick up this issue 😄 
Cheers Moritz

**Comment by antalszava** [comment]
Hi @MoritzWillmann, awesome, I'll have a go at addressing them. :slightly_smiling_face: Note that in general we have some flexibility here.

> When you say "Pauli Error acting on an arbitrary number of qubits", does that mean the Kraus Matrices "only" need to be upscaled to act on the according state vector?

What I had in mind there is that we could specify a Pauli string, the wires the error acts on and the corresponding probability , e.g., "XYZ", `wires=[0,1,2]` and `p=0.1` for example.

In such a case, with probability `0.1` we'll apply the following
```python
qml.PauliX(0)
qml.PauliY(1)
qml.PauliZ(2)
```
and with a probability of `0.9` the state is reserved.

One step further, we could define 3 lists:
1. a list of Pauli-strings;
2. a list of wires;
3. a list of probabilities.

For example, `qml.PauliError(["XX","YY","ZZ"],[ [0,1], [1,2], [2,0]],[0.1, 0.2, 0.3])`, such that

1. With probability `0.1` we'll apply
```python
qml.PauliX(0)
qml.PauliX(1)
```
with probability `0.2` we'll apply
```python
qml.PauliY(1)
qml.PauliY(2)
```
with probability `0.3` we'll apply the following
```python
qml.PauliZ(2)
qml.PauliZ(0)
```
and with a probability 0.4 the state is preserved.

Constructing the Kraus matrices will likely be computationally heavy when we have many wires.

We could then express your example as:
* `qml.PauliError("X", [0], p)` which has the same syntax as a bitflip essentially or;
* `qml.PauliError("XI", [0,1], p)`, provided that we allow identities in the Pauli string.

----

> Should there be a possibility to choose which Pauli Error channel is applied or should all 4 Kraus Matrices be returned?

Not quite sure about this one, what would "choose which Pauli Error channel is applied" mean?

**Comment by MoritzWillmann** [comment]
Hey @antalszava, Thanks for the detailed answer! 🚀 
You actually sort of answered my second question 😄 I think this would make sense!

My first question was more aiming towards the dimension of the returned Kraus matrices because I couldn't find any examples for Kraus Matrices for multiple wires.
To clarify let's say we have the function call `qml.PauliError("X", [0], p)`
As you already stated, this would have the same return as bitflip, so essentially
```
K_0 = sqrt(1-p) * [1 0]
                  [0 1]
K_1 = sqrt(p) * [0 1]
                [1 0]
```
If we have the call `qml.PauliError("XI", [0,1], p)` we should receive the 4 X 4 Kraus matrices from my initial example, right?

Or maybe, the total number of wires should be supplied in a separate argument?

I'll start a WIP PR, so we can maybe continue talking there 🙂
