### ISSUE TITLE
Add support for `qml.ResetError` in `default.mixed`

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1530]
### Feature details

The `qml.ResetError` channel has been added in #1321. We would like to add support for this channel in `default.mixed` and test applying it.

### Implementation

Support for `qml.ResetError` in `default.mixed` would allow the following to execute and yield correct results:

```python
import pennylane as qml

dev = qml.device('default.mixed', wires=1)

@qml.qnode(dev)
def circuit():
    qml.ResetError(0.3, 0.4, wires=0)
    return qml.expval(qml.PauliZ(0))
    
circuit()
```

*List of tasks for completion:*

1. Add support for `qml.ResetError` in the `default.mixed` device by adding it to the [list of supported operations](https://github.com/PennyLaneAI/pennylane/blob/0088704258018171ad955d83238fb08ef94ed88d/pennylane/devices/default_mixed.py#L92).
2. Add tests for [applying the channel](https://github.com/PennyLaneAI/pennylane/blob/0088704258018171ad955d83238fb08ef94ed88d/tests/devices/test_default_mixed.py#L266) using `default.mixed`.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by wongwsvincent** [comment]
Hi! I have just created a PR with my attempt on this issue. I believe it's ready for review. Please let me know if there's anything missing.

**Comment by antalszava** [comment]
Hi @wongwsvincent, thank you! :slightly_smiling_face:  We will be having a look at it soon.
