### ISSUE TITLE
Add deprecation warning for `qml.Interferometer` before renaming

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1531]
### Feature details

There is both an operation and a template called `Interferometer` which causes confusion. To resolve this, we'd like to rename `qml.Interferometer` to `qml.InterferometerUnitary`. See more details at https://github.com/PennyLaneAI/pennylane/issues/1256.

First, we would like to add a deprecation warning (at the moment we use `UserWarning`) to the current `ops.cv.Interferometer` class. If someone uses this gate, the warning should tell them that it will be renamed. This change will be there for one release cycle, so people have time to change their code.

The warning has to be tested. It is best to create a new test case for example after where the [gate is tested](https://github.com/PennyLaneAI/pennylane/blob/0088704258018171ad955d83238fb08ef94ed88d/tests/ops/test_cv_ops.py#L58), by adding a new test function using `pytest.warns`. And you have to add the change to the CHANGELOG file, and add yourselves as contributers of the release.

### Implementation

*List of tasks for completion:*

1. Add a `UserWarning` with a deprecation message to the `ops.cv.Interferometer` class explaining that it will be renamed to `InterferometerUnitary`.
2. Test that the warning is raised when creating the operation.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by AkashNarayanan** [comment]
Hi! I would like to work on this issue.

**Comment by albi3ro** [comment]
Thanks for letting us know @AkashNarayanan !

We look forward to seeing your pull request.

Feel free to comment here or open a "Work-in-Progress" Pull Request if you run into any trouble.
