### ISSUE TITLE
Categorizing the qubit gates in the documentation

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1566]
Now that qubit gates are sorted into categories in the code base, we should do so as well in the [documentation section on operations](https://github.com/PennyLaneAI/pennylane/blob/master/doc/introduction/operations.rst).  This change will help organize a list that is getting rather long, and help users find the operations in the code easier.

Instead of the section:

```
Qubit gates
^^^^^^^^
```

We should instead have a series of sections for
* Observables (already exists)
* Non-parametric Ops
* Parametric Ops
* State preparations (already exists)
* Quantum Chemistry ops
* Matrix ops
* Arithmetic ops

The sorting should follow the division of operations in [pennylane/ops/qubit](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/ops/qubit).

**Comment by Pratul-Saini** [comment]
Will the Hamiltonian operation be placed in it's own category as it is in [pennylane/ops/qubit](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/ops/qubit)? Also, given that the Pauli matrices are also observables, should we also include them under the qubit observable section or just simply mirror what is in code?

**Comment by antalszava** [comment]
Hi @Pratul-Saini, thanks for your interest! :slightly_smiling_face: 

> Will the Hamiltonian operation be placed in it's own category as it is in pennylane/ops/qubit?

Maybe, for now, we could have it listed under the observables. There are some ongoing changes made to this class, we could modify its place in the list if need be.

> Also, given that the Pauli matrices are also observables, should we also include them under the qubit observable section or just simply mirror what is in code?

They could be included at multiple places. That way they are for sure not missed. :slightly_smiling_face:
