### ISSUE TITLE
Location of identity observable in the documentation

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1567]
Currently, the [Identity observable](https://pennylane.readthedocs.io/en/stable/introduction/operations.html#shared-operations) has its own section at the bottom of the page to show that it's both a CV and a qubit operation.  By hiding it in its own section at the bottom of the page, it's so hard to notice it's effectively in neither category.

I propose that we just have the Identity operation twice on the page, once under CV observables and once under Qubit Observables.

**Comment by AkashNarayanan** [comment]
Hi @albi3ro ! I have made a PR for this issue. Please let me know if that was the expected change.

**Comment by albi3ro** [comment]
Closed by #1576
