### ISSUE TITLE
[BUG][DOCUMENTATION] "Show on GitHub" button doesn't redirect to source

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1569]
### Expected behavior

https://pennylane.readthedocs.io/en/stable/code/api/pennylane.broadcast.html on this page https://github.com/PennyLaneAI/pennylane/blob/master/doc/code/api/pennylane.broadcast.rst
this is the show on GitHub button

The show on GitHub button should take me to the GitHub page for the documentation. 

### Actual behavior

Clicking on the button results in
404 This is not the page you are looking for

### System information

```shell
N/A
Error on webpage
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Hi @ankit27kh, thank you for uncovering this! We'll investigate this issue and get back to you on with more details.

**Comment by mariaschuld** [comment]
I can confirm that this also happens for a lot of other function documentation pages, like other templates, some (or all?) fourier module and grouping module functions...so it seems to be a structural issue of how sphinx automatically builds the docs, and how the paths are then used as links.

**Comment by mariaschuld** [comment]
We decided to remove the link everywhere, since it is hard to maintain with automatic docs generation!
