### ISSUE TITLE
Draw circuit without passing circuit arguments

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1572]
### Feature details

Currently, to draw a circuit, we need to pass the inputs which are then used in the circuit drawing.
I suggest having a general circuit drawing function that can draw the circuit without those inputs. Instead of showing the angles of rotation, for example, it can simply say which type of rotation gate it is.
We can then have a general circuit. Not a parameterized one.

### Implementation

Drawing capability is already there. Just need to modify it such that `circuit.draw()` will draw a general circuit if no parameters have been passed, instead of raising an error. If parameters are given, `circuit.draw()` will function as it does now and `circuit.draw(parametric=False)` will draw the general circuit.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

#1484 is somewhat related. It enables drawing of mpl circuits. Not sure if will draw general circuits or not. If not, this issue can also be added for that. 
Parameterized circuits are good but general circuits are also needed.

**Comment by josh146** [comment]
Hey @ankit27kh! This is a good suggestion, but might be quite difficult to design and implement.

The reason is that PennyLane QNodes are quantum _functions_, and need to be executed (with parameters) for the circuit to be created.

There are also some subtleties! For instance, if the QNode includes conditional statements:

```python
@qml.qnode(dev)
def circuit(x, hadamard=False):
    qml.RX(x, wires=0)
    if hadamard:
        qml.Hadamard(wires=0)
    return qml.expval(qml.PauliZ(0))
```

```pycon
>>> print(qml.draw(circuit)(0.1, hadamard=True))
 0: ──RX(0.1)──H──┤ ⟨Z⟩
>>> print(qml.draw(circuit)(0.1, hadamard=False))
 0: ──RX(0.1)──┤ ⟨Z⟩
```

So in the short term, there might not be away around passing parameters when drawing the circuit 🤔 

However, even though we might be forced to pass arguments, it is probably much more doable in the short-term to turn off parameters if that is what you mean in your issue? Something like the following, for example:

```pycon
>>> print(qml.draw(circuit, show_parameters=False)(0.1, hadamard=True))
 0: ──RX──H──┤ ⟨Z⟩
```

**Comment by ankit27kh** [comment]
I had imagined that we could pass some fixed set of parameters internally to create the tape and then draw the circuit without showing the parameters. I had not thought of conditional statements. This does make it difficult.

But yes, considering your comment, having an option like `show_parameters=False` will be nice to have in general, even after the more complicated issue has been addressed.

**Comment by mariaschuld** [comment]
@ankit27kh this sounds like a nice feature. Let us know if you'd like to give it a go and we can point you to the important bits! The circuit drawer is in the `pennylane/circuit_drawer` folder, and the code takes a while to see through, but it is in principle just string rendering, so it may be a fun little task...

**Comment by ankit27kh** [comment]
@mariaschuld I can not commit myself right now but would love to work on it if it's still an issue at a later date.

**Comment by albi3ro** [comment]
I'm in the process of developing a new circuit drawer using matplotlib, and will keep this in mind when I get to the right stage.

**Comment by albi3ro** [comment]
@ankit27kh 

As long as the values don't have any classical processing (like `x+y` or `if x`),
then strings can be used in place of numbers in the current circuit drawer.

```python
@qml.qnode(qml.device('default.qubit', wires=1))
def circ(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

print(qml.draw(circ)('x'))
``` 
```
0: ──RX(x)─┤  <Z>
```

Does this provide what you wanted? It won't work in all situations, but hopefully will be useful enough for most.

**Comment by ankit27kh** [comment]
Hello @albi3ro! Thanks for this! And also for the wonderful mpl drawer! Great addition!

**Comment by antalszava** [comment]
I'll be closing this issue until further notes on the topic. :+1:
