### ISSUE TITLE
Add a barrier "gate"(?) in circuit library. 

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1577]
### Feature details

A barrier that acts similar to the barrier in Qiskit. It is supposed to separate pieces of the circuit into blocks that are optimised and run separately. Also, it will help in the visualization of circuits. As currently, it becomes a little difficult to see what's happening when all gates are drawn from left to right without any correlation with gates on other qubits.

### Implementation

It will work like this:

```
dev = qml.device("default.qubit", wires=2)

@qml.qnode(dev)
def func(x):
    qml.PauliX(0)
    qml.PauliX(0)
    qml.PauliX(0)
    qml.PauliZ(1)
    return qml.expval(qml.PauliZ(0))

func.draw()
>>> 0: ──X──X──X──┤ ⟨Z⟩ 
    1: ──Z────────┤     

@qml.qnode(dev)
def func(x):
    qml.PauliX(0)
    qml.PauliX(0)
    qml.PauliX(0)
    qml.barrier()
    qml.PauliZ(1)
    return qml.expval(qml.PauliZ(0))

func.draw()
>>> 0: ──X──X──X─||─┤ ⟨Z⟩ 
    1: ──────────||Z┤     
```
Something like this.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

https://quantum-computing.ibm.com/composer/docs/iqx/operations_glossary#barrier-operation

https://qiskit.org/documentation/stubs/qiskit.circuit.library.Barrier.html

**Comment by mariaschuld** [comment]
Thanks @ankit27kh, that is indeed a nice feature. Just to fully understand, would the added benefit just be a visual one, i.e. to inspect circuit drawings? Or do you have performance/compilation goals in mind too?

An idea of how to do this is to give gates a shared id to "group" them:

```python

def circuit():
   qml.Hadamard(wires=0, id="groupA")
   qml.RX(1.2, wires=1, id="groupA")
   qml.RY(-0.1, wires=0, id="groupB")
   qml.CNOT(wires=[0,1], id="groupB")
```

The circuit drawer, or even compilers could take these groups into account.

**Comment by ankit27kh** [comment]
It will provide more control to the user. Choosing which gates should be merged/transpiled. Also to control the sequence in which the gates will be run. 
The visual benefit is also an important one in my opinion because when circuits get bigger, it becomes difficult to see what's happening just from the code. Clear circuit drawings help a lot in this regard.

**Comment by mariaschuld** [comment]
@glassnotes I am wondering if your compilation transforms could cater for something like this? I.e. they only merge gates that have the same id (if we run with my suggestion for a moment)?

**Comment by glassnotes** [comment]
@mariaschuld @ankit27kh this is an interesting and useful idea, and should be straightforward to implement :rocket: The transforms work by looping through the list of gates on the tape, then looking ahead at the next relevant operation to check whether something can be done with it. We can simply add a flag like `merge_same_id_only` and use it as an extra condition in those checks.

**Comment by ankit27kh** [comment]
@mariaschuld @glassnotes 
The id system is good for grainer control, but it will be more difficult to do in bigger circuits practically. I guess it will result in a lot more repetitive code.
Also, I hope it will still be able to help in visualization. (?)

**Comment by mariaschuld** [comment]
You are right, maybe a `qml.Barrier()` would be a better option, and it seems compilation could just check and then stop at that dummy gate.

In any case, we may not be able to implement this feature right now from our side, but hopefully this issue will encourage contributors to pick it up (@ankit27kh, let us know if you want to give it a shot yourself :) ). Note that we would still have to fix a design before going ahead.
