### ISSUE TITLE
Inconsistency in treatment of optimizer hyperparameters

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1578]
The hyperparameter for `GradientDescentOptimizer` is `opt._stepsize`, a private variable that is updated with `opt.update_stepsize(stepsize=new_value)`.  This private variable does not have a getter function for accessing it's value.

On the other hand, all other optimizers with hyperparameters merely set the parameters as public variables, like `adagrad_opt.beta1` or  `momemntum_opt.momentum`.  This way users can view and set the hyperparameters without accessing private variables.

We should treat all hyperparameters the same.

I propose simply making `opt._stepsize` public via renaming it to `opt.stepsize` and deprecating the `opt.update_stepsize` method.

**Comment by AkashNarayanan** [comment]
Hi @albi3ro ! I would like to work on this issue. Just to make sure I am on the right track, this issue involves renaming the hyperparameter in the `GradientDescentOptimizer` class as well as in all the classes that inherit it and in the test cases. `UserWarning` should be added to the `update_stepsize()` method and a test case has to be defined to check if the warning is raised, right?

**Comment by albi3ro** [comment]
Thanks @AkashNarayanan 🎇 You basically covered it, but I wrote it up in a list form below.  Since someone might be accessing `_stepsize` directly in their code, I think we should temporarily make `_stepsize` a property that gets `stepsize`, sets `stepsize`, and raises a `UserWarning` both times.

Here's a list with relevant code links:

* Make [`_stepsize`](https://github.com/PennyLaneAI/pennylane/blob/802c45cd13ca422bad982b5bef660739bc015282/pennylane/optimize/gradient_descent.py#L39) a public variable `stepsize`
* Update relevant references to it through each optimizer.  These will probably be within the `apply_grad` method.
* Modify [`update_stepsize`](https://github.com/PennyLaneAI/pennylane/blob/802c45cd13ca422bad982b5bef660739bc015282/pennylane/optimize/gradient_descent.py#L41) to raise a `UserWarning` about this method being deprecated.
* Create a property `_stepsize` that raises a `UserWarning` about deprecation and then returns `stepsize`. To maintain backward compatibility temporarily, we should also have a property setter allowing users to set `stepsize` via setting `_stepsize`.
* Update tests.  Optimizer tests are currently a mess, so modify `test_update_stepsize`, then add the other tests to the bottom.
    - Modify [`test_update_stepsize`](https://github.com/PennyLaneAI/pennylane/blob/802c45cd13ca422bad982b5bef660739bc015282/tests/optimize/test_optimize.py#L671) to check it raises a `UserWarning`.
    - Add tests for temporary property `_stepsize`.  Make sure we can still get and set `stepsize` via `opt._stepsize`. Just add these to the bottom
* Add an entry to "Breaking changes" in the Changelog.

We will have the `UserWarnings` and old code for a release cycle and then deprecate them afterward.

**Comment by AkashNarayanan** [comment]
Thank you for the detailed list!
