### ISSUE TITLE
[BUG] Unable to add Identity gate to a circuit.

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1630]
### Expected behavior

Adding Identity gate in a circuit should work fine. Like any other gate without any extra parameters.

### Actual behavior

Errors out.

### Additional information

100 % of the time. Comment out the identity gate line and everything works fine.

### Source code

```shell
dev = qml.device('default.qubit', wires=3)
@qml.qnode(dev)
def circuit(res):
    qml.Hadamard(wires=1)
    qml.CNOT(wires=[1, 2])
    qml.Identity(wires=0)
    return qml.expval(qml.PauliZ(1))
circuit(1)
```

### Tracebacks

```shell
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "\lib\site-packages\pennylane\qnode.py", line 606, in __call__
    self.construct(args, kwargs)
  File "\lib\site-packages\pennylane\qnode.py", line 525, in construct
    self.qfunc_output = self.func(*args, **kwargs)
  File "\lib\site-packages\pennylane\tape\tape.py", line 354, in __exit__
    self._process_queue()
  File "\lib\site-packages\pennylane\tape\tape.py", line 453, in _process_queue
    raise ValueError(f"Observable {obj} does not have a measurement type specified.")
ValueError: Observable Identity(wires=[0]) does not have a measurement type specified.
```

### System information

```shell
Name: PennyLane
Version: 0.17.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: \lib\site-packages
Requires: semantic-version, autoray, autograd, networkx, numpy, scipy, appdirs, toml
Required-by: 
Platform info:           Windows-10-10.0.22449-SP0
Python version:          3.9.6
Numpy version:           1.21.2
Scipy version:           1.7.1
Installed devices:
- default.gaussian (PennyLane-0.17.0)
- default.mixed (PennyLane-0.17.0)
- default.qubit (PennyLane-0.17.0)
- default.qubit.autograd (PennyLane-0.17.0)
- default.qubit.jax (PennyLane-0.17.0)
- default.qubit.tf (PennyLane-0.17.0)
- default.tensor (PennyLane-0.17.0)
- default.tensor.tf (PennyLane-0.17.0)
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Hi @ankit27kh, thanks for mentioning this! This is expected as `qml.Identity` is an observable in PennyLane. Therefore its main use case in mind is to be used in the `return` statement of a quantum function. The error message is refering to this, it's expected to be in the `return` statement and as there is no measurement type specified, the error arises.

Would it be worthwhile having `qml.Identity` be usable as an operation too? I think so far we haven't come across cases where this could be useful, but if so, we could definitely consider allowing this feature too.

**Comment by ankit27kh** [comment]
Ah! Ok!

>Would it be worthwhile to have qml.Identity act as an operation too?

Yes! I mean why not? It's the most basic of gates. This should be there. One use is to have forced delay between gates. It can also be used in benchmarks.
Even without any direct application, I would hope to have this in the arsenal just in case.

**Comment by antalszava** [comment]
Hi @ankit27kh, I've created issue https://github.com/PennyLaneAI/pennylane/issues/1632 dedicated to adding support for `qml.Identity` to act as an operation. I'll be closing this issue, but let us know either here or at the other issue if you'd have any further suggestions/thoughts. Thanks for reach out! :slightly_smiling_face:
