### ISSUE TITLE
Allow using `qml.Identity` as an operation in quantum functions

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1632]
### Feature details

As noted in https://github.com/PennyLaneAI/pennylane/issues/1630, it would be worthwhile to allow `qml.Identity` to act as an operation in quantum functions, e.g.,:

```python
import pennylane as qml

dev = qml.device('default.qubit', wires=3)

@qml.qnode(dev)
def circuit():
    qml.Identity(wires=[0])
    return qml.expval(qml.PauliZ(wires=[0]))

circuit()
```
```
tensor(1., requires_grad=True)
```

At the moment, `qml.Identity` acts as an observable by inheriting from `CVObservable`. It can be included in both CV and qubit based quantum functions.

### Implementation

1. First, the `Identity` operation would need to be extended, such that it will inherit from the `Operation` class too:

```python
class Identity(CVObservable, Operation):
```
(the import in the file will need to be adjusted to `from pennylane.operation import AnyWires, Observable, CVObservable, Operation`).

*Note:* It would also be nice to adjust `num_wires` to be `num_wires = 1`, though it might be that this will uncover some edge cases.

2. Once this is done, support for built-in devices would follow. As `qml.Identity` can act in both CV and qubit based quantum functions, we'd like to add support for both the CV based `default.gaussian` device and for qubit based devices (`default.qubit` and `default.mixed`).

     a. For `default.gaussian`, this can be achieved by adding the `"Identity": qml.Identity._matrix,` entry to the `_operation_map` attribute of the device.
     b. For `default.qubit` and `default.mixed`, the `"Identity",` item needs to be added to the `operations` attribute of the device.
3. Finally, we'd like to ensure the `qml.Identity` works well. Therefore, we'd like to add tests that verify and check the correctness of applyting the `qml.Identity` operation in each of the following files:
* https://github.com/PennyLaneAI/pennylane/blob/master/tests/ops/test_cv_ops.py
* https://github.com/PennyLaneAI/pennylane/blob/master/tests/ops/qubit/test_non_parametric_ops.py
* https://github.com/PennyLaneAI/pennylane/blob/master/tests/devices/test_default_gaussian.py
* https://github.com/PennyLaneAI/pennylane/blob/master/tests/devices/test_default_mixed.py
* https://github.com/PennyLaneAI/pennylane/blob/master/tests/devices/test_default_qubit.py

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

While the main approach is described above, there might be unexpected edge cases that are uncovered by carrying out these changes. When creating a work in progress PR, let us know if this would be the case.

**Comment by QRiddler** [comment]
Hi! can I work on it?

**Comment by antalszava** [comment]
Hi @QRiddler, yes, sure! Let us know if you have any questions along the way and feel free to open a work in progress pull request. :slightly_smiling_face:

**Comment by QRiddler** [comment]
@antalszava what does "Once this is done, support for built-in devices would follow" mean? I didn't get that part.

**Comment by QRiddler** [comment]
@antalszava can you help in how to add tests? I am stuck on it.
