### ISSUE TITLE
Add `torch` exception for `sort` to math's `single_dispatch.py`.

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/pennylane#1660]
### Feature details

Update handling of `sort` in `qml.math` such that the return values are the same across all interfaces. 

The current behaviour is as follows. For `numpy`, `jax`, and `tf`, 
```pycon
>>> a = np.array([1, 3, 4, 2])
>>> qml.math.sort(a)
tensor([1, 2, 3, 4], requires_grad=True)
``` 

But for `torch`, the argument indices are also returned:
```pycon
>>> a = torch.tensor([1, 3, 4, 2])
>>> qml.math.sort(a)
torch.return_types.sort(
values=tensor([1, 2, 3, 4]),
indices=tensor([0, 3, 1, 2]))
```

### Implementation

It should be possible to just add a custom implementation in `math/single_dispatch.py` and then register the new function. For example (taken from the current implementation of `_take_torch`):

```python
def _sort_torch(tensor):
    # Do the sort 
    # return only the sorted array 

ar.register_function("torch", "sort", _sort_torch)
```

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by RubidgeCarrie** [comment]
Hi @glassnotes I am new to the open source community and wanted to ask if it is alright if I try this as my first issue?

**Comment by glassnotes** [comment]
Hi @RubidgeCarrie , welcome! Absolutely, please go ahead, and let us know if you have questions. :grin:

**Comment by RubidgeCarrie** [comment]
HI @glassnotes, thank you! I did the update by replacing the sort for tensors with the customized sort as you mentioned above. However when I ran the unit test I realized some functions in transform are using the indices or at least expecting them from sort. Would it be worth creating a new sort function here or is this something you would then leave as is and not update?

**Comment by glassnotes** [comment]
> HI @glassnotes, thank you! I did the update by replacing the sort for tensors with the customized sort as you mentioned above. 

Great!  When you're ready, please go ahead and open a PR :smiley:

> However when I ran the unit test I realized some functions in transform are using the indices or at least expecting them from 
> sort. Would it be worth creating a new sort function here or is this something you would then leave as is and not update?

Ahh, from the `two_qubit_decomposition` transform right? Writing that transform is actually how we realized that  torch sort worked differently :sweat_smile: The sort indices aren't required, so what you could do is just remove the interface checks for torch, and simply replace those few lines with the new-and-improved `qml.math.sort`.

**Comment by RubidgeCarrie** [comment]
Thank you @glassnotes that makes a lot of sense, I have updated those. When adding a unit test I noticed that the current python test files under test\math are being skipped. I haven't been able to find the reason for this and my unit test does run when saved under a separate file. Would you recommend I save my unit test in tests\math\basic_test_functions.py for now and would this then be an issue that would be sorted out later?

**Comment by glassnotes** [comment]
Hi @RubidgeCarrie , I recommend to open a PR and then we can see what happens when the continuous integration runs the tests. I'm looking at the files in `tests/math`, and at the beginning it checks to see which interfaces are available, and skips what it can't run (e.g., if it cannot import tensorflow, it will skip all those tests). Within the context of the PR, everything will be installed for it so it shouldn't skip anything.

**Comment by RubidgeCarrie** [comment]
Hi @glassnotes, thank you for all the help and recommendations, I really appreciate it. I have opened a PR, hopefully it is alright otherwise I will give it another try.

**Comment by glassnotes** [comment]
Great thanks @RubidgeCarrie , we'll give that a review as soon as possible!
