### ISSUE TITLE
Jax interface for classical machine learning

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#168]
The lead developer of [Autograd](https://github.com/HIPS/autograd) is now developing a new classical machine learning framework, [Jax](https://github.com/google/jax).

While the interface and API remain very similar to Autograd, Jax has a couple of advantages:

* It is very actively maintained
* It uses XLA to compile and run your NumPy programs on GPUs and TPUs

It would be great (and should be relatively easy) to have a classical interface between PennyLane and Jax.

**Comment by co9olguy** [comment]
Should now be possible with new (experimental) tensornet device

**Comment by josh146** [comment]
Note that this is slightly different then what is provided by the experimental tensornet device. Separately, a new `pennylane.interfaces` function will be required to add JAX support to the front-end UI.

**Comment by josh146** [comment]
This has been superceded by #943
