### ISSUE TITLE
Density matrix equivalent of qml.QubitStateVector for a mixed state simulation

### ISSUE THREAD

**Issue by shukob** [PennyLaneAI/pennylane#1686]
### Feature details

For a mixed state simulation, I want to start from a given density matrix, but there is no such operation.

### Implementation

A mixed state equivalent to the `QubitStateVector` class will be required, also `_apply_operation` for mixed state simulators should be modified.

### How important would you say this feature is?

3: Very important! Blocking work.

**Comment by CatalinaAlbornoz** [comment]
Hi @shukob, thank you for this feature request! We will take a look into it.

**Comment by kharazity** [comment]
Can you prepare an arbitrary density matrix on a quantum computer? Doesn't the density operator need to be in a pure state? Up to a global phase you can recover the underlying statevector given a pure state density matrix.

**Comment by shukob** [comment]
I think it can be statistically prepared. Diagonalize density matrix and probabilistically feed each eigenstate.
But my intention here is to make simulation using `default.mixed` being convenient.

**Comment by kharazity** [comment]
What do you mean by probabilistically feeding the eigenstates?

**Comment by shukob** [comment]
If it is a|x><x| + b |y><y| whre a + b = 1, then prepare pure states probabilistically as p(|x>) = a , p(|y>) = b.

**Comment by kharazity** [comment]
That is, if you run the experiment for a thousand shots, you'd run a*1000 with |x> and b*1000 with |y>?

**Comment by shukob** [comment]
I think that is one idea if both of the classical results can be easily combined in the postprocessing.

**Comment by shukob** [comment]
At least for simple observable, you can just compute a(expectation for |x>) + b(expectation for |y>) with arbitrary shots.

**Comment by CatalinaAlbornoz** [comment]
Hi @shukob, would you like to tackle this issue? It's participating in Hacktoberfest, so it's a good chance to try it. Let me know if you want to know what Hacktoberfest is all about!

**Comment by shukob** [comment]
@CatalinaAlbornoz 
Hi, I don't know about Hacktobefest, apart from that I have already implemeted locally but will need testing for transposition when feeding non-conitnuous wire indices. If you know a reference implementation for transposing density matrix, it will be greatly helpful.
Thanks!

**Comment by CatalinaAlbornoz** [comment]
Hi @shukob! Hacktoberfest is an initiative to motivate contributions to open-source. Participants who register on the [Hacktoberfest website](https://hacktoberfest.digitalocean.com/) and complete at least 4 approved pull requests can win a t-shirt or plant a tree (unless the organizers run out of t-shirts). The pull requests have to be done on participating repositories, such as PennyLane! For the contribution to count it must be approved by October 31st. 
Let me know if you have any more questions!

Regarding the reference implementation for transposing density matrix I'm not sure if I understand the question. Have you tried `np.transpose`?

**Comment by CatalinaAlbornoz** [comment]
Hi @shukob, if the issue is with partial transposition you can do partial transpose with a combination of reshape and transpose. Please let me know if this helps or if I'm understanding the question wrong.

**Comment by shukob** [comment]
I made a separate WIP PR #1850 for this.

**Comment by CatalinaAlbornoz** [comment]
Thank you @shukob!
