### ISSUE TITLE
Hamming Distance Utility function

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1703]
Many quantum applications use the [Hamming Distance](https://en.wikipedia.org/wiki/Hamming_distance) between two states.

While this is a fairly straightforward thing to calculate, we should make it even easier and keep users from having to think about it at all.

We should also allow the function to accept all state representation forms:

A) integers representing states in their binary forms. for example `4 = "100"`
B) string form of a binary number, like `"100"`
C) array of booleans, like `[1,0, 0]`

Potential examples:
```
>>> qml.HammingDistance(3,4) 
3
>>> qml.HammingDistance("100", "011")
3
>>> qml.HammingDistance([1,0,0], [0,1,1])
3
```

This utility function could be placed in the [`utils.py`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/utils.py) file.

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by antalszava** [comment]
Hi @aniket-24, thanks for your interest! :slightly_smiling_face: Let us know if you'd have any questions along the way. Feel free to open a new work in progress pull request.

**Comment by antalszava** [comment]
Hi @aniket-24, will be closing this issue for now, as there is a simple way of obtaining the Hamming distance using SciPy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.hamming.html

Therefore we'd recommend using that one.

Feel free to browse through the rest of the "good first issues" and other open issues we have!

**Comment by aniket-24** [comment]
okay! fine
