### ISSUE TITLE
Rename `qml.Interferometer` to `qml.InterferometerUnitary`

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1709]
### Feature details

As per https://github.com/PennyLaneAI/pennylane/issues/1256, we're changing `qml.Interferometer`, as it collides with a the template `qml.templates.Interferometer`.

A short summary based on the (updated) comments in the linked issue:

> In this PR we need to rename the class, and then search for lines in the code where `Interferometer` is translated to an implementation.

### Implementation

> 1. Check the `default.gaussian` device, and change the operation name there. More precisely, at the moment when `default.gaussian` encounters a gate called Interferometer, it expects it to have a param that represents the unitary which defines the interferometer's matrix. This logic should now only be performed when it sees `InterferometerUnitary`. When it sees Interferometer it should not find a translation in the list, and will then decompose this operation into the gates defined in `template.Interferometer`. In other words, in future InterferometerUnitary is an operation that is natively supported by devices, while `templates.Interferometer` is an operation that is only defined by its decomposition.

> 2. The `representation_revolver` would also require a change such that circuit drawing is updated.

See details on the possible changes to be made:

* https://github.com/PennyLaneAI/pennylane/issues/1256#issuecomment-845350642

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

We'd like to have this in for `v0.19.0`.

**Comment by AkashNarayanan** [comment]
Hi @antalszava ! I would like to work on this issue.

**Comment by antalszava** [comment]
Hi @AkashNarayanan, that's great to hear! :slightly_smiling_face: Feel free to ask any questions and open a work in progress PR.

**Comment by Anaxagoras7** [comment]
@antalszava I would like to know if this issue is still open and could I work on it?

**Comment by antalszava** [comment]
Hi @Anaxagoras7, it is, but we've received a submitted contribution for it which we'll be reviewing. One thing to keep in mind is the first accepted PR to the issue will be accepted for Hacktoberfest too. We do have some other "good first issues" and further issues open. :slightly_smiling_face:

**Comment by Anaxagoras7** [comment]
Sure...thank you for the info🙂

**Comment by antalszava** [comment]
Closing with #1714 merged.
