### ISSUE TITLE
Have devices allocate `wires` dynamically

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1717]
### Feature details

Devices should decide how many wires are needed once a specific QNode uses them.
This has the following advantages:
- Conceptually, this is nicer because there is no underlying need to specify the numbers of wires a priori. In thus forms a restriction/requirement of information earlier than necessary in the pipeline
- Currently, when executing a few-wires circuit on a many-wires device, performance is smaller than when executing the same circuit on a device with matching number of wires.
- Even more extreme, executing a single-wire circuit on a very-many-wires simulator will not be possible if the statevector can not be initialized due to memory capacity.
- When implementing transforms that require an auxiliary qubit, no new device will have to be created. 

### Implementation

Probably it would be best to maintain the _option_ of specifying the wires when creating the device, mostly for backwards-compatibility.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by josh146** [comment]
> Would this be best to put off till the device refractor, and just be another element of that?

I think so yes, but something to add to the list 🙂

Having said that, I don't think this is that much of a breaking change, since specifying wires is not a requirement currently (I think?), as hardware devices do not need to specify the number of wires. So it might just be a tweak to `default.qubit` 🤔

**Comment by dwierichs** [comment]
I have the impression this issue could be closed, as the topic is tracked within the refactor by now? @albi3ro

**Comment by albi3ro** [comment]
Yep. Our next-gen "default qubit 2" dynamically allocates wires.
