### ISSUE TITLE
jax interface missing from QNode documentation

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1729]
In the information about [interfaces in the QNode documentation](https://github.com/PennyLaneAI/pennylane/blob/949f5d52f3fd3806b051aa8d15cc5a7038d46832/pennylane/qnode.py#L53), the "jax" option is missing, even though the QNode can have a jax interface.

We need to have a bullet point for the `"jax"` option.

**Comment by Animikh2301** [comment]
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

    <bean class="com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON" />
    <bean class="com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider" />
    <bean class="com.wordnik.swagger.jaxrs.listing.ResourceListingProvider" />
</beans>

**Comment by San091102** [comment]
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

    <bean class="com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON" />
    <bean class="com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider" />
    <bean class="com.wordnik.swagger.jaxrs.listing.ResourceListingProvider" />
</beans>

**Comment by anonymousr007** [comment]
Hi @albi3ro, Can you please elaborate ?

**Comment by anonymousr007** [comment]
Yes, I want to tackle this problem
