### ISSUE TITLE
Create a central file for `expand_fn` functions

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1732]
### Feature details

With transforms taking shape and being used by some features now, a centralized file containing common expansion rules would be useful for both developers and users.
It would contain stopping criteria as well as a generic generator of `expand_fn` from stopping criteria.

### Implementation

This likely is a very small addition, in terms of lines of code.

Stopping criteria could be implemented as simple lambdas or short functions:
```python
has_generator = lambda obj: hasattr(obj, "generator") and obj.generator[0] is not None

has_unitary_generator = lambda obj: hasattr(obj, "has_unitary_generator") and obj.has_unitary_generator

has_multiple_parameters = lambda obj: obj.num_params>1
```
Then there could be a generator for `expand_fn`s from such criteria:
```python
def get_expand_fn(criteria):
    return lambda obj: all(crit(obj) for crit in criteria)
```

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

I think this is very easy to incorporate but will become more work once more transforms and `expand_fn`s are scattered around the code base. Therefore it would be best to do this sooner rather than later. However, it is not crucial for any functionality or blocking any further progress as far as I can tell...

**Comment by dwierichs** [comment]
@josh146, am I mistaken or did #1734 actually close this issue?

**Comment by josh146** [comment]
Yes! good catch :) I think we forgot to close this.
