### ISSUE TITLE
Add consistent documentation for qml.templates section

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1735]
### Feature details

In the documentation for templates [here](https://pennylane.readthedocs.io/en/stable/introduction/templates.html), some templates have "Usage Details" section, like [this](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.StronglyEntanglingLayers.html) and [this](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.broadcast.html). Others don't, like [this](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.embeddings.AngleEmbedding.html).
Even with those that have the section, you'll find some don't have much detail in them, like the first one above, while some have full example codes, like the second one.
This is inconsistent and bad user experience.

I suggest adding code examples with details to all templates.

### Implementation

Add simple examples to all templates with details of parameters.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by CatalinaAlbornoz** [comment]
Hi @ankit27kh, thank you! The main templates file which is part of the quickstart guides is [here](https://github.com/PennyLaneAI/pennylane/blob/master/doc/introduction/templates.rst). There you will find the links to each of the templates, and you can modify all of those that you want.

This [doc](https://pennylane.readthedocs.io/en/stable/development/guide/documentation.html) might be helpful too. In any case, if you have another question please ask us!

**Comment by antalszava** [comment]
Closing this as all templates now have an example.
