### ISSUE TITLE
Add transform for alternative ZXZ Euler-angle decomposition of `Rot` gates

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/pennylane#1747]
### Feature details

Currently the decomposition of the `Rot` gate is fixed as `[RZ(theta), RY(phi), RZ(omega)]`. However, it is possible to write an arbitrary single-qubit unitary in 12 different ways using different combinations of `RX, RY, RZ`. One common decomposition is as  `[RZ(a), RX(b), RZ(c)]`. It would be nice to have a qfunc transform that could pass through a circuit, and convert all instances of `Rot` gates into an equivalent sequence of gates of the form `[RZ, RX, RZ]`.

### Implementation

This feature should be implemented as a transform `rot_to_zxz` in the `pennylane/transforms` folder. 

There are two possible approaches. One is to add an explicit matrix decomposition, `zxz_decomposition` `transforms/decompositions/single_qubit_unitary.py`, and then use this in the transform. Another is to perform that decomposition within the transform itself.

In either case, the transform should preserve the differentiability of the input arguments of the `Rot` gates. This can be done by using the `qml.math` module to ensure tensor manipulation is supported on Autograd, TensorFlow, Torch, and JAX. Tests for differentiation of this transform should also be added.

**Comment by albi3ro** [comment]
Fixed by #4246
