### ISSUE TITLE
Implement matrix attribute for qml.Hamiltonian

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1758]
### Feature details

```
obs = [qml.PauliX(0), qml.PauliX(1), qml.PauliZ(0)]
coeffs = np.array([1., 2., 3.])
H = qml.Hamiltonian(coeffs, obs)
H.matrix
```
This should work. 

`matrix` and `eigvals` are mentioned on the documentation page [here](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Hamiltonian.html#pennylane.Hamiltonian.matrix).
These raise `NotImplementedError`.

### Implementation

Should be straightforward. Need to use tensor products to get matrix representations of the individual terms of the Hamiltonian and then add them all up.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by antalszava** [comment]
Hi @ankit27kh, thanks for opening this issue! Indeed, we have a rethink of operators coming up in the pipeline and the matrix representation of Hamiltonians will also be affected by that push. For now, we're still in the exploratory phases of an incoming bigger change.

@mariaschuld could perhaps leave even more details on the approach.

**Comment by josh146** [comment]
This can now be closed, as we support `qml.matrix(H)` 🙂
