### ISSUE TITLE
Add batching support to the `BasicEntanglerLayers` template

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1776]
### Feature details

Following up on the issue description from https://github.com/PennyLaneAI/pennylane/issues/1745 we would like to add batch support to the [`BasicEntanglerLayers` template](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.BasicEntanglerLayers.html).

This follows the addition in https://github.com/PennyLaneAI/pennylane/pull/1710. That PR also showcases how batching support was added to `StronglyEntanglingLayers`.

### Implementation

We would like to support the following example:

```python
import pennylane as qml
from pennylane import numpy as np

dev = qml.device("default.qubit", wires=3)

@qml.batch_params
@qml.beta.qnode(dev)
def circuit(weights):
    qml.templates.BasicEntanglerLayers(weights, wires=[0, 1, 2])
    return qml.expval(qml.Hadamard(0))

batch_size = 3
weights = np.random.random((batch_size, 10, 3))
circuit(weights)
```

This can be done by modifying the `BasicEntanglerLayers` source code as needed. In addition, a test should be added to `tests/transforms/test_batch_params.py`.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by puzzleshark** [comment]
open PR for this issue https://github.com/PennyLaneAI/pennylane/pull/1883
