### ISSUE TITLE
Preventing printing overflow for long circuits in terminal with `qml.draw_circuit()`

### ISSUE THREAD

**Issue by greenstick** [PennyLaneAI/pennylane#1841]
### Feature details

Calling `qml.drawcircuit` and rendering the output to the terminal results in illegible circuits if the circuit width (*i.e.* the number of text columns used) is greater than the column width of the terminal window. This issue is due to the overflow of text used to visualize the circuit onto the next line. For example:

**Current Behavior:**
```
|------------------terminal width ------------------|
 0: ─H─RZ(1.0)──╭C──────────╭X─RX(3.14)─╭C──────────
 ╭X─RX(3.14)──────┤ ⟨Z⟩
 1: ─H─RZ(0.1)──╰X─╭C───────│──RX(3.14)─╰X─╭C───────
 │──RX(3.14)──────┤
 2: ─H─RZ(0.2)─────╰X─╭C────│──RX(3.14)────╰X─╭C────
 │──RX(3.14)──────┤
 3: ─H─RZ(0.3)────────╰X─╭C─│──RX(3.14)───────╰X─╭C─
 │──RX(3.14)──────┤
 4: ─H─RZ(0.4)───────────╰X─╰C─RX(3.14)──────────╰X─
 ╰C─RX(3.14)──────┤
```
A possible solution would be to detect the width of the terminal prior to printing the circuit. With the width detected, the printing of lines could occur with the circuit length modulo the terminal width to facilitate line skipping as needed. This skipping would be repeated to allow the full circuit to be cleanly rendered in the terminal without the overflow issues. For example:

**Alternative Behavior:**
```
|------------------terminal width ------------------|
 0: ─H─RZ(1.0)──╭C──────────╭X─RX(3.14)─╭C────────── 
 1: ─H─RZ(0.1)──╰X─╭C───────│──RX(3.14)─╰X─╭C───────
 2: ─H─RZ(0.2)─────╰X─╭C────│──RX(3.14)────╰X─╭C────
 3: ─H─RZ(0.3)────────╰X─╭C─│──RX(3.14)───────╰X─╭C─
 4: ─H─RZ(0.4)───────────╰X─╰C─RX(3.14)──────────╰X─

 0: ─╭X─RX(3.14)──────┤⟨Z⟩
 1: ─│──RX(3.14)──────┤
 2: ─│──RX(3.14)──────┤
 3: ─│──RX(3.14)──────┤
 4: ─╰C─RX(3.14)──────┤
```

Provided there's interest, I'd be happy to send a pull request with this feature (although I may need assistance testing it on Linux and Windows operating systems). 

### Implementation

To detect the terminal size:

```python
import shutil
cols, _ = shutil.get_terminal_size()
```

Note that `shutil` is part of the standard library and would not require an additional dependency. 

It seems to me this could be integrated fairly trivially into `qml.circuit_drawer.draw()` (below), but perhaps this could be confirmed by a developer more familiar with the code base. 

```python
    def draw(self):
        """Draw the circuit diagram.
        Returns:
            str: The circuit diagram
        """
        rendered_string = ""

        # extract the wire labels as strings and get their maximum length
        wire_names = []
        padding = 0
        for i in range(self.full_representation_grid.num_wires):
            wire_name = str(self.active_wires.labels[i])
            padding = max(padding, len(wire_name))
            wire_names.append(wire_name)

        for i in range(self.full_representation_grid.num_wires):
            # format wire name nicely
            wire = self.full_representation_grid.wire(i)
            s = " {:>" + str(padding) + "}: {}"

            rendered_string += s.format(wire_names[i], 2 * self.charset.WIRE)

            for s in wire:
                rendered_string += s

            rendered_string += "\n"

        for symbol, cache in [
            ("U", self.representation_resolver.unitary_matrix_cache),
            ("H", self.representation_resolver.hermitian_matrix_cache),
            ("M", self.representation_resolver.matrix_cache),
        ]:
            for idx, matrix in enumerate(cache):
                rendered_string += "{}{} =\n{}\n".format(symbol, idx, matrix)

        return rendered_string
```

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by albi3ro** [comment]
Hi @greenstick  and thanks for your feedback.

I have a new text circuit drawer planned for the next few months (fingers crossed) and can incorporate this feature at that point.  

I would probably make a keyword `max_length=80` that users can modify and specify as need be, instead of reading something about the operating system and environment.

If you want this feature sooner, feel free to try and implement it yourself, but I will warn you that that isn't the easiest chunk of code to understand, and it is already on the chopping block.

**Comment by greenstick** [comment]
Are you planning on entirely new code or refactoring the current code? If it's the latter, I'd take a crack at implementing a `max_length=80` kwdarg.

**Comment by albi3ro** [comment]
I plan on writing entirely new code.

In the meantime, we welcome support for this feature in the existing code. 

The [`CircuitDrawer.draw` method](https://github.com/PennyLaneAI/pennylane/blob/997d0a28e08296b79156208879fc4b0de57c4cb8/pennylane/circuit_drawer/circuit_drawer.py#L338) you quoted above would be the correct location to add this change.

The keyword would also need to be added to 

* [`CircuitGraph.draw`](https://github.com/PennyLaneAI/pennylane/blob/997d0a28e08296b79156208879fc4b0de57c4cb8/pennylane/circuit_graph.py#L593)
* [`QuantumTape.draw`](https://github.com/PennyLaneAI/pennylane/blob/997d0a28e08296b79156208879fc4b0de57c4cb8/pennylane/tape/tape.py#L1086)
* The [`draw` transform](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/transforms/draw.py)

If you have any questions, feel free to ask them here or open an [WIP] (Work in progress) Pull Request.

**Comment by greenstick** [comment]
@albi3ro I'm working on updating the test suite to account for this feature. Unfortunately I'm running into an issue when running `make test`:

```shell
> make test
python3 -m pytest tests --tb=native --no-flaky-report
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --no-flaky-report
  inifile: /Users/User/Development/opensource/pennylane/tests/pytest.ini
  rootdir: /Users/Usern/Development/opensource/pennylane/tests

make: *** [test] Error 4
```

Any ideas what might be driving this error?

As an aside, it looks like the `max_length` parameter will break quite a few tests because the printing to the CLI will differ with the default value `max_length = 80`. Does the PennyLane team have any preferences on how to handle this? The simplest approach would be to set `max_length` top a high value on all the tests (like `500`) and then write a specific test for the feature where it's set to `80`. Alternatively, all the existing tests could be updated to account for the default `max_length` of `80`. Thoughts?

**Comment by antalszava** [comment]
Hi @greenstick, for the first question, could it be that `flaky` is not installed? (can be installed via `pip install flaky`).

**Comment by greenstick** [comment]
@antalszava Hah! Yup. That did it! Thanks.

**Comment by greenstick** [comment]
@albi3ro Okay sounds good!

**Comment by greenstick** [comment]
I've updated the test suite but it seems I'm still having issues running the tests (borking on what appears to be an unrelated problem). Everything should be in order though, going to send a pull request.
