### ISSUE TITLE
Multi dispatch `tensordot`

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1865]
### Feature details

It would be nice to be able to do
```python
qml.math.tensordot(a_list, an_autograd_array, axes=axes)
```
with `tensordot` dispatching to Autograd. Currently, the value of the above operation is correct but its derivative is `0`:
```python
x = qml.math.array([0.2, 0.1])
a_list = [1.2, 0.8]

f = lambda x: qml.math.tensordot(a_list, x, axes=[[0], [0]])
f(x) # Evaluates correctly to 0.32
qml.grad(f)(x) # Evaluates wrongly to [0.0, 0.0]
```
When using the Autograd array as first entry, the derivative is correct:

```python
g = lambda x: qml.math.tensordot(x, a_list, axes=[[0], [0]])
g(x) # Evaluates correctly to 0.32
qml.grad(g)(x) # Evaluates correctly to [1.2, 0.8]
``` 

Therefore, a multi dispatch over the arguments of `tensordot` would be nice to have.

### Implementation

One could probably implement this quite similar to #1816 

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
Perhaps a reason to add in #1820? That way we could do

```python
tensordot = multi_dispatch(argnum=[0, 1])(autoray.numpy.tensordot)
```

(by the way, was this causing the issue with the Torch tests in #1716?)

**Comment by dwierichs** [comment]
Oh yes, this would be a perfect application for #1820 :)

No, it was causing a bug in differentiability of reconstructions (#1864)

**Comment by dwierichs** [comment]
This is actually fixed due to `tensordot` being introduced manually in #1725 :)
In my opinion, we should add tests for `tensordot`, though, which currently only exist for Torch.
Also, automatically coercing the input tensors might be nice, to allow the following to work:
```python
x = torch.tensor([0.2, 0.1])
a_list = [1.2, 0.8]

f = lambda x: qml.math.tensordot(a_list, x, axes=[[0], [0]])
f(x) # Torch raises an error because `a_list` is a list.
```

**Comment by josh146** [comment]
Now that #1820 has been merged, we can also use that :D
