### ISSUE TITLE
Support `sx` gate for QASM conversion.

### ISSUE THREAD

**Issue by vtomole** [PennyLaneAI/pennylane#1891]
### Feature details

Pennylane doesn't support `sx` gate out of the box. It compiles it to a `QubitUnitary` instead:

```python

import pennylane

qasm_string = """
// Generated from Cirq v0.13.1

OPENQASM 2.0;
include "qelib1.inc";


// Qubits: [0, 1]
qreg q[2];


rz(0) q[0];
rx(pi*0.1) q[1];
sx q[1];
rz(pi*0.4) q[1];
s q[1];
cx q[0],q[1];
"""

qfunc = pennylane.from_qasm(qasm_string)

with pennylane.tape.QuantumTape() as tape:
        qfunc(wires=pennylane.wires.Wires(range(2)))

print(tape.operations)
# prints
# [RZ(0.0, wires=[0]), 
# RX(0.3141592653589793, wires=[1]), 
# QubitUnitary(array([[0.5+0.5j, 0.5-0.5j],
#        [0.5-0.5j, 0.5+0.5j]]), wires=[1]), 
#        RZ(1.2566370614359172, wires=[1]), 
#        S(wires=[1]), 
#        CNOT(wires=[0, 1])]
```

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by antalszava** [comment]
Hi @vtomole, thank you for catching this! :slightly_smiling_face:  We have a PR in the works that will address this.

**Comment by vtomole** [comment]
Thank you for the quick turnaround!

**Comment by antalszava** [comment]
Hi @vtomole sure thing! The PR in PennyLane-Qiskit has been merged and will be included in the next release (it's already available on the `master` branch of the plugin).
