### ISSUE TITLE
[BUG] qml.PauliRot does not have 'pauli_word' and 'theta' argument

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1901]
### Expected behavior

```
@qml.qnode(dev)
def circuit(theta):
    qml.PauliRot(theta, pauli_word='Z', wires=0)
    return qml.state()
print(circuit(1))
```
This should result in `[0.87758256-0.47942554j 0.        +0.j        ]`

### Actual behavior

We get type error: `TypeError: __init__() got an unexpected keyword argument 'pauli_word'`.
Similarly `theta` is also not a keyword argument.

### Additional information

This is on the page of qml.PauliRot:
```
class PauliRot(theta, pauli_word, wires)
```
You would guess this means `theta` and  `pauli_word` are keyword arguments.

This is not the case.

In reality, the arguments must be supplied as *params. `params[1]` is the pauli word string and `params[0]` is the angle.

`theta` and `pauli_word` should be keyword arguments.

### Source code

```shell
# Does not work
@qml.qnode(dev)
def circuit(theta):
    qml.PauliRot(theta, pauli_word='Z', wires=0)
    return qml.state()

# Does not work
@qml.qnode(dev)
def circuit(theta):
    qml.PauliRot(theta=theta, pauli_word='Z', wires=0)
    return qml.state()

# Does not work
@qml.qnode(dev)
def circuit(theta):
    qml.PauliRot('Z', theta, wires=0)
    return qml.state()

# Works
@qml.qnode(dev)
def circuit(theta):
    qml.PauliRot(theta, 'Z', wires=0)
    return qml.state()
```

### System information

```shell
Name: PennyLane
Version: 0.19.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /lib/python3.9/site-packages
Requires: semantic-version, appdirs, cachetools, scipy, autoray, autograd, numpy, networkx, toml, pennylane-lightning
Required-by: PennyLane-qiskit, PennyLane-Lightning
Platform info:           Linux-5.11.0-40-generic-x86_64-with-glibc2.31
Python version:          3.9.6
Numpy version:           1.20.3
Scipy version:           1.7.1
Installed devices:
- default.gaussian (PennyLane-0.19.0)
- default.mixed (PennyLane-0.19.0)
- default.qubit (PennyLane-0.19.0)
- default.qubit.autograd (PennyLane-0.19.0)
- default.qubit.jax (PennyLane-0.19.0)
- default.qubit.tf (PennyLane-0.19.0)
- default.qubit.torch (PennyLane-0.19.0)
- default.tensor (PennyLane-0.19.0)
- default.tensor.tf (PennyLane-0.19.0)
- qiskit.aer (PennyLane-qiskit-0.18.0)
- qiskit.basicaer (PennyLane-qiskit-0.18.0)
- qiskit.ibmq (PennyLane-qiskit-0.18.0)
- lightning.qubit (PennyLane-Lightning-0.18.0)
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by Jaybsoni** [comment]
Hi @ankit27kh, thanks for reporting this bug! We will look into it and get back to you soon 👍🏼

**Comment by Jaybsoni** [comment]
Can I ask, where did you see that the keywords should be `pauli_word` and `theta` ?

**Comment by ankit27kh** [comment]
@Jaybsoni on the documentation page for `qml.PauliRot` [here](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.PauliRot.html).
It says:


Parameters
- theta (float) – rotation angle θ
- pauli_word (string) – the Pauli word defining the rotation
- wires (Sequence[int] or int) – the wire the operation acts on

**Comment by Jaybsoni** [comment]
@ankit27kh Awesome ! Thanks for pointing that out !
