### ISSUE TITLE
[BUG] Many operations do not take the required arguments as keywords.

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1905]
### Expected behavior

N/A

### Actual behavior

N/A

### Additional information

There are multiple operations like `qml.U3`, `qml.QubitStateVector`, `qml.BasisState` etc., that require arguments and have keywords defined in the documentation but do not take keyword arguments.

A thorough look at all operations is required to find these and change their behaviour, and/or update the documentation.

Related #1903 

### System information

```shell
N/A
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by ankit27kh** [comment]
In a related way, some operations do not require any argument (except wires) but still have `*params`. This makes it necessary to use keyword argument `wires` with them.
For example, these do not work:
`qml.S(2)`, `qml.T(0)`, `qml.CNOT([1,2])`
But, these work:
`qml.Hadamard(0)`, `qml.PauliZ(2)`

There should not be this discrepancy. Some can work without `wires`, others can not. This must be fixed.

**Comment by CatalinaAlbornoz** [comment]
Thank you for bringing this up @ankit27kh!

**Comment by antalszava** [comment]
> In a related way, some operations do not require any argument (except wires) but still have *params. This makes it necessary to use keyword argument wires with them.
For example, these do not work:
qml.S(2), qml.T(0), qml.CNOT([1,2])
But, these work:
qml.Hadamard(0), qml.PauliZ(2)

This reason here is that `qml.Hadamard(0)` `qml.PauliZ(2)` are both operations and observables. For observables, we have a logic in to assume that the first parameter passed is the `wires`:
https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/operation.py#L1003

**Comment by Jaybsoni** [comment]
I can take on this bug and take a look throughout the various operations for this kind of functionality. I will also cross reference with the documentation to make sure that we aren't writing logic for functionality that wasn't intended to be supported. Thanks for brining this to our attention !

**Comment by Jaybsoni** [comment]
Hey @ankit27kh, 

In case you were waiting for this change to take effect. We just wanted to update you and let you know that there is a bigger change for the Operator class as a whole which would affect the way these operations are implemented. We are waiting on that as changing the code now, might require us to change it again after the Operator class change. 

Thanks,

**Comment by Jaybsoni** [comment]
[sc-11422]

**Comment by albi3ro** [comment]
I'm going to go ahead and close this issue, as it seems like #1976 should have cleaned up the problem.
