### ISSUE TITLE
shape method for Interferometer

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#1945]
### Feature details

The Interferometer template does not have a `shape` method to give out the required parameters' shapes.
It would be helpful to have this method as three parameters are required that have two different shapes.

### Implementation

The interferometer template is not defined as a class, so probably, it'll need restructuring before this can be implemented.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
Hi @ankit27kh! Was this a feature you would like to work on? 🙂

**Comment by ankit27kh** [comment]
Hi @josh146! Yes, I would like to work on this. I'll try to submit a PR soon.

**Comment by CatalinaAlbornoz** [comment]
Thank you @ankit27kh !
