### ISSUE TITLE
Speed up PennyLane load time

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1961]
### Feature details

I have noticed that PennyLane import time is growing longer and longer and did a quick profiling session following [this guide](https://pythondev.readthedocs.io/startup_time.html). The results look like this:

![image](https://user-images.githubusercontent.com/60615188/144246164-b782e7e9-fd12-4b70-ad6d-9a4ab147ab6d.png)

So, over 60% of the time is spent on importing qchem and most of that is attributable to openfermion. Now of course you can say that I should approach the openfermion people and tell them to speed up their load time, but clearly there are many programs that use pennylane, but don't need qchem and openfermion and in that case, even if those are installed, it would be nice if pennylane would start up fast.

Can qchem maybe be imported on demand?

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
Nice catch @cvjjm! Speeding up the import time would be a huge quality-of-life improvement.

Currently, we dynamically import `qchem` here, if the entry point exists:

https://github.com/PennyLaneAI/pennylane/blob/854d4b4c5045d69e3def921c8f6ca3519afac193/pennylane/__init__.py#L140-L142

but I'm sure we can somehow make this a 'lazy' import that is only loaded when first called.

**Comment by josh146** [comment]
@cvjjm I'm suddenly a bit confused. I can't recreate this behaviour locally; when I `import pennylane as qml`, I don't have OpenFermion automatically imported.

It seems we are already taking care of this in the `qchem` package:

https://github.com/PennyLaneAI/pennylane/blob/9687c130b7c4f758238859f2fe0dbb811a07825a/qchem/pennylane_qchem/qchem/openfermion.py#L18-L24

Are you using an older version of qchem?

**Comment by cvjjm** [comment]
Indeed!! Looks like I picked a bad conda env for this test. This was with qchem 15.1 :-) Well, happy that at least this lead you to looking into making the whole qchem import lazy :-)
