### ISSUE TITLE
Provide a table of supported functionalities

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1997]
### Feature details

In general, the amount of configurations for QNodes is quite large, and due to the supported 5 interfaces, it is quite hard to estimate a priori which scenarios are supported, which can not be supported for mathematical/programmatical reasons and which are simply not _yet_ supported because they haven't been implemented.
I suggest to provide an overview of some sort to users in the documentation that
1. informs them about the supported scenarios,
2. explains which scenarios are conceptually unsupportable - and why,
3. suggests workarounds for unsupported scenarios.
Configuration axes include: `interface`, `diff_method`, `shots`, `return_type`. Theses axes alone lead to at least `5x4x2x4=160` scenarios, which of course makes it hard to provide such an overview.

My personal background for this is, that despite having worked on the code stack for a year now, I spent about 4 hours on finding the right configuration to make a specific QNode setup work in JAX with JIT support and I imagine that this may become very frustrating for users that don't want to look into details but just want a specific setup to work - or to have information on how to work around unsupported scenarios.

A concrete example for which the transitions between supported/unsupported scenarios were quite surprising:
Consider the following QNode:
```python
dev = qml.device("default.qubit.jax", wires=1, shots=100)
@qml.qnode(dev, interface="jax", diff_method="parameter-shift")
def circuit(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.Hermitian(qml.math.diag([1., -1.]), wires=0))
```
This code does not work, it throws an indexing error. When changing `shots` to `None`, changing the string in `qml.device` to `"default.qubit"`, or replacing the observable in `expval` with `qml.PauliZ(0)`, it works (in particular, the return type does not change in the latter fix!)
For `diff_method="finite-diff"` the problem persists.
Note: The particular issue with this device, `shots!=None` and `diff_method in ["parameter-shift", "finite-diff"]` was covered in the bug report #1412. It is highly unintuitive that the problem vanishes when changing the observable, in my opinion.

I am not sure how much of a niche problem/request this is, but I'd imagine that an overview like this would be helpful in development and debugging as well: Unsupported scenarios that are conceptually supportable can be identified quickly and a systematic overview of scenarios for debugging would be available.

### Implementation

Given the very large number of configurations, a list of unsupported scenarios could be a good way to implement this.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
This is a _very_ good idea @dwierichs!

> This code does not work, it throws an indexing error. When changing shots to None, changing the string in qml.device to "default.qubit", or replacing the observable in expval with qml.PauliZ(0), it works (in particular, the return type does not change in the latter fix!)

Hmm, this strikes me as a bug that `Hermitian` doesn't work with the JAX device

**Comment by dwierichs** [comment]
You mean with the explicit switch to the `JAXinterface`, right? Although it does if we don't explicitly set `default.qubit.jax` but `default.qubit`. Is that compatible with what you are saying (I don't have a very clear picture of all the branches for different scenarios yet :sweat_smile:) ?

**Comment by josh146** [comment]
Ah, so what happens is that the QNode attempts to 'smartly' choose the device and differentiation method like so:

![image](https://user-images.githubusercontent.com/2959003/145210692-63cad35d-c2c5-4895-9993-d195079058c2.png)

So this is why changing `shots` and `diff_method` have an effect.

In my comment above though, it seems like the `default.qubit.jax` device somehow isn't working correctly when `shots=None`, and `Hermitian` is returned? So this could be a bug 🤔
