### ISSUE TITLE
failed to tun https://pennylane.ai/qml/demos/tutorial_kernels_module.html demo on ibmq_qasm_simulator

### ISSUE THREAD

**Issue by lironmo** [PennyLaneAI/pennylane#2016]
### Expected behavior

the demo is up and running using ibmq_qasm_simulator backend

### Actual behavior

1. when running with ibmq_qasm_simulator it's created hundreds if not thousands of jobs of the same circuit and fail to reach the optimization stage and  stack at 
```
init_plot_data = plot_decision_boundaries(svm, plt.gca())
``` 

2. when running with IBM  aer simulator it's stacked/very slow at compute_grads

### Additional information

https://pennylane.ai/qml/demos/tutorial_kernels_module.html

### Source code

```shell
https://pennylane.ai/qml/demos/tutorial_kernels_module.html
```

### Tracebacks

```shell
did not finish
```

### System information

```shell
windows 10 / wsl 2
```

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by lironmo** [comment]
https://github.com/Qiskit/qiskit/issues/1382

**Comment by lironmo** [comment]
it seems that the function square_kernel_matrix sent N*(N+1) Quantum operations to compute the square_kernel_matrix, along with the 500 optimization step it's required 5000 jobs on IBM quantum experience.

it's best to do it with batch operation of possible - see https://github.com/Qiskit/qiskit/issues/1382

**Comment by lironmo** [comment]
I saw https://pennylane.readthedocs.io/en/stable/development/release_notes.html that you do support it,

internally, if multiple circuits are generated for simultaneous execution, they will be packaged into a single job for execution on the device. This can lead to significant performance improvement when executing the QNode on remote quantum hardware or simulator devices with parallelization capabilities

I will update PennyLane==0.19.1 to 0.20.0 and check if it's fixed

**Comment by josh146** [comment]
@lironmo let us know how it goes! Note that you will also need to upgrade the Qiskit plugin:

```python
pip install pennylane-qiskit==0.20
```
