### ISSUE TITLE
Provide a transform-friendly version of qml.map

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#2029]
### Feature details

Trying to use `QNodeCollection` with a mitigated qnode results in the error:
```
AttributeError: 'function' object has no attribute 'interface'
````
It would be nice to have mitigated qnode support in `QNodeCollection` so that ideal, noisy and mitigated circuits can be run in a single line.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by albi3ro** [comment]
Given `QNodeCollection` and `map` are now removed, I believe we can mark this issue as closed.
