### ISSUE TITLE
Using `qml.sample` twice with `shots=(1,2)` raises an error

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2039]
```python
import pennylane as qml

dev = qml.device("default.qubit", wires=2, shots=(1,2))

@qml.qnode(dev, diff_method='parameter-shift', interface='autograd')
def circuit(a):
    qml.RY(a, wires=0)
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

a = np.array(0.1)
res = circuit(a)
```
Raises
`ValueError: could not broadcast input array from shape (2,2) into shape (2,)`

The edge case seems to come down to:
* Having `1` and `2` defined after each other in the shot vector;
* Having exactly two `qml.sample` directives in the `return` statement.

This issue is likely very low priority.

**Comment by rmoyard** [comment]
[sc-12767]

**Comment by antalszava** [comment]
Potentially related: other shot-vector values seem to output results with unintuitive shapes.

Getting an array of samples for each entry in the shot vector would be expected
```python
dev = qml.device("default.qubit", wires=3, shots=(1,))

@qml.qnode(dev)
def circuit(a, b):
    qml.RY(a, wires=0)
    qml.RX(b, wires=0)
    return qml.sample()

circuit(0,3)
```
```
tensor([1, 0, 0], requires_grad=True)
```
```python
dev = qml.device("default.qubit", wires=3, shots=(1,1))

@qml.qnode(dev)
def circuit(a, b):
    qml.RY(a, wires=0)
    qml.RX(b, wires=0)
    return qml.sample()

circuit(0,3)
```
```
(tensor(1, requires_grad=True),
 tensor(0, requires_grad=True),
 tensor(0, requires_grad=True),
 tensor(1, requires_grad=True),
 tensor(0, requires_grad=True),
 tensor(0, requires_grad=True))
```
The originally submitted issue seems to be more general and can be reproduced for most shot vectors that contain distinct number of copies and don't contain `1` in the shot vector, e.g., `shots=(2,3)` or `shots=(3,4)`.

**Comment by albi3ro** [comment]
The above code seems to work fine now. Not sure what fixed it, but it is no longer a problem.
