### ISSUE TITLE
missing features from numpy 

### ISSUE THREAD

**Issue by lironmo** [PennyLaneAI/pennylane#2054]
### Feature details

some features are missing from pennylane numpy version

### Implementation

diag_indices_from
LinAlgError
inf
newaxis
einsum
log
pi
diag

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
Thanks @lironmo!

I was wondering if you could provide more details on the missing functions, including code examples? For example, quite a few of the ones listed do work via the PennyLane-wrapped numpy:

```python
>>> from pennylane import numpy as np
>>> np.pi
3.141592653589793
```

**Comment by lironmo** [comment]
@josh146 - you are right only np.linalg.LinAlgError is missing.

it's a problem with IntelliSense.

![image](https://user-images.githubusercontent.com/37513762/147086943-eb00b494-005e-4d32-b387-335a21c51735.png)

**Comment by lironmo** [comment]
@josh146 do you have any idea why I can't use 
np.diag_indices_from(K)
where K is the kernel returned from 
qml.kernels.square_kernel_matrix

the type of K is autograd.numpy.numpy_boxes.ArrayBox

do I need to use different import?

this is the error:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\213.5744.248\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\envs\quantum_solution\lib\site-packages\pennylane\numpy\wrapper.py", line 75, in _wrapped
    res = obj(*args, **kwargs)
  File "C:\envs\quantum_solution\lib\site-packages\autograd\tracer.py", line 45, in f_wrapped
    node = node_constructor(ans, f_wrapped, argvals, kwargs, argnums, parents)
  File "C:\envs\quantum_solution\lib\site-packages\autograd\core.py", line 34, in __init__
    raise NotImplementedError("VJP of {} wrt argnums {} not defined"
NotImplementedError: VJP of fill_diagonal wrt argnums (0, 1) not defined

**Comment by josh146** [comment]
Hi @lironmo - PennyLane uses [Autograd](https://github.com/HIPS/autograd) as a backend for the differentiable version of NumPy that is provided, and unfortunately it looks like `np.diag_indices_from` is not supported by Autograd.

You could try either:

- opening an issue on the Autograd repository, or
- switching to a different autodiff framework (see [the PennyLane documentation](https://pennylane.readthedocs.io/en/latest/introduction/interfaces.html#training-and-interfaces), where we show how to use PennyLane with Torch, JAX, and TensorFlow.
