### ISSUE TITLE
[BUG] `gradient_transform`s do not work with single-gate circuits

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#2070]
While fixing the `qml.jacobian` output signature by removing the stacking+transposing behaviour in #2056, I noticed that the `gradient_transform` QNode wrapper behaves a but funnily for a variety of input/output signatures:

1. _If there is only a single gate that is controlled by a QNode argument_ (or an element in an array-valued argument), `qml.math.squeeze` performs unwanted axis removals. This leads to a large number of basic QNode signatures (including `one scalar QNode arg -> one scalar output value`) for which the `gradient_transform`s return unexpected output (shapes). For other scenarios, the output is an empty 1D array where it shouldn't, and for multiple array QNode arguments together with outputs that contain arrays (like `qml.probs`), the transform raises an error, as the contraction between the tape Jacobian and the classical Jacobians does not work.
2. If there is more than one gate, the problem is _much_ less severe: For inputs of differing shape, `qml.jacobian` returns a tuple with as many entries as there are arguments. Each entry of the tuple has the shape `(*QNode output shape, *arg shape)`. The `gradient_transform`s instead return a list and the shape of each entry is `(*arg shape, *QNode output shape)`, i.e. the order of the two partial shapes is swapped, but no ordinary transposition takes place.

**Example**
Consider the QNode
```python
dev = qml.device("default.qubit", wires=2)

@qml.qnode(dev)
def circuit_probs(X, Y):
    qml.RY(0.4, wires=0)
    qml.RX(X[0], wires=0)
    # qml.RX(X[0], wires=0)
    return qml.probs(wires=[0, 1])

X = np.array([0.3, 0.5, 0.1, 0.2, 0.4])
Y = np.array([[0.3, 0.5], [0.1, 0.2], [0.4, -0.5]])
```
It takes two arguments with shapes `(5,)` and `(3, 2)`, and returns an array of shape `(4,)`.
```pycon
>>> jac = qml.jacobian(circuit_probs)(X, Y)
>>> print(type(jac), len(jac))
<class 'tuple'> 2
>>> print(jac[0].shape, jac[1].shape)
(4, 5) (4, 3, 2)
```
`qml.jacobian` computes a tuple of 2 entries, one for each QNode argument, and with "leading shape" being the QNode output shape.
```pycon
>>> trafo_jac = qml.gradients.param_shift(circuit_probs)(X, Y)
...
ValueError: shape-mismatch for sum
```
In this case, the `gradient_transform` raises an Error.
If we uncomment the last gate in `circuit_probs`, we get the same qualitative output from `qml.jacobian` (speaking of the formatting and output shape only, of course).
With the transform we get
```pycon
>>> trafo_jac = qml.gradients.param_shift(circuit_probs)(X, Y)
>>> print(type(trafo_jac), len(trafo_jac))
<class 'list'> 2
>>> print(trafo_jac[0].shape, trafo_jac[1].shape)
(5, 4) (3, 2, 4)
```
As described above, the transform now works but it returns the output with a different formatting/shape and it is a list instead of a tuple.

**Comment by rmoyard** [comment]
[sc-12765]

**Comment by josh146** [comment]
@dwierichs should we update this with additional context from our chat yesterday?

**Comment by dwierichs** [comment]
Thanks for the reminder, @josh146 . I'll look into this in detail and then modify :)

**Comment by dwierichs** [comment]
Update: This issue is almost resolved by #2059 . In particular, the transposed axis ordering and the conversion to list/tuple is taken care of.

The only remaining aspect of this issue hence is the error raised for single-gate circuits or QNode arguments with an axis of size 1 due to the usage of `qml.math.squeeze`.

**Comment by josh146** [comment]
😍

**Comment by dwierichs** [comment]
#2080 implemented this.
