### ISSUE TITLE
Instability of new hf.generate_fermionic_hamiltonian feature

### ISSUE THREAD

**Issue by DeanEmmettSmith** [PennyLaneAI/pennylane#2073]
Hello Pennylane maintainers,

I am a great fan of your framework. I am working on a geometry optimization routine and am using your differentiable fermionic Hamiltonian constructor which came out a few weeks ago (https://arxiv.org/pdf/2111.09967.pdf). 

I need to keep the code confidential. Please reach out to me in case there are any questions or interest in our activities. 

Briefly, the output of this kind of code segment is causing issues.

> hf.generate_fermionic_hamiltonian(parametrizable_molecular_data_pennylane, cutoff=1e-8)(parametrizable_geometry)

If I set the cutoff greater than 1e-4, the output produced of this method will not maintain a consistent length for the fermionic Hamiltonian operator.  This can be demonstrated for a hydrogen molecule (STO-3G basis set) with these coordinates ([r] = Bohr)

coordinates_data = [['H', [ -0.0002251435, 0.0000083035, 0.0000000000]], ['H', [ 0.0002251435, -0.0000083035, 0.0000000000]]]

This is an issue if one would like to parallelize the evaluation of the 1. and 2. order partial derivatives of the 1, 2 and 4-indexed molecular integrals.

Thanks for support!

Best regards,
Dean

**Comment by soranjh** [comment]
Hi @DeanEmmettSmith and thanks for using the differentiable solver! 

When you construct the fermionic Hamiltonian from the one- and two-body integrals, those integrals with a value smaller than the cutoff are neglected. This basically prevents having a large Hamiltonian with many negligible (close to zero) terms and simplifies computing the expectation value of the Hamiltonian in the subsequent calculations. When you increase the value of the cutoff you practically eliminate more and more terms in the computed fermionic Hamiltonian and make it smaller each time. If you keep the cutoff, and all other variables, constant and still get inconsistent number of terms in the Hamiltonian, this might be possibly due to numerical round offs when some of the integrals are very close to the cutoff value. Overall, it is not always safe to increase the cutoff value as this might cause missing important terms in the Hamiltonian, unless you have a good reason for doing it safely. 

Furthermore, I noticed that in the atomic coordinates provided above, the hydrogen atoms are both located near the origin and practically overlap. This could also cause having non-physical values for the integrals and the computed Hamiltonian. 

Please let me know if this helps fixing the issue. I will be happy to have a look at your code if you can share a non-confidential minimal version of the code with us.

**Comment by dime10** [comment]
Hi @DeanEmmettSmith, hopefully your issue has been resolved. If you have any more problems in regards to this don't hesitate to comment here with additional information and we can reopen the issue.

**Comment by DeanEmmettSmith** [comment]
Hello David,

I have been busy the last weeks.

I am aware of the numerical instability issues of solving the Roothan-Hall/Pople-Nesbet equations. These are nonlinear eigenvalue problems.

The point I am trying to make is that setting a fermionic Hamiltonian with molecular integral cutoff values set to a value >= 10^-4 to yield a stable number of terms for the fermionic Hamiltonian.

I have not had the time to test the method for a range of systems and nuclear geometries though rebuilding fermionic Hamiltonians can give non-deterministic results for cutoff values < 10^-4.

The reply I received that this is normal. If it was possible to retrieve and set the initial values (LCAO orbital coefficients/density matrices) for the SCF routine, it should guarantee stable outputs assuming the numerical stability of the SCF routine with respect to round-off errors.

If I find the time in the future, I will document the issue more elaborately. I still hope my user feedback was helpful.

Best regards,
Dean


From: David Ittah ***@***.***>
Sent: Montag, 24. Januar 2022 16:55
To: PennyLaneAI/pennylane ***@***.***>
Cc: Smith, Dean Emmett ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [PennyLaneAI/pennylane] Instability of new hf.generate_fermionic_hamiltonian feature (Issue #2073)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


Hi @DeanEmmettSmith<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DeanEmmettSmith&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=SPNkbur8QGrfSegNYE5xlnRPy92DDJHnZXHhgUIEEEXi9_Jtc9f9fd7uMM7f7WNR&s=6RRJfQOhl48EkbcdmJo5m7N2qQ8T2R8WmWoIs5oVI2I&e=>, hopefully your issue has been resolved. If you have any more problems in regards to this don't hesitate to comment here with additional information and we can reopen the issue.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PennyLaneAI_pennylane_issues_2073-23issuecomment-2D1020248825&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=SPNkbur8QGrfSegNYE5xlnRPy92DDJHnZXHhgUIEEEXi9_Jtc9f9fd7uMM7f7WNR&s=d-E0mJ-6H5UFh-lV1UKrOd_0SzTs8kW14T9h6GqsI2s&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOMHVINFLJ5T7E3MIZHH6CLUXVY6XANCNFSM5LMLTQ4A&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=SPNkbur8QGrfSegNYE5xlnRPy92DDJHnZXHhgUIEEEXi9_Jtc9f9fd7uMM7f7WNR&s=nYDIQDftR8bGf6dSAckyDJONhnr_RJg1_Iy_HgECrxE&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=SPNkbur8QGrfSegNYE5xlnRPy92DDJHnZXHhgUIEEEXi9_Jtc9f9fd7uMM7f7WNR&s=2LPa1l_17jDFgU7im3VbfEtVq2TJ49rjUDpn8u9WgTc&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=SPNkbur8QGrfSegNYE5xlnRPy92DDJHnZXHhgUIEEEXi9_Jtc9f9fd7uMM7f7WNR&s=cB22TEpyOgv8bmwhwywNmMmYTWitOXGNtAh-ARQM_Dg&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by soranjh** [comment]
Hi @DeanEmmettSmith,

Thank you very much again for using PennyLane. Your feedback is definitely helpful for us. Yes, it would be great if you could please document the issue more elaborately.

**Comment by DeanEmmettSmith** [comment]
Sure, I am comparing the Pennylane Fermionic transformation to that of Qiskit Nature. I may be doing some more intense troubleshooting the next days.

From: soranjh ***@***.***>
Sent: Donnerstag, 27. Januar 2022 17:54
To: PennyLaneAI/pennylane ***@***.***>
Cc: Smith, Dean Emmett ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [PennyLaneAI/pennylane] Instability of new hf.generate_fermionic_hamiltonian feature (Issue #2073)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


Hi @DeanEmmettSmith<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DeanEmmettSmith&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=w5-I2dV_WRaOEyDLylfZPzLvSSu-2mBVDBPJVUuM0nzdjN1YANrWVFAjk_72uBT2&s=_rpN0HWYq_W5SgNMOQPpZs9SscYMxOOfWvcQ0gkEoI8&e=>,

Thank you very much again for using PennyLane. Your feedback is definitely helpful for us. Yes, it would be great if you could please document the issue more elaborately.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PennyLaneAI_pennylane_issues_2073-23issuecomment-2D1023435596&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=w5-I2dV_WRaOEyDLylfZPzLvSSu-2mBVDBPJVUuM0nzdjN1YANrWVFAjk_72uBT2&s=bsONmHbkZuo-y779JA_6-Gw4ptHtDcKrh6ZuUXJavaI&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOMHVIKCHSDG62GKSISHJF3UYF2B3ANCNFSM5LMLTQ4A&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=w5-I2dV_WRaOEyDLylfZPzLvSSu-2mBVDBPJVUuM0nzdjN1YANrWVFAjk_72uBT2&s=8tDiuCA8bWlVIksialMwBEHKEF5NQ8btstGiH8RDT8U&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=w5-I2dV_WRaOEyDLylfZPzLvSSu-2mBVDBPJVUuM0nzdjN1YANrWVFAjk_72uBT2&s=4B0pY649eGo0SOHgBYs1gADC9g14V5VKB2P3B9v_L-Q&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=FGnubJHiCPr_aFTE65ze_6F08DZuxd-p3HzAokSzFeA&m=w5-I2dV_WRaOEyDLylfZPzLvSSu-2mBVDBPJVUuM0nzdjN1YANrWVFAjk_72uBT2&s=fLbVWB1RDT_VTfQ04pDUHJAzO2lbcqu8DyPJQC6BcvI&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by soranjh** [comment]
Thanks @DeanEmmettSmith. Will be great to see the details.
