### ISSUE TITLE
Warn/raise in case shot noise and caching are enabled at the same time?

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2150]
### Feature details

When `default.qubit` with `shots != None` but also `cache=1` is used then the same (noisy) result is returned again and again when a `QNode` is called. It is hard to imagine a case where this is what a user wants. 

Either they want a `QNode` to return a noisy result that is different each time it is called (they can get this by setting `cache=0`), or they want only a single noisy result, in which case caching doesn't provide any benefit.

I think it would be nice to raise an exception or at least a warning when a user makes a device with shot noise and caching enabled.

Alternatively the the device could go back to state caching, as it used to be in ancient times... This would give a speed benefit because the circuit would not need to be re-evaluated when the same shot-noisy `QNode` is called several times.
    

### Implementation

To demonstrate the "problem" consider this sample program:
```
import pennylane as qml
from pennylane import numpy as np

shots=76

dev = qml.device(
    'default.qubit',
    wires=2,
    shots=shots,
    cache=1,
)

np.random.seed(87)
params = np.random.randn(2, 2, 3)
observable_as_array = np.array([[ 1. +0.j,  0. +0.j,  0. +0.j,  0. +0.j],
                                [ 0. +0.j,  0.4+0.j, 21.6+0.j,  0. +0.j],
                                [ 0. +0.j, 21.6+0.j, -0.4+0.j,  0. +0.j],
                                [ 0. +0.j,  0. +0.j,  0. +0.j, -1. +0.j]])

@qml.qnode(dev, diff_method='parameter-shift')
def circuit(params):
    qml.templates.layers.StronglyEntanglingLayers(params, wires=range(dev.num_wires))
    return qml.expval(qml.Hermitian(observable_as_array, wires=range(dev.num_wires)))

for _ in range(10):
    print(circuit(params))
```

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
Thanks for reporting this @cvjjm!

I'm curious if this is fixed in the new caching system that is provided by the QNode. 
This new caching system is designed to be device independent, and allows creating your own cache object (it can be simply a dictionary, or a `cachetools.LRUCache`, for example), and pass it to QNodes you want to use it in:

```python
dev = qml.device('default.qubit', wires=nwires)

cache = {}

@qml.qnode(dev, diff_method='parameter-shift', cache=cache)
def expval_circuit(params):
    qml.templates.BasicEntanglerLayers(params, wires=wires, rotation=qml.RX)
    return qml.expval(qml.Hermitian(hamiltonian, wires=wires))

@qml.qnode(dev, diff_method='parameter-shift', cache=cache)
def var_circuit(params):
    qml.templates.BasicEntanglerLayers(params, wires=wires, rotation=qml.RX)
    return qml.var(qml.Hermitian(hamiltonian, wires=wires))

>>> print(expval_circuit(params), var_circuit(params)))
-2.6224875809703287, 0.011605015096940896
>>> print(cache)
{-2104543859499562169: array([-2.62248758]), 3268478774057874589: array([0.01160502])}
>>> print(expval_circuit(params), var_circuit(params)))  # evaluate QNodes again
-2.6224875809703287, 0.011605015096940896
>>> dev.num_executions  # only the first two executions will register
2
```

The plan is to make this the new user-facing caching system, and deprecate/remove the device-level one.

**Comment by cvjjm** [comment]
This is a very nice UI. Caching on Qnode level is a very good idea now that results are cached ad not states (for the latter it used to be natural to do it on a device level). 

The new cache shows the same behavior.
```
import pennylane as qml
from pennylane import numpy as np

shots=76

dev = qml.device(
    'default.qubit',
    wires=2,
    shots=shots,
    cache=0,
)

np.random.seed(87)
params = np.random.randn(2, 2, 3)
observable_as_array = np.array([[ 1. +0.j,  0. +0.j,  0. +0.j,  0. +0.j],
                                [ 0. +0.j,  0.4+0.j, 21.6+0.j,  0. +0.j],
                                [ 0. +0.j, 21.6+0.j, -0.4+0.j,  0. +0.j],
                                [ 0. +0.j,  0. +0.j,  0. +0.j, -1. +0.j]])

cache = {}

@qml.qnode(dev, diff_method='parameter-shift', cache=cache)
def circuit(params):
    qml.templates.layers.StronglyEntanglingLayers(params, wires=range(dev.num_wires))
    return qml.expval(qml.Hermitian(observable_as_array, wires=range(dev.num_wires)))

for _ in range(10):
    print(circuit(params))

print(cache)
```
Output:
```
6.403654883035922
6.403654883035922
6.403654883035922
6.403654883035922
6.403654883035922
6.403654883035922
6.403654883035922
6.403654883035922
6.403654883035922
6.403654883035922
{8257838482108885402: array([6.40365488])}
```
 This is not a bid deal but I think it can surprise users and disallowing the combination of shot noise and caching or raising a warning could be nice.

**Comment by josh146** [comment]
> This is not a bid deal but I think it can surprise users and disallowing the combination of shot noise and caching or raising a warning could be nice.

I agree, this is a good idea!

**Comment by cvjjm** [comment]
This is mostly resolved, the only thing that remains is adding the warning when shot noise and caching are combined.

**Comment by antalszava** [comment]
Hi @cvjjm,
> This is mostly resolved, the only thing that remains is adding the warning when shot noise and caching are combined.

just to double-check: the `QubitDevice` caching capability is to be removed (a deprecation warning is now emitted).

The warning should be added when caching on Qnode level, correct?

**Comment by cvjjm** [comment]
Yes, that is entirely correct.

**Comment by trbromley** [comment]
Not sure if this is related, but @anthayes92 and myself have gotten surprised by the following using `qml.execute()`. Suppose we have a list that contains the same tape more than once:
```python
import pennylane as qml

dev = qml.device("default.qubit", wires=1, shots=3)

with qml.tape.QuantumTape() as tape:
    qml.RX(1.5, wires=0)
    qml.sample(wires=0)

tapes = [tape, tape]
```
Running `qml.execute()` gives:
```
>>> qml.execute(tapes, dev, gradient_fn=None)
[array([[[1],
         [0],
         [0]]]),
 array([[[1],
         [0],
         [0]]])]
```
i.e., we get the same set of samples each time. To get what we expect, we have to do:
```
>>> qml.execute(tapes, dev, gradient_fn=None, cache=False)
[array([[[1],
         [0],
         [1]]]),
 array([[[1],
         [0],
         [0]]])]
```
Perhaps this can be fixed with the warning mentioned above, i.e., when using caching in finite shots mode.

**Comment by josh146** [comment]
@trbromley good catch -- this is not a case I considered (submitting the same tape multiple times in a single call) when I coded up `qml.execute()`.

I'm curious to the reason behind this usage, could you instead do `qml.execute([tape], ...)`, but specify a batch of shots?

**Comment by trbromley** [comment]
Thanks @josh146, yes it's maybe a bit of a fringe usecase.
Suppose we have a function/transform that takes an input circuit and randomly alters it (e.g., performing some random state preps/measurements), and outputs a sequence of such randomly altered tapes. We then want to execute these tapes, each with a fixed number of shots. We can call `qml.execute(tapes, ...)`, but there is a chance that our random generation has created a "collision" and we'll have the same circuit being run twice, resulting in repeated samples outlined above. An alternative could be to count how many times a given circuit has been randomly generated and alter the shots accordingly, but I don't think `qml.execute` supports a differerent shot value for each input tape?

**Comment by josh146** [comment]
Good points @trbromley, this is a good reason to support the same tape multiple times 🤔 

>  but I don't think qml.execute supports a differerent shot value for each input tape?

It doesn't atm, but this is something I would like to add - allow `shots` to be metadata on tape objects.

**Comment by antalszava** [comment]
Closing this with #2478 merged, though lmk if it should be reopened. :+1:
