### ISSUE TITLE
Allow specification of control_values for qml.ctrl

### ISSUE THREAD

**Issue by KarimAED** [PennyLaneAI/pennylane#2176]
### Feature details

- qml.ControlledQubitUnitary, qml.MultiControlledX etc allow for specification of control_values in form of e.g. a string "0110" for all control_wires
- qml.ctrl should allow for the specification of a control_values keyword like those other operations
- currently, qml.PauliX has to be used to flip each control_wire to the desired value when using qml.ctrl

### Implementation

- Either, qml.ctrl itself could include the implementation of qml.PauliX on relevant control_wires before and after implementing the passed function

The alternative suggestion I am unsure about, as my understanding of the code & underlying considerations is limited:
- Or, according to my current understanding, expand_with_control requires modification to 1) use qml.ControlledQubitOperation for all ops, or 2) change the default behaviour of different _controlled methods to also allow for specification of control_values

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

Please excuse me if this behaviour has been considered but determined to be suboptimal. I did not find any issues or explanations regarding this subject, so I thought it might be a nice feature to request.

**Comment by CatalinaAlbornoz** [comment]
Hi @KarimAED, thank you for suggesting this feature! It does look like something that could be added. Would you like to try to implement this?

**Comment by KarimAED** [comment]
Hi, @CatalinaAlbornoz, yes I would love to try working on this. Which implementation would you suggest I move forward with? The first suggestion seems the most self-contained, but it also feels like it's maybe not the cleanest implementation? Let me know what you think.

**Comment by albi3ro** [comment]
@KarimAED 
We are in the process of a deeper set of restructuring and improvements to how we do control operations, and adding `control_values` to all operations is definitely something we want to support.

While currently `MultiControlledX` and `ControlledQubitUnitary` accept a string to denote the control values, I'm wanting to move that to be a list of booleans/ zeroes and ones instead. For example, we could support the syntax `qml.ctrl(qml.PauliX, control=[2,3], control_values=[1, 1])(wires=0)`.

I'm not sure yet on the timeline of our more invasive internal changes.  What you proposed for modifying `ctrl` will be helpful regardless.

A PR could involve:
* adding a `control_values=None` keyword argument to `qml.ctrl`.  This argument should be a list of booleans.
* adding a `control_values=None` keyword argument to `ControlledOperation`. 
* Performing `qml.PauliX` on relevant wires in `ControlledOperation.expand`. This would be before and after the loop over control wires, so `expand_with_control` would not need to take `control_values`.
* pass the `control_values` on to the new `ControlledOperation` ops created in `adjoint` and `_controlled`.
* Adding tests

Thanks for your feedback 🚀

**Comment by KarimAED** [comment]
@albi3ro
Sounds good, I've started implementing it now already.

Slightly unrelated question, but on opening `qml.transforms.control` in my IDE, it flags the `ControlledOperation.adjoint` method because it doesn't match the `Operation.adjoint` signature from which it inherits. The `do_queue` keyword argument is omitted. Is there any reason not to include it in the `adjoint` method with the same default value as in the `ControlledOperation` initializer (`True`) and pass it through? Otherwise, I would just add that in as well.
