### ISSUE TITLE
Add a function that returns the 'best' differentiation method string for a particular device and interface

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2217]
### Feature details

As discussed [in the forum](https://discuss.pennylane.ai/t/way-to-tell-how-pennylane-will-differentiate-a-qnode/1675) with @josh146, it would be nice if PennyLane offered an officially supported way to learn how it will differentiate QNode.

This can be good for debugging and also to verify a users expectations about PL increasingly complex decomposition/differentiation/compilation abilities.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
As noted in the discussion, a nice solution could be a utility function applied to the device and interface:

```python
def best_diff_method(dev, interface):
    transform = qml.QNode.get_best_method(dev, interface)[0]

    if transform is qml.gradients.finite_diff:
        return "finite-diff"

    if transform in (qml.gradients.param_shift, qml.gradients.param_shift_cv):
        return "parameter-shift"

    # only other options by this point are "backprop" or "device"
    return transform
```
