### ISSUE TITLE
Improve/implement get_matrix() of Tensor and Hamiltonian 

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2228]
### Feature details

Probably this is being worked on as part of the Operation refactor and/or the support of arythmetic operations between Observables, but I am putting it out here anyway:

It would be great if `Tensor.get_matrix()` implemented implemented the `wire_order` parameter and if that were done in a way that the returned matrix were always on all wires contained in `wire_order`. This should then also allow for a straight forward implementation of `Hamiltonian.get_matrix()`, which would be great to have for many reasons, but also, e.g., for converting between the old (as a matrix) and new (as a sum of Operations) way of specifying generators.

Side remark: The current `Tensor.get_matrix()` contains a few strange comments that refer to "diagonalizing unitaries".

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by josh146** [comment]
> Probably this is being worked on as part of the Operation refactor and/or the support of arythmetic operations between Observables,

@cvjjm yes this is the plan, but unfortunately may not be merged by the next release! So your comment is very valid. We definitely want to unify `Tensor` and `Hamiltonian`.

The current plan is to remove these classes, and instead allow all operators to define `Operator.terms` (linear combinations) and `Operator.decomposition` (tensor products). A nice benefit will be that operator arithmetic will always return another operator, with the same methods and logic.

This is partly why we have not refactored too much the `Tensor` and `Hamiltonian` class.

In the meantime, I am working on a `qml.matrix()` top-level function here #2221 to provide a unified functional interface

**Comment by josh146** [comment]
@cvjjm PR #2241 includes a high-level fix 🙂

**Comment by cvjjm** [comment]
I think #2241 fully closes this feature request.
