### ISSUE TITLE
[BUG] Should the tensor product operation alter objects in-place?

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#2235]
### Expected behavior

Consider:
```python
obs = qml.PauliZ(0) @ qml.PauliZ(1)
obs2 = obs @ qml.PauliZ(2)
```
I expect:
```pycon
>>> print(obs)
PauliZ(wires=[0]) @ PauliZ(wires=[1])
>>> print(obs2)
PauliZ(wires=[0]) @ PauliZ(wires=[1]) @ PauliZ(wires=[2])
```

### Actual behavior

First running:
```python
obs = qml.PauliZ(0) @ qml.PauliZ(1)
obs2 = obs @ qml.PauliZ(2)
```
We get:
```pycon
>>> print(obs)
PauliZ(wires=[0]) @ PauliZ(wires=[1]) @ PauliZ(wires=[2])
```

### Additional information

I'm not sure if this is an issue or expected behaviour. Perhaps a requirement for queuing? The `__matmul__` [method](https://github.com/PennyLaneAI/pennylane/blob/9b61f17649c4b7c45dc3d66576e0727433726430/pennylane/operation.py#L1751) clearly shows the in-place approach :thinking:

### System information

```shell
Dev PL
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment]
@trbromley I don't think this is a bug --- it looks intentional.

Having said that, this is definitely not behaviour we want going forward! And will be addressed when the `Tensor` class is removed and the tensor product support included in the base operator class

**Comment by astralcai** [comment]
This issue no longer exists with new operator arithmetic.
