### ISSUE TITLE
Move mid-circuit measurement and conditional op transform into device

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2282]
### Feature details

#2211 applies the `defer_measurements` transform in the QNode if mid-circuit measurements are not natively supported by the device.

We'd like to move this transformation into the `Device` class. However, this breaks the differentiability with certain interfaces (Torch and JAX conditional op tests in `tests/test_qnode.py`).

See the [original discussion thread here](https://github.com/PennyLaneAI/pennylane/pull/2211#discussion_r817577000).

### Implementation

Move the transformation into either:
* [Device.default_expand_fn](https://github.com/PennyLaneAI/pennylane/blob/b494a2bf1b68156a9688178e1d97dc348ebf1583/pennylane/_device.py#L601) or
* [Device.batch_transform](https://github.com/PennyLaneAI/pennylane/blob/b494a2bf1b68156a9688178e1d97dc348ebf1583/pennylane/_device.py#L660).

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

This step would be future-facing: we've identified previously that such tape expansions are better fitted on the device level, otherwise blocking potential new features.

**Comment by astralcai** [comment]
![](https://media.tenor.com/TigFWS1gf50AAAAM/2000anos-depois.gif)

I believe we should be able to consider this issue resolved now. @mudit2812 can you confirm?
