### ISSUE TITLE
[BUG] Unable to reference some decorated top-lvl functions

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2283]
### Expected behavior

The syntax
```
func:`~.pennylane.compile`
```
works for referencing any top-level functions in the docs.

### Actual behavior

```
func:`~.pennylane.compile`
```
doesn't include a hyperlink to the related documentation change, likely because `qml.compile` is decorated with `@qfunc_transform`. This behaviour was originally noted with the [`@qml.defer_measurements` transform](https://github.com/PennyLaneAI/pennylane/pull/2211#discussion_r818996929).

### Additional information

Further note, that the documentation pages for such decorated functions also differs in style:
![Screenshot from 2022-03-04 15-06-39](https://user-images.githubusercontent.com/24476053/156834715-847fe2ad-429b-4481-9912-8b658d3773cf.png)
![Screenshot from 2022-03-04 15-06-58](https://user-images.githubusercontent.com/24476053/156834725-bfcd6955-190b-47b9-bf0f-887a84630a55.png)

### System information

```shell
Name: PennyLane
Version: 0.22.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/antal/xanadu/pennylane
Requires: numpy, scipy, networkx, retworkx, autograd, toml, appdirs, semantic_version, autoray, cachetools, pennylane-lightning
Required-by: PennyLane-Lightning, amazon-braket-pennylane-plugin, PennyLane-Orquestra, pennylane-qulacs, PennyLane-Honeywell, PennyLane-AQT, PennyLane-PQ, PennyLane-Forest, PennyLane-qsharp, PennyLane-Qchem, PennyLane-IonQ, PennyLane-SF, PennyLane-Cirq, PennyLane-qiskit
Platform info:           Linux-5.13.0-30-generic-x86_64-with-glibc2.10
Python version:          3.8.5
Numpy version:           1.22.1
Scipy version:           1.7.3
Installed devices:
- default.gaussian (PennyLane-0.22.0.dev0)
- default.mixed (PennyLane-0.22.0.dev0)
- default.qubit (PennyLane-0.22.0.dev0)
- default.qubit.autograd (PennyLane-0.22.0.dev0)
- default.qubit.jax (PennyLane-0.22.0.dev0)
- default.qubit.tf (PennyLane-0.22.0.dev0)
- default.qubit.torch (PennyLane-0.22.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.21.0)
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.5.3)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.5.3)
- orquestra.forest (PennyLane-Orquestra-0.15.0)
- orquestra.ibmq (PennyLane-Orquestra-0.15.0)
- orquestra.qiskit (PennyLane-Orquestra-0.15.0)
- orquestra.qulacs (PennyLane-Orquestra-0.15.0)
- qulacs.simulator (pennylane-qulacs-0.17.0.dev0)
- honeywell.hqs (PennyLane-Honeywell-0.16.0.dev0)
- aqt.noisy_sim (PennyLane-AQT-0.18.0)
- aqt.sim (PennyLane-AQT-0.18.0)
- projectq.classical (PennyLane-PQ-0.18.0.dev0)
- projectq.ibm (PennyLane-PQ-0.18.0.dev0)
- projectq.simulator (PennyLane-PQ-0.18.0.dev0)
- forest.numpy_wavefunction (PennyLane-Forest-0.18.0.dev0)
- forest.qvm (PennyLane-Forest-0.18.0.dev0)
- forest.wavefunction (PennyLane-Forest-0.18.0.dev0)
- microsoft.QuantumSimulator (PennyLane-qsharp-0.19.0)
- ionq.qpu (PennyLane-IonQ-0.17.0.dev0)
- ionq.simulator (PennyLane-IonQ-0.17.0.dev0)
- strawberryfields.fock (PennyLane-SF-0.20.0.dev0)
- strawberryfields.gaussian (PennyLane-SF-0.20.0.dev0)
- strawberryfields.gbs (PennyLane-SF-0.20.0.dev0)
- strawberryfields.remote (PennyLane-SF-0.20.0.dev0)
- strawberryfields.tf (PennyLane-SF-0.20.0.dev0)
- cirq.mixedsimulator (PennyLane-Cirq-0.20.0.dev0)
- cirq.pasqal (PennyLane-Cirq-0.20.0.dev0)
- cirq.qsim (PennyLane-Cirq-0.20.0.dev0)
- cirq.qsimh (PennyLane-Cirq-0.20.0.dev0)
- cirq.simulator (PennyLane-Cirq-0.20.0.dev0)
- qiskit.aer (PennyLane-qiskit-0.22.0.dev0)
- qiskit.basicaer (PennyLane-qiskit-0.22.0.dev0)
- qiskit.ibmq (PennyLane-qiskit-0.22.0.dev0)
- qiskit.ibmq.circuit_runner (PennyLane-qiskit-0.22.0.dev0)
- qiskit.ibmq.sampler (PennyLane-qiskit-0.22.0.dev0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment]
> `func:~.pennylane.compile` doesn't include a hyperlink to the related documentation change, likely because qml.compile is decorated with `@qfunc_transform`.

@antalszava this one is weird, since [`two_qubit_decomposition`](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.transforms.two_qubit_decomposition.html) includes a cross reference to [`unitary_to_rot`](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.transforms.unitary_to_rot.html), which is also decorated, and this cross reference seems to work 🤔 

https://github.com/PennyLaneAI/pennylane/blob/281e55f1d7f36901501535ddc2a903a3b146a463/pennylane/transforms/decompositions/two_qubit_unitary.py#L540-L542

> Further note, that the documentation pages for such decorated functions also differs in style:

I will see if I can fix this one :) If not, we may need to port `@qfunc_transform` to a class, like we do with other decorators:

https://github.com/PennyLaneAI/pennylane/blob/703ae35f206bb0c3782a18a117b95012315ba7f0/pennylane/transforms/batch_transform.py#L187-L191
