### ISSUE TITLE
[BUG] Generating .PEX 

### ISSUE THREAD

**Issue by CelineDVL** [PennyLaneAI/pennylane#2355]
### Expected behavior

I would like to generate a .pex of pennylane.

### Actual behavior

The source directory "/tmp/pip-req-build-7p8g9z8p" does not appear to contain CMakeLists.txt. Failed building wheel for PennyLane-Lightning

### Source code

```shell
pex pennylane -o pennylane.pex
```

### System information

```shell
Last pennylane
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by CelineDVL** [comment]
Hi @maliasadi,
I still face the problem

**Comment by maliasadi** [comment]
As I cannot regenerate this error, it would be a great help if you can provide more information about the system you're trying on and let us know if you get the same error running:
```console
 pex pip setuptools pennylane_lightning
```

**Comment by CelineDVL** [comment]
Hi,
It was due to an incompatibility of thé python version (3.6).
Sorry
