### ISSUE TITLE
More measurments supported with JAX-JIT

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#2404]
### Feature details

With a shots vector that is not None, the jax device only supports Variance and Expectation. It would be a great addition if JAX can support other measurements like probabilities and state.

Hope will to have things like this work:
```
dev = qml.device('default.qubit.jax', wires=2, shots=10)

@jax.jit
@qml.qnode(dev, interface='jax')
def circ(x):
    qml.PauliZ(wires=0)
    qml.RY(x, wires=0)
    return qml.probs(0)
print(circ(1))
```

### How important would you say this feature is?

3: Very important! Blocking work.

### Additional information

`qml.probs()` used to work earlier. But it is now raising InterfaceUnsupportedError

**Comment by ankit27kh** [comment]
I found this is same as #1208. There it only mentions JAX. JAX does support these. It is only with JIT and finite shots that this does not work.

**Comment by antalszava** [comment]
Hi @ankit27kh, thanks for the report! It's good to see that you would like to use these features.

A workaround when using `defaul.qubit.jax` is to set `interface=None` with `shots>0`. The reason why this would be necessary is that when `shots>0`, we always apply the interface (regardless of the device) and the JAX jittable interface doesn't support returning probabilities and states.

This addition is also in works with https://github.com/PennyLaneAI/pennylane/pull/2034.

**Comment by ankit27kh** [comment]
Hey @antalszava, `interface=None` works if I want to run a model once. But it does not support training the circuit. I hope your new additions will also support circuit training?

**Comment by antalszava** [comment]
Hi @ankit27kh, indeed, it doesn't. For `diff_method="backprop"`, the results obtained through differentiation are incorrect, hence it's disallowed to train such a circuit.

The previously linked PR (https://github.com/PennyLaneAI/pennylane/pull/2034) should allow other differentiation methods to be supported, so in that sense, this would tie into the issue https://github.com/PennyLaneAI/pennylane/issues/1208. Let me link this issue on the mentioned PR too.

**Comment by antalszava** [comment]
Hi @ankit27kh, the original example should work now with the `master` branch (and will be released soon) :+1: Note still, that the example makes use of the JAX jit interface.
