### ISSUE TITLE
Could `doc/requirements.txt` contain fewer dependencies?

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2433]
### Feature details

It looks that multiple dependencies in `doc/requirements.txt` were added because PennyLane is used for building the docs.

The only occurrence of using PennyLane, however, seems to be in `doc/conf.py` to get the version number in `doc/conf.py`:
```py
import pennylane

# The full version, including alpha/beta/rc tags.
release = pennylane.__version__
```
If this call requires adding new dependencies then we could:
1. Either investigate the importing mechanism of PennyLane;
2. Get the version number via file manipulation.

For 2., provided that it's executed from the doc folder and we have the same folder structure as now, this could work:
```py
import os

path = os.path.join("..", "pennylane", "_version.py")
with open(path, 'r', encoding="utf8") as f:
    lines = f.readlines()
    
line_with_version = lines[-1]
version = line_with_version.split('"')[-2] # last but one is the version, assuming that the last is a newline character

import pennylane

assert version == pennylane.__version__
```

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

Having fewer dependencies could improve docs builds (maybe).

**Comment by josh146** [comment]
Hey Antal, I think that Sphinx requires we import the package that is to be documented. This is how it extracts all the docstrings

**Comment by antalszava** [comment]
:crying_cat_face:

**Comment by josh146** [comment]
Check out [`autodoc_mock_imports`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports) for some background on what to do if you want to document something, but don't want to/can't install a dependency 🙂
