### ISSUE TITLE
Measuring the same wire multiple times

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#244]
On hardware devices, measuring an observable on a wire gives you information about both the expectation values and the variance; i.e., you get variance for 'free'. However, currently the QNode doesn't allow the same wire to be measured twice.

We should update the QNode rules to allow the same wire to be measured twice, as long as it is the same (or perhaps a commuting) observable being measured:

```python
def circuit()
    ...
    return qml.expval(qml.PauliZ(0)), qml.var(qml.PauliZ(0))
```

In addition, it might be useful to also ease this restriction entirely on devices that make it known that they are simulators - however I'm more on the fence with this one, so I'll open it up to discussion.

**Comment by co9olguy** [comment]
This kind of stuff would be a big win for users. They wouldn't have to create separate circuits which differ only in the measurement done. However, we'd have to be cautious to make it always obvious and transparent what is going on, in particular with regards to linearly independent observables on the same wire

**Comment by johannesjmeyer** [comment]
I think the most straightforward approach is to allow the user to return a 2D array of measurements:
```python
def circuit(x):
    ...
    return [[qml.expval(qml.PauliX(0)), qml.expval(qml.PauliX(1))],
            [qml.expval(qml.PauliY(0)), qml.expval(qml.PauliY(1))],
            [qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1))]]
```
In the QNode implementation we would check the type of the return:
* Returns expval -> nothing changes
* Returns Iterable of expvals -> nothing changes
* Returns an Iterable of Iterables of expvals -> Multi-measurement

Each element of the multi-measurement would then be treated and sanity-checked like a regular measurement right now.

This is also intimately related to #216

**Comment by johannesjmeyer** [comment]
I see two ways of implementing the measurement of commuting observables on the same wires:

#### a)
Group commuting measurements that act on the same wires together in a tuple
```python
def circuit(x):
    ...
    # I omit the qml.'s for brevity
    return [[PauliX(0), (Tensor(PauliZ(1), PauliZ(2)), Tensor(PauliX(1), PauliX(2)))],
            [PauliY(0), (Tensor(PauliY(1), PauliY(2)), Tensor(PauliZ(1), PauliZ(2)))]]
```
Advantage: Makes the use of the commuting observables explicit by grouping them together.
Drawback: We would have to flatten the output and in this way the actual output structure would not match the output structure of the circuit function.

#### b)
Just have a check in the QNode logic: If the same wires are measured in the same measurement the QNode checks if the operators commute and throws an error if not. Usage would be
```python
def circuit(x):
    ...
    # I omit the qml.'s for brevity
    return [[PauliX(0), Tensor(PauliZ(1), PauliZ(2)), Tensor(PauliX(1), PauliX(2))],
            [PauliY(0), Tensor(PauliY(1), PauliY(2)), Tensor(PauliZ(1), PauliZ(2))]]
```

Advantages: More liberal and flexible, the actual output looks like the circuit function output.
Drawback: Just a little bit more of code in the QNode.
___
I prefer **b)**

**Comment by josh146** [comment]
I'm not sure I see the reason for having an iterable of iterables; having
```python
return qml.expval(qml.PauliZ(0)), qml.var(qml.PauliZ(0))
```
is more straightforward for users, does not enforce rules on particular return shape, and should still be doable mostly by the plugin, with minimal changes within the QNode

**Comment by josh146** [comment]
(this doesn't preclude allowing a nested list of multiple measurements in addition)

**Comment by johannesjmeyer** [comment]
The reason why I would prefer to have an iterable of iterables is that I want to force the user to group the measurements together that he is interested in. For example, consider
```python
return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliY(1)), qml.expval(qml.PauliY(0)), 
       qml.var(qml.PauliX(1)), qml.var(qml.PauliZ(1))
```
In this case you could measure the first two things at the same time, then the second two. Then you would probably run the circuit again to measure the fifth thing -- which you could have already done in the first run! 

To improve upon this you would have to implement some kind of analysis in the QNode that groups measurements together for one run.

But if you do this, imagine the case where you are using a device for which the grouping of the observables matters (for example, measuring X and Z on multiple wires gives weird side effects, while measuring Z and Z and multiple wires works well). Then you need the user to have obvious control about what is measured in conjunction with what.

That's why I want to enforce this right away.

**Comment by co9olguy** [comment]
What if we had some additional MetaOperations, which can be used by advanced users to group together multiple things, e.g., observables that cannot be measured simultaneously?
e.g., 
```qml.expval(qml.CommutingObservables(Op0(wire0), Op1(wire0)))```

**Comment by josh146** [comment]
>What if we had some additional MetaOperations, which can be used by advanced users to group together multiple things, e.g., observables that cannot be measured simultaneously?
> e.g.,
> `qml.expval(qml.CommutingObservables(Op0(wire0), Op1(wire0)))`

I like this, it means less internal logic required by the QNode, more explicit, and a future higher-level abstraction layer could make use of this declarative approach to 'automate'  operations known to commute.

It would be nice to have a more concise way of writing it though.

**Comment by johannesjmeyer** [comment]
Independent of how the UI will turn out -- have you ideas how to implement this in the plugin-interface?

What about adding some parameter `multirun=(False|True)` or `run=(0|1|2|...)` to `pre_apply` and let the plugin return a value that indicates if the `apply` part should be skipped? This could be a Flag like 
```python
class Skip(IntFlag): 
    NONE,
    APPLY, 
    POST_APPLY, 
    PRE_MEASURE, 
    POST_MEASURE
``` 
that would be used like
```python
def pre_apply(run=0):
    ...
    if run > 0:
        return Skip.APPLY | Skip.POST_APPLY | Skip.PRE_MEASURE

    return Skip.NONE
```

**Comment by co9olguy** [comment]
My thinking is currently leaning towards leaving the low-level core as-is, with the "one function = one circuit (including measurements)" pattern, but having higher-level classes which can be used to manage several different (possibly non-commuting) final measurement options for the same circuit

**Comment by johannesjmeyer** [comment]
> My thinking is currently leaning towards leaving the low-level core as-is, with the
> "one function = one circuit (including measurements)"
> pattern.
> We could then look into higher-level classes ( `multiQNode`?) which can be used to manage several different (possibly non-commuting) final measurement options for the same circuit, and break these down into a minimal set of components to be executed by the plugins. That would also allow us to not have to update every single plugin, but rather leave the complexity to the core library

I agree that this is desirable, but you have to find a sensible way to do it. 
___
Probably one could do it like this
```python
@qml.ansatz(dev) # probably not necessary
def state_preparation(var):
    qml.RX(var[0], wires=0)
    ...

@qml.measurement(dev) # probably not necessary
def measure_X:
    return qml.expval(qml.PauliX(0)), ....

@qml.measurement(dev) # probably not necessary
def measure_Y:
    ...

node = MultiQNode([dev,] ansatz, measure_X, measure_Y, measure_Z)
# or
node = MultiQNode([dev,] ansatz, (measure_X, measure_Y, measure_Z))
```
What I don't like about it is that the return type (which would probably just be the concatenation of the results of the measurements) is not obvious from the code.

**Comment by josh146** [comment]
Update: as of PennyLane v0.13, it is now possible to measure commuting observables on the same wire within a single QNode. Measuring non-commuting observables is a different story, and we may not support this within the QNode/tape. @co9olguy I suggest closing this issue for now.
