### ISSUE TITLE
Broken link for qml.CRZ (Codebook)

### ISSUE THREAD

**Issue by jeonbik** [PennyLaneAI/pennylane#2486]
### Expected behavior

Link for qml.CRZ navigates to documentation.

### Actual behavior

The page does not exist.

### Additional information

The link for [qml.CRZ](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.CRz.html) on [codebook I.12.2](https://codebook.xanadu.ai) navigates to a broken webpage. 
<img width="749" alt="Screen Shot 2022-04-22 at 7 49 44 PM" src="https://user-images.githubusercontent.com/36014522/164843702-997edaee-fb8a-42e2-8d59-abb7a81e4194.png">

### System information

```shell
N/A
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by CatalinaAlbornoz** [comment]
Thank you for pointing this out @jeonbik! We will fix this problem. The correct link is [this one](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.CRZ.html).

Enjoy using the codebook and let us know in case you find any other issues!

**Comment by dwierichs** [comment]
@CatalinaAlbornoz This link was never updated, but I suppose it does not matter too much because this is about the old codebook? Is the plan to leave the issue open until the old codebook is taken offline?
