### ISSUE TITLE
Add a `requirements_dev.txt` file

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2560]
### Feature details

We would like to have a separate `requirements_dev.txt` file located top level, that gathers all the requirements required for developing PennyLane.

The file should contain the following packages, all with a permissive `>=` pinning:
```
pre-commit
pytest
pytest-cov
pytest-mock
pytest-xdist
flaky
black>=21
```
The requirement of `black` should be removed from the `requirements.txt`.

### Implementation

* Creating a new `requirements_dev.txt` file;
* Mentioning that developers new to PennyLane can use the `requirements_dev.txt` file in the [Ways to contribute to the PennyLane repository section](https://pennylane.readthedocs.io/en/stable/development/guide/contributing.html#ways-to-contribute-to-the-pennylane-repository) for contributing to PennyLane.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by divshacker** [comment]
So basically one just have to make a text file consisting of above text and add it to the repo? That's it? Am I interpreting it right? Please Correct me if I am wrong.
