### ISSUE TITLE
Very slow execution of qml.ctrl

### ISSUE THREAD

**Issue by imac1994** [PennyLaneAI/pennylane#2623]
Hello,

I have implemented a multi qubit controlled gate using the qml.ctrl method. Specifically, It is a parameterized 3 qubit gate controlled on 6 other qubits in a 9 qubit circuit. It seems to take about 4-5 minutes to execute the gate a single time, and I need to execute it 64 times in the circuit I am constructing. Is there a faster way to implement such a gate, or a particular option I can pass to `qml.ctrl` to speed this up? Below is a sample of the relevant code:
```python
def ops(params,a,b,c):
    qml.IsingXX(params[0],wires=[b,c])
    qml.IsingXX(params[1],wires=[a,b])
    qml.U2(params[2],params[3],wires=a)

ops2 = qml.ctrl(ops, control=[1,2,4,5,7,8])
ops2(params=p[52:56],a=0,b=3,c=6)
```
It is also worth noting that the `ops2` operation is being executed inside of the `entanglingLayer()` function in the following function, which I need to run in the torch interface:
```python
@qml.qnode(dev, interface="torch")#, diff_method="parameter-shift")
def get4qubitbqcnn(x,p): 
    statePrep(9,x)
    entanglingLayer(p)
    temp=[qml.expval(qml.PauliZ(0))]
    return tuple(temp)
```

Thank you!

Ian

**Comment by CatalinaAlbornoz** [comment]
Hi @imac1994, thank you for opening this issue!

Did you get this speed using `diff_method="parameter-shift"`? Could you try using `diff_method="adjoint"`? This should bring you speedups. You can also use the `lightning.qubit` device, which runs much faster.

If none of these work please post the output of `qml.about()` and your full code if possible so that we can look into this.

**Comment by imac1994** [comment]
Thank you for the quick response! Using lightning.qubit does indeed decrease the runtime of a single one of these gates to ~150s from ~330s using default.qubit. In both cases I have the diff_method commented out. Using "adjoint" as the diff_method increases the runtime to ~640s with default.qubit and ~150s with lightning.qubit. Unfortunately this is still a bit too slow for the purposes of optimizing a variational circuit that contains 64 of these gates. Are there any other options?

**Comment by CatalinaAlbornoz** [comment]
Hi @imac1994. If you have access to a GPU you could try using the `lightning.gpu` device. You could also look into using Jax or parallelizing circuit executions. The discussion [here](https://discuss.pennylane.ai/t/parallelization-of-circuit-executions/1566) is a good place to learn about this.

**Comment by CatalinaAlbornoz** [comment]
Hi @imac1994!
If you can share your full code and the output of `qml.about()` I may be able to find another speedup, but with the information I have I can't think of anything else to speed up your program.
If you do try the GPU route please let us know what speeds you get!

**Comment by albi3ro** [comment]
This slow down was likely due to the inefficient decompositions and the inability for the simulators to handle operations with many control wires.

Given 
```
@qml.qnode(qml.device('default.qubit', wires=10), diff_method=None)
def circuit(x):
    qml.ctrl(qml.IsingXX(x, (0,1)), (2,3,4,5,6,7,8,9))
    qml.ctrl(qml.U2(x, 0.2, wires=0), (2,3,4,5,6,7,8,9))
    return qml.expval(qml.PauliZ(0))
```

now executes in 9.15 ms on my computer, I'm going to mark this as closed.
