### ISSUE TITLE
Implement decomposition of `QubitUnitary` with parameter broadcasting

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#2636]
### Feature details

When using a broadcasted unitary matrix in `QubitUnitary` (possible as of #2609), the `decomposition` is not defined yet.
This can be implemented but may not be entirely straightforward.

### Implementation

To implement this feature:
1. The broadcasted matrix of shape `(batch_size, dim, dim)` has to be split into `batch_size` matrices (trivial)
2. The correct decomposition method (`zyz_decomposition` for 1 qubit/`two_qubit_decomposition` for 2 qubits) has to be applied to each of the matrices from step 1. (for example list comprehension)
3. The data of the operations in the resulting decompositions has to be read out and unified (may be tricky depending on how homogeneous the decompositions obtained in step 2. are),
4. operations containing the broadcasted data from step 3 have to be collected into a single decomposition list (might also be a bit tricky).

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by albi3ro** [comment]
Links to relevant pieces of source code:

* [`QubitUnitary`](https://github.com/PennyLaneAI/pennylane/blob/6633fcb91a7d83900fce876295df60594a241e48/pennylane/ops/qubit/matrix_ops.py#L28)
* [`zyz_decomposition`](https://github.com/PennyLaneAI/pennylane/blob/6633fcb91a7d83900fce876295df60594a241e48/pennylane/transforms/decompositions/single_qubit_unitary.py#L39)
* [`two_qubit_decomposition`](https://github.com/PennyLaneAI/pennylane/blob/6633fcb91a7d83900fce876295df60594a241e48/pennylane/transforms/decompositions/two_qubit_unitary.py#L499)

## The problem

Suppose have matrices with a batch dimension:

```pycon
>>> x = np.array([1.2, 2.3, 2.7])
>>> mats = qml.RX.compute_matrix(x)
>>> mats
tensor([[[0.82533561+0.j        , 0.        -0.56464247j],
         [0.        -0.56464247j, 0.82533561+0.j        ]],

        [[0.40848744+0.j        , 0.        -0.91276394j],
         [0.        -0.91276394j, 0.40848744+0.j        ]],

        [[0.21900669+0.j        , 0.        -0.97572336j],
         [0.        -0.97572336j, 0.21900669+0.j        ]]], requires_grad=True)
>>> mats.shape
(3, 2, 2)
``` 

We can construct a `QubitUnitary` operation using this matrix batch:

```pycon
>>> op = qml.QubitUnitary(mats, wires=0)
```

But trying to decompose it leads to a `DecompositionUndefinedError`:
```pycon
>>> op.decomposition()
DecompositionUndefinedError: The decomposition of QubitUnitary does not support broadcasting.
```

 If we didn't have a batch dimension, we could decompose the `QubitUnitary` into  `Rot` gate:

```pycon
>>> qml.QubitUnitary(mats[0, ...], 0).decomposition()
[Rot(tensor(1.57079633, requires_grad=True), tensor(1.2, requires_grad=True), tensor(-1.57079633, requires_grad=True), wires=[0])]
```

We would like to be able to decompose `QubitUnitary` when it has a batch dimension as well.

## Possible Solutions

There are (at least) two main ways to solve this problem.

### Solution 1

`QubitUnitary.decomposition` could:

* loop over the batch dimension,
* create a decomposition for each individual matrix
* combine the decompositions back together

### Solution 2

We could update the `zyz_decomposition` and/ or `two_qubit_decomposition` functions to work with batched matrices.  Batch support for these two functions could be implemented independently in separate PR's.  

Once `zyz_decomposition` (and/ or `two_qubit_decomposition`) supports batched matrices, we would need to update `QubitUnitary.compute_decomposition` as well.

### Additional Requirements

Any PR solving this problem would need tests and a changelog entry.

**Comment by albi3ro** [comment]
@dwierichs updated and clarified for potential use as a technical assessment.
