### ISSUE TITLE
Add mathematical definition to `qml.metric_tensor`

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#2638]
### Feature details

I noticed that the doc-string of [`qml.metric_tensor`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.metric_tensor.html) does not have a formal definition of what is computed. Adding that would gain clarity in general, and especially clarify the prefactor, which is important for the quantum fisher information (see [2103.15191](https://arxiv.org/pdf/2103.15191.pdf) eq. (27)).

I would add it myself in a short PR but I actually dont fully understand what is computed (which is why the question arose in the first place).

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by dwierichs** [comment]
This issue seems to have been resolved. From the linked function doc:
![image](https://github.com/PennyLaneAI/pennylane/assets/20772922/f5f182c6-0f2f-475c-bd37-3003ff2c164e)
