### ISSUE TITLE
Implement labels for broadcasted operators

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#2641]
### Feature details

When using parameter broadcasting and creating the label of an operation, its data is perceived as a matrix by PennyLane and therefore represented only symbolically:
```pycon
>>> @qml.qnode(dev)
>>> def qnode(x):
>>>     qml.RY(x, 0)
>>>     return qml.expval(qml.PauliZ(0))
>>> qml.draw(qnode)(np.array(0.5))
'0: ──RY(0.50)─┤  <Z>'
>>> qml.draw(qnode)(np.array([0.5, 0.9]))
'0: ──RY(M0)─┤  <Z>'
```
For large broadcasting dimensions this is definitely reasonable, as otherwise large arrays would be printed in circuit drawings, cluttering the drawing. However, for small broadcasting dimensions, like the two shifts of Pauli rotation parameter-shift rules, it would be useful to print out the broadcasted parameters explicitly.

### Implementation

One could
1. Decide for a cut-off size of the broadcasting axis and "simply" implement parameter printing for smaller data and symbolic printing (like `M0` above) for larger data; or
2. as tapes with broadcasted parameters have a unique `batch_size`, one could print out _multiple_ tapes, one for each value of the broadcasted parameter(s) (and the other ones being constant, of course). Again, there probably should be an upper limit as to how many tapes are drawn at most.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

The priority of this is lowered due to broadcasting being used mostly internally until now.

**Comment by dwierichs** [comment]
Revisiting this, I'm wondering whether we really want to change this. How big is the benefit of printing out numerical values over a symbolic placeholder? @albi3ro @trbromley do you have an opinion on this?

**Comment by trbromley** [comment]
:thinking: As it currently works now (i.e., showing `M0` if parameters are batched), I'd maybe wonder what `M0` represents. So I think there is something to improve here, but not sure what option is best, e.g., change `M0` to directly be the parameters vector in the circuit, or define `M0` outside of the circuit, or something else.

**Comment by dwierichs** [comment]
Oh, I think spontaneously I like the idea of having a "legend" of `tensor_like` objects labeled in a tape drawing :heart_eyes:

**Comment by albi3ro** [comment]
`qml.draw(circuit, show_matrices=True)()`.

We could consider changing the default to `True` instead of `False`.

**Comment by dwierichs** [comment]
Shall I implement the following?
Automatically switch `show_matrices` to `True` when broadcasting is detected.

Or do we simply want to change the default as suggested by @albi3ro?

**Comment by trbromley** [comment]
> Automatically switch show_matrices to True when broadcasting is detected.

This makes sense to me. @albi3ro?

**Comment by albi3ro** [comment]
I wouldn't automatically switch a keyword argument internally.  The entire point of the argument is to give users control over the output.

I would support switching the default behaviour.

**Comment by dwierichs** [comment]
Okay, that sounds reasonable :sweat_smile: 
I thought one could have switched the default value to be `None`, which gets reinterpreted as `False`, but switching the default might be more reasonable as it is such a minimal change.

**Comment by dwierichs** [comment]
I opened a PR for this.
