### ISSUE TITLE
Have control state of qubits visible in the circuit drawing

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#2660]
### Feature details

When using a controlled gate with custom control values, the drawing of the circuit does not represent this. The control values correctly show up in the mpl figure.
Example:
```
dev = qml.device('default.qubit',wires=4, shots=100)
@qml.qnode(dev)
def circ():
    for i in range(4):
        qml.Hadamard(wires=i)
    qml.MultiControlledX([0,1,2],3,'010')
    qml.MultiControlledX([0, 1, 2], 3, '111')
    qml.MultiControlledX([0, 1, 2], 3, '000')
    return qml.probs(0)

print(qml.draw(circ)())
fig, ax = qml.draw_mpl(circ)()
fig.show()
```
```
0: ──H─╭C─╭C─╭C─┤  Probs
1: ──H─├C─├C─├C─┤       
2: ──H─├C─├C─├C─┤       
3: ──H─╰X─╰X─╰X─┤
```
![image](https://user-images.githubusercontent.com/51011137/171986384-d868d98f-2e5f-4e8c-b89a-ca43a0b7daa5.png)

### Implementation

Will have to fix different symbols for 0 and 1 control state. Maybe 0 state can be represented by an 'O' and keep 'C' for state 1.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by CatalinaAlbornoz** [comment]
Hi @ankit27kh, this looks like a great issue to fix! Would you like to work on this for UnitaryHACK? You wouldn't get a bounty but you would get swag. Let us know if you would be interested!

**Comment by ankit27kh** [comment]
Hey @CatalinaAlbornoz, sure I can take a stab at it.

**Comment by ankit27kh** [comment]
The mpl drawer also fails to consider `control_values` when using `ControlledQubitUnitary`
![image](https://user-images.githubusercontent.com/51011137/172300613-5f42cea9-46f8-4e85-913d-21d28b207185.png)
This also needs to change

**Comment by ankit27kh** [comment]
Hey @albi3ro, totally agree with you on the symbols. It was my intention to ask for a better symbol anyway, Thanks to you we have it! :)

**Comment by CatalinaAlbornoz** [comment]
Remember to add [unitaryhack] in the title for your PR @ankit27kh. And remember to [sign up](https://unitaryhack.dev/signup/) for the hack in case you haven't already!
