### ISSUE TITLE
Provide more `QubitDevice` base method definitions instead having them abstract

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2674]
### Feature details

The `QubitDevice` class has a couple of abstract methods: `state`, `density_matrix`,  `analytic_probability`, etc..

There are certain abstract methods that would be implemented (almost) the same way for several devices.

For example, for `analytic_probability`, we could have the following general definition, assuming that the device is a pure-state simulator that can access the state:
```py
    def analytic_probability(self, wires=None):

        state = self.access_state() # Instead of accessing self._state directly

        if state is None:
            return None

        prob = self.marginal_prob(np.abs(state) ** 2, wires)
        return prob
```
This definition would utilize the error handling from `self.access_state()` and use  `self.marginal_prob` that is already defined in `QubitDevice`.

Many devices (e.g., state vector simulators from PennyLane-Qiskit, PennyLane-Forest, PennyLane-Qulacs, etc.) could utilize this definition of `analytic_probability` and if some do require a custom implementation (e.g., `default.mixed`), they then could just re-define `analytic_probability`.

This addition would help to further move away from repeating the same piece of code and have it in `QubitDevice`. The docstring of each base implementation could clarify which devices could utilize the specific method.

Note that providing definitions for the `state` and `density_matrix` methods could help provide support for returning `qml.state()` and `qml.density_matrix(wires=wires)` for certain plugin devices out of the box.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by albi3ro** [comment]
Closing this issue as `QubitDevice` is due to be replaced by `devices.experimental.Device`.

Our new philosophy also provides default behaviour through composition rather than inheritance, to make it easier to pick and choose implementation details.
