### ISSUE TITLE
Add `qml.FlipSign` subroutine template

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/pennylane#2681]
### Feature details

It would be great to have a FlipSign operator that supports an integer n or its binary representation, such that:

FlipSign(n)|m> = -|m> if m = n 
FlipSign(n)|m> = |m> if m != n 

That is, to change the sign of a specified state.
This would facilitate the process of oracle creation

### Implementation

Let guess, we have the binary representation `bin_n = [1,0,0,0]` and `wires = range(4)`
The template could have the following form:

```python
if bin_n[-1] == 0:
     qml.PauliX(wires = wires[-1])

qml.ctrl(qml.PauliZ, control = wires[:-1], control_values = n[:-1])(wires = wires[-1])

if bin_n[-1] == 0:
     qml.PauliX(wires = wires[-1])
```

We should check that the dimensions of `bin_n` and `wires` are the same.
Here I leave a subroutine to pass `n` to list that can be useful :)

```python

n = 21
wires = range(5)
bin_string = f"{n:b}".zfill(len(wires))
bin_n = [int(i) for i in bin_string]
print(bin_n)

```

```console
[1,0,1,0,1]
```

#### Implementation

* Create a new subroutine template in the [subroutines folder](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/templates/subroutines) named `FlipSign` and make it available via `qml.FlipSign`;
* Allow `qml.FlipSign` to appear in the relevant parts of the documentation.

See other subroutine templates from the above-linked folder for the details of the implementation and documentation

#### Testing

Add tests to a new test file to the `templates/test_subroutines/` folder. The testing should follow similar to the testing of other subroutines.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

Final example

```python

@qml.qnode(dev)
def circuit():
   qml.Hadamard(wires = 0)
   qml.FlipSign(1, wires = 0)
   qml.Hadamard(wires = 0)
   return qml.sample()

circuit()
```

```console
[1]
```

|0> --> |0> + |1> --> |0> - |1> --> |1>

**Comment by sergiomtzlosa** [comment]
Hi @KetpuntoG 

I would like to get involved in this enhancement, i fork this repo...let's see what else I can do🤓

**Comment by KetpuntoG** [comment]
Great! let's see what you can do 😉
Ask anything, no problem!

**Comment by KetpuntoG** [comment]
Hey! Look here: `pennylane/tests/templates/test_subroutines`
The tests are in a separate folder :)

**Comment by KetpuntoG** [comment]
Oh when you edited the comment I didn't get the notification! If you can do the PR and put me as a reviewer I can comment on the code. Do you know how to do the PR the repo or do you need help with it?

**Comment by sergiomtzlosa** [comment]
Hi @KetpuntoG , I made the pull request but I cannot assign you as reviewer

**Comment by antalszava** [comment]
Hi @KetpuntoG, can this issue be closed? :slightly_smiling_face:

**Comment by KetpuntoG** [comment]
Yes! Closed 🚀
