### ISSUE TITLE
Simulated Annealing

### ISSUE THREAD

**Issue by maxwell04-wq** [PennyLaneAI/pennylane#2689]
### Feature details

I would like to contribute a tutorial on simulated annealing using PennyLane. If needed, I can work on making a module on simulated annealing. This will allow a method for finding global optima. 

### Implementation

I have already implemented it for a hobbyist project on a simple quantum circuit. I have hardcoded the entire algorithm of simulated annealing to optimize a quantum circuit.  

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

I am participating in UnitaryHack 2022 and would like to claim a bounty. Is it possible to make this contribution as a part of UnitaryHack?

**Comment by maxwell04-wq** [comment]
Hi @CatalinaAlbornoz,

I noticed that the link you shared for submitting the tutorial is of the qml repo and not the pennylane one. Will the tutorial still be considered for UnitaryHack?

**Comment by CatalinaAlbornoz** [comment]
Hi @maxwell04-wq, as you noticed our repo for tutorials is different from the PennyLane repo. Officially it would be outside of UnitaryHack but we can send you a swag pack directly from Xanadu (not from the Unitary Fund) as a special-occasion gift.

**Comment by trbromley** [comment]
Thanks @maxwell04-wq for the great demo on this: https://github.com/maxwell04-wq/simulated-annealing-pennylane/blob/main/Simulated_Annealing_Tutorial_Pennylane.ipynb

I will close this issue.
