### ISSUE TITLE
Support shot lists with parameter broadcasting

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#2690]
### Feature details

The new parameter broadcasting feature does not work together with shot lists yet, i.e. with devices with partitioned shots.
To achieve feature parity and increase flexibility when using broadcasting, it would be great to add this support.

### Implementation

It is not straight-forward how to implement this, because the transposing behaviour for partitioned shot statistics in `_qubit_device.py::QubitDevice.statistics` is hard to generalize to all possible scenarios, and in particular to both broadcasted and unbroadcasted circuits. In addition, the `statistics` code is shared for the analytically exact, single shot number and shot list cases, making the generalization tricky.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by dwierichs** [comment]
This works now:
```python
@qml.qnode(qml.device('default.qubit', wires=2, shots=(10, 11)))
def circuit(x):
    qml.RX(x, wires=0)
    qml.RX(x, wires=1)
    return qml.expval(qml.PauliZ(0)), qml.var(qml.Y(1))

x = qml.numpy.array([1.1, 0.2])
circuit(x)
>>> ((array([0.2, 1. ]), array([0.  , 0.96])),
     (array([0.63636364, 1.        ]), array([0.33057851, 0.79338843])))
```

@trbromley good to close?

**Comment by dwierichs** [comment]
pinging @trbromley @albi3ro :)

**Comment by albi3ro** [comment]
Seems good to close to me :)
