### ISSUE TITLE
Add trivial behaviour logic to `qml.operation.expand_matrix`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#2739]
Right now, `qml.operation.expand_matrix` is often called in a code-block like:
```
if wire_order is None or self.wires == Wires(wire_order):
    return canonical_matrix

expand_matrix(canonical_matrix, wires=self.wires, wire_order=wire_order)
```
see [pennylane/operation.py Line 587](https://github.com/PennyLaneAI/pennylane/blob/b6fc5380abea6215661704ebe2f5cb8e7a599635/pennylane/operation.py#L587)

We should absorb that first bit of logic into the `expand_matrix` function and give the `wire_order` keyword argument a default value of `None`.

Benefits:
* Reduction in code duplication
* Reducting in the mental load of remembering those preprocessing steps
* Enhanced readability

To solve this issue, one would need to:
* edit [qml.operation.expand_matrix](https://github.com/PennyLaneAI/pennylane/blob/b6fc5380abea6215661704ebe2f5cb8e7a599635/pennylane/operation.py#L128)
* update its docstring and tests
* Check uses of `expand_matrix` throughout the code base to see if it can absord adjacent logic.

**Comment by kris524** [comment]
Hello! Can I help with this issue? Is there any additional info I might need? Thank you!

**Comment by albi3ro** [comment]
@kris524 Go ahead!

You can find our guide on pull requests [in the development guide](https://pennylane.readthedocs.io/en/stable/development/guide/pullrequests.html).  Feel free to ask any questions you have here, or open a "work-in-progress" PR for discussions there.

**Comment by kris524** [comment]
I am having a small issue with this: `ModuleNotFoundError: No module named 'numpy.core'` If you have any advice let me know.
