### ISSUE TITLE
[BUG] Minor documentation issue

### ISSUE THREAD

**Issue by CatalinaAlbornoz** [PennyLaneAI/pennylane#2789]
### Expected behavior

The link to the requirements-dev.txt file in the [contribution guideline in the docs](https://pennylane.readthedocs.io/en/stable/development/guide/contributing.html) is broken. We should link to [this link ](https://github.com/PennyLaneAI/pennylane/blob/master/requirements-dev.txt)instead.

### Actual behavior

The [current link](https://github.com/PennyLaneAI/pennylane/requirements_dev.txt) produces a Not Found page.

### System information

```shell
NA
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by PrajwalBorkar** [comment]
Please review for any changes. :)
