### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'numpy.core'

### ISSUE THREAD

**Issue by kris524** [PennyLaneAI/pennylane#2793]
### Expected behavior

I don't expect any output as the doctests should all pass

### Actual behavior

I want to run doctests, so I want to run for example `python3 operation.py` (inside /pennylane/pennylane/operation.py), but I get that error module not found. 

### Tracebacks

```shell
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 73, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kristiyandilov/pennylane/pennylane/operation.py", line 108, in <module>
    import pennylane as qml
  File "/opt/homebrew/lib/python3.9/site-packages/pennylane/__init__.py", line 20, in <module>
    import pkg_resources
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 30, in <module>
    import platform
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/platform.py", line 119, in <module>
    import subprocess
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 80, in <module>
    import selectors
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 11, in <module>
    import math
  File "/Users/kristiyandilov/pennylane/pennylane/math/__init__.py", line 34, in <module>
    import autoray as ar
  File "/opt/homebrew/lib/python3.9/site-packages/autoray/__init__.py", line 1, in <module>
    from .autoray import (
  File "/opt/homebrew/lib/python3.9/site-packages/autoray/autoray.py", line 26, in <module>
    import numpy as _numpy
  File "/Users/kristiyandilov/pennylane/pennylane/numpy/__init__.py", line 84, in <module>
    from autograd import numpy as _np
  File "/opt/homebrew/lib/python3.9/site-packages/autograd/__init__.py", line 2, in <module>
    from .differential_operators import (
  File "/opt/homebrew/lib/python3.9/site-packages/autograd/differential_operators.py", line 13, in <module>
    import autograd.numpy as np
  File "/opt/homebrew/lib/python3.9/site-packages/autograd/numpy/__init__.py", line 2, in <module>
    from .numpy_wrapper import *
  File "/opt/homebrew/lib/python3.9/site-packages/autograd/numpy/numpy_wrapper.py", line 7, in <module>
    from numpy.core.einsumfunc import _parse_einsum_input
ModuleNotFoundError: No module named 'numpy.core'
```

### System information

```shell
Name: PennyLane
Version: 0.25.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           macOS-12.3.1-arm64-arm-64bit
Python version:          3.9.10
Numpy version:           1.23.0
Scipy version:           1.8.1
Installed devices:
- default.gaussian (PennyLane-0.25.0.dev0)
- default.mixed (PennyLane-0.25.0.dev0)
- default.qubit (PennyLane-0.25.0.dev0)
- default.qubit.autograd (PennyLane-0.25.0.dev0)
- default.qubit.jax (PennyLane-0.25.0.dev0)
- default.qubit.tf (PennyLane-0.25.0.dev0)
- default.qubit.torch (PennyLane-0.25.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.24.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by CatalinaAlbornoz** [comment]
Hi @kris524, thank you for posting this issue here. I have looked into the issue and the most likely explanations are that your version of numpy is broken or that it's being pulled from some unexpected place. A lot of people seem to have had this issue as can be seen [here](https://github.com/numpy/numpy/issues/12977).

The common suggestion there is to try 
```
pip uninstall numpy
conda install numpy
```

If this doesn't work the best possible actions to follow probably are:
1. Create a new virtual environment. [This conda cheat sheet](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf) can be very helpful.
2. Install only the libraries you need in this new environment.

If the problem persists please let me know! We want to help you fix this problem.

**Comment by kris524** [comment]
Thank you so much for getting back to me! I will update you when I try the commands tomorrow.

**Comment by CatalinaAlbornoz** [comment]
I'm sorry that the fix didn't work @kris524. It's possible that this is an M1 mac issue.

**Comment by kris524** [comment]
> I'm sorry that the fix didn't work @kris524. It's possible that this is an M1 mac issue.

No worries. Thank you so much for helping me! Do you want me to close the issue?

**Comment by antalszava** [comment]
Hi both, I can replicate the `ModuleNotFoundError: No module named 'numpy.core'` error on my side on Ubuntu, I suspect it's some namespace issue.

> I want to run doctests, so I want to run for example python3 operation.py
I'm not sure I understand the original motivation here in specific, how does this work? Shouldn't the docstring tests be separated into a Python script?

**Comment by kris524** [comment]
Hi @antalszava, Thank you so much for joining in the fix! So it all came from me wanting to add a doctest to a function which I wanted to run. I usually would just use pytest and they would get detected, but it didn't work that way. So I tried python3 [name_of_script] and it came up with this original error. Hence, I thought that it was preventing me from running doctests and aimed to get it fixed. I did see that a module doctest is used for this. Maybe I should ask, how do you run doctests and do you even run them?

**Comment by antalszava** [comment]
Hi @kris524, we've been considering the use of `doctest`, but haven't made the required changes to run examples automatically yet. Did you perhaps come across info that explains otherwise?

I think we usually just run docstring examples (this is what you mean by doctest, correct?) from IPython notebooks or Jupyter notebooks.

**Comment by kris524** [comment]
I see now. Yeah, I interchanged docstring and doctests. Thank you for letting me know, I thought you just used some terminal command but if that's not the case then that's fine. From my limited experience, I have some code that uses only pytest to capture doctests as well.

 I will have a look at some code tomorrow and share it here in case I find it. Maybe it just uses the doctest module. At the end of the day, it's not a big deal. But thank you so much for the help. Is this issue still relevant then? I guess I now know this for my future pennylane contributions.

**Comment by antalszava** [comment]
I think it's great to have on record, though if it does turn out that it's not blocking your work, then maybe it can be closed.

I have seen the `ModuleNotFoundError: No module named 'numpy.core'` error locally when attempting to import PennyLane from the internal `pennylane` folder in an IPython notebook, though it didn't turn out to be a crucial issue to hunt down. This does tell me now, however, that it was not just a matter of some personal local configurations.

**Comment by antalszava** [comment]
So let me know if this issue is good to be closed for now.

**Comment by antalszava** [comment]
Just had a chat with Josh on this and the issue arises because of our custom NumPy implementation done in the `numpy` module. This module is attempted to be used for the import as per namespacing.

For this reason, this error is expected. I'll close this issue, it can be reopened if this causes any other issues.
