### ISSUE TITLE
Use appropriate names in circuit drawings of `qml.cond`

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#2806]
### Feature details

Drawing a circuit with `qml.cond` shows this gate as `ControlledOperation` in the circuit drawing,
Instead, use the name of the function in the condition.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by CatalinaAlbornoz** [comment]
It would definitely be nice to have @ankit27kh. I'm not sure how easy or hard this is to implement though. Do you have any thoughts on this @albi3ro?

**Comment by albi3ro** [comment]
The example you posted now returns:
```
0: ──H──┤↗├──────────────────────────────────────┤     
1: ──────║───H──RY(0.30)──H──Rot(1.20,1.10,0.30)─┤  <Z>
         ╚═══╩══╩═════════╩══╝                         
```

This was added in PR #4930 and #4901
