### ISSUE TITLE
Raise an error when instantiating an operator with `wires=[]`

### ISSUE THREAD

**Issue by AlbertMitjans** [PennyLaneAI/pennylane#2829]
### Feature details

Operators that have `num_wires = AnyWires` or `num_wires = AllWires` (such as `qml.Barrier`) are applied to all wires when instantiated with `wires = []`. This is the default behaviour for the `qml.Barrier` operation, but generally we want to raise an error when this happens.

This feature request follows the issue https://github.com/PennyLaneAI/pennylane/issues/2496, which was solved by the PR https://github.com/PennyLaneAI/pennylane/pull/2826.

### Implementation

See PR https://github.com/PennyLaneAI/pennylane/pull/2511.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by meenu-kri** [comment]
Hi @antalszava and @AlbertMitjans, I have created the PR for this issue and it is ready to review.
