### ISSUE TITLE
Add Integer Comparision template

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane#2887]
### Feature details

Add a template that can compare a provided integer $L$ with a basis state $\left|i\right>_n$ and flip a target qubit if $i\ge L$ or $i  < L$ depending on a user-defined parameter:
$\left|i\right>_n\left|0\right>\rightarrow\left|i\right>_n\left|i\ge L\right>$

### Implementation

This is available in Qiskit [here](https://qiskit.org/documentation/stubs/qiskit.circuit.library.IntegerComparator.html#qiskit.circuit.library.IntegerComparator).

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by isaacdevlugt** [comment]
Hey @ankit27kh ! Thanks for your issue 😄
