### ISSUE TITLE
Merge all `default.qubit` subclasses into a single device

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2909]
### Feature details

We'd like to have a single `default.qubit` device by merging each of the subclasses of `default.qubit`. The new `default.qubit` device should use `qml.math` such that it provides backpropagation for each ML framework supported by PennyLane and just-in-time compilation with JAX and Autograph with TensorFlow.

See https://github.com/PennyLaneAI/pennylane/pull/1334 for the first steps.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by rmoyard** [comment]
That was done by the device rework. :+1:
