### ISSUE TITLE
[BUG] Adjoint(None)(wires=[]) ends up on tape causeing AttributeError: 'Adjoint' object has no attribute 'control_wires' when drawing

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2921]
### Expected behavior

QNodes with Adjoint operations should draw fine.

### Actual behavior

In some cases (I have not yet been able to make a minimal example) a QNode construction ends up with `qnode.qtape.operations` looking like this:

`[RY(1.5707963267948966, wires=[0]), <QuantumTape: wires=[], params=0>, RZ(-0.3, wires=[0]), Adjoint(None)(wires=[]), RY(-1.5707963267948966, wires=[0])]`

I don't fully understand why and how `Adjoint(None)(wires=[])` ends up on the tape, but when I then try to draw the QNode I get:
```
  File "/.../pennylane/pennylane/drawer/draw.py", line 218, in wrapper
    return tape_text(
  File "/.../pennylane/pennylane/drawer/tape_text.py", line 320, in tape_text
    layer_str = add(op, layer_str, wire_map, decimals, cache)
  File "/.../pennylane/pennylane/drawer/tape_text.py", line 48, in _add_op
    control_wires = op.control_wires
AttributeError: 'Adjoint' object has no attribute 'control_wires'
```
The real problem is probably that this strange `Adjoint(None)(wires=[])` gets on the tape in the first place. Any idea how this could happen that could help me make a minimal example?

### System information

```shell
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pennylane as qml; qml.about()
Name: PennyLane
Version: 0.25.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/cvjjm/src/covqcstack/qcware/pennylane
Requires: numpy, scipy, networkx, retworkx, autograd, toml, appdirs, semantic-version, autoray, cachetools, pennylane-lightning
Required-by: pytket-pennylane, PennyLane-Qchem, PennyLane-Lightning, covvqetools

Platform info:           Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python version:          3.8.8
Numpy version:           1.20.1
Scipy version:           1.8.0
Installed devices:
- default.gaussian (PennyLane-0.25.0)
- default.mixed (PennyLane-0.25.0)
- default.qubit (PennyLane-0.25.0)
- default.qubit.autograd (PennyLane-0.25.0)
- default.qubit.jax (PennyLane-0.25.0)
- default.qubit.tf (PennyLane-0.25.0)
- default.qubit.torch (PennyLane-0.25.0)
- default.qutrit (PennyLane-0.25.0)
- pytket.pytketdevice (pytket-pennylane-0.1.0)
- lightning.qubit (PennyLane-Lightning-0.24.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
@cvjjm  Can you show code that reproduces the problem? 

We shouldn't ever have `Adjoint(None)`, so I'd very much like to know where it's being created.

Maybe I should add a validation to check to make sure `Adjoint` is always constructed with an `Operator`.

**Comment by albi3ro** [comment]
@cvjjm Have you managed to figure out what was going on, or is this still an active issue?

**Comment by cvjjm** [comment]
To be honest I didn't go into depth and this is not longer a problem. Sorry for not closing this earlier...
