### ISSUE TITLE
Clear up warnings in the `tests/devices/test_default_qubit_torch.py` file

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#2969]
### Feature details

Running `pytest` on the `tests/devices/test_default_qubit_torch.py` file yields multiple warnings like:
```
UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
    op_mat = torch.tensor(Rot3(a, b, c), dtype=torch.complex128, device=torch_device)
```
We'd like to not have such warnings.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by Amana-L** [comment]
Hi, I'd like to work on this. Can you provide the link to this please?

**Comment by antalszava** [comment]
Hi @Amana-L, apologies for the delayed response here. What link would that be?

**Comment by YutoMorohoshi** [comment]
Hello, I would like to contribute to this repository in some way, and am looking for issues that I can help with.
Is this issue still active? At first glance, it seems that tests/devices/test_default_qubit_torch.py no longer exists.
Thanks.

**Comment by astralcai** [comment]
![](https://media.tenor.com/TigFWS1gf50AAAAM/2000anos-depois.gif)

`default.qubit.torch` does not exist anymore.
