### ISSUE TITLE
[BUG] Scalar product of observable produces `qml.Hamiltonian` incorrectly for framework tensors

### ISSUE THREAD

**Issue by eddddddy** [PennyLaneAI/pennylane#2971]
### Expected behavior

A `qml.Hamiltonian` object is constructed correctly for the product of a Python scalar with an observable:
```
>>> h = 0.3 * qml.PauliX(0)
>>> h.coeffs, h.ops
(array([0.3]), [PauliX(wires=[0])])
```
We would expect the product of a framework-specific scalar tensor with an observable to also work:
```
>>> # should be the same as qml.Hamiltonian([np.array(0.3)], [qml.PauliX(0)])
>>> h = np.array(0.3) * qml.PauliX(0)   
```

### Actual behavior

Instead, the latter code produces the following output:
```
>>> h = np.array(0.3) * qml.PauliX(0)
>>> h
tensor(<Hamiltonian: terms=1, wires=[0]>, dtype=object, requires_grad=True)
```
This is a "scalar" tensor, where the scalar is the Hamiltonian object itself.

### System information

```shell
Name: PennyLane
Version: 0.25.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: c:\users\edward.jiang\documents\pennylane
Requires: numpy, scipy, networkx, retworkx, autograd, toml, appdirs, semantic-version, autoray, cachetools, pennylane
-lightning
Required-by: PennyLane-qiskit, PennyLane-Lightning

Platform info:           Windows-10-10.0.19042-SP0
Python version:          3.8.10
Numpy version:           1.20.3
Scipy version:           1.7.3
Installed devices:
- default.gaussian (PennyLane-0.25.0.dev0)
- default.mixed (PennyLane-0.25.0.dev0)
- default.qubit (PennyLane-0.25.0.dev0)
- default.qubit.autograd (PennyLane-0.25.0.dev0)
- default.qubit.jax (PennyLane-0.25.0.dev0)
- default.qubit.tf (PennyLane-0.25.0.dev0)
- default.qubit.torch (PennyLane-0.25.0.dev0)
- qiskit.aer (PennyLane-qiskit-0.24.0)
- qiskit.basicaer (PennyLane-qiskit-0.24.0)
- qiskit.ibmq (PennyLane-qiskit-0.24.0)
- qiskit.ibmq.circuit_runner (PennyLane-qiskit-0.24.0)
- qiskit.ibmq.sampler (PennyLane-qiskit-0.24.0)
- lightning.qubit (PennyLane-Lightning-0.25.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by AlbertMitjans** [comment]
Hi @eddddddy, I tried this code and obtained the expected behaviour:
```python
>>> h = np.array(0.3) * qml.PauliX(0)
>>> h
  (0.3) [X0]
>>> h.coeffs, h.ops
(array([0.3]), [PauliX(wires=[0])])
```

**Comment by AlbertMitjans** [comment]
I am not sure if we can change the current behaviour, given that we would lose information about trainability:
```python
>>> np.array(0.3, requires_grad=True) * qml.PauliX(0)
tensor(<Hamiltonian: terms=1, wires=[0]>, dtype=object, requires_grad=True)
```

FYI, you can obtain the Hamiltonian from the tensor by calling `unwrap`:
```python
>>> h = np.array(0.3) * qml.PauliX(0)
>>> h.unwrap()
  (0.3) [X0]
```

**Comment by eddddddy** [comment]
Right, OK. I guess from this and the other issue as well, it's clear that `qml.Hamiltonian` is not really intended to handle framework-specific tensors.

However, this looks to be handled by the new operator arithmetic. Just wondering, is the new operator arithmetic going to replace `qml.Hamiltonian` somewhere down the line?

**Comment by AlbertMitjans** [comment]
> However, this looks to be handled by the new operator arithmetic. Just wondering, is the new operator arithmetic going to replace `qml.Hamiltonian` somewhere down the line?

Yes!

**Comment by AlbertMitjans** [comment]
@eddddddy can I close this issue?

**Comment by eddddddy** [comment]
Sure, you can go ahead and close this issue.
