### ISSUE TITLE
Grouping in `qchem.molecular_hamiltonian` qubit-wise-commuting

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#2996]
Currently, there is no option in `qchem.molecular_hamiltonian` instances to set a grouping, i.e. to qubit-wise-commuting `'qwc'`. I believe this is a relic as up until recently this was done in `ExpvalCost` which is now deprecated.

There is a workaround
```python
coeffs, obs = H.coeffs, H.ops
H_qwc = qml.Hamiltonian(coeffs, obs, grouping_type="qwc")
```
for a molecular Hamiltonian H. I think it would be good to have that option available directly in the molecular Hamiltonian and I am not sure if there are some properties of the molecular one that gets lost in that process.

**Comment by astralcai** [comment]
Should we close this issue now?
