### ISSUE TITLE
Add `lazy=True` keyword argument to `qml.s_prod`, `qml.prod`, and `qml.op_sum`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#3094]
Currently, `qml.pow` and `qml.adjoint` both have a keyword argument `lazy=True` that indicates whether or not to perform some basic simplification steps:

```
>>> qml.adjoint(qml.PauliX(0), lazy=True)
Adjoint(PauliX(wires=[0]))
>>> qml.adjoint(qml.PauliX(0), lazy=False)
PauliX(wires=[0])
>>> qml.pow(qml.RX(1.2, 0), 2.0, lazy=False)
RX(2.4, wires=[0])
```

For `s_prod`, `prod`, and `op_sum`, if `lazy=False`, we can do something similar.

For `qml.s_prod(scalar, op, lazy=False)`, we should check if `op` is already a scalar product `SProd`.  If so, we combine the coefficients.

```pycon
>>> qml.s_prod(3, qml.s_prod(4, qml.PauliX(0)))
3*(4*(PauliX(wires=[0])))
>>> qml.s_prod(3, qml.s_prod(4, qml.PauliX(0)), lazy=False) #target behavior
12*(PauliZ(wires=[0]))
```

For `qml.prod(*ops, lazy=False)`, we should check if any of the provided operators are already of type `Prod`.  If so, we use its `operands` instead.

```pycon
>>> op = qml.prod(qml.S(0), qml.prod(qml.S(1), qml.T(1)))
>>> op
S(wires=[0]) @ (S(wires=[1]) @ T(wires=[1]))
>>> op.operands
(S(wires=[0]), S(wires=[1]) @ T(wires=[1]))
>>> qml.prod(qml.S(0), qml.prod(qml.S(1), qml.T(1)), lazy=False).operands # target behavior
(S(wires=[0]), S(wires=[1]), T(wires=[1]))
```

Same for `qml.op_sum`.  If any operators are of type `Sum`, we would use its constituents instead of itself.

**Comment by anonymousr007** [comment]
Hello, I am interested in this issue. Please let me know some more details about this issue. Thanks.

**Comment by antalszava** [comment]
Hi @anonymousr007, thank you for your interest! :slightly_smiling_face:

The idea here is that an object that is created by top-level functions that transform operations (e.g., `qml.s_prod`, `qml.prod`, and `qml.op_sum`) can have some simplification steps that may be performed. What the simplification step is, depends on the operation and the transform itself, but for example the original snippet
```py
>>> qml.adjoint(qml.PauliX(0), lazy=False)
PauliX(wires=[0])
```
is an example where the adjoint of a PauliX is PauliX. If we evaluate `qml.adjoint(qml.PauliX(0), lazy=False)` in a lazy manner, then we don't yet conclude that the result will simply be `qml.PauliX(0)`, but rather create `Adjoint(PauliX(wires=[0]))`.

Hope this helps, let us know if you have more questions!
