### ISSUE TITLE
Extend `qml.equal` to `MeasurementProcess` objects

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#3101]
PennyLane now has a `qml.equal` function that is useful for comparing the equality of `Operator`'s.

  We could extend this function to `MeasurementProcess` objects as well.

```pycon
>>> qml.equal(qml.expval(qml.PauliX(0)), qml.expval(qml.PauliX(0)) )
True
>>> qml.equal(qml.probs(wires=(0,1)), qml.probs(wires=(1,2)) )
False
```

If both inputs were `MeasurementProcess` objects, we would then need to:
1) compare `return_type`
2) Check the existence of `m.obs`, compare if exists for both
3) Check wires

**Comment by kmyali** [comment]
Hi, I am interested in taking this issue. I have good software experience but I haven't done much Open Source contributions.

Is there an expected date when I should have the PR ready by?

**Comment by AryanJ13** [comment]
Hello, i would love to work on this. can you please share some guide or sample for me to look into and prep.

**Comment by Gopal-Dahale** [comment]
@kmyali Are you still working on this?

**Comment by kmyali** [comment]
> @kmyali Are you still working on this?

Yes, I am. I got distracted for a bit, but I should be opening my PR within 24 hours.
