### ISSUE TITLE
`qml.measure` queues operation with name "Identity" (revisit `MeasurementProcess.name`)

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/pennylane#3102]
### Expected behavior

The `name` attribute of the measure operation found in the `tape.operations` list should be set correctly (e.g. `measure`).

### Actual behavior

Instead the `name` attribute contains `Identity`.

### Source code

```shell
import pennylane as qml

with qml.tape.QuantumTape() as tape:
    qml.measure(wires=[0])

tape.operations[0].name
```

### System information

```shell
-
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Hi @dime10 thanks for finding this! The updating of the [`MeasurementProcess.name` attribute](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/measurements.py#L151) in general is something that needs update, though that update would likely come up once we have a standardized device API in place.

Mid-circuit measurements are treated as operations at the moment, hence the behaviour above.

Does this affect any use case?

**Comment by dime10** [comment]
Thanks for your response @antalszava :) 

Hmm I see. The use case was just identifying a `measure` operation in the tape list (`tape.operations`).
All other operations have the `.name` attribute which I can check, but for the `measure` "operation" I only found `.return_type.value`, which doesn't exist for operations however so I have to resort to `hasattr/getattr`.

Not dramatic, just nice to have a more "unified" way of checking this I guess :)

**Comment by antalszava** [comment]
Sure :+1: Thanks :)

We have it in the pipeline to look at the `MeasurementProcess` class a bit more, this could be something to consider then too.

**Comment by albi3ro** [comment]
`MeasurementProcess.name` is now removed, but `MidMeasureMP` is now `"MidMeasureMP"`.  So I believe we can mark this bug as closed.
