### ISSUE TITLE
change the default wire order of qml.matrix

### ISSUE THREAD

**Issue by alice4space** [PennyLaneAI/pennylane#3131]
### Feature details

At the moment the wire order of the `qml.matrix` function doesn't follow the natural id number by default, but rather the order in which gates are executed. I find this can be an issue, when a circuit is designed to have qubits with a specific id to have a special role, like ancilla for measurement or post selection.

To illustrate this lets take the two following circuits, doing the same thing except the qubit I want to use for some post selection is id 0 in the first case and id 2 in the second case:

```
def c_q0(x1,x2):
    qml.RY(np.pi/2,wires=0)
    qml.ctrl(qml.RY,(0),(0))(x1,wires=1)
    qml.ctrl(qml.RY,(0),(1))(x2,wires=2)
    qml.adjoint(qml.RY)(np.pi/2,wires=0)

def c_q2(x1,x2):
    qml.RY(np.pi/2,wires=2)
    qml.ctrl(qml.RY,(2),(0))(x1,wires=0)
    qml.ctrl(qml.RY,(2),(1))(x2,wires=1)
    qml.adjoint(qml.RY)(np.pi/2,wires=2)
```

With the current version of pennylane '0.26.0', if execute the following: 

```
M0 = qml.matrix(c_q0)(1,2)
M2 = qml.matrix(c_q2)(1,2)
```

I will get the same matrix (M0=M2), which can be confusing.. I was trying to do some post selection looking at certain blocks of the matrix and it actually took me some time to figure out what was wrong, and found out that instead to get the matrix with the correct id I would need to do :

```
M0 = qml.matrix(c_q0,wire_order=[0,1,2])(1,2)
M2 = qml.matrix(c_q2,wire_order=[0,1,2])(1,2)
```

I there a reason why the default order has been chosen as such ?

### Implementation

In the [`qml.matrix`](https://docs.pennylane.ai/en/stable/_modules/pennylane/ops/functions/matrix.html) source code :

`wire_order = wire_order or tape.wires `

could be replaced by

`wire_order = wire_order or range(len(tape.wires))`

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by albi3ro** [comment]
Thanks for the feedback @alice4space .

You've stumbled on a peculiarity of how PennyLane is designed. 

While most of the time wire labels are simple integers starting from zero, we don't make that restriction.  We allow wire labels to be any "hashable" object.  For example, `"aux"`, `(1,2)`, and `1.234` are perfectly valid wire labels. `range(len(tape.wires))` would fail if the tape had any wires like these.

Suppose we instead sort them.  How would we compare wire labels like `"aux"`, `(1,2)`, and `(2,1)`?

Because of these questions, we only give wires an order in the context of a specified wire order.

Would better documentation in for `qml.matrix` help?

One other way to specify a wire order is via a device.  Turning both above functions into `QNode`'s with a wire order from the device also gets the results you are looking for:

```
@qml.qnode(qml.device('lightning.qubit', wires=(0,1,2)))
def c_q0(x1,x2):
    qml.RY(np.pi/2,wires=0)
    qml.ctrl(qml.RY,(0),(0))(x1,wires=1)
    qml.ctrl(qml.RY,(0),(1))(x2,wires=2)
    qml.adjoint(qml.RY)(np.pi/2,wires=0)
    return qml.state()

@qml.qnode(qml.device('lightning.qubit', wires=(0,1,2)))
def c_q2(x1,x2):
    qml.RY(np.pi/2,wires=2)
    qml.ctrl(qml.RY,(2),(0))(x1,wires=0)
    qml.ctrl(qml.RY,(2),(1))(x2,wires=1)
    qml.adjoint(qml.RY)(np.pi/2,wires=2)
    return qml.state()

qml.math.allclose(qml.matrix(c_q0)(1,2), qml.matrix(c_q2)(1,2))
```

**Comment by alice4space** [comment]
thank you @albi3ro, I understand better now the reasons behind this.

Maybe highlighting in the documentation that the default order for wires is NOT the sorted id array would help. 

However, taking into account that the wide majority of pennylane demos (at least from my perspective) actually use numbers as wires id, I would expect that for most users assuming that qml.matrix will give out the logical order is natural. I am probably not the first one being bugged by this.

Therefore I would propose an alternative which is to remove the default order of wires altogether, that is forcing users to make a conscious choice about the order they would like to see the matrix returned.

What are your thoughts on this ?

**Comment by alice4space** [comment]
I think this is a good option as well :)

**Comment by CatalinaAlbornoz** [comment]
Any thoughts on this @josh146?

**Comment by trbromley** [comment]
With #5039, we have decided to require a wire order with `qml.matrix()` in situations where the wire order is ambiguous, such as with quantum functions or tapes. For scenarios where a ordered integer wires are preferred, one can use `wire_order=range(n_wires)`. For example:
```python
import pennylane as qml
import numpy as np

def c_q0(x1,x2):
    qml.RY(np.pi/2,wires=0)
    qml.ctrl(qml.RY,(0),(0))(x1,wires=1)
    qml.ctrl(qml.RY,(0),(1))(x2,wires=2)
    qml.adjoint(qml.RY)(np.pi/2,wires=0)

def c_q1(x1,x2):
    qml.RY(np.pi/2,wires=2)
    qml.ctrl(qml.RY,(2),(0))(x1,wires=0)
    qml.ctrl(qml.RY,(2),(1))(x2,wires=1)
    qml.adjoint(qml.RY)(np.pi/2,wires=2)

m0 = qml.matrix(c_q0, wire_order=range(3))(1., 2.)
m1 = qml.matrix(c_q1, wire_order=range(3))(1., 2.)

assert not np.allclose(m0, m1)
```
