### ISSUE TITLE
Add `purity` function to quantum information module

### ISSUE THREAD

**Issue by eddddddy** [PennyLaneAI/pennylane#3139]
### Feature details

It would be nice to add support for [purity](https://en.wikipedia.org/wiki/Purity_(quantum_mechanics)) in the quantum information module. This can be achieved by implementing a separate function in `pennylane/math/quantum.py` that takes as input either a state vector or a density matrix, and outputs a scalar.

Of course, we would want the function to be fully differentiable as well.

### Implementation

**Steps to take:**
1. Implement a function `purity()` in `pennylane/math/quantum.py` that takes as input a state vector or a density matrix.
2. Add tests for the function in `tests/math/`. In this particular case it might make sense to create a separate test file instead of putting the tests in an existing file.

**Notes:**
1. For both of these steps, you can refer to the implementations of the other quantum information functions.
2. Other quantum information quantities have additional support for i) measurement processes and ii) QNode transforms. In this case neither of these are required.
3. Differentiability is required. Testing must cover differentiability for all interfaces (autograd, TF, torch, and JAX).

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by CatalinaAlbornoz** [comment]
For anyone solving this issue as part of hacktoberfest please remember to register at the [hacktoberfest website](https://hacktoberfest.com/)!

**Comment by astralcai** [comment]
Hi, I have created a pull-request for this feature (https://github.com/PennyLaneAI/pennylane/pull/3290). I also added support for measurement processes and QNode transforms, as they might be useful. There are non-trivial use cases of computing purity for a circuit state:
1. Computing the purity of a sub-system to determine if this subsystem is entangled with the rest of the circuit.
2. Computing the purity of a noisy circuit built with the ```default.mixed``` device.

**Comment by CatalinaAlbornoz** [comment]
Hi @astralcai, thank you for creating a pull request for this feature! 🤩 Please add any questions you may have on the PR itself.

**Comment by astralcai** [comment]
The pull request is merged, however this feature is still missing the measurement component. This is to be implemented after the refactor of the `measurement` module is complete. Do not close this issue yet.

**Comment by CatalinaAlbornoz** [comment]
Thanks for the heads-up @astralcai ! We won't close this issue yet.

**Comment by astralcai** [comment]
> Thanks for the heads-up @astralcai ! We won't close this issue yet.

Hi @CatalinaAlbornoz,

Can you let me know when the refactor is complete? I'll open up a new PR for the purity measurement then.

Best,

Astral

**Comment by CatalinaAlbornoz** [comment]
Hi @astralcai. The VnEntropy MP class in (#3326) has been merged. Was there another PR that you were waiting for? @antalszava, is there another PR that we should be aware of here?

**Comment by astralcai** [comment]
@eddddddy I noticed that both pull requests you mentioned are merged. Is the refactor on measurements complete?

**Comment by AlbertMitjans** [comment]
Hi @astralcai! Yes, the refactor is complete! We will soon add documentation on how to create custom measurement processes ([see PR](https://github.com/PennyLaneAI/pennylane/pull/3506)).

**Comment by astralcai** [comment]
> 

Hi @AlbertMitjans 

I am trying to implement the ```purity``` measurement but getting a bit confused, specifically with the structure of ```QubitDevice``` in ```_qubit_device.py```.

1. It seems that for every method there is a ```xxx``` and a ```xxx_new``` that are almost duplicates of one another, such as ```statistics``` and ```statistics_new```. If I understand correctly, ```statistics``` uses return types to distinguish between measurements, and ```statistics_new``` uses the `MeasurementProcess` class. I see that we are to stop using return types, does that mean I should only implement ```purity``` to ```statistics_new``` and not ```statistics```?
2. In both ```statistics``` and ```statistics_new```, I see that there is an `elif` clause for all instances of ```SampleMeasurement``` and  ```StateMeasurement``` that goes to call `self._measure`, which then calls the ```process_state``` or ```process_sample``` of that measurement, which makes perfect sense, but then this doesn't seem to be used much. There are still many measurements such as ```VnEntropy``` and `MutualInfo` that define their own methods ```vn_entropy``` and ```mutual_info``` in ```QubitDevice``` which compute values directly using the ```math``` module, completely bypassing the ```process_state``` of both measurement processes.

**Comment by AlbertMitjans** [comment]
Hi @astralcai!

Sorry for the mess in the code, the `QubitDevice` is undergoing multiple refactors right now, but luckily with the refactor of the measurements module you don't need to worry about `QubitDevice` anymore! 

1. The `xxx_new` methods have been added in a big refactoring that will change the return value of QNodes ([see here for more documentation](https://docs.pennylane.ai/en/latest/code/api/pennylane.enable_return.html)). These methods will replace the original function in the near future.

2. You are completely right. Ideally we wanted to remove all these measurements from `QubitDevice` and handle them using the calls to `process_state` or `process_samples`. However there might be users that are using these methods directly, that's why we are keeping them for this release to avoid any breaking changes.

In the upcoming release there will be documentation on how to create custom measurement processes. You can check a preview [here](https://xanaduai-pennylane--3506.com.readthedocs.build/en/3506/code/qml_measurements.html).

**Comment by astralcai** [comment]
Hi @AlbertMitjans ,

If you look at ```tests/qinfo/test_entropies.py```, there are two test classes associated with vn entropy. The ```TestVonNeumannEntropyQNode``` test class contains tests for ```vn_entropy``` as a measurement process, used inside a QNode.

**Comment by AlbertMitjans** [comment]
Hi @astralcai 

Thank you for catching this! These tests shouldn't be there, I opened a PR moving these tests inside the `measurements/` folder.

**Comment by astralcai** [comment]
@AlbertMitjans I just created a PR for the purity measurement, can you drop a review? https://github.com/PennyLaneAI/pennylane/pull/3551

**Comment by astralcai** [comment]
@CatalinaAlbornoz This issue can be closed now.

**Comment by CatalinaAlbornoz** [comment]
Thank you for your contribution @astralcai!
