### ISSUE TITLE
Add `min_entropy` function to quantum information module

### ISSUE THREAD

**Issue by eddddddy** [PennyLaneAI/pennylane#3141]
### Feature details

It would be nice to add support for [min-entropy](https://en.wikipedia.org/wiki/R%C3%A9nyi_entropy#Min-entropy) in the quantum information module. This can be achieved by implementing a separate function in `pennylane/math/quantum.py` that takes as input either a state vector or a density matrix, plus additional arguments such as the logarithm base, and outputs a scalar.

Of course, we would want the function to be fully differentiable as well.

### Implementation

**Steps to take:**
1. Implement a function `min_entropy()` in `pennylane/math/quantum.py` that takes as input a state vector or a density matrix, plus any additional arguments you see fit.
2. Add tests for the function in `tests/math/test_entropies_math.py`.

**Notes:**
1. For both of these steps, you can refer to the implementations of the other quantum information functions.
2. Other quantum information quantities have additional support for i) measurement processes and ii) QNode transforms. In this case neither of these are required.
3. Differentiability is required. Testing must cover differentiability for all interfaces (autograd, TF, torch, and JAX). (Note that tests for differentiability for the other entropies, such as `vn_entropy`, are instead done in `tests/qinfo/test_entropies.py`. Since you're not implementing a QNode transform, it's fine to place these tests in `tests/math/test_entropies_math.py` instead.)

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by devilkiller-ag** [comment]
Can I work on this issue?

**Comment by eddddddy** [comment]
Yep, go ahead! Let me know if you have any questions 😃.

**Comment by CatalinaAlbornoz** [comment]
For anyone solving this issue as part of hacktoberfest please remember to register at the [hacktoberfest website](https://hacktoberfest.com/)!

**Comment by devilkiller-ag** [comment]
Hi, I wanted to work on this but I can't understand clearly what I have to do. Can you please help?

**Comment by devilkiller-ag** [comment]
Thanks @eddddddy Now I can start working on this

**Comment by devilkiller-ag** [comment]
Hey @eddddddy , I am a beginner in Quantum Computing and I am not sure if my implementation is correct or not due to my inability to clearly understand Renyi entropy. Can you please check my implementation of the function before I move forward with writing tests?

**Comment by eddddddy** [comment]
Hi @devilkiller-ag, you can open a PR and mark it as draft. We can continue this discussion on the PR.

**Comment by devilkiller-ag** [comment]
Sure @eddddddy

**Comment by isaacdevlugt** [comment]
Thanks for making the PR @devilkiller-ag !

**Comment by EuGig** [comment]
Hi, is somebody still working on the issue? I would like to pick it up!

**Comment by isaacdevlugt** [comment]
Hey @EuGig! Please go ahead! 😃
