### ISSUE TITLE
Entanglement entropy of pure bipartite states (`qml.qinfo` module)

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#3150]
### Feature details

[Quantifying the entanglement](https://www.quantiki.org/wiki/entanglement-measure) for example by determining the [entropy of entanglement](https://en.wikipedia.org/wiki/Entropy_of_entanglement) of bipartite quantum states can be useful for applications of quantum information (e.g., in quantum cryptography).

One way of determining entanglement entropy is to compute the [von Neumann entropy](https://docs.pennylane.ai/en/stable/code/api/pennylane.qinfo.transforms.vn_entropy.html) of one of the reduced states (see [reduced density matrix feature](https://docs.pennylane.ai/en/stable/code/api/pennylane.qinfo.transforms.reduced_dm.html) here).

It could be useful to add a user interface for such a measure specifically for the bipartite quantum state case.

### Implementation

The implementation could depend on already existing features in the quantum information module of PennyLane and perhaps the `qml.density_matrix` measurement.

Differentiation with machine learning frameworks should be supported (see a [relevant test case](https://github.com/PennyLaneAI/pennylane/blob/master/tests/qinfo/test_entropies.py#L749) here).

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by astralcai** [comment]
Hi, I have opened a pull request for this feature (https://github.com/PennyLaneAI/pennylane/pull/3271).

**Comment by astralcai** [comment]
The original pull request was discarded because the new commit to master which re-organized the measurements module conflicts with my commit. I have re-organized my code and opened up a new pull request (https://github.com/PennyLaneAI/pennylane/pull/3275)
