### ISSUE TITLE
Broken GitHub link for Tutorials on Demos page

### ISSUE THREAD

**Issue by jeonbik** [PennyLaneAI/pennylane#3158]
### Expected behavior

The `View on GitHub` link [here](https://pennylane.ai/qml/demos/tutorial_kernels_module.html) should direct users to its corresponding GitHub  page.

### Actual behavior

The link leads to [this](https://github.com//blob/master/demonstrations/tutorial_kernels_module.py) blank page. 

### System information

```shell
Name: PennyLane
Version: 0.23.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /Users/bikramkhanal/miniforge3/envs/tf_mac/lib/python3.10/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           macOS-12.6-arm64-i386-64bit
Python version:          3.10.5
Numpy version:           1.22.4
Scipy version:           1.8.1
Installed devices:
- default.gaussian (PennyLane-0.23.1)
- default.mixed (PennyLane-0.23.1)
- default.qubit (PennyLane-0.23.1)
- default.qubit.autograd (PennyLane-0.23.1)
- default.qubit.jax (PennyLane-0.23.1)
- default.qubit.tf (PennyLane-0.23.1)
- default.qubit.torch (PennyLane-0.23.1)
- lightning.qubit (PennyLane-Lightning-0.23.0)
```
```


### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by jeonbik** [comment]
I tried with a few other `GitHub` links provided for demos [here](https://pennylane.ai/qml/demos_qml.html). None of these links works. i.e none of the `View on GitHub` links redirect to GitHub on any demo tutorials.

**Comment by josh146** [comment]
Thanks @jeonbik for reporting this! We are currently tracking this bug on the [QML repository](https://github.com/PennyLaneAI/qml/issues/591), and should have it fixed very shortly. I'll close this issue here, but if you have any other comments feel free to post on the linked issue :)
