### ISSUE TITLE
Decompose gates into universal set (Clifford + T)

### ISSUE THREAD

**Issue by isaacdevlugt** [PennyLaneAI/pennylane#3162]
### Feature details

Given a quantum function or operation, decompose it into gates from a universal gate set (Clifford + T).

### Implementation

Add a new transform to the [set of compilation transforms we have](https://docs.pennylane.ai/en/latest/code/qml_transforms.html#transforms-for-circuit-compilation) (e.g., qml.transforms.clifford_decomposition()).

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

Feature request driven by [this user question](https://discuss.pennylane.ai/t/converting-circuit-gates-to-clifford-t-gates/2205/3).

**Comment by ankit27kh** [comment]
Hey @isaacdevlugt 
I can work on this. My idea is to have a method for all gates (which don't have a decomposition method) to give their clifford+T decomposition. Then the transform can go through the tape, decompose the gates, and replace them with their clifford+T substitutes.
The decomposition can only be an approximation, the order of which will have to be decided.
Let me know.

**Comment by ankit27kh** [comment]
fixed decomposition will not work for parameterised gates. An algorithm will have to be used for such gates, which will generate the decomposition up to a threshold error
