### ISSUE TITLE
OrbitalRotation should decompose itself into SingleExitation

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#3169]
### Feature details

OrbitalRotation consists of two SingleExitation gates and should thus not decompose itself all the way down into single Pauli and CNOT but into two SingleExitation gates, which themselves have a decomposition into more elementary gates.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by isaacdevlugt** [comment]
Hey @cvjjm! Great suggestion. There are a few reasons why this is a good thing to implement on our side. We're working on a fix 😄

**Comment by cvjjm** [comment]
Thanks!
