### ISSUE TITLE
[BUG] `qml.prod` incompatible with some `grouping` functionality (likely due to order of ops passed to `qml.prod`)

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#3210]
### Expected behavior

`qml.prod` works with `qml.grouping.utils.are_pauli_words_qwc`.

### Actual behavior

Incorrect behaviour. Swapping the order of two ops passed to `qml.prod` changes to correct behaviour (perhaps due to the wire ordering changing).

### Source code

```shell
o1 = qml.PauliZ(1)
o2 = qml.prod(*[qml.PauliZ(1), qml.Identity(0)])
print(qml.grouping.utils.are_pauli_words_qwc([o1, o2]))

o1 = qml.PauliZ(1)
o2 = qml.operation.Tensor(*[qml.PauliZ(1), qml.Identity(0)])
print(qml.grouping.utils.are_pauli_words_qwc([o1, o2]))

False
True
```

### System information

```shell
PL dev
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Doing 

```py
o1 = qml.PauliZ(1)
o2 = qml.prod(*[qml.Identity(0), qml.PauliZ(1)])
print(qml.grouping.utils.are_pauli_words_qwc([o1, o2]))
```
instead of
```py
o1 = qml.PauliZ(1)
o2 = qml.prod(*[qml.PauliZ(1), qml.Identity(0)])
print(qml.grouping.utils.are_pauli_words_qwc([o1, o2]))
```
Outputs `True` (as expected).

**Comment by timmysilv** [comment]
this should be addressed by the Pauli Word rework

**Comment by albi3ro** [comment]
Hasn't been addressed by the Pauli word rework, since we haven't gone back and updated the utilities.  We will now re-prioritize this issue.

**Comment by astralcai** [comment]
I don't think this issue is present anymore?

**Comment by albi3ro** [comment]
Looks like this is fixed now.
