### ISSUE TITLE
Cache jacobians when using finite-differences with Autograd

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#3217]
### Feature details

Generalize the [caching mechanism in the Autograd interface used for the parameter-shift rule](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/interfaces/autograd.py#L199) to the finite differences gradient transform too.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by AnuravModak** [comment]
hey @antalszava, is anyone working on this if not I would like to start working, any more information about this enhancement or feature might help.

**Comment by antalszava** [comment]
Hi @AnuravModak, I'm no longer an active contributor to PennyLane, ccing @albi3ro to provide more details here.

**Comment by albi3ro** [comment]
@AnuravModak I'm currently rewriting that section of code in #4557 , and it looks like my PR which actually be closing this issue. Sorry about that.
