### ISSUE TITLE
gates block

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/pennylane#3319]
### Feature details

It would be great to be able to group gates under the same name so that they would be drawn as a single block in the drawer.
Possible implementations:

```python

def U(param, wires):
   qml.RX(param, wires = wires[0])
   qml.CNOT(wires = wires)

dev = qml.device("default.qubit", wires = 3)

@qml.qnode(dev)
def circuit():
   qml.Hadamard(wires = 0)
   qml.Block(U, name = "my block")(param, wires = [0,1])

```

So if I now paint the circuit, I will not see the U gates but a block called "my block".
As a decorator it would also look very nice:

```python

@qml.block("my block")
def U(param, wires):
   qml.RX(param, wires = wires[0])
   qml.CNOT(wires = wires)

dev = qml.device("default.qubit", wires = 3)

@qml.qnode(dev)
def circuit():
   qml.Hadamard(wires = 0)
   U(param, wires = [0,1])

```

I have called it block but maybe it can be given another better name

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

I think It would better not complicate the logic of it by adding new properties to that block (it is just important for the drawer). At a didactic level it is very useful since many algorithms use oracles that would be better to put in a small box so their operations are invisible to the user.

**Comment by josh146** [comment]
@KetpuntoG actually you could do this with operations!
```python
>>> class U(qml.operation.Operation):
...     num_wires = 2
...     num_params = 1
...
...     @staticmethod
...     def compute_decomposition(param, wires):
...         qml.RX(param, wires=wires[0])
...         qml.CNOT(wires=wires)
...
...     def label(self, **kwargs):
...         return "my_block"
...
>>> @qml.qnode(dev)
... def circuit():
...     qml.Hadamard(wires=0)
...     U(0.2, wires=[0, 1])
...     return qml.expval(qml.PauliZ(0))
...
>>> print(qml.draw(circuit)())
0: ──H─╭my_block─┤  <Z>
1: ────╰my_block─┤
```

**Comment by KetpuntoG** [comment]
Oh okay, it works for me! Thanks :)
