### ISSUE TITLE
Warning or useful error message if initializing Exp with swapped arguments

### ISSUE THREAD

**Issue by lillian542** [PennyLaneAI/pennylane#3332]
### Feature details

When creating an `Exp`, the intention (and assumption of various class methods) is that the first argument is the base operator, and the second the coefficient. 

No error or warning is raised when creating the operator if these arguments are switched, but trying to use the resulting operator raises errors later, with error messages that would be fairly cryptic to a user who had unintentionally switched the order of the arguments.

This should warn you that this won't work:

```
base_op = qml.PauliX(0) @ qml.PauliZ(1)
op = exp(2, base_op)
```
 

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by astralcai** [comment]
This is the current behaviour. I believe we're safe to close this now? @lillian542 
```
>>> base_op = qml.PauliX(0) @ qml.PauliZ(1)
>>> op = qml.exp(2, base_op)
TypeError: base is expected to be of type Operator, but received <class 'int'>
```
