### ISSUE TITLE
[BUG] is_pauli_word returns incorrect output

### ISSUE THREAD

**Issue by lillian542** [PennyLaneAI/pennylane#3334]
### Expected behavior

That a function called `is_pauli_word` checks if the operator is a Pauli word.

### Actual behavior

Currently it checks if all the operators are Pauli operators or Identity. *If* all the Pauli operators also target different wires, this is the same as checking if its a Pauli word. If the same wire is targeted by multiple Pauli operators, imaginary coefficient start popping up and its not the same as checking if it's a Pauli word anymore. The function does not check for this.

Also for Hamiltonians considers only whether all operators are Pauli operators, not whether it's actually a Pauli word.

### Additional information

A function is probably also needed that performs the function `is_pauli_word` currently does. It should just be called something like `only_pauli_operators`.

### Source code

```shell
qml.pauli.is_pauli_word(qml.PauliX(0) @ qml.PauliZ(0))
>>> True # should be False, or function should be only_pauli_operators
```

### System information

```shell
not relevant
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
Given that the documentation has been updated for `is_pauli_word` and we now have a warning that specifies:
```
UserWarning: Tensor object acts on overlapping wires; in some PennyLane functions this will lead to undefined behaviour
```
and clarifies that strange behaviour will occur, I'm going to mark this bug as closed.
