### ISSUE TITLE
AmplitudeEmbedding padding/normalization

### ISSUE THREAD

**Issue by toshi-koike-akino** [PennyLaneAI/pennylane#3379]
I encounter issues when embedding non-power-of-two features with AmplitudeEmbedding. Older version works, but v0.27.0 does not work.
When I see the source code, the change in padding is:
from
 feature_set = qml.math.concatenate([feature_set, padding], axis=0)
to 
 feature_set = qml.math.hstack([feature_set, padding])

The error message is as follows:
python3.9/site-packages/pennylane/templates/embeddings/amplitude.py", line 221, in _preprocess
    feature_set = qml.math.hstack([feature_set, padding])
  File "python3.9/site-packages/autoray/autoray.py", line 80, in do
    return get_lib_fn(backend, fn)(*args, **kwargs)
TypeError: expected Tensor as element 1 in argument 0, but got list

**Comment by rmoyard** [comment]
Hi @toshi-koike-akino thank you for reporting your problem! Indeed there was a change in this PR https://github.com/PennyLaneAI/pennylane/pull/3166. Could give an example of what do you mean by non-power-of-two features? 

I tried that and still works:

```
dev = qml.device("default.qubit", wires=2)
@qml.qnode(dev)
def circuit(f=None):
    qml.AmplitudeEmbedding(features=f, wires=range(2), normalize=True)
    return qml.expval(qml.PauliZ(0))


circuit(f=[15, 15, 15, 15])
print(dev.state)
```

**Comment by toshi-koike-akino** [comment]
I meant the case such as 3 features not 4(=2^2) features
  circuit(f=[15,15,15])
And, using 'pad_with' like
  qm.AmplitudeEmbedding(f, wires=range(2), pad_with=1, normalize=True)

**Comment by rmoyard** [comment]
Thank you @toshi-koike-akino , @eddddddy opened a PR to fix that problem.
