### ISSUE TITLE
[BUG] Finite difference does not work with special object observable

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#3398]
### Expected behavior

There is a [dedicated test](https://github.com/PennyLaneAI/pennylane/blob/dae6540be0ad78f258ebf7f342e4537c120addfc/tests/gradients/test_finite_difference.py#L357) for special observables that return some special object instead of a number and differentiating them with `finite_diff`.

### Actual behavior

Unfortunately, the test linked above for `diff_method="finite_diff"` does not use `diff_method="finite_diff"` but copied over `diff_method="parameter-shift"`. Changing it actually breaks the test, i.e. special observables are actually not supported by finite diff.

### Additional information

The test breaks because `SpecialObject` in the test implements `__mul__` and `__add__` but not right-multiplication and -addition, and does not have a method for division by floats.

### System information

```shell
Name: PennyLane
Version: 0.28.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/david/venvs/xenv/lib/python3.10/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Python version:          3.10.6
Numpy version:           1.23.4
Scipy version:           1.9.3
Installed devices:
- default.gaussian (PennyLane-0.28.0.dev0)
- default.mixed (PennyLane-0.28.0.dev0)
- default.qubit (PennyLane-0.28.0.dev0)
- default.qubit.autograd (PennyLane-0.28.0.dev0)
- default.qubit.jax (PennyLane-0.28.0.dev0)
- default.qubit.tf (PennyLane-0.28.0.dev0)
- default.qubit.torch (PennyLane-0.28.0.dev0)
- default.qutrit (PennyLane-0.28.0.dev0)
- null.qubit (PennyLane-0.28.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.27.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment]
Thanks for catching this @dwierichs! Does this mean that special observables _do_ work with parameter-shift? Or is that also broken?

**Comment by dwierichs** [comment]
Yes, with parameter-shift there should not be any issue. The FD test is a copy of the PS test, as far as I can tell, and it passes :)
This is not a critical issue, because the changes required are actually that the `SpecialObject` is a bit more versatile than the test emulates, i.e. it is supposed to not only allow for `SpecialObject(value) * float` but also for `float * SpecialObject(value)`, as well as some other standard manipulations. In particular, if an Observable returns some custom version of a `float`, this will be implemented and the `finite-diff` mode will work with said Observable. :)
