### ISSUE TITLE
[BUG] [Return-types] Some tests raise `VisibleDeprecationWarning` (perhaps due to param-shift)

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#3428]
### Expected behavior

No test in `tests/returntypes` raises `VisibleDeprecationWarning` (or those that do have such warnings handled and caught).

### Actual behavior

Some tests do raise warnings, e.g., running `pytest tests/returntypes/test_jax_qnode_new.py --tb=short -s -x -k 'test_diff_multi_probs'` raises

```py
returntypes/test_jax_qnode_new.py::TestVectorValuedQNode::test_diff_multi_probs[default.qubit-parameter-shift-backward-jax-python]
  /anaconda3/lib/python3.8/site-packages/autograd/numpy/numpy_wrapper.py:77: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    return _np.array(args, *array_args, **array_kwargs)
```

### Additional information

It might be that the parameter-shift gradient transform itself creates ragged arrays for multiple probabilities with varying number of wires.

### System information

```shell
PL dev
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by dwierichs** [comment]
This particular example raises the warning because of a ragged array that is being created within the test suite and that contains the expected result. It is not a problem with the PL suite. I'll fix this and potential similar occurences in `tests/returntypes`.
