### ISSUE TITLE
[BUG] pauli_word_to_string doesn't work for Hamiltonians

### ISSUE THREAD

**Issue by lillian542** [PennyLaneAI/pennylane#3482]
### Expected behavior

Relevant for executing a circuit involving an Evolution operator with a Hamiltonian as a base.

```
t = qml.PauliX(0) @ qml.PauliY(1)
h = qml.Hamiltonian([1], [t])

pauli_word_to_string(t)
>>> 'XY'

pauli_word_to_string(h)
>>> 'XY'
```

### Actual behavior

```
pauli_word_to_string(h)
>>>
File ~/pennylane/pennylane/pauli/utils.py:411, in pauli_word_to_string(pauli_word, wire_map)
    409     if pauli_word.name != "Identity":
    410         wire_idx = wire_map[pauli_word.wires[0]]
--> 411         pauli_string[wire_idx] = character_map[pauli_word.name]
    412     return "".join(pauli_string)
    414 for name, wire_label in zip(pauli_word.name, pauli_word.wires):

KeyError: 'Hamiltonian'
```

### System information

```shell
-
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by isaacdevlugt** [comment]
Hey @lillian542! I think the behaviour is intended. Hamiltonians, in general, aren't Pauli words; they're linear combinations of Pauli words.

The example Hamiltonian that you chose is _technically_ a Pauli word (H = XY), but I think the observed behaviour is expected. For instance, if you instead defined your Hamiltonian as `h = qml.Hamiltonian([0.5], [t])`, calling `qml.pauli.pauli_word_to_string` should return an error.

I'd be happy to hear anyone else's thoughts!
