### ISSUE TITLE
Allow setting data on qml.Hamiltonian to update coefficients

### ISSUE THREAD

**Issue by lillian542** [PennyLaneAI/pennylane#3507]
### Expected behavior

Setting the data corresponding to coefficients on a Hamiltonian would update the coefficients.

### Actual behavior

Only the data list is updated.

### Source code

```shell
h = qml.Hamiltonian([1, 2, 1], [qml.PauliX(0), qml.PauliY(1), qml.PauliZ(2)])
h.data, h.coeffs
>>> ([1, 2, 1], [1, 2, 1])

h.data = [3, 3, 3]
h.data, h.coeffs
>>> ([3, 3, 3], [1, 2, 1])
```
```


### Tracebacks

_No response_

### System information

```shell
-
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
`bind_new_parameters` is now the recommended way to update data, and it updates coefficients as well.
