### ISSUE TITLE
Add decomposition for `ControlledQubitUnitary`

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/pennylane#3521]
### Expected behavior

It would be nice if the `ControlledQubitUnitary` had a decomposition method, so that devices that don't explicitly support it are still able to compile a program containing it, assuming the device supports at least `QubitUnitary`.

The decomposition function can then simply return
```py
QubitUnitary(self.matrix(), wires=self.wires)
```

### Actual behavior

The operator raises a `DecompositionUndefinedError`.

### System information

```shell
-
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by lillian542** [comment]
[sc-30599]

**Comment by albi3ro** [comment]
I wouldn't call this as much a bug as a lack of features.

With PR #3450 , decompositions will exist for one and two-qubit target unitaries and a single control wire, as `ControlledQubitUnitary` will derive it's decomposition from that of `QubitUnitary`.

In the future, we also want to add better general controlled decomposition formulas in a coherent way.

**Comment by dime10** [comment]
> I wouldn't call this as much a bug as a lack of features.

Yes you are right, apologies.

> With PR https://github.com/PennyLaneAI/pennylane/pull/3450 , decompositions will exist for one and two-qubit target unitaries and a single control wire, as ControlledQubitUnitary will derive it's decomposition from that of QubitUnitary.

The issue with that is that decompositions for QubitUnataries are very limited, and only exist for 1- and 2-qubit gates. A decomposition that turns ControlledQubitUnitary into QubitUnatary would work for any number of qubits, and additionally removes the controlled wires, which themselves don't decompose that well for more than 1 control wire.

**Comment by dime10** [comment]
Hi @albi3ro, what do you think about giving `ControlledQubitUnitary` its own decomposition given the aforementioned drawbacks, or is this undesired?

**Comment by albi3ro** [comment]
We have a goal for this quarter to add additional controlled-decomposition algorithms.  These algorithms should allow decomposition in the number of control wires for any target operation.

**Comment by dime10** [comment]
Would those algorithms work with ControlledQubitUnitary, given that we only have decomposition algorithms for 1- and 2-qubit unitaries? Or would they be based on the matrix representation of the base gate anyways rather than the decomposition strategy of the base gate?

**Comment by albi3ro** [comment]
There are a variety of decomposition algorithms.  One of the more efficient ones at low numbers of control wires relies on being able to apply a singly-controlled version of a root of the operator `op **(1/(2**n))`.

**Comment by albi3ro** [comment]
Marked as duplicate to #2322
