### ISSUE TITLE
The demos have Google Structured Data

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#3712]
We would like the demos pages to implement Google Structured Data \- probably using the article form: <https://developers.google.com/search/docs/appearance/structured-data/article> <span data-preserve-white-space></span>

<p></p>

This may improve the search rankings of the demos pages\.

<p></p>

It should be possible to generate this data from the demo metadata\.

<p></p>

## Stages

<p></p>

- Investigate how this would be implemented with Sphinx\.

**Comment by josh146** [comment]
Link to subfeature: https://xanadu.productboard.com/feature-board/planning/features/17833815

**Comment by trbromley** [comment]
Closing this as it's a request for the QML repo. @BM7878
