### ISSUE TITLE
[BUG] PennyLane accidentally initializes a root logger instance

### ISSUE THREAD

**Issue by leofang** [PennyLaneAI/pennylane#3731]
### Expected behavior

PennyLane should use its own logger, not writing to the root logger directly. This causes hard-to-track bugs in the downstream where user-initialized root logger instances are expected.

### Actual behavior

This line
https://github.com/PennyLaneAI/pennylane/blob/102a3efe2bf394c9749d4765d0860ac74e48162d/pennylane/configuration.py#L58
is the culprit. According to the logging documentation (under the [`logging.debug()`](https://docs.python.org/3/library/logging.html#logging.debug) entry):
> This function (as well as [info()](https://docs.python.org/3/library/logging.html#logging.info), [warning()](https://docs.python.org/3/library/logging.html#logging.warning), [error()](https://docs.python.org/3/library/logging.html#logging.error) and [critical()](https://docs.python.org/3/library/logging.html#logging.critical)) will call [basicConfig()](https://docs.python.org/3/library/logging.html#logging.basicConfig) if the root logger doesn’t have any handler attached.

meaning a default logging handler (created via `basicConfig()`) would be attached to the root logger. But this is unexpected behavior to end users who just wanna use the root logger. Symptoms include:
- losing pre-defined logging format
- excessive logging output due to multiple handlers
- see also #2006

### Additional information

The correct fix is simple, just two lines 🙂
1. Fix this line to use a PennyLane-owned logging instance (which is standard practice)
https://github.com/PennyLaneAI/pennylane/blob/102a3efe2bf394c9749d4765d0860ac74e48162d/pennylane/configuration.py#L25
by changing it to `logger = logging.getLogger("PennyLane")`. (By the way, this line is currently a no-op...)
2. Use the PennyLane-owned logger to log everywhere, for example the offending line above should be
```
logger.info("No PennyLane configuration file found.") 
```

There's a prior discussion https://github.com/PennyLaneAI/pennylane/issues/2006, however I do not believe it addresses this issue correctly.

### System information

```shell
n/a
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
Thanks for this @leofang .

Since it does seem like this is problematic, I'm wondering if we need it at all in this location, or if a warning would suffice.

**Comment by leofang** [comment]
I did a quick search before filing the issue, and unless I miss something `configuration.py` is the only place PennyLane logs. So you can certainly remove all logging stuff there, which is also a two-line fix 😆
