### ISSUE TITLE
[BUG] Incorrect implementation of the `qml.transforms.fold_global`

### ISSUE THREAD

**Issue by mmlouamri** [PennyLaneAI/pennylane#3772]
### Expected behavior

We (with @Belaloui, @abduhu, @Taha-Rouabah) have been learning about error mitigation like ZNE since few days. And, thus, we have been using the `qml.transforms.fold_global` method quite a lot. It appears to us that the `s` related to the partial folding part can take any value as long as it is not larger than `d` (the circuit's number of operations).

Example:
---------------

Let's pick the example present in the documentation:

```python
import pennylane as qml
from pennylane import numpy as np

dev = qml.device("default.qubit", wires=3)
x = np.arange(6)

@qml.qnode(dev)
def circuit(x):
    qml.RX(x[0], wires=0)
    qml.RY(x[1], wires=1)
    qml.RZ(x[2], wires=2)
    qml.CNOT(wires=(0,1))
    qml.CNOT(wires=(1,2))
    qml.RX(x[3], wires=0)
    qml.RY(x[4], wires=1)
    qml.RZ(x[5], wires=2)
    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2))

folded = qml.transforms.fold_global(circuit, 1.5)
print(qml.draw(folded)(x)) 
```

We expect it to give:
```
0: ──RX(0.00)─╭●──RX(3.00)──────────────────────────┤ ╭<Z@Z@Z>
1: ──RY(1.00)─╰X─╭●─────────RY(4.00)──RY(4.00)†──RY(4.00)─┤ ├<Z@Z@Z>
2: ──RZ(2.00)────╰X─────-───RZ(5.00)──RZ(5.00)†──RZ(5.00)─┤ ╰<Z@Z@Z>
```

Because, with `d=8` and `lambda=1.5`, we should get `n=0` and `s=0.5*4=2` --> the last `RY, RZ` get folded and we obtain a circuit with `d * scale_factor = 8 * 1.5 = 12` operations in total as expected  (see [ref.](https://arxiv.org/pdf/2005.10921.pdf)).

### Actual behavior

However, in the current implementation `s` can only take `0` and `d/2` as potential values, i.e: decimal values of the scaling factor have no effect on the output of `qml.transforms.fold_global`.

Example:
---------------

Let's pick the example present in the documentation,

```python
import pennylane as qml
from pennylane import numpy as np

dev = qml.device("default.qubit", wires=3)
x = np.arange(6)

@qml.qnode(dev)
def circuit(x):
    qml.RX(x[0], wires=0)
    qml.RY(x[1], wires=1)
    qml.RZ(x[2], wires=2)
    qml.CNOT(wires=(0,1))
    qml.CNOT(wires=(1,2))
    qml.RX(x[3], wires=0)
    qml.RY(x[4], wires=1)
    qml.RZ(x[5], wires=2)
    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2))

folded = qml.transforms.fold_global(circuit, 1.5)
print(qml.draw(folded)(x)) 
```

The result that we get is:
```
0: ──RX(0.00)─╭●──RX(3.00)─---──────────┤ ╭<Z@Z@Z>
1: ──RY(1.00)─╰X─╭●─────────RY(4.00)───┤ ├<Z@Z@Z>
2: ──RZ(2.00)────╰X─────-───RZ(5.00)───┤ ╰<Z@Z@Z>
```

Which has length `8` and thus doesn't approximate well-enough `d * scale_factor = 12`.

### Additional information

The issue is related to the fact that the `_divmod` function gives back two integer (instead of an integer and a floating number).

```python
# from pennylane.transforms.mitigate
def _divmod(a, b):
    """Performs divmod but in an all-interface compatible manner"""
    out1 = qml.math.floor(a / b)
    out2 = a - out1 * b
    return int(out1), int(out2)
 ```

Therefore, the `fraction_scale` variable can only take `{0, 1}` as values which then leads to the issue mentioned above.

In [mitiq](https://mitiq.readthedocs.io/en/v.0.1a2/_modules/mitiq/zne/scaling.html#fold_global), the code uses [divmod](https://www.programiz.com/python-programming/methods/built-in/divmod) which actually returns floating point number and not integers.

Additionally, the formula given in the [documentation](https://docs.pennylane.ai/en/stable/code/api/pennylane.transforms.fold_global.html) for `fold_global(U)` is erroneous as it doesn't correctly formalized the desired effect of the scaling factor. More explicitly, and as an illustration, let's pick the case where `s=2`. We can see the number of operations that actually get folded is `d - s + 1` instead of `s`.  

### System information

```shell
Name: PennyLane
Version: 0.28.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           Linux-5.10.147+-x86_64-with-glibc2.29
Python version:          3.8.10
Numpy version:           1.21.6
Scipy version:           1.7.3
Installed devices:
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by timmysilv** [comment]
Hi @mmlouamri, thanks for bringing this to our attention, and thanks for the detailed report! I'll look into fixing this soon.

**Comment by Qottmann** [comment]
Thanks for the very clear and detailed report!

For $d=8$ and $\lambda=1.5$, $s=((\lambda-1)\mod 2) \frac{d}{2} = (0.5 \mod 2) \frac{8}{2} = 0$ so I would say this is expected behavior. I remember simply recreating the mitiq implementation, can you check if it returns a different (/your expected circuit)?

What you describe is a fair request, but more of an enhancement of the current implementation.

**Comment by Qottmann** [comment]
The updated `fold_global` now provides the requested functionality. `git checkout master` to use it or wait for the `v0.29.0` release in two weeks :)
