### ISSUE TITLE
[BUG] `ParametrizedEvolution` operations with different time parameters are reported to be the same by `qml.equal`

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#3846]
### Expected behavior

If two `ParametrizedEvolution` operations differ by their time windows, they should be recognized to be different, similar to when they have different parameters:
```python
import pennylane as qml
from jax import numpy as jnp

h = qml.pulse.pwc([0.3, 1.]) * qml.PauliX(2)
p1, p2 = [jnp.linspace(0, 1., 5)], [jnp.linspace(0, 2., 5)]
t1, t2 = 0.7, 2.
op_p1_t1 = qml.evolve(h)(p1, t1)
op_p2_t1 = qml.evolve(h)(p2, t1)
op_p1_t2 = qml.evolve(h)(p1, t2)

qml.equal(op_p1_t1, op_p1_t1) # True
qml.equal(op_p1_t1, op_p2_t1) # False
qml.equal(op_p1_t1, op_p1_t2) # should be False but reports True
```

### Actual behavior

See above, last line of the code block.

### Additional information

This is because the attribute `t` is not stored in the parameters or hyperparameters of `ParametrizedEvolution` but as a separate attribute.

### System information

```shell
Name: PennyLane
Version: 0.29.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/david/venvs/dev/lib/python3.10/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning, PennyLane-qiskit

Platform info:           Linux-5.19.0-32-generic-x86_64-with-glibc2.35
Python version:          3.10.6
Numpy version:           1.23.5
Scipy version:           1.9.3
Installed devices:
- default.gaussian (PennyLane-0.29.0.dev0)
- default.mixed (PennyLane-0.29.0.dev0)
- default.qubit (PennyLane-0.29.0.dev0)
- default.qubit.autograd (PennyLane-0.29.0.dev0)
- default.qubit.jax (PennyLane-0.29.0.dev0)
- default.qubit.tf (PennyLane-0.29.0.dev0)
- default.qubit.torch (PennyLane-0.29.0.dev0)
- default.qutrit (PennyLane-0.29.0.dev0)
- null.qubit (PennyLane-0.29.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.28.2)
- qiskit.aer (PennyLane-qiskit-0.29.0)
- qiskit.basicaer (PennyLane-qiskit-0.29.0)
- qiskit.ibmq (PennyLane-qiskit-0.29.0)
- qiskit.ibmq.circuit_runner (PennyLane-qiskit-0.29.0)
- qiskit.ibmq.sampler (PennyLane-qiskit-0.29.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by lillian542** [comment]
@dwierichs So, this is also true for comparing coefficients and comparing operators (they are hidden away on `ev.H.coeffs` and `ev.H.obs`, and are not checked at any point by `qml.equal`).

Comparing the operators is pretty straightforward, but I'm not quite sure what the best way is to go about comparing the callable coefficients. I can't think of a way to compare two different function objects aside from evaluating them and checking if they are the same. At how many time points do we want to confirm this? Are we happy with confirming that they match at the initial and final time? Do we want to compare them at time points in-between, and if so, how many?

Currently I'm thinking of sampling at the start and end times, as well as 3 timestamps in-between, and if they all match, I will declare them equal. But this is not very rigorous, and could return things as equal that are not. Any thoughts?

**Comment by dwierichs** [comment]
Oh, this is indeed a tough question! The approach in `qml.math.is_independent` could maybe be adapted, although I'm not quite sure it's similar enough... There we do an analytic and a numeric test to check whether a function is independent/constant of an argument. By looking at the difference of the coefficient functions between the two operators, and verifying that it is both constant and 0 at one point, we could implement the equality check :thinking:
