### ISSUE TITLE
qml.OrbitalRotation: inconsistent Jordan-Wigner ordering

### ISSUE THREAD

**Issue by StefanoPolla** [PennyLaneAI/pennylane#3854]
https://github.com/PennyLaneAI/pennylane/blob/941f41573ff1c86b9cc786485b700e7000a728a6/pennylane/ops/qubit/qchem_ops.py#L876

Most objects using the Jordan-Wigner transform in pennylane (e.g. `qml.qchem.spin2` and `qml.qchem.molecular_hamitlonian` default) assume the "spin interleaved" convention for mapping fermionic modes to qubits. This means two things:
1. The α-spin fermionic modes are mapped to even wires, the β to odd wires
2. The JW-strings are built following the order of the wires

The `qml.OrbitalRotation` operation tacitally breaks the second convention. While the mode-to-wire mapping is still (1.), the JW-strings are built based on the "α-then-β" convention, where all α-spin modes come first and all β-modes come after.
This produces counterintuitive and undocumented results, like in the example below (the 

```
#### example ####
import pennylane as qml
import numpy as np

n_electrons = 2
n_orbitals = 2
ref_state = qml.qchem.hf_state(n_electrons, 2*n_orbitals)
wires = np.arange(2*n_orbitals)
dev = qml.device('default.qubit', wires=len(wires))

@qml.qnode(dev)
def spin2_after_rotation(phi):
    qml.BasisEmbedding(ref_state, wires=wires)
    qml.OrbitalRotation(phi, wires=wires)
    return qml.expval(qml.qchem.spin2(n_electrons, n_orbitals))

print(spin2_after_rotation(1))
# outputs 0.6103008024514844
# it should instead output 0.0, as qml.OrbitalRotation is a spin-adapted rotation and it acts on a singlet state.
```

**Comment by obliviateandsurrender** [comment]
Hi Stefano! Thank you for pointing out this issue. The results indeed look counterintuitive, and after further discussion with one of the authors of the [paper](https://arxiv.org/abs/2104.05695) based on which we implemented the operation, it seems that the decomposition presented in their paper needs to be modified to make sure the second convention is not broken. I have already opened a #3861 to address this.
