### ISSUE TITLE
Assure that state preparations only happen at the beginning of a circuit

### ISSUE THREAD

**Issue by johannesjmeyer** [PennyLaneAI/pennylane#386]
Right now, state preparations, e.g. `QubitStateVector` and `BasisState`, can in principal be used everywhere in a circuit. That they are not used after an operation is checked in the plugins, resulting in code that is not very elegant: Usually, plugins track if apply was called the first time when a state preparation is applied.

I would suggest to move the check if the state preparations are the first operations in the circuit to the time of queuing. I think the most coherent way of doing this would be to add another subclass `StatePreparationOperation` of `Operation` along with the corresponding predicate. While queuing, one could then ensure that all state preparations in the graph have no incoming edges.

**Comment by smite** [comment]
Doesn't the `vis_check` feature in `qnode_new.qnode.QNode._construct` solve this issue, if we give state preparations no incoming edges when the DAG is built? 
This way the visibility check will raise an error if an Operation X is entirely shadowed by a state preparation (i.e. there is no directed path between X and an observable).

**Comment by johannesjmeyer** [comment]
That would work, yes. But this would require us to run the construct with `vis_check = True` for all QNodes, something we did not intend to do, because people might deliberately choose to have unused wires.

We could already raise an error at time the state preparation is queued, and this is what I think we should do.

**Comment by co9olguy** [comment]
Seems like the simplest solution is to just ensure that, when we see a state prep in the queue, check to ensure that none of its wires have been used yet by previous ops

**Comment by smite** [comment]
`vis_check` does not complain about unused wires, it only raises an error if it encounters invisible Operations.

One can certainly also enforce that state preps are the first Operations on each wire, either during the queuing or alternatively when the CircuitGraph is built.

However, eventually there might be valid use cases for using another state prep on a wire in the middle of the circuit, e.g.
```
S--A--|  S--|--M
S--B--|--C--|--M
```
where A, B, C are local gates, | represents a two-subsystem gate, S a state prep and M a measurement.

**Comment by co9olguy** [comment]
Allowing state preps in the middle of a circuit is certainly doable (and there are use-cases from a quantum information perspective). However, previous experience indicates that this is much more complex to maintain, so probably not worth it

**Comment by johannesjmeyer** [comment]
I think this is a very low-prio feature. If people want to do this they can just have more wires.

And I still think that vis_check is the wrong way to go, even if you can have empty wires. If people want to have lone PauliX gates that don't influence the result of the computation they should have them. I think we can build vis_check into a feature for circuit analysis and as such it will be really cool! Maybe one could also think of other features for this.

But for the state preps I'd simply check if they are the first ops on the wire.

**Comment by johannesjmeyer** [comment]
I propose to revive this. Now, with the CircuitGraph infrastructure in place this should be easy to do. I would like to implement this via an additional mixin `StatePreparation` that is used in e.g. `BasisStatePreparation` or `FockStatePreparation`. What do you think about this?

**Comment by co9olguy** [comment]
I'm not opposed. @josh146 any thoughts?

**Comment by josh146** [comment]
Go for it, as long as the existing operation names don't change (just the inheritance) I'm happy!

Note: @antalszava has also discussed this, and the thinking so far is that:

1. State preparations are validated when the circuit graph is constructed.

2. The `CircuitGraph.preparations` returns any state preparations in the graph

3. Potentially, `QubitDevice.execute` is modified so that state preparations occur before circuit operations are applied (but not 100% sure if this is necessary)

**Comment by josh146** [comment]
Closing this issue as this is now the behaviour of PennyLane in the new core. In fact, it is maybe _too_ zealous - multiple initial state preparations on different wires are not allowed, see #1140.
