### ISSUE TITLE
[BUG]ValueError: probabilities do not sum to 1

### ISSUE THREAD

**Issue by XiangGaofeng** [PennyLaneAI/pennylane#3894]
### Expected behavior

I think quantum circuits should output an expected value.

### Actual behavior

...... 
 File "mtrand.pyx", line 939, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1

### Additional information

"When I set shots to 1000 and generated a 3x3 random tensor, there was a bug in the result when I passed it into a quantum circuit using amplitude embedding. But when I generated a 1-dimensional column vector, the result could be output normally."

### Source code

```shell
import torch
import pennylane as qml
from pennylane import numpy as np

dev = qml.device('default.qubit', wires=4, shots = 1000)
@qml.qnode(dev, interface='torch')
def circuit(phi, train_params):
    
    # phi = phi.reshape(-1)
    qml.AmplitudeEmbedding(phi, wires=range(4), normalize=True, pad_with=0.0)
    
    qml.broadcast(qml.CNOT, wires=[0, 1, 2, 3], pattern="ring")
    
    
    for j in range(4):
        qml.RY(np.pi * train_params[ j], wires=j)
    
        # Measurement producing 1 classical output values
    return qml.expval(qml.PauliZ(0))
# 设置torch的随机数种子
torch.manual_seed(42)

# a = np.array([0.1, 0.3, 0.1, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
a = torch.rand(3,3)
print(a.shape)

b = np.array([0.1, 0.2, 0.3,0.4])

for _ in range(100):
    print(circuit(a,b))
```

### Tracebacks

```shell
warnings.warn(
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    print(circuit(a,b))
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/qnode.py", line 661, in __call__
    res = qml.execute(
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/interfaces/execution.py", line 443, in execute
    res = _execute(
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/interfaces/torch.py", line 248, in execute
    return ExecuteTapes.apply(kwargs, *parameters)
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/interfaces/torch.py", line 85, in forward
    res, ctx.jacs = ctx.execute_fn(ctx.tapes, **ctx.gradient_kwargs)
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/interfaces/execution.py", line 197, in wrapper
    res = fn(execution_tapes.values(), **kwargs)
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/interfaces/execution.py", line 122, in fn
    return original_fn(tapes, **kwargs)
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/_qubit_device.py", line 586, in batch_execute
    res = self.execute(circuit)
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/_qubit_device.py", line 319, in execute
    self._samples = self.generate_samples()
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/_qubit_device.py", line 1037, in generate_samples
    samples = self.sample_basis_states(number_of_states, rotated_prob)
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/_qubit_device.py", line 1065, in sample_basis_states
    [np.random.choice(basis_states, shots, p=prob) for prob in state_probability]
  File "/home/xianggaofeng/work/xgf/anaconda/envs/xgf_torch/lib/python3.8/site-packages/pennylane/_qubit_device.py", line 1065, in <listcomp>
    [np.random.choice(basis_states, shots, p=prob) for prob in state_probability]
  File "mtrand.pyx", line 939, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

### System information

```shell
- lightning.qubit (PennyLane-Lightning-0.26.1)
- default.gaussian (PennyLane-0.26.0)
- default.mixed (PennyLane-0.26.0)
- default.qubit (PennyLane-0.26.0)
- default.qubit.autograd (PennyLane-0.26.0)
- default.qubit.jax (PennyLane-0.26.0)
- default.qubit.tf (PennyLane-0.26.0)
- default.qubit.torch (PennyLane-0.26.0)
- default.qutrit (PennyLane-0.26.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by CatalinaAlbornoz** [comment]
Hi @XiangGaofeng,

This isn't really a bug. What happens here is that [qml.AmplitudeEmbedding](https://docs.pennylane.ai/en/stable/code/api/pennylane.AmplitudeEmbedding.html) expects your input tensor to have dimension `(2^len(wires),)` or less. In your case you should use `a = torch.rand(3,1)` in order to have the right dimensions. This should make your code run properly.

Please let us know if you still find errors or if you have any further questions 🙂 .

**Comment by timmysilv** [comment]
I took another look at this today, and I found that (although not mentioned in the docs), `qml.AmplitudeEmbedding` does in fact support batching so the second dimension to `torch.rand` is fine. However, the problem appears to come from using torch. Running your code, I see that `np.random.choice` fails with the sum being just shy of 1 (eg. 0.99999995), but shy enough that numpy is unhappy. If instead, I cast `a` to a numpy array before passing it to `circuit`, it works as expected! I don't yet know why using torch causes this issue, but I'm going to investigate further.

**Comment by XiangGaofeng** [comment]
> 我今天又看了一下，我发现（虽然文档中没有提到），实际上确实支持批处理，所以第二个维度很好。然而，问题似乎来自使用火炬。运行您的代码，我看到它失败了，总和只有 1 一点（例如 0.99999995），但害羞以至于 numpy 不高兴。相反，如果我在将它传递给 之前投射到 numpy 数组，它按预期工作！我还不知道为什么使用手电筒会导致这个问题，但我会进一步调查。`qml.AmplitudeEmbedding``torch.rand``np.random.choice``a``circuit`

This issue seems to be related to the shots value specified when initializing the quantum device. If shots is specified during initialization, using torch produces an error while numpy does not. On the other hand, if shots is not specified, both torch and numpy can run .

**Comment by timmysilv** [comment]
yep! the random sampling is only used when shots are provided, otherwise we compute the expectation value analytically.

The error you're seeing comes from a rounding error when normalizing the features (`phi`) provided to `AmplitudeEmbedding`. The global default tensor type for torch is `torch.float32`, which will cause this rounding error. If you instead do `a = torch.rand(3, 3, dtype=torch.float64)` (or [set the global default](https://pytorch.org/docs/stable/generated/torch.set_default_tensor_type.html)), you won't see this error anymore. Hope this helps!

**Comment by XiangGaofeng** [comment]
> yep! the random sampling is only used when shots are provided, otherwise we compute the expectation value analytically.
> 
> The error you're seeing comes from a rounding error when normalizing the features (`phi`) provided to `AmplitudeEmbedding`. The global default tensor type for torch is `torch.float32`, which will cause this rounding error. If you instead do `a = torch.rand(3, 3, dtype=torch.float64)` (or [set the global default](https://pytorch.org/docs/stable/generated/torch.set_default_tensor_type.html)), you won't see this error anymore. Hope this helps!

What is the implementation principle of Penny Lane's amplitude embedding? And what is the principle behind Penny Lane supporting batched data input for amplitude embedding? Can you provide relevant documentations?

**Comment by timmysilv** [comment]
You can find information on AmplitudeEmbedding [here](https://docs.pennylane.ai/en/stable/code/api/pennylane.AmplitudeEmbedding.html), and information on parameter broadcasting in QNodes [here](https://docs.pennylane.ai/en/stable/introduction/circuits.html#parameter-broadcasting-in-qnodes).

**Comment by XiangGaofeng** [comment]
> You can find information on AmplitudeEmbedding [here](https://docs.pennylane.ai/en/stable/code/api/pennylane.AmplitudeEmbedding.html), and information on parameter broadcasting in QNodes [here](https://docs.pennylane.ai/en/stable/introduction/circuits.html#parameter-broadcasting-in-qnodes).

Thanks！
