### ISSUE TITLE
qml.ctrl integer input 

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/pennylane#3949]
### Feature details

It would be great if `qml.ctrl` in the `control_values` attribute would accept an integer.
What I mean is that for example if we have that `control = [0,1,2,3,4]` and `control_values = 5`, internally I know to interpret that I am making reference that I want to apply the control if I have the state [0,0,1,0,1]. 
This would facilitate the implementation of QRAMs or algorithms such as LCU because you could easily do things such as:

```
    for i in range(4):
        qml.ctrl(qml.QubitUnitary, control = control_wires, control_values = i)(unitaries[i], wires = wires_A)

```

### Implementation

In `qml.BasisEmbedding` is already implemented -> [here](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/templates/embeddings/basis.py)

```
qml.BasisEmbedding([0,1,1], wires = [0,1,2]) 

qml.BasisEmbedding(3, wires = [0,1,2]) 
```

these two lines implement the same template

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by trbromley** [comment]
Thanks @KetpuntoG, let's close this for now - although it's a bit clunky, one current solution is:
```python
import numpy as np

map(int, list(np.binary_repr(5, width=5)))
```

**Comment by KetpuntoG** [comment]
If possible I would love to see this implemented at some point :)
It is more common than it may seem
