### ISSUE TITLE
Replace `retworkx` with `rustworkx` across package

### ISSUE THREAD

**Issue by mlxd** [PennyLaneAI/pennylane#3973]
### Feature details

As`retworkx` was renamed to `rustworkx` the package name is now locked-in. Currently dependencies on the old package name are causing issues for the Lightning conda builder, as the package is expected as `rustworkx`. Renaming all occurrences and dependenices on the new name would help with dependency resolution in this ecosystem.

### Implementation

Replace all occurrences of `retworkx` with `rustworkx`, inlcuding package dependencies and source code uses.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

This will help with maintenance of the conda releases for the Lightning packages across all architectures.

**Comment by albi3ro** [comment]
Closed by #3975
