### ISSUE TITLE
Provide an informative string representation for ParametrizedHamiltonian

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#4088]
### Feature details

PennyLane recently introduced the [`ParametrizedHamiltonian`](https://docs.pennylane.ai/en/stable/code/api/pennylane.pulse.ParametrizedHamiltonian.html) class. It allows users to define time-dependent parametrized Hamiltonians such as:
```python
import pennylane as qml

def f1(p, t):
    return p[0] * jnp.sin(p[1] * t)

def f2(p, t):
    return p * t

coeffs = [2., f1, f2]
observables =  [qml.PauliX(0), qml.PauliY(0), qml.PauliZ(0)]
H = qml.dot(coeffs, observables)
```
The `H` can be evaluated for specific parameters and time:
```python
p1 = jnp.array([1., 1.])
p2 = 1.
params = [p1, p2]
H(params, t=0.4)
```
What if we want to inspect `H` directly? Users [currently get](https://github.com/PennyLaneAI/pennylane/blob/6fe528951a1f3840859a8f45e460c97cdcd63359/pennylane/pulse/parametrized_hamiltonian.py#L242) the following:
```python
>>> H
ParametrizedHamiltonian: terms=3
```
This is not informative. Instead, we would like the representation of `H` to provide useful information to the user.

### Implementation

The string representation of `H` in the example above can look like the following:
```python
>>> H
(2.0*(PauliX(wires=[0]))) + ((f0(params_0, t)*(PauliY(wires=[0]))) + (f1(params_1, t)*(PauliZ(wires=[0]))))
```
- We want the output repr to closely follow what is used in operator arithmetic (e.g. [here](https://github.com/PennyLaneAI/pennylane/blob/6fe528951a1f3840859a8f45e460c97cdcd63359/pennylane/ops/op_math/composite.py#L79) and [here](https://github.com/PennyLaneAI/pennylane/blob/6fe528951a1f3840859a8f45e460c97cdcd63359/pennylane/ops/qubit/hamiltonian.py#L490))
- Given a function `my_func` that is at position `i` in the sum, the repr for that part should read `my_func(params_i, t)`
- Lambda functions will be a sticky point because we can't infer their name using `my_func.__name__`. In this case, we can keep it simple and use `lambda` as the name. We can also update the docs of `ParametrizedHamiltonian` (and similar places) to avoid recommending use of `lambda` (not a requirement for this issue).

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by Gopal-Dahale** [comment]
Hi @trbromley, I think this feature is nice to have and a quick implementation can close this issue. Can you assign it to me?

**Comment by anushkrishnav** [comment]
Hey, can you assign this issue? I have submitted a pull request for review.

**Comment by trbromley** [comment]
Hi @Gopal-Dahale and @anushkrishnav, welcome!

@anushkrishnav, thanks for opening a pull request! A member of the PennyLane development team will take a look and give feedback :ok_hand:

Feel free to post here if you have any questions, or check out our [development guide](https://docs.pennylane.ai/en/stable/development/guide.html)!

**Comment by anushkrishnav** [comment]
Can you assign the issue for the Unitary hack bot?

**Comment by trbromley** [comment]
Thanks @anushkrishnav for taking this on, and congrats on earning the bounty! :tada:

**Comment by anushkrishnav** [comment]
> Thanks @anushkrishnav for taking this on, and congrats on earning the bounty! tada

Thank you so much !

**Comment by trbromley** [comment]
Hi @anushkrishnav! As part of our 0.31 release, we're planning to promote UnitaryHack contributions to PennyLane on social media.

This is completely optional, but would you like to be mentioned in our social media posts? Specifically, we'd need either your Twitter profile, your LinkedIn profile, or your name.

**Comment by anushkrishnav** [comment]
> Hi @anushkrishnav! As part of our 0.31 release, we're planning to promote UnitaryHack contributions to PennyLane on social media.
> 
> This is completely optional, but would you like to be mentioned in our social media posts? Specifically, we'd need either your Twitter profile, your LinkedIn profile, or your name.
Sorry I had to deal with an emergency for the past week , just came back.
That would be great, if it's not too late ! 
You can use all the 3 if you wish to 
Name: Anush Krishna 
Twitter: https://twitter.com/Anush_krishna_v
Linkedln : https://www.linkedin.com/in/anush-krishna-v-8270941a0/
