### ISSUE TITLE
[BUG] Using BasisEmbedding raises an error when returning expectation values of multiple Hamiltonians

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#4119]
### Expected behavior

Execute the following code:
```python
import pennylane as qml
from pennylane import numpy as np

qubits = 2

H = qml.PauliX(0) @ qml.PauliY(1) + qml.PauliX(1)

@qml.qnode(qml.device('default.qubit', wires=qubits))
def circuit():
    qml.BasisEmbedding([1, 0], wires=range(qubits))
    return qml.expval(H), qml.expval(H)

circuit() 
```
The output should be:
```
(tensor(0., requires_grad=True), tensor(0., requires_grad=True))
```

### Actual behavior

The execution fails:
```
QuantumFunctionError: Only observables that are qubit-wise commuting Pauli words can be returned on the same wire, some of the following measurements do not commute:
[  (1) [X1]
+ (1) [X0 Y1],   (1) [X1]
+ (1) [X0 Y1]]
```

### Additional information

If you swap `BasisEmbedding` for `BasisState`, the circuit executes successfully.

### System information

```shell
Happens in PL 0.30 and in 0.31.0-dev
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by trbromley** [comment]
@Jaybsoni @soranjh

**Comment by Emieeel** [comment]
I was wondering whether there is any progress on this issue, as multiple useful functions I'm using have the same problem, like noise channels and UCCSD circuits.

**Comment by Jaybsoni** [comment]
Hi @Emieeel, 

Thanks for checking into this! I am working on a fix that should address this bug.

Cheers,
