### ISSUE TITLE
Update plugins in Docker builds

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#4123]
### Feature details

[Building of PennyLane images in Docker](https://docs.pennylane.ai/en/stable/development/guide/installation.html#docker) is supported, including [optional installation of the plugins](https://github.com/PennyLaneAI/pennylane/blob/b568abf5b89f97b5e77a7ecb71594afef9b1541d/docker/Makefile#L15). We would like to update the available plugins to:
- Remove [PL-SF](https://docs.pennylane.ai/projects/strawberryfields/en/latest/) because this is no longer supported in version 0.30 and above.
- Add the new [Quantum Inspire](https://pennylane-quantuminspire.readthedocs.io/en/latest/) plugin

### Implementation

The changes will occur in [install_plugin.sh](https://github.com/PennyLaneAI/pennylane/blob/master/docker/plugins/install-plugin.sh) and the [Makefile](https://github.com/PennyLaneAI/pennylane/blob/master/docker/Makefile).

Optionally, we would also like to update the [interface versions](https://github.com/PennyLaneAI/pennylane/blob/master/docker/interfaces/install-interface.sh) to match those [used in the CI](https://github.com/PennyLaneAI/pennylane/blob/master/.github/workflows/tests.yml).

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by manulpatel** [comment]
Hello @trbromley! I am new to Pennylane and would like to work on this issue. Could you please assign me?

**Comment by trbromley** [comment]
Hi @manulpatel! That's awesome, you can check out our [development guide](https://docs.pennylane.ai/en/stable/development/guide.html) or just post here if you have any questions. Good luck!

**Comment by timmysilv** [comment]
done and confirmed the bounty has been updated on the hackathon site! thanks for catching that.

**Comment by manulpatel** [comment]
Hello @trbromley! Yes I am fine with it (My [LinkedIn](https://www.linkedin.com/in/manul-patel/)). But I doubt my contribution isn't that big yet making myself worth enough to post on socials.

**Comment by trbromley** [comment]
Thanks @manulpatel! No problem - it's up to you, let us know if you'd rather not be mentioned.
