### ISSUE TITLE
Pre-built noise models

### ISSUE THREAD

**Issue by kshyatt-aws** [PennyLaneAI/pennylane#4170]
### Feature details

Would be great to provide some prepackaged noise models and tools for easily building custom models that could be applied to a circuit or quantum tape, similar to what Qiskit has in [Qiskit Terra](https://qiskit.org/documentation/tutorials/simulators/2_device_noise_simulation.html) and Braket with [`NoiseModel`](https://github.com/aws/amazon-braket-sdk-python/blob/main/src/braket/circuits/noise_model/noise_model.py). One could then apply the noise model to an entire tape so that (e.g.) every `CNot` gets the appropriate noise applied automatically.

### Implementation

Some kind of transform on top of an existing tape might work, something like:

```python
noisy_circ = qml.apply_noise(my_circ, noise_model)
```

or as an optional argument to `qnode`:

```python
@qml.qnode(dev, diff_method=diff_method, noise_model=noise_model)
```

Then, during tape processing, the noise model can be automatically applied to the circuit gates (semi-similar to measurement transforms like shadows).

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

Would be great to implement this in a way that makes it easy to translate back and forth to other providers like Qiskit or Braket -- having some member of `Circuit` or `QuantumTape` that can be probed for the noise model separately from the circuit gates would be very helpful.

**Comment by trbromley** [comment]
Thanks @kshyatt-aws, this is a great suggestion! For now, users looking to include basic noise in their circuit can use the [`qml.insert`](https://docs.pennylane.ai/en/stable/code/api/pennylane.transforms.insert.html) transform with the `default.mixed` device.

**Comment by trbromley** [comment]
@kshyatt-aws - we've made a lot of progress in this direction :tada:

- The [latest release added noise models](https://pennylane.ai/blog/2024/07/pennylane-release-0.37/#add-noise-models-to-your-quantum-circuits-)
- The next release will support [converting noise models from Qiskit](https://github.com/PennyLaneAI/pennylane/pull/5996)

I'll close this feature request for now, but please let us know if there is more functionality you'd like.
