### ISSUE TITLE
Support non-consecutive wire ordering in QNodes

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#423]
When working with physical hardware, it is useful to provision 'devices' with non-consecutive qubit numbers, for instance if a user has reserved a sub-lattice of a larger chip, and wants to ensure that multiple runs are executing on the same physical qubit.

Currently, PennyLane works only with consecutive wire numbering, so if a user has provisioned a lattice with qubits numbers 1, 4, 7, they will need to use the labelling 1, 2, 3, and have PennyLane translate under the hood.

It would be great to also add support for non-consecutive numbering - either defined by the user when creating the device, or provided by the device directly.

**Comment by msohaibalam** [comment]
As an example, Rigetti QPUs are shaped as connected octagons. When a user reserves e.g. 5 out of 8 qubits from an octagonal lattice, those 5 qubits are not necessarily qubits 0-4, but rather some connected subset of qubits and could be e.g. qubits 2-6. Currently, PennyLane would complain about having a qubit "6" on a 5q lattice.

Moreover, qubit numbers on Rigetti lattices also carry info about the particular octagons they reside on, and are numbered as <octagon-number><qubit-number 0-7>. E.g. on a 16q lattice, composed of two connected octagons, octagon 0 would carry the qubits 1..7, while octagon 1 would carry the qubits 11..17. And more generally, octagon n would carry the qubits n1..n7.

**Comment by smite** [comment]
I think this is nicely handled by remapping subsystems. A program/quantum func can act on qubits 0-3, for example, and when it is executed on a device the user can pass along an injective mapping, for example `{0:0, 1:4, 2:5, 3:6}`. Or indeed initialize the device with the mapping so every program executed on it will use that same mapping.

**Comment by josh146** [comment]
> Or indeed initialize the device with the mapping so every program executed on it will use that same mapping.

I'm thinking this might make more sense. This way, a particular device with a known qubit numbering can provide the mapping directly to the QNode. Perhaps via a class attribute?

```python
class SomeDevice(Device):
    wire_mapping = {0:0, 1:4, 2:5, 3:6}
```

The wire mapping can also be determined programmatically if supported by the target framework.

**Comment by trbromley** [comment]
This would be a great feature to add!

**Comment by josh146** [comment]
Closed as this should now be possible with the wires refactor 🙂

**Comment by co9olguy** [comment]
:champagne:
