### ISSUE TITLE
[BUG]Density matrix cannot be used in QNN.

### ISSUE THREAD

**Issue by Pride-Huang** [PennyLaneAI/pennylane#4236]
### Expected behavior

I want to use the density to in QNN,  and learn the parameters of the QNN. The main code as follow:
![code](https://github.com/PennyLaneAI/pennylane/assets/34713001/c3ed399c-deb7-4cdc-8704-2898d6ac14a4)
About the optimizer, it is written as:

opt = NesterovMomentumOptimizer(0.01)

weights, _, _, _ = opt.step(cost, weights, gamma, X_batch, Y_batch)

### Actual behavior

[BUG]I try to measure the density matrix, and utilize it in QNN. However, the code cannot run, and the error is "TypeError: Grad only applies to real scalar-output functions. Try jacobian, elementwise_grad or holomorphic_grad."
![1686401811920](https://github.com/PennyLaneAI/pennylane/assets/34713001/9fb93b90-62ce-4b91-b672-3d348020883f)

### System information

```shell
Name: PennyLane
Version: 0.23.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /root/anaconda3/envs/QSSL/lib/python3.9/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning, PennyLane-Lightning-GPU

Platform info:           Linux-4.18.0-348.2.1.el8_5.x86_64-x86_64-with-glibc2.27
Python version:          3.9.0
Numpy version:           1.24.3
Scipy version:           1.10.1
Installed devices:
- default.gaussian (PennyLane-0.23.0)
- default.mixed (PennyLane-0.23.0)
- default.qubit (PennyLane-0.23.0)
- default.qubit.autograd (PennyLane-0.23.0)
- default.qubit.jax (PennyLane-0.23.0)
- default.qubit.tf (PennyLane-0.23.0)
- default.qubit.torch (PennyLane-0.23.0)
- lightning.qubit (PennyLane-Lightning-0.28.0)
- lightning.gpu (PennyLane-Lightning-GPU-0.28.1)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by frederikwilde** [comment]
Hi @Pride-Huang, the gradient is only defined for functions with scalar output. But your function outputs the entire density matrix, hence what you encounter is definitely not a bug. You will need to compute the Jacobian in your optimizer. Note that your optimizer probably also expects a scalar-output cost function, just as `qml.grad` does.

For usage questions regarding PennyLane, please refer to our [discussion forum](https://discuss.pennylane).

**Comment by Pride-Huang** [comment]
OK, I see it. But I still want the method to use density matrix in my QNN. It is really helpful if you can give me any advices in detail.
