### ISSUE TITLE
[BUG] Clarify `wires` arguments of `qinfo.fidelity`

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#4318]
### Feature details

The [documentation on `qml.qinfo.fidelity`](https://docs.pennylane.ai/en/stable/code/api/pennylane.qinfo.transforms.fidelity.html) could be clearer about what the wires arguments do: They actually are to be read as indices into the sorted list of device wires, rather than wire labels. The docstring examples only ever use canonical wire labels `[0, 1, ..]` and provide `[0]` to the wires arguments of `fidelity`, such that this subtlety goes unnoticed in the docs.

**edit:** Other functions are affected by this discrepancy between wire indices and wire labels:
- `qinfo.fidelity`, `qinfo.reduced_dm`, `qinfo.vn_entropy`, `qinfo.mutual_info`, `qinfo.relative_entropy` raise an error when passed wire labels
- `qinfo.purity` uses wrong wires. It is not possible to compute the purity w.r.t, say, a string-labeled qubit. Importantly, no error is raised in this case.

Users may expect the following code to work:
```python
dev = qml.device("default.qubit", wires=[0, "a", 12])

@qml.qnode(dev)
def circuit0(x):
    qml.RX(x, 0)
    return qml.state()

@qml.qnode(dev)
def circuit1(x):
    qml.RX(x, "a")
    return qml.state()

x = np.array(1.3)
qml.qinfo.fidelity(circuit0, circuit1, [0], ["a"])((x,), (x,)) # raises an error
qml.qinfo.reduced_dm(circuit1, ["a"])((x,), (x,)) # raises an error
qml.qinfo.vn_entropy(circuit, wires=["a"])(x) # raises an error
qml.qinfo.mutual_info(circuit0, [0], [12])(x) # raises an error, already because of the _existence_ of a custom label
qml.qinfo.relative_entropy(circuit0, circuit1, [0], ["a"])((x,), (x,)) # raises an error
```

Likewise, users may try to compute a purity w.r.t a custom-labeled qubit:
```python
dev = qml.device("default.mixed", wires=[0, "a", 12])

@qml.qnode(dev)
def circuit(x):
    qml.DepolarizingChannel(x, "a")
    return qml.state()

x = np.array(0.2)

qml.qinfo.purity(circuit, wires=["a"])(x) # returns 1, which is incorrect, interpreting `wires` as labels
qml.qinfo.purity(circuit, wires=[1])(x) # returns 1, which is incorrect, interpreting `wires` as indices into the labels
```

### Implementation

I would suggest that we either clarify the documentation about this, or even better change the implementation itself, so that the `wires0` and `wires1` arguments refer to device wire _labels_ and are mapped to wire indices within `fidelity`. This way, users that are using canonical wires will not notice any change, and users that are using advanced wire labels can use those in the arguments of the qinfo functions, instead of having to find their indices manually.
In the case of `purity` we need to change the behaviour for sure if we want to make it work with custom labels.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

A test in `tests/qinfo/test_fidelity.py` that was supposed to test this actually does not use the wire argument that it is parametrized over. Activating that parametrization unveils this "bug".

**Comment by albi3ro** [comment]
I would actually call this a bug.

**Comment by eddddddy** [comment]
Yep, these transforms were always meant to take in indices, not wire labels. In `pennylane/math/quantum.py` this argument is rightfully named `indices` instead of `wires`, but the transforms don't take on this naming.

I'd say for now it's better to add documentation that clarifies this behaviour, and maybe include some fail-fast validation checks in the transforms. In the long run (as an enhancement), we can think about supporting custom wire labels.

**Comment by albi3ro** [comment]
So in `math`, we don't have access to the device or the `QuantumTape`, so they only "wire order" we have is indices in the state.

For transforms on a `QNode`, we have a wire order. We should use it.

For all of the "single qnode" qinfo transformations, we should actually reformulate them with the new transforms decorator.

**Comment by dwierichs** [comment]
I don't have a strong preference here, but would lean towards making use of the information we have and following @albi3ro's suggestion. Reformulating them in the new abstraction sounds good :)

The only really sensitive case in my opinion is `purity`, which will actually silently output wrong results in contrast to the other transforms that will raise an error.
