### ISSUE TITLE
[BUG] `validate_and_expand_adjoint` does not handle new parameters correctly

### ISSUE THREAD

**Issue by timmysilv** [PennyLaneAI/pennylane#4351]
### Expected behavior

`expanded_tape.trainable_parameters` is preserved from the original tape, but set correctly with new parameters

### Actual behavior

If expansion adds parameters, the new trainable indices do not account for it. In the code example provided, the `QubitUnitary` has one parameter, but it gets decomposed via ZYZ decomposition. This replaces the one parameter (the unitary matrix) with 3 (the 3 rotations). The original trainable parameter was `[1]`, indicating the `x` tensor passed to `RX`, but after expansion it should be `[3]`.

### Source code

```shell
import pennylane as qml
from pennylane import numpy as np
from pennylane.devices.qubit.preprocess import validate_and_expand_adjoint

U = np.array([[0, 1], [1, 0]])
x = np.array(0.1)

qs = qml.tape.QuantumScript([qml.QubitUnitary(U, 0), qml.RX(x, 0)])
qs.trainable_params = [1]
expanded = validate_and_expand_adjoint(qs)
# trainable_params is [1] here, but it should be [3]
print(expanded.trainable_params, expanded.get_parameters(trainable_only=False))
```

### System information

```shell
pl dev
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
@timmysilv  can we consider this closed by #4365 ?
