### ISSUE TITLE
[BUG] qspin quantum datasets return same data for both open and closed boundary conditions

### ISSUE THREAD

**Issue by knottyanyon** [PennyLaneAI/pennylane#4390]
### Expected behavior

Input:

> ```
> data_tfim = qml.data.load("qspin", sysname="Ising", periodicity="closed", lattice="chain", layout='1x4')[0]
> 
> for term in data_tfim.hamiltonians:
>     print(term)
>     print(' ')
> ```

Output:

> ```
> (0.0) [X0]
> + (0.0) [X1]
> + (0.0) [X2]
> + (0.0) [X3]
> + (-1) [Z0 Z1]
> + (-1) [Z1 Z2]
> + (-1) [Z2 Z3]
> + (-1) [Z3 Z0]
> ```

### Actual behavior

> ```
> data_tfim = qml.data.load("qspin", sysname="Ising", periodicity="closed", lattice="chain", layout='1x4')[0]
> 
> for term in data_tfim.hamiltonians:
>     print(term)
>     print(' ')
> ```

Output:

> ```
> (0.0) [X0]
> + (0.0) [X1]
> + (0.0) [X2]
> + (0.0) [X3]
> + (-1) [Z0 Z1]
> + (-1) [Z1 Z2]
> + (-1) [Z2 Z3]
> ```

### Additional information

The open boundary condition datasets returned are same for both closed and open chains. (Checked for TFIM and XXZ). 

### System information

```shell
Name: PennyLane
Version: 0.31.0
Location: /Users/________/.pyenv/versions/pennylane_venv/lib/python3.11/site-packages

Platform info:           macOS-13.4.1-arm64-arm-64bit
Python version:          3.11.4
Numpy version:           1.23.5
Scipy version:           1.10.0
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by ikurecic** [comment]
Hi @umbrellabike , thanks a lot for spotting this and sending us a bug report! I'll follow up with the team and let you know as soon as this is fixed. 🙂

**Comment by obliviateandsurrender** [comment]
Hey @umbrellabike, thanks for pointing this out! Hopefully, this should be fixed now. You may try deleting any old existing data for the mentioned systems and retry downloading them again. 
![image](https://github.com/PennyLaneAI/pennylane/assets/23234279/98c1c2c2-27ac-44cb-ac7a-7404e5e63a44)
