### ISSUE TITLE
Decomposition of multi-controlled RZ not supported[BUG]

### ISSUE THREAD

**Issue by jsmallz333** [PennyLaneAI/pennylane#4473]
### Expected behavior

Should be able to decompose a multi-controlled RZ gate:

```python
import pennylane as qml
dev = qml.device("default.qubit", wires=[0,1,2])
decomposition = qml.ctrl(qml.RZ(0, wires=[0]), control=[1,2]).decomposition()
@qml.qnode(dev)
def my_circuit():
    for op in decomposition:
        qml.apply(op)
    return qml.state()
qml.draw(my_circuit)()
```

this should be akin to how one can decompose a multi-controlled PauliX, eg:
```python
dev = qml.device("default.qubit", wires=[0,1,2])
decomposition = qml.ctrl(qml.PauliX(wires=[0]), control=[1,2]).decomposition()
@qml.qnode(dev)
def my_circuit():
    for op in decomposition:
        qml.apply(op)
    return qml.state()
qml.draw(my_circuit)()
```

### Actual behavior

A `DecompositionUndefinedError` is raised

### Additional information

This causes errors with various plug-in devices, eg the ionq or qiskit simulators, see:
```python
@qml.qnode(qml.device('ionq.simulator', wires=3,shots=10))
def my_circuit():
    qml.ctrl(qml.RZ(0,wires=[0]),control=[1,2])
    return qml.expval(qml.PauliZ(wires=0))
my_circuit()
```

Seems that this backs up to the base operation not having a decomposition in `_decompose_no_control_values` of `qml.ops.op_math.controlled.py` (though commented out lines 591-600 seem to get near to this). Should be able to add something like the following below line 586 of `controlled.py`:
```python
if isinstance(op.base, qml.RZ):
    return [qml.RZ(phi=op.data[0]/2,wires=op.target_wires), qml.MultiControlledX(wires=op.active_wires, work_wires=op.work_wires),qml.RZ(phi=-1*op.data[0]/2,wires=op.target_wires), qml.MultiControlledX(wires=op.active_wires, work_wires=op.work_wires)]
```
Can do something similar for a mulitcontrolled-RY and from there, via a ZYZ decomposition, should be able to implement multicontrolled versions of all 1 qubit unitaries

### Tracebacks

```shell
DecompositionUndefinedError               Traceback (most recent call last)
Cell In[54], line 3
      1 dev = qml.device("default.qubit", wires=[0,1,2])
----> 3 decomposition = qml.ctrl(qml.RZ(0, wires=[0]), control=[1,2]).decomposition()
      5 @qml.qnode(dev)
      6 def my_circuit():
      7     for op in decomposition:

File /opt/homebrew/Caskroom/miniconda/base/envs/penny/lib/python3.8/site-packages/pennylane/ops/op_math/controlled.py:497, in Controlled.decomposition(self)
    495     decomp = _decompose_no_control_values(self)
    496     if decomp is None:
--> 497         raise qml.operation.DecompositionUndefinedError
    498     return decomp
    500 # We need to add paulis to flip some control wires

DecompositionUndefinedError:
```

### System information

```shell
Name: PennyLane
Version: 0.31.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /opt/homebrew/Caskroom/miniconda/base/envs/penny/lib/python3.8/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml
Required-by: PennyLane-IonQ, PennyLane-Lightning, PennyLane-qiskit

Platform info:           macOS-13.3.1-arm64-arm-64bit
Python version:          3.8.17
Numpy version:           1.23.5
Scipy version:           1.10.0
Installed devices:
- default.gaussian (PennyLane-0.31.0)
- default.mixed (PennyLane-0.31.0)
- default.qubit (PennyLane-0.31.0)
- default.qubit.autograd (PennyLane-0.31.0)
- default.qubit.jax (PennyLane-0.31.0)
- default.qubit.tf (PennyLane-0.31.0)
- default.qubit.torch (PennyLane-0.31.0)
- default.qutrit (PennyLane-0.31.0)
- null.qubit (PennyLane-0.31.0)
- ionq.qpu (PennyLane-IonQ-0.28.0)
- ionq.simulator (PennyLane-IonQ-0.28.0)
- lightning.qubit (PennyLane-Lightning-0.31.0)
- qiskit.aer (PennyLane-qiskit-0.31.0)
- qiskit.basicaer (PennyLane-qiskit-0.31.0)
- qiskit.ibmq (PennyLane-qiskit-0.31.0)
- qiskit.ibmq.circuit_runner (PennyLane-qiskit-0.31.0)
- qiskit.ibmq.sampler (PennyLane-qiskit-0.31.0)
- qiskit.remote (PennyLane-qiskit-0.31.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by isaacdevlugt** [comment]
Hey @jsmallz333, thanks! Looks like one of our devs (@albi3ro) has this on their radar 📡. We will stay in touch here when updates are made 👍

**Comment by albi3ro** [comment]
We currently have two specialized decompositions for single qubit targets with any number of control wires:

* [`qml.ops.op_math.ctrl_decomp_zyz`](https://docs.pennylane.ai/en/stable/code/api/pennylane.ops.op_math.ctrl_decomp_zyz.html)
* [`qml.ops.op_math.ctrl_decomp_bisect`](https://docs.pennylane.ai/en/stable/code/api/pennylane.ops.op_math.ctrl_decomp_bisect.html)

Unfortunately, both of those decompositions rely on the target operation being special unitary, not just unitary. We removed them from the default pathway because they were mistakenly being called on operations that were not `SU(2)`. I'm looking at adding them back in for `SU(2)` operations, but until then, either of those operations can be manually called.

**Comment by jsmallz333** [comment]
Okay, I follow how these can be manually called, I had this issue pop up with an operation that itself was calling a ctrl on an RZ, ie PCPhase as in: 
```python
@qml.qnode(qml.device("qiskit.aer", wires=[0,1,2]))
def my_circuit():
    qml.PCPhase(0, dim=2, wires=[0,1,2])
    return qml.state()
my_circuit()
```
I suggested a solution towards remedying this without a custom PCPhase.

**Comment by CatalinaAlbornoz** [comment]
Thanks for adding your thoughts here @jsmallz333 ! We are currently adding a `GlobalPhase` operation that will help with this problem, but right now neither the WIP Global Phase nor the SProd are integrated with our devices. I would recommend using your own workaround in the meantime but stay tuned for future releases when we might include full support for this.
