### ISSUE TITLE
Test edge cases for the eigenvalues returned by Tensor

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#460]
Certain edge cases might cause errors for returning eigenvalues for a ``Tensor`` when using ``Hermitian`` ([see the following TODO in the related PR](https://github.com/XanaduAI/pennylane/blob/c3120a547bc9cd6bd287849ef065d54d309bd3e5/pennylane/operation.py#L803)).

It would be nice to have these cases covered as well by the logic.

**Comment by josh146** [comment]
@antalszava, I believe this bug can be closed for the same reason that #591 was closed, but I might just confirm first with @mariaschuld
