### ISSUE TITLE
[BUG] Thermal Relaxation Channel Not Physical

### ISSUE THREAD

**Issue by onurdanaci** [PennyLaneAI/pennylane#4630]
### Expected behavior

Kraus representation of the Thermal Relaxation Channel to be physical such that probabilities add up to unity, and the trace after the channel implementation is also unity.

### Actual behavior

In the T2 \leq T1 probabilities don't even add upto unity. sqrt(pr0) and sqrt(pr1) of the Kraus operators need to be replaced with sqrt(pr0/2) and sqrt(pr1/2).

It's great that for the T2> T1 case you gave the Kraus operators of the Choi matrix by analytically computing the eigen decomposition, and writing them in column major order. But this only works when all the physical parameters of the Choi matrix makes the matrix Hermitian (non-negative eigvals). For the negative eigvals, singular value decomposition needs to be computed instead.

### System information

```shell
Irrelevant
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by CatalinaAlbornoz** [comment]
Hi @onurdanaci, thank you for opening this issue! We will look into it.

**Comment by lillian542** [comment]
Hi @onurdanaci! Thanks for reporting this. Could you be more specific about an example where you are seeing probabilities that don't add to unity for T2 < T1? When I test this, I see:

```
>>> t1 = 10e-6
>>> t2 = 6e-6

>>> krauss_operators = qml.ThermalRelaxationError.compute_kraus_matrices(0.17, t1, t2, 1e-6)
>>> sum([K.conj().transpose() @ K for K in krauss_operators])
array([[1., 0.],
       [0., 1.]])
```

**Comment by lillian542** [comment]
Hi @onurdanaci - I just wanted to follow up. It would be great to get more details so we can offer support with the problem you’re seeing!

**Comment by lillian542** [comment]
Hi @onurdanaci! Thanks again for your feedback. We haven't been able to replicate this issue, so I'm going to close this for now, but please let us know if you have any further problems.
