### ISSUE TITLE
Adding `AQFT` operation

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/pennylane#4641]
### Feature details

# Context

The goal is to build the AQFT (Approximate Quatum Fourier Transform) operation in Pennylane.
This is an approach that reduces the number of `ControlledPhaseShift` operations we need to implement QFT.
Example:

`qml.AQFT(order = 3, wires = range(6))`

<img width="702" alt="Captura de pantalla 2023-10-02 a las 14 54 29" src="https://github.com/PennyLaneAI/pennylane/assets/65235481/a10cc35d-aadf-4023-a4ea-ced60eb065e8">

As we can see, instead of performing all the controls up to the last qubit, we are bounding by `order = 3`.
Note that to complete this operator with the PennyLane standard , the final Swap gates should be added.

# Steps to take

## Add the operator

- Create the file  `aqft.py` in `pennylane/pennylane/templates/subroutines`.
- Create the AQFT class and define the operator.
- Complete its docstring in a similar fashion as for other operations. Make sure the class is accessible through `qml.AQFT`.

## Testing

- Create tests in `pennylane/tests/templates/test_subroutines/test_aqft.py`

# Notes

- Note that in different programming frameworks the order of the wires is different. Make sure you are following the same scheme as our `qml.QFT`.

![Captura de pantalla 2023-10-02 a las 14 51 47](https://github.com/PennyLaneAI/pennylane/assets/65235481/275dc4bd-c605-4941-ae1a-2a2a809ddaee)

- In case `order` is not an integer number it will be approximated by the nearest valid element and a warning will be shown. If it is also greater or equal to the number of wires, `order = num_wires` will be used and the use of `qml.QFT` will be recommended (they would be equivalent).

### Implementation

To implement it, use the [`qml.QFT` class](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/templates/subroutines/qft.py) to help you.
You will find two main differences:
- In this case it will not be necessary the method `compute_matrix`.
- This operator supports an `order` parameter (which will be mandatory) indicating the depth of the approach.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by KetpuntoG** [comment]
Awesome! Thanks @ankit27kh 
Eager to see progress in this operation :)

**Comment by ankit27kh** [comment]
Hi @KetpuntoG, you mentioned:

> If it is also greater or equal to the number of wires, order = num_wires will be used and the use of qml.QFT will be recommended (they would be equivalent).

but shouldn't `order=n-1` already equal QFT for `n` wires?
i think there can be different cases:
`order<0` raise error
`order=0` H gates
`0<order<n-1` aqft
`order>=n-1` qft

**Comment by KetpuntoG** [comment]
You are right @ankit27kh 
It make sense what you comment 😊
