### ISSUE TITLE
[BUG] Could not install PennyLane-Lightning-GPU using `pip install pennylane-lightning[gpu]`

### ISSUE THREAD

**Issue by derange-alembic** [PennyLaneAI/pennylane#4665]
### Expected behavior

Running `pip install pennylane-lightning[gpu]` and get `lightning.gpu` installed.

### Actual behavior

When installing through pip:
`Requirement already satisfied: pennylane-lightning[gpu] in /home/cuquantum/conda/envs/cuquantum-23.06/lib/python3.9/site-packages (0.32.0)
WARNING: pennylane-lightning 0.32.0 does not provide the extra 'gpu'`

When running `dev = qml.device("lightning.gpu", wires=nq, batch_obs=True)` in Python script:
`pennylane._device.DeviceError: Device lightning.gpu does not exist. Make sure the required plugin is installed.`

### Additional information

I have to install through `pip install PennyLane-Lightning-GPU` and it works.

### Source code

```shell
pip install pennylane-lightning[gpu]
```

### Tracebacks

```shell
Requirement already satisfied: pennylane-lightning[gpu] in /home/cuquantum/conda/envs/cuquantum-23.06/lib/python3.9/site-packages (0.32.0)
WARNING: pennylane-lightning 0.32.0 does not provide the extra 'gpu'
```

### System information

```shell
Below actually shows the system info after I installed the gpu plugin with `pip install PennyLane-Lightning-GPU`

----------

Name: PennyLane
Version: 0.32.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author:
Author-email:
License: Apache License 2.0
Location: /home/cuquantum/conda/envs/cuquantum-23.06/lib/python3.9/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane-Lightning, PennyLane-Lightning-GPU

Platform info:           Linux-5.15.0-84-generic-x86_64-with-glibc2.31
Python version:          3.9.16
Numpy version:           1.23.5
Scipy version:           1.11.1
Installed devices:
- default.gaussian (PennyLane-0.32.0)
- default.mixed (PennyLane-0.32.0)
- default.qubit (PennyLane-0.32.0)
- default.qubit.autograd (PennyLane-0.32.0)
- default.qubit.jax (PennyLane-0.32.0)
- default.qubit.tf (PennyLane-0.32.0)
- default.qubit.torch (PennyLane-0.32.0)
- default.qutrit (PennyLane-0.32.0)
- null.qubit (PennyLane-0.32.0)
- lightning.gpu (PennyLane-Lightning-GPU-0.32.0)
- lightning.qubit (PennyLane-Lightning-0.32.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by mlxd** [comment]
Hi @derange-alembic 

Thanks for reporting this. We have an attached PR that will rectify this, which will be resolved with our next release of PennyLane. For now, we can suggest using `pip install pennylane-lightning-gpu` to explicitly install the package.
