### ISSUE TITLE
Different drawing for templates with controls

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/pennylane#4770]
### Feature details

We are starting to have operators that have qubits where only controls are used. It would be great if the drawer could distinguish that and take it into account when painting. An example of this is the `Select` or `ControlledSequence` operator.
Perhaps the best way to do it would be something like this:

<img width="737" alt="Captura de pantalla 2023-11-01 a las 15 05 39" src="https://github.com/PennyLaneAI/pennylane/assets/65235481/4326780f-2be8-402b-a065-b5f0a225fbd2">

A small ball in which half is white and half is black to indicate that they are not normal controls, simply indicating that there are control operations. 

### Implementation

Stepan and Jay worked on something similar some time ago. It would be good to check with them

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by trbromley** [comment]
Thanks @KetpuntoG! @DSGuala I remember we were thinking along these lines for `Select` but ran into issues, do you remember what it was?

**Comment by timmysilv** [comment]
hi @KetpuntoG, thanks for opening this issue! we don't have any imminent plans to implement this, so I'm going to close this one. That said, we're gonna track it on our side and try to get to it somewhere down the line
