### ISSUE TITLE
Implement XZX one qubit decomposition

### ISSUE THREAD

**Issue by Alex-Preciado** [PennyLaneAI/pennylane#4826]
### Important Note

⚠️ This issue is part of an internal assignment and not meant for external contributors.

### Details

One can decompose a 1-qubit gate as:

$$U=e^{i \gamma} R_X(\phi) R_Z(\theta) R_X(\lambda)$$

We'd like to add a new decomposition which breaks down a gate according to this relationship.

### Implementation

A function should be added to the file `pennylane/transforms/decompositions/single_qubit_unitary.py` and follow the same format used for other decompositions already implemented there. See for example:

https://github.com/PennyLaneAI/pennylane/blob/677fbe00f70e8456dacd5b0c4e9a46923036eeca/pennylane/transforms/decompositions/single_qubit_unitary.py#L264

Once implemented, the new decomposition should be added to:

https://github.com/PennyLaneAI/pennylane/blob/677fbe00f70e8456dacd5b0c4e9a46923036eeca/pennylane/transforms/decompositions/single_qubit_unitary.py#L331

as one of the available decompositions (and making sure docstrings are also updated).

### Requirements

A PR must satisfy the following:

- Make sure the function is tested for autograd, tensorflow, pytorch, jax and jax-jit.
- The tests should also use some analytical results in order to make sure the decomposition is correct. 
- Add a test class `TestQubitUnitaryXZXDecomposition` to the test folder: `tests/transforms/test_decompositions.py`.
- Pass black and pylint checks
- include a changelog entry under "Improvements"

**Comment by Alex-Preciado** [comment]
@astralcai Please note that we have made an adjustment to this issue. The problem now requires implementing the `XZX` decomposition. We have adjusted the mathematical expression and title of this issue accordingly. Please let me know if you have any questions.

**Comment by astralcai** [comment]
> @astralcai Please note that we have made an adjustment to this issue. The problem now requires implementing the `XZX` decomposition. We have adjusted the mathematical expression and title of this issue accordingly. Please let me know if you have any questions.

Thank you for letting me know! I will move on to implement the XZX decomposition instead.

**Comment by trbromley** [comment]
@Alex-Preciado, shall we close this issue now that #4862 is merged?

**Comment by rmoyard** [comment]
Yes this can be closed :+1:
