### ISSUE TITLE
[BUG] Equal does not work with symmetry of control wires

### ISSUE THREAD

**Issue by rmoyard** [PennyLaneAI/pennylane#4842]
### Expected behavior

By reviewing the code for the equal method of ``ControlledSequence`` I have found that the equal function has a bug  for ``Controlled`` . It does not take into account that operations are symmetric over control wires. We should compare the set of wires,  the order of control wires should not matter if control values are all the same.

```
base1 = qml.PauliX(wires=0)
base2 = qml.PauliX(wires=0)

op1 = qml.ops.op_math.Controlled(base1, control_wires=[1, 2])
op2 = qml.ops.op_math.Controlled(base2, control_wires=[2, 1])
print(qml.equal(op1, op2))
False #it should be true
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
I think this does bring up a question about the role and scope of `qml.equal`. 

Historically, it has been more of:

> The qml.equal function is based on a comparison of the type and attributes of the measurement or operator, not a mathematical representation.

But where do we draw that line? We already compare tensors and hamiltonians after simplification, and we sort sums and products before comparison.  

If we considered `qml.ctrl(qml.PauliX(0), wires=(1,2))` and `qml.ctrl(qml.PauliX(0), wires=(2,1))`  the same, would we also need to treat `IsingXX(1.2, wires=(0,1))` and `IsingXX(1.2, wires=(1,0))` the same? How about `qml.RX(1.2, wires=0)` and `RX(1.2 + 4*np.pi, wires=0)`?

**Comment by trbromley** [comment]
@rmoyard is this blocking the `ControlledSequence` PR?

**Comment by rmoyard** [comment]
@trbromley No not at all, for `ControlSequence` it makes sense because the order of the control wire matters

**Comment by rmoyard** [comment]
I think when a simple comparison is available we should add it, for example here compare the set instead of the list of control wires offers supports for controlled operation. We could use `pennylane/ops/qubit/attributes.py` to identify what is easy to check (symmetry mainly).
