### ISSUE TITLE
Add support for arbitrary measurements to `Snapshot`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#4876]
### Important Note

⚠️ This issue is part of an internal assignment and not meant for external contributors.

### Context

PennyLane currently has the `qml.Snapshot` operation that works in conjunction with the `qml.snapshots` transform to allow users to inspect the state at any point in a calculation. But, the state can be hard to interpret and analyze for larger numbers of qubits, limiting its utility in sanity checks and debugging.

To fix this, we want to support arbitrary state-based measurements with snapshots. This should look like:

```python
dev = qml.device('default.qubit')

@qml.qnode(dev)
def circuit(x):
    for _ in range(5):
        qml.Snapshot(measurement=qml.expval(qml.PauliZ(0))
        qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

qml.snapshots(circuit)(0.1)
```
```
{0: tensor(1., requires_grad=True),
1: tensor(0.99500417, requires_grad=True),
2: tensor(0.98006658, requires_grad=True),
3: tensor(0.95533649, requires_grad=True),
4: tensor(0.92106099, requires_grad=True),
"execution_results": tensor(0.87758256, requires_grad=True)}
```

### Implementation

The task would involve two main steps:

1) Adding a `measurement` keyword argument to `Snapshot`. This value should default to `None` and be stored in the `hyperparameters` property under `measurement`. The `measurement` should be validated to only be instances of `qml.measurements.StateMeasurement`.
2) Handling a measurement in the `apply_snapshot` kernel. The `qml.devices.qubit.measure` function is capable of performing any measurement on a state. The output of the measurement should be stored into `debugger.snapshots` at either the tag or an incremented integer.

In addition to these code changes, 

* The examples in `Snapshot` and `qml.snpashots` should be updated to showcase the use of the `measurements` keyword
* Relevant tests should be added to [test_debugging.py](https://github.com/PennyLaneAI/pennylane/blob/master/tests/test_debugging.py)
* A Changelog entry should be added to [the changelog](https://github.com/PennyLaneAI/pennylane/blob/master/doc/releases/changelog-dev.md) under "Improvements"

### Relevant Files:

* [`pennylane/ops/meta.py`]( https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/ops/meta.py). Contains the `Snapshot` operation

* [`pennylane/devices/qubit.py`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/devices/qubit/apply_operation.py). Contains the `apply_operation` function used by `default.qubit`.  Of particular note is the [`apply_snapshot`](https://github.com/PennyLaneAI/pennylane/blob/34aba1216116dca37fed5afde7cb41d820a042b9/pennylane/devices/qubit/apply_operation.py#L319) function that handles any snapshot operations

* [`pennylane/qubit/measure.py`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/devices/qubit/measure.py) contains the `measure` function capable of applying any state-based measurement process to state

* [`pennylane/qubit/debugging.py`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/debugging.py) contains the `snapshots` transform and the debugger class.

**Comment by JuanGiraldo0212** [comment]
Hi team, is there a convention on how to write ValueError messages? For the case if the measurement is not a StateMeasurement is it ok to have this message?

`raise ValueError(
                f"The measurement {measurement.__class__.__name__} is not supported as it is not "
                f"an instance of {qml.measurements.StateMeasurement}"
            )`

Let me know if I should change it. 

Thanks!

**Comment by albi3ro** [comment]
Thanks for asking your questions @JuanGiraldo0212  .

Sorry about forgetting to explain the queuing part. If a measurement is provided, we should remove the measurement from the queue.  This can be done with:

```
qml.queuing.QueuingManager.remove(measurement)
```

You can see this method in use places like [here](https://github.com/PennyLaneAI/pennylane/blob/2de14a44b872c681801fb0e7d006df323e5097ad/pennylane/ops/op_math/pow.py#L104) where we are removing an operator in favor or an altered version of it (raised to a power).

As for error messages, anything that gets the point across should be fine.

**Comment by JuanGiraldo0212** [comment]
Ohhh that makes sense, it works now! Thank you very much @albi3ro.

**Comment by Alex-Preciado** [comment]
Closing this issue now that https://github.com/PennyLaneAI/pennylane/pull/4908 has been merged. Many thanks @JuanGiraldo0212 🙏🏼 !!
