### ISSUE TITLE
Add parity transformation

### ISSUE THREAD

**Issue by soranjh** [PennyLaneAI/pennylane#4881]
### Feature details

⚠️ This issue is part of an internal assignment and not meant for external contributors.

The parity transformation can be used to convert fermionic operators to qubit operators. See section `III. A` of this [reference](https://arxiv.org/abs/1208.5986) for details.

The `parity_transform` function should be created to perform fermionic to qubit mapping, similar to the PennyLane [jordan_wigner](https://docs.pennylane.ai/en/stable/code/api/pennylane.jordan_wigner.html) function.

```
>>> qml.parity_transform(fermionic_operator)
0.5 * Z(1) @ X(2)
+ 0.5j * Y(2)
```

### Implementation

The function should be added to the [conversion](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/fermi/conversion.py) module.

### Requirements

1. The input fermionic operator can be a [FermiWord](https://docs.pennylane.ai/en/stable/code/api/pennylane.fermi.FermiWord.html) or a [FermiSentence](https://docs.pennylane.ai/en/stable/code/api/pennylane.fermi.FermiSentence.html).

2. The output qubit operator should have a similar type to the output of the [jordan_wigner](https://docs.pennylane.ai/en/stable/code/api/pennylane.jordan_wigner.html) function.

3. Unit tests should be added to check the accuracy of the new function.

**Comment by ddhawan11** [comment]
Do I need to add qubit tapering as well or just the parity mapping?

**Comment by ddhawan11** [comment]
The PR for this issue is here: #4928
