### ISSUE TITLE
Implement comparison between `QuantumScript` classes with `qml.equal`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#4894]
Currently, we can use `qml.equal` to compare operations and measurements:
```python
>>> qml.equal(qml.RX(1.2, wires=0), qml.RX(1.2, wires=0))
True
>>> qml.equal(qml.probs(wires=(0,1)), qml.probs(wires=(0,1)) )
True
```

but we cannot currently compare our circuit object, `qml.tape.QuantumScript`.  

To add comparison support, we would need to register a new dispatch for the `_equal` single dispatch function: 

https://github.com/PennyLaneAI/pennylane/blob/deaf3870e7ab4bf6c76147f94f36c30eeb9cfa5e/pennylane/ops/functions/equal.py#L159

This function
```python
def _equal(op1 : qml.tape.QuantumScript, op2 : qml.tape.QuantumScript,
    check_interface=True,
    check_trainability=True,
    rtol=1e-5,
    atol=1e-9,
    ) -> bool :
```

Should return ``True`` if:
* all operations are equal, see https://docs.pennylane.ai/en/stable/code/api/pennylane.tape.QuantumScript.html#pennylane.tape.QuantumScript.operations
* all measurements are equal, see https://docs.pennylane.ai/en/stable/code/api/pennylane.tape.QuantumScript.html#pennylane.tape.QuantumScript.measurements
* The shots are equal, see https://docs.pennylane.ai/en/stable/code/api/pennylane.tape.QuantumScript.html#pennylane.tape.QuantumScript.shots
* The `trainable_params` are equal, see https://docs.pennylane.ai/en/stable/code/api/pennylane.tape.QuantumScript.html#pennylane.tape.QuantumScript.trainable_params

And ``False`` otherwise.

A PR implementing this should also update the docstring for `qml.equal` and include unit tests for comparison.

**Example of desired behavior:**

```python
>>> tape1 = qml.tape.QuantumScript([qml.PauliX(0), qml.RX(1.2, wires=0)], [qml.expval(qml.PauliZ(0))], shots=10)
>>> tape2 = qml.tape.QuantumScript([qml.PauliX(0)], [qml.expval(qml.PauliZ(0))], shots=10)
>>> qml.equal(tape1, tape2)
False
>>> qml.equal(tape1, tape1)
True
>>> tape3 = qml.tape.QuantumScript([qml.PauliX(0)], [qml.expval(qml.PauliZ(0))], shots=None)
>>> qml.equal(tape2, tape3)
False
>>> tape4 = qml.tape.QuantumScript([qml.PauliX(0), qml.RX(1.2+1e-6, wires=0)], [qml.expval(qml.PauliZ(0))], shots=10)
>>> qml.equal(tape1, tape4, atol=1e-5)
True
>>> qml.equal(tape1, tape4, atol=1e-7)
False
```

**Comment by minhtriet** [comment]
I would like to work on this if you don't mind

**Comment by albi3ro** [comment]
Thanks @minhtriet . Let me know if you have any further questions.

**Comment by minhtriet** [comment]
I think we could close it this @albi3ro :)

**Comment by albi3ro** [comment]
Thanks for the PR @minhtriet 🎉
