### ISSUE TITLE
Implement `ProbabilityMP.process_counts`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#4943]
### Important Note

⚠️ This issue is part of an internal assignment and not meant for external contributors.

### Context

Currently, our sample-based measurement processes that inherit from `SampleMeasurement` implement a [process_samples](https://github.com/PennyLaneAI/pennylane/blob/a05ae286c5925e0c881099cea751193d368779fc/pennylane/measurements/measurements.py#L535) method. This method is capable of turning any samples (array of int64) into the required measurement result. This method is currently used internally by default.qubit.

```
@qml.qnode(qml.device('default.qubit'))
def circuit():
    qml.Hadamard(0)
    return qml.sample(wires=(0,1))

samples = circuit(shots=100)
qml.probs(wires=(0,)).process_samples(samples, wire_order=qml.wires.Wires((0,1)))
```

But external devices and plugins may want to store sampling information in the form of a counts dictionary instead, like `{'00': 45, '01': 55}`. This representation is much more condensed and memory efficient. Because of this, we have recently added a `SampleMeasurement.process_counts` method.

### Implementation Details

The task is to implement [ProbabilityMP.process_counts(counts, wire_order)](https://github.com/PennyLaneAI/pennylane/blob/4942327df674f25785e6127dab9a25e5ba8cd191/pennylane/measurements/probs.py#L121) in such a way that a probability measurement can be computed from a counts dictionary.

```pycon
>>> counts = {'000': 100, '100': 100 }
>>> wire_order = qml.wires.Wires((0,1,2))
>>> qml.probs(wires=(0,1)).process_counts(counts, wire_order)
array([0.5, 0, 0.5, 0])
```

### Requirements

A completed PR should:

* Add the `process_counts` method to `ProbabilityMP`
* Add unit tests to [pennylane/tests/measurements/test_probs.py](https://github.com/PennyLaneAI/pennylane/blob/master/tests/measurements/test_probs.py)
* Pass black and pylint checks
* Add a changelog entry to [pennylane/releases/changelog-dev.md](https://github.com/PennyLaneAI/pennylane/blob/master/doc/releases/changelog-dev.md) under Improvements. Don't forget to add your name to the list of contributors at the bottom.

**Comment by PietropaoloFrisoni** [comment]
Good morning, Christina. I hope you are doing well.

As you can see, I just created [this draft pull request](https://github.com/PennyLaneAI/pennylane/pull/4952) to address this issue.

Please, if you want me to proceed differently (or if you want me to change something), you just have to ask it. 
I'll do my best to implement such a feature over the next few days. I am incredibly grateful for your time!

All the best.

**Comment by Alex-Preciado** [comment]
Thank you so much @PietropaoloFrisoni!! I'm closing this issue now that https://github.com/PennyLaneAI/pennylane/pull/4952 has been merged 🙂. Aaron will reach out to you with more details about next steps.

**Comment by PietropaoloFrisoni** [comment]
> Thank you so much @PietropaoloFrisoni!! I'm closing this issue now that #4952 has been merged 🙂. Aaron will reach out to you with more details about next steps.

Thank you, Alex! It was fun : )
