### ISSUE TITLE
[BUG] tensorflow autograph with finite diff and M1 Mac kills the kernel

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#4953]
### Expected behavior

I expect to get the gradient. Or at least an error message that tells me what I'm doing wrong.

### Actual behavior

bus error  python untitled.py

Very helpful traceback there.

### Additional information

The kernel gets killed with finite diff or spsa, but works fine with parameter shift.

### Source code

```shell
import pennylane as qml
import numpy as np

import tensorflow as tf

dev = qml.device('default.qubit', wires=1)

@tf.function
@qml.qnode(dev, diff_method="finite-diff")
def circuit(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

x = tf.Variable(0.1, dtype=tf.float64)
with tf.GradientTape() as tape:
    y = circuit(x)
tape.gradient(y, x)
```

### System information

```shell
M1 Mac
tensorflow 2.14.1

PL master
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by minhtriet** [comment]
It seems to me that `tensorflow/python/eager/imperative_grad.py` uses a  `pywrap_tfe.TFE_Py_TapeGradient`, which access a memory address it isn't supposed to. Guess that the next step is to create a MRE and raise to TensorFlow team?

**Comment by albi3ro** [comment]
I've managed to track down the problem to this line:

https://github.com/PennyLaneAI/pennylane/blob/8702182672f0a074c5a2f9f67206ae7a9d95e929/pennylane/gradients/finite_difference.py#L149

Why that would be causing a problem, I have no idea.

**Comment by albi3ro** [comment]
And it seems to be fixed by switching `np.linalg.solve` with `scipy.linalg.solve`. 😕
