### ISSUE TITLE
[Bug] Wire order changes in PauliSentence for string-valued wires

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#5040]
Going from this
```
>>> pw3 = PauliWord({"a": "Y", "b": "Z"})
>>> pw3.wires
<Wires = ['a', 'b']>
```

to this

```
>>> PauliSentence({pw3: 1.}).wires
<Wires = ['b', 'a']>
```

Feels like a bug or at least unexpected behavior. This came up in https://github.com/PennyLaneAI/pennylane/pull/5018 and is caused by https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/pauli/pauli_arithmetic.py#L445

**Comment by Qottmann** [comment]
Some curios interplay between `Wires` and `set`:

The `Wires` class seems to be re-ordering wires when passed as a set
```python
>>> set().union(["b", "c"], ["a", "b", "c"])
{'a', 'b', 'c'}
>>> qml.wires.Wires(set().union(["b", "c"], ["a", "b", "c"]))
<Wires = ['b', 'c', 'a']>
```

To add to the confusion, the result is also different depending on how that set was created (what is the attribute that is carried to determine this behavior!?)
```python
>>> qml.wires.Wires({"a", "b", "c"})
<Wires = ['a', 'c', 'b']>
```

This behavior seems to stem from casting the input to `Wires`'s init to a tuple in https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/wires.py#L54
```python
>>> tuple({"a", "b", "c"})
('a', 'c', 'b')
```

Still dont understand why `qml.wires.Wires(set().union(["b", "c"], ["a", "b", "c"]))` and `qml.wires.Wires({"a", "b", "c"})` yield different results. But bottom line to me from this is `Wires` + `set` is a big no no

**Comment by astralcai** [comment]
We can probably close this issue now?
