### ISSUE TITLE
Update documentation on devices/plugins

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#5053]
### Feature details

The [Bulding a plugin](https://docs.pennylane.ai/en/latest/development/plugins.html) documentation is still featuring a warning that it is rereferring to the old (therein referred to as _current_) [pennylane.Device](https://docs.pennylane.ai/en/latest/code/api/pennylane.Device.html) and [pennylane.QubitDevice](https://docs.pennylane.ai/en/latest/code/api/pennylane.QubitDevice.html) class. 

It would be great to have that part of the documentation up to date now that the new [pennylane.devices.Device](https://docs.pennylane.ai/en/latest/code/api/pennylane.devices.Device.html) interface has now been standard since [0.33.0](https://github.com/PennyLaneAI/pennylane/releases/tag/v0.33.0).

I can see that some documentation on the new interface is on https://docs.pennylane.ai/en/latest/code/api/pennylane.devices.Device.html.

I would be particularly interested in when you recommend sub-classing qml.devices.Device and when qml.devices.DefaultQubit when implementing a qubit based device.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by albi3ro** [comment]
I started #4619 , but it got backlogged. I can try and move it up in priority.

**Comment by trbromley** [comment]
Thanks @cvjjm! We can discuss more on our call, but we've been purposefully a bit slower on recommending the new Device API on that page, giving us a bit more time to be confident in any pain points with the new API. Though you're right, it's probably time for us to at least have another page for the new device API (if not yet replacing the old one).
