### ISSUE TITLE
Improve the condition when caching Variables for mutable QNodes

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#507]
#### Issue description
As per https://github.com/XanaduAI/pennylane/pull/505, an improved caching condition was introduced when using Variable instances in mutable Qnodes. It would be desirable to align this check:
* with keyword arguments
* cases similar to the one outlined at https://github.com/XanaduAI/pennylane/pull/505#issuecomment-585444220
* *(any potential further edge cases)*

Furthermore, a more sophisticated, but still lightweight check for the `args` would be desirable.

**Comment by josh146** [comment]
This is no longer a bug that needs fixing, it light of the [extensive tape-mode refactor](https://pennylane.readthedocs.io/en/latest/code/qml_tape.html). As a result:

* there are no longer any restrictions on QNode signatures; they follow the same logic and behave exactly as python functions.

* The `Variable` class has been marked for deprecation and removal.

Closing this for now.
