### ISSUE TITLE
Ability to count number of executions of a device

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#5075]
### Feature details

With the old device classes it was possible with the attribute https://docs.pennylane.ai/en/stable/code/api/pennylane.Device.html?highlight=executions#pennylane.Device.num_executions to track the number of executions (=number of times a real hardware device would have needed to be reprogrammed to execute a different circuit) in addition to the number of shots (=number of times the device was "run"). 

I understand how I can count the number of shots by means of https://docs.pennylane.ai/en/stable/code/qml_resource.html?highlight=resource, but I was unable to find a functionality in the new Device class https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/devices/device_api.py#L40 to count the number of executions.

In batch mode, since the circuits in a batch are usually different, I would not want to count the number of calls to `execute()` but rather the cumulative number of tapes of all batches there were executed on the device. 

Maybe I am just overlooking something, but I can't figure out how to do this with the new device api.  

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by cvjjm** [comment]
To be more precise: I have a device and I am going to hand this device to a function that I call. I don't want to make any assumptions about what this function does internally. After the function is completed I want to know how many executions of my device were performed during the execution of the function.

**Comment by albi3ro** [comment]
The new device interface still has integration with `qml.Tracker`, see: https://docs.pennylane.ai/en/stable/code/api/pennylane.Tracker.html?highlight=tracker#pennylane.Tracker

Is there a place we should add more documentation to point to the existance of the `Tracker` class?

**Comment by cvjjm** [comment]
Yes, I know and I know how to get the number of shots from the Tracker, but there seems to be no way to track the number of executions. Or am I just blind?

**Comment by cvjjm** [comment]
Turns out I am indeed blind :-) Thanks very much and sorry for the trouble!
