### ISSUE TITLE
Partial trace function for ops and matrices (qml.math.partial_trace)

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#5093]
### Feature details

A partial trace function for general matrices beyond density matrices (bonus for operators but that should be a bit more difficult)

We have most of the functionality already, it's just tailored to density matrices. So the point of this feature is to make some of that functionality public and calling it `partial_trace` instead of `reduced_dm`.

### Implementation

We essentially already have it in `qml.math.quantum._batched_partial_trace`, would just need to turn that into a user-facing feature. We currently only have `qml.math.reduced_dm` specific to density matrices.

### Acceptance criteria

- [ ] A user-facing `qml.math.partial_trace(op, wires)` function exists and can handle numerical matrices
- [ ] It can handle matrices as well as lists of matrices (essentially what `qml.math.quantum._batched_partial_trace` is doing
- [ ] The function has a descriptive doc string that define inputs, outputs and provides at least one illustrative example
- [ ] A changelog entry is added to `doc/releases/changelog-dev.md`
- [ ] Unit tests are added to `tests/math/test_matrix_manipulation.py` ensuring inputs and outputs of the function are correct (in particular checking the supported dtypes `float` and `complex` and the supported interfaces `jax`, `torch`, ` autograd`, `tensorflow`
- [ ] Integration tests are added to `tests/math/test_matrix_manipulation.py`

#### Optional Follow-up 1
To be done in a second Pull Request

- [ ] The function `qml.math.partial_trace` supports PennyLane operators. E.g. 
```
>>> op = X(0) @ X(1) + Y(0) @ Y(1)
>>> qml.math.partial_trace(op, wires=[1])
X(0) + Y(0)
>>> qml.math.partial_trace(op, wires=[0])
X(1) + Y(1)
```
- [ ] The same criteria for the above (documentation, changelog, unit tests, integration tests) are fulfilled
- [ ] In particular, integration tests should cover instances of `SProd`, `Sum` and `Prod` classes (pennylane operator classes)

#### Optional Follow-up 2
- [ ] The function `qml.math.partial_trace` supports `PauliWord` and `PauliSentence`
- [ ] Same criteria as above again

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by babcockt18** [comment]
Hey this looks like a good first issue for me, would you mind assigning it to me?

**Comment by Qottmann** [comment]
Awesome, thanks! :-)

**Comment by babcockt18** [comment]
@Qottmann just made the first [PR](https://github.com/PennyLaneAI/pennylane/pull/5152), please let me know if it looks good/if there's anything I'm missing!
