### ISSUE TITLE
Implement `ExpectationMP.process_counts`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#5241]
# Context

Currently, our sample-based measurement processes that inherit from `SampleMeasurement` implement a [process_samples](https://github.com/PennyLaneAI/pennylane/blob/a05ae286c5925e0c881099cea751193d368779fc/pennylane/measurements/measurements.py#L535) method. This method is capable of turning any samples (array of int64) into the required measurement result. This method is currently used internally by `default.qubit`.

```
@qml.qnode(qml.device('default.qubit'))
def circuit():
    qml.Hadamard(0)
    return qml.sample(wires=(0,1))

samples = circuit(shots=100)
qml.expval(qml.Z(0)).process_samples(samples, wire_order=qml.wires.Wires((0,1)))
```

But external devices and plugins may want to store sampling information in the form of a counts dictionary instead, like `{'00': 45, '01': 55}`. This representation is much more condensed and memory efficient. Because of this, we have recently added a `SampleMeasurement.process_counts` method, and implemented it for `ProbabilityMP`.

# Implementation Details

The task is to implement [ExpectationMP.process_counts(counts, wire_order)](https://github.com/PennyLaneAI/pennylane/blob/b97f7a55c5fcd5b3d0397e9654043b151a7aa0ba/pennylane/measurements/expval.py#L77) in such a way that expectation values can be computed from a counts dictionary.

```pycon
>>> counts = {'000': 100, '100': 100 }
>>> wire_order = qml.wires.Wires((0,1,2))
>>> qml.expval(qml.Z(0)).process_counts(counts, wire_order)
0.0
>>> qml.expval(qml.Z(1)).process_counts(counts, wire_order)
1.0
```

Note that the counts are assumed to be taken in the basis for the provided observable already, with any diagonalizing gates already applied.

# Requirements

A completed PR should:

* Add the `process_counts` method to `ExpecatationMP`
* Add unit tests to [pennylane/tests/measurements/test_expval.py](https://github.com/PennyLaneAI/pennylane/blob/master/tests/measurements/test_expval.py)
* Pass black and pylint checks
* Add a changelog entry to [pennylane/releases/changelog-dev.md](https://github.com/PennyLaneAI/pennylane/blob/master/doc/releases/changelog-dev.md) under Improvements. Don't forget to add your name to the list of contributors at the bottom :)

**Comment by Tarun-Kumar07** [comment]
Hello @albi3ro ,

I'm new to Pennylane and eager to start contributing. Could I begin by working on this particular issue?

Thank you!

**Comment by albi3ro** [comment]
Thanks for reaching out @Tarun-Kumar07 . I've assigned you the issue.

Feel free to reach out with any additional questions, or open a draft PR for early feedback.

**Comment by Tarun-Kumar07** [comment]
Hello @albi3ro , I opened a [PR](https://github.com/PennyLaneAI/pennylane/pull/5256). 
Can you please have a look at it?
Thanks :)
