### ISSUE TITLE
[Bug] dtype promotion to `complex128` with tensorflow SProds _only_ in pauli_rep

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#5245]
We are currently promoting the dtype of tensorflow variables in the pauli rep of scalar products, this leads to some unexpected and inconsistent behavior, e.g.

```python
op = qml.s_prod(tf.constant(0.5), X(0))
print(op.scalar)
print(next(iter(op.pauli_rep.values())))
```

```
(<tf.Tensor: shape=(), dtype=float32, numpy=0.5>,
 <tf.Tensor: shape=(), dtype=complex128, numpy=(0.5+0j)>)
```

This problem stems from this line https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/ops/op_math/sprod.py#L152

**Comment by Alex-Preciado** [comment]
Closed with https://github.com/PennyLaneAI/pennylane/pull/5246
