### ISSUE TITLE
[Bug] `PauliSentence.to_mat(wire_order)` cannot handle Identities with wires

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#5354]
```python
PauliSentence({PauliWord({}): 1.}).to_mat([0, 1])
```

```pycon
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 PauliSentence({PauliWord({}): 1.}).to_mat([0, 1])

File ~/Xanadu/pennylane/pennylane/pauli/pauli_arithmetic.py:876, in PauliSentence.to_mat(self, wire_order, format, buffer_size)
    864 mats_and_wires_gen = (
    865     (
    866         coeff * pw.to_mat(wire_order=_pw_wires(pw.wires), format=format),
   (...)
    869     for pw, coeff in self.items()
    870 )
    872 reduced_mat, result_wire_order = math.reduce_matrices(
    873     mats_and_wires_gen=mats_and_wires_gen, reduce_func=math.add
    874 )
--> 876 return math.expand_matrix(reduced_mat, result_wire_order, wire_order=wire_order)

File ~/Xanadu/pennylane/pennylane/math/matrix_manipulation.py:135, in expand_matrix(mat, wires, wire_order, sparse_format)
    131 # get a subset of `wire_order` values that contain all wire labels inside `wires` argument
    132 # e.g. wire_order = [0, 1, 2, 3, 4]; wires = [3, 0, 2]
    133 # --> subset_wire_order = [0, 1, 2, 3]; expanded_wires = [3, 0, 2, 1]
    134 wire_indices = [wire_order.index(wire) for wire in wires]
--> 135 subset_wire_order = wire_order[min(wire_indices) : max(wire_indices) + 1]
    136 wire_difference = list(set(subset_wire_order) - set(wires))
    137 expanded_wires = wires + wire_difference

ValueError: min() arg is an empty sequence
```

**Comment by Tarun-Kumar07** [comment]
Hello @Qottmann,

I'm interested in contributing to this issue. I've recently started working with PennyLane and am eager to help out. Could I work on this one?

Thank you!

**Comment by Tarun-Kumar07** [comment]
Hello @Qottmann,

Thank you for explaining the issue. I'm interested in tackling this bug to expand my understanding of PennyLane. It's a great opportunity for me to learn and contribute. Could I take on this task?

Thank you!

**Comment by albi3ro** [comment]
In my mind, a fix would involve updating this inner function:

https://github.com/PennyLaneAI/pennylane/blob/58ad1dfdc661fb58034225743503167e3006d86f/pennylane/pauli/pauli_arithmetic.py#L829

When the `PauliWord` itself doesn't have wires, it falls back to pulling a wire from the `PauliSentence` object instead.  But in this case, the `PauliSentence` doesn't have any wires either.

I could try pulling a random wire from the `wire_order` instead of from the `PauliSentence` instance and see if that fixes the issue and still passes tests.

**Comment by Tarun-Kumar07** [comment]
Hey @Qottmann, would you mind assigning this bug to me, please?
@albi3ro, the fix worked well. I just need a bit of time to understand the code better. 
I'll aim to submit a PR by tomorrow. 
Thank you for your assistance!

**Comment by Tarun-Kumar07** [comment]
@Qottmann, I'd like to clarify the expected behavior in the following scenario: 
When there is an empty PauliWord and no wire_order provided. Currently, the behavior is as follows:
```
>>> PauliSentence({PauliWord({}): 1.5}).to_mat()
[[1.5]]
```
Is this behavior expected, or should it raise a ValueError instead?

**Comment by Qottmann** [comment]
That case is expected I would say, it is also what is happening for `PauliWord`:
```
>>> PauliWord({}).to_mat()
array([[1.]])
```
