### ISSUE TITLE
Implement `SampleMP.proces_counts`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#5371]
# Context

Currently, our sample-based measurement processes that inherit from `SampleMeasurement` implement a [process_samples](https://github.com/PennyLaneAI/pennylane/blob/a05ae286c5925e0c881099cea751193d368779fc/pennylane/measurements/measurements.py#L535) method. This method is capable of turning any samples (array of int64) into the required measurement result. This method is currently used internally by `default.qubit`.

```
@qml.qnode(qml.device('default.qubit'))
def circuit():
    qml.Hadamard(0)
    return qml.sample(wires=(0,1))

samples = circuit(shots=10)
qml.sample(wires=0).process_samples(samples, wire_order=qml.wires.Wires((0,1)))
```

But external devices and plugins may want to store sampling information in the form of a counts dictionary instead, like `{'00': 45, '01': 55}`. This representation is much more condensed and memory efficient. Because of this, we have recently added a `SampleMeasurement.process_counts` method.

# Implementation Details

The task is to implement [SampleMP.process_counts(counts, wire_order)](https://github.com/PennyLaneAI/pennylane/blob/3407a9e3fd76f0b112ef22e14ef8a4ba3d5a339f/pennylane/measurements/counts.py#L159) in such a way that a counts dictionary to look like raw samples.

```pycon
>>> counts = {'00': 2, '10': 3}
>>> qml.sample(wires=(0,1)).process_counts(counts, wire_order=qml.wires.Wires((0,1)))
array([[0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0]])
>>> qml.sample(wires=0).process_counts(counts, wire_order=qml.wires.Wires((0,1)))
array([0, 0, 1, 1, 1])
```

# Requirements

A completed PR should:

* Add the `process_counts` method to `SampleMP`
* Add unit tests to [pennylane/tests/measurements/test_sample.py](https://github.com/PennyLaneAI/pennylane/blob/master/tests/measurements/test_sample.py)
* Pass black and pylint checks
* Add a changelog entry to [pennylane/releases/changelog-dev.md](https://github.com/PennyLaneAI/pennylane/blob/master/doc/releases/changelog-dev.md) under Improvements. Don't forget to add your name to the list of contributors at the bottom :)

**Comment by Tarun-Kumar07** [comment]
Hey @albi3ro , could you please assign this to me.
Thanks
