### ISSUE TITLE
[BUG] Pennylane qml.device error.

### ISSUE THREAD

**Issue by Pak-Riz** [PennyLaneAI/pennylane#5394]
### Expected behavior

dev0 = qml.device("rigetti.qvm", device="4q-qvm")
dev0 = qml.device("forest.qvm", device="4q-qvm")
dev0 =qml.device("qiskit-aer", wires=4, backend='statevector_simulator') 

### Actual behavior

I have installed the desire liberies with plugins and still facing the 
DeviceError: Device qiskit-aer does not exist. Make sure the required plugin is installed.

installed qiskit-aer
      pennylane-qiskit
     pennylane-rigetti
     qiskit=1.0.2 and also tried old version of qiskits.

### System information

```shell
Nill
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by Pak-Riz** [comment]
appdirs               1.4.4
asttokens             2.4.1
autograd              1.6.2
autoray               0.6.9
cachetools            5.3.3
certifi               2024.2.2
cffi                  1.16.0
charset-normalizer    3.3.2
click                 8.1.7
cloudpickle           3.0.0
colorama              0.4.6
comm                  0.2.2
contourpy             1.2.0
cryptography          42.0.5
cycler                0.12.1
dask                  2024.3.1
debugpy               1.8.1
decorator             5.1.1
dill                  0.3.8
executing             2.0.1
fonttools             4.49.0
fsspec                2024.2.0
future                1.0.0
ibm-cloud-sdk-core    3.19.2
ibm-platform-services 0.52.0
idna                  3.6
ipykernel             6.29.3
ipython               8.22.2
jedi                  0.19.1
joblib                1.3.2
jupyter_client        8.6.1
jupyter_core          5.7.2
kiwisolver            1.4.5
locket                1.0.0
matplotlib            3.8.3
matplotlib-inline     0.1.6
mpmath                1.3.0
nest-asyncio          1.6.0
networkx              3.2.1
numpy                 1.26.4
packaging             24.0
pandas                2.2.1
parso                 0.8.3
partd                 1.4.1
pbr                   6.0.0
PennyLane             0.35.1
PennyLane_Lightning   0.35.1
PennyLane-qiskit      0.35.1
pillow                10.2.0
pip                   24.0
platformdirs          4.2.0
prompt-toolkit        3.0.43
psutil                5.9.8
pure-eval             0.2.2
pycparser             2.21
Pygments              2.17.2
PyJWT                 2.8.0
pyparsing             3.1.2
pyspnego              0.10.2
python-dateutil       2.9.0.post0
pytz                  2024.1
pywin32               306
PyYAML                6.0.1
pyzmq                 25.1.2
qiskit                1.0.2
qiskit-aer            0.13.3
qiskit-ibm-provider   0.10.0
qiskit-ibm-runtime    0.20.0
requests              2.31.0
requests-ntlm         1.2.0
rustworkx             0.14.2
scikit-learn          1.4.1.post1
scipy                 1.12.0
semantic-version      2.10.0
six                   1.16.0
sspilib               0.1.0
stack-data            0.6.3
stevedore             5.2.0
symengine             0.11.0
sympy                 1.12
threadpoolctl         3.3.0
toml                  0.10.2
toolz                 0.12.1
tornado               6.4
traitlets             5.14.2
typing_extensions     4.10.0
tzdata                2024.1
urllib3               2.2.1
wcwidth               0.2.13
websocket-client      1.7.0
websockets            12.0

**Comment by isaacdevlugt** [comment]
Hey @Pak-Riz! A couple things:

1. With version 1.0 or higher of Qiskit and version 0.35.1 of PennyLane and the PennyLane-Qiskit plugin, you can't use any devices (we are working on supporting this, though, of course 😄). This is what will happen if you try to use, say, `qiskit.aer`

```
>>> import pennylane as qml
>>> dev = qml.device('qiskit.aer', wires=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/isaac/.virtualenvs/pennylane-qiskit/lib/python3.11/site-packages/pennylane/__init__.py", line 378, in device
    dev = plugin_device_class(*args, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaac/.virtualenvs/pennylane-qiskit/lib/python3.11/site-packages/pennylane_qiskit/aer.py", line 63, in __init__
    super().__init__(wires, provider=qiskit_aer.Aer, backend=backend, shots=shots, **kwargs)
  File "/Users/isaac/.virtualenvs/pennylane-qiskit/lib/python3.11/site-packages/pennylane_qiskit/qiskit_device.py", line 158, in __init__
    raise RuntimeError(
RuntimeError: The devices in the PennyLane Qiskit plugin are currently only compatible with versions of Qiskit below 0.46. You have version 1.0.2 installed. Please downgrade Qiskit to use the devices. The devices will be updated in the coming weeks to be compatible with Qiskit 1.0!
```

As the message states, you need to downgrade to versions below 0.46 of Qiskit for this to work.

2. Your specific error in your code example has a typo: `qiskit-aer` should be `qiskit.aer`. Make sure you check out the documentation for the device identifiers: https://docs.pennylane.ai/projects/qiskit/en/stable/

Let me know if this helps!

**Comment by Pak-Riz** [comment]
Hi @isaacdevlugt, thank you so much for your reply. 
I have also checked with Qiskit version 0.46, 0.45, 0.40, even 0.34.
Secondly not only qiskit-aer, with forest.qvm and also render the same problem, even I have installed pennylane-qiskit and pennylane-forest also.

**Comment by isaacdevlugt** [comment]
We have experienced some bugs with 0.46, but definitely 0.45 and lower should be bug-free in this instance. I can run this without any issues:

```
dev = qml.device('qiskit.aer', wires=2)
```

Here's what's in my virtual environment that I'm using (the output of `python -m pip freeze`:

```
appdirs==1.4.4
appnope==0.1.4
asttokens==2.4.1
autograd==1.6.2
autoray==0.6.9
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
comm==0.2.2
cryptography==42.0.5
debugpy==1.8.1
decorator==5.1.1
dill==0.3.8
executing==2.0.1
future==1.0.0
ibm-cloud-sdk-core==3.19.2
ibm-platform-services==0.52.0
idna==3.6
ipykernel==6.29.3
ipython==8.22.2
jedi==0.19.1
jupyter_client==8.6.1
jupyter_core==5.7.2
matplotlib-inline==0.1.6
mpmath==1.3.0
nest-asyncio==1.6.0
networkx==3.2.1
numpy==1.26.4
packaging==24.0
parso==0.8.3
pbr==6.0.0
PennyLane==0.35.1
PennyLane-qiskit==0.35.1
PennyLane_Lightning==0.35.1
pexpect==4.9.0
platformdirs==4.2.0
ply==3.11
prompt-toolkit==3.0.43
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.17.2
PyJWT==2.8.0
pyspnego==0.10.2
python-dateutil==2.9.0.post0
pyzmq==25.1.2
qiskit==0.45.0
qiskit-aer==0.13.3
qiskit-ibm-provider==0.10.0
qiskit-ibm-runtime==0.20.0
qiskit-terra==0.45.0
requests==2.31.0
requests-ntlm==1.2.0
rustworkx==0.14.2
scipy==1.12.0
semantic-version==2.10.0
six==1.16.0
stack-data==0.6.3
stevedore==5.2.0
symengine==0.9.2
sympy==1.12
toml==0.10.2
tornado==6.4
traitlets==5.14.2
typing_extensions==4.10.0
urllib3==2.2.1
wcwidth==0.2.13
websocket-client==1.7.0
websockets==12.0
```

I recommend creating a fresh new virtual environment and doing `python -m pip install pennylane pennylane-qiskit qiskit=0.45`. Sometimes environments can get a little messy and weird dependency issues like what you're seeing pop up :).

Regarding the similar rigetti issues, just make sure you follow the instructions in this demo for running circuits on the qvm device: https://pennylane.ai/qml/demos/ensemble_multi_qpu/

**Comment by Pak-Riz** [comment]
Hi @isaacdevlugt ,
Thanks alot for your help. I exactly make a new environment and installed all the libraries that you have installed. Now I am getting the following error when run that qml.device cell.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], [line 2](vscode-notebook-cell:?execution_count=2&line=2)
      [1](vscode-notebook-cell:?execution_count=2&line=1) import pennylane as qml
----> [2](vscode-notebook-cell:?execution_count=2&line=2) dev = qml.device('qiskit.aer', wires=2)

File [c:\Users\ubaid.ullah\Desktop\ub\.penny\Lib\site-packages\pennylane\__init__.py:367](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:367), in device(name, *args, **kwargs)
    [364](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:364) options.update(kwargs)
    [366](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:366) # loads the device class
--> [367](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:367) plugin_device_class = plugin_devices[name].load()
    [369](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:369) if hasattr(plugin_device_class, "pennylane_requires") and Version(
    [370](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:370)     version()
    [371](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:371) ) not in SimpleSpec(plugin_device_class.pennylane_requires):
    [372](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:372)     raise DeviceError(
    [373](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:373)         f"The {name} plugin requires PennyLane versions {plugin_device_class.pennylane_requires}, "
    [374](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:374)         f"however PennyLane version {__version__} is installed."
    [375](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/pennylane/__init__.py:375)     )

File [C:\python\Lib\importlib\metadata\__init__.py:205](file:///C:/python/Lib/importlib/metadata/__init__.py:205), in EntryPoint.load(self)
    [200](file:///C:/python/Lib/importlib/metadata/__init__.py:200) """Load the entry point from its definition. If only a module
    [201](file:///C:/python/Lib/importlib/metadata/__init__.py:201) is indicated by the value, return that module. Otherwise,
    [202](file:///C:/python/Lib/importlib/metadata/__init__.py:202) return the named object.
    [203](file:///C:/python/Lib/importlib/metadata/__init__.py:203) """
    [204](file:///C:/python/Lib/importlib/metadata/__init__.py:204) match = self.pattern.match(self.value)
--> [205](file:///C:/python/Lib/importlib/metadata/__init__.py:205) module = import_module(match.group('module'))
...
---> [19](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/qiskit_ibm_provider/api/session.py:19) import pkg_resources
     [21](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/qiskit_ibm_provider/api/session.py:21) from requests import Session, RequestException, Response
     [22](file:///C:/Users/ubaid.ullah/Desktop/ub/.penny/Lib/site-packages/qiskit_ibm_provider/api/session.py:22) from requests.adapters import HTTPAdapter

ModuleNotFoundError: No module named 'pkg_resources'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?1239e809-b3b6-4762-87a0-e216af222b92) or open in a [text editor](command:workbench.action.openLargeOutput?1239e809-b3b6-4762-87a0-e216af222b92). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by Pak-Riz** [comment]
Hi @isaacdevlugt 
Thank you so much for your detailed explanation. I followed your trick and almost I am success in it. Now I have the following error I tried it also but still stucked in it.
![Bug](https://github.com/PennyLaneAI/pennylane/assets/97063778/60ec2b8f-680f-47d4-9c50-74ea04ab8925)

**Comment by isaacdevlugt** [comment]
Hey @Pak-Riz, the `collections` module, which contains `QNodeCollection`, was deprecated in v0.29 of PennyLane (https://docs.pennylane.ai/en/stable/development/deprecations.html). The good thing here is that individual QNodes can now handle multiple measurements and parameter broadcasting! Check this out: https://docs.pennylane.ai/en/stable/introduction/returns.html

**Comment by Pak-Riz** [comment]
Hey @isaacdevlugt thank you so much for your entire help. I really appriciated your help, finally I clear all the error and now success to run the desire model.

**Comment by isaacdevlugt** [comment]
Lovely! 🚀 Glad I could help 😄. Please reach out to us on our forum (https://discuss.pennylane.ai) if you have any further questions about how to use PennyLane!
