### ISSUE TITLE
Improve use of keyword args in `qml.equal` comparison

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#5408]
While `qml.equal` has the keyword arguments `check_interface`, `check_trainability`, `atol`, and `rtol`, not all specialized kernels use them when they should.

These operators are:

`Pow`:

https://github.com/PennyLaneAI/pennylane/blob/78abf2b935ea3545f4e540d1da4b080a511b8a73/pennylane/ops/functions/equal.py#L324

`Adjoint`:

https://github.com/PennyLaneAI/pennylane/blob/78abf2b935ea3545f4e540d1da4b080a511b8a73/pennylane/ops/functions/equal.py#L333

`Exp`:

https://github.com/PennyLaneAI/pennylane/blob/78abf2b935ea3545f4e540d1da4b080a511b8a73/pennylane/ops/functions/equal.py#L341

`SProd`:

https://github.com/PennyLaneAI/pennylane/blob/78abf2b935ea3545f4e540d1da4b080a511b8a73/pennylane/ops/functions/equal.py#L361

After this change, we should have:

```pycon
>>> op1 = qml.RX(1.2, wires=0)
>>> op2 = qml.RX(1.2 + 1e-4, wires=0)
>>> qml.equal(op1 **2, op2 ** 2, atol=1e-3)
True
>>> qml.equal(op1 **2, op2 ** 2, atol=1e-6)
False
>>> qml.equal(qml.adjoint(op1), qml.adjoint(op2), atol=1e-3)
True
>>> qml.equal(qml.adjoint(op1), qml.adjoint(op2), atol=1e-6)
False
>>> op3 = qml.exp( qml.s_prod(2j, qml.X(0)))
>>> op4 = qml.exp(qml.s_prod(qml.numpy.array(2j), qml.X(0)))
>>> qml.equal(op3, op4, check_interface=True)
False
>>> qml.equal(op3, op4, check_interface=False)
True
```

Relevant tests should be added to:

https://github.com/PennyLaneAI/pennylane/blob/master/tests/ops/functions/test_equal.py

A changelog entry should be added under `Community Contributions`

https://github.com/PennyLaneAI/pennylane/blob/78abf2b935ea3545f4e540d1da4b080a511b8a73/doc/releases/changelog-dev.md?plain=1#L144

And your name should be added to the list of contributors at the bottom of the changelog:

https://github.com/PennyLaneAI/pennylane/blob/78abf2b935ea3545f4e540d1da4b080a511b8a73/doc/releases/changelog-dev.md?plain=1#L238

**Comment by kenya-sk** [comment]
@albi3ro 
I am working on another issue, but am also interested in this one. 
Can you please assign it to me?

**Comment by Alex-Preciado** [comment]
Closed by https://github.com/PennyLaneAI/pennylane/pull/5668
