### ISSUE TITLE
[BUG] Issues with `ExpectationMP.process_samples`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#5432]
### Expected behavior

I would expect the output of `ExpectationMP(obs=Z(0)).process_samples` to match the output of its diagonalized form `ExpectationMP(eigvals=[-1, 1], wires=qml.wires.Wires(0)).process_samples`

### Actual behavior

When the measurement is in its diagonalized form with eigvals and wires instead of an observable, the sample processing does not occur correctly and it ends up with a very different shape.

```
>>> qml.expval(qml.Z(0)).process_samples(samples, qml.wires.Wires((0,1)) )
tensor(1., requires_grad=True)
>>> ExpectationMP(eigvals=[-1,1], wires=qml.wires.Wires(0)).process_samples(samples, qml.wires.Wires((0,1)))
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
```

### Source code

```shell
@qml.qnode(qml.device('default.qubit'))
def circuit():
    return qml.sample(wires=(0,1))

samples = circuit(shots=10)

qml.expval(qml.Z(0)).process_samples(samples, qml.wires.Wires(0) )
ExpectationMP(eigvals=[0,1], wires=qml.wires.Wires(0)).process_samples(samples, qml.wires.Wires(0))
```

### System information

```shell
master
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by astralcai** [comment]
I can take a look at this.
