### ISSUE TITLE
Add `Shots.bins()` generator method

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#5433]
[`qml.measurements.Shots`](https://github.com/PennyLaneAI/pennylane/blob/c2f5d44ae3428ac3bdc5fa82a776594110e935fb/pennylane/measurements/shots.py#L46) is our class for keeping track of how many shots to use in calculating measurements.

One of the reasons we need a class like this is to better interact with and support *shot vectors*.  A shot vector is when the same measurements as calculated multiple times using subsets of the total shots.  For example, `shots=(1, 10, 100, 100)` requests that measurements are done with `1` shot, `10` shots, `100` shots, and `100` shots again:

```
@qml.qnode(qml.device('default.qubit'))
def circuit():
    return qml.counts(wires=0)

circuit(shots=(1, 10, 100,100))
```
```
({'0': tensor(1, requires_grad=True)},
 {'0': tensor(10, requires_grad=True)},
 {'0': tensor(100, requires_grad=True)},
 {'0': tensor(100, requires_grad=True)})
```

If we calculated 211 total shots, measurement 1 would be calculated from shots `0:1`, measurement 2 from `1:11`, measurement 3 from `11:111`, and 3 from `111:211`.

This task is to add a property that makes it easy and convenient to access these ranges as "bins", a tuple of `(lower_bound, upper_bound)`. 

For example:

```
>>> shots = Shots((1, 10, 100, 100))
>>> shots.bins()
<generator object <genexpr> at 0x3095a5630>
>>> list(shots.bins())
[(0,1), (1,11), (11,111), (111,211)]
>>> for bin in shots.bins():
...     print(bin)
(0,1)
(1,11)
(11,111)
(111,211)
```

To complete this task, the contributor should:

1) Add the `bins` method to `Shots` in `pennylane/measurements/shots.py`
2) Add tests for the new method in [`tests/measurements/test_shots.py`](https://github.com/PennyLaneAI/pennylane/blob/master/tests/measurements/test_shots.py)
3) Add a changelog entry under `Community Contributions`
4) Add your name to the list of contributors at the bottom of the changelog
5) Make sure that all tests pass and the code adheres to our black and pylint standards

**Comment by Tarun-Kumar07** [comment]
Hey @albi3ro, would it be possible for me to work on this issue? Could you please assign it to me?

**Comment by albi3ro** [comment]
Thanks for reaching out @Tarun-Kumar07 . I've assigned you the issue.

**Comment by Tarun-Kumar07** [comment]
Hey @albi3ro, I was wondering about the method  `bins`. Is it part of a larger task or project?

**Comment by albi3ro** [comment]
More of something that could make things easier in the future.

An example of where this could be used is here:

https://github.com/PennyLaneAI/pennylane/blob/04be31747c2946d1561f35ea9487a9b486778983/pennylane/devices/qubit/sampling.py#L268

Currently in `devices/qubit/sampling.py`, we handle shot vectors by sampling multiple times and processing the shots independently.  In an ideal world, we would want to just sample once, and then process each bin separately. We made compromises due to time constraints and conceptual ease. This method would allow us to move toward the more ideal way of implementing sampling.

**Comment by Tarun-Kumar07** [comment]
Hey @albi3ro just wanted to confirm the case when there are duplicates i.e. shot quantity is repeated twice,
is below the expected behaviour
```
>>> shots = Shots((1, 1, 2, 3))
>>> list(shots.bins())
[(0,1), (1,2), (2,4), (4,7)]
```

**Comment by albi3ro** [comment]
Exactly 👍 

Another quick note that the same shots class can also be created with:

```
>>> qml.measurements.Shots(((1,2), 2, 3))
Shots(total_shots=7, shot_vector=(ShotCopies(1 shots x 2), ShotCopies(2 shots x 1), ShotCopies(3 shots x 1)))
```

**Comment by Tarun-Kumar07** [comment]
Hey @albi3ro , is there an issue for a follow up task as mentioned in this [comment](https://github.com/PennyLaneAI/pennylane/issues/5433#issuecomment-2032522211). 
I would love to work on it :)

**Comment by albi3ro** [comment]
That'd be great.  Would you like to do that a separate PR or add the change into #5476 ?

Basically, you would need to update `_measure_with_samples_diagonalizing_gates` and how it handles the case of partitioned shot vectors. Instead of sampling + processing many times, we sample `shots.total_shots` once, and then pass along individual bins to `_process_single_shot` and then `SampleMeasurement.process_samples`.

Since this would just be a change in implementation details, no tests would need to be changed or added.

**Comment by Tarun-Kumar07** [comment]
@albi3ro , I will add it to #5476, and change the description of PR as well.
I will move it to Draft till I am back with updated implementation of `_measure_with_samples_diagonalizing_gates`

**Comment by Tarun-Kumar07** [comment]
Hey @albi3ro #5476 PR is ready for review, can you please have a look at it.
Thanks :)
