### ISSUE TITLE
[BUG] Finite-shot mid-circuit measurement support is not compatible with broadcasting

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#5443]
### Expected behavior

The following QNode can be executed, which includes:
- Finite-shot mid-circuit measurements
- Lots of mid-circuit measurements
- Broadcasting over parameters

### Actual behavior

Instead of using the [one-shot](https://docs.pennylane.ai/en/latest/code/api/pennylane.dynamic_one_shot.html) transform, the [deferred measurement](https://docs.pennylane.ai/en/latest/code/api/pennylane.defer_measurements.html) approach is used as a fallback. This results in too many qubits being used.

### Additional information

Note that no error occurs if the number of mid-circuit measurements is lowered to, for example, ten. This is because the deferred measurement transform is able to cope when fewer mid-circuit measurements are present. Hence, one could argue that this issue is a feature request to support batching/broadcasting in [dynamic_one_shot()](https://docs.pennylane.ai/en/latest/code/api/pennylane.dynamic_one_shot.html).

### Source code

```shell
import pennylane as qml
import numpy as np

dev = qml.device("default.qubit", shots=10)

@qml.qnode(dev)
def f(x):
    for i in range(100):
        qml.RY(x, 0)
        m = qml.measure(0)
    return qml.expval(qml.PauliX(0))

x = np.array([0.4, 0.6])
f(x)
```

### Tracebacks

```shell
ValueError: maximum supported dimension for an ndarray is 32, found 101
```

### System information

```shell
Working on dev branch of PL
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by trbromley** [comment]
Related to [this](https://discuss.pennylane.ai/t/running-circuits-with-many-mid-circuit-measurements/4355) forum post.

**Comment by trbromley** [comment]
CC @vincentmr.

**Comment by albi3ro** [comment]
One really quick solution to this is adding `broadcast_expand` as a `expand_transform` for `dynamic_one_shot`. Then we just update the condition on `qml.devices.preprocess.mid_circuit_measurements`.

Native broadcasting with mid circuit measurements might be possible, but I'm not sure if it'll be worth the effort.

**Comment by mudit2812** [comment]
`broadcast_expand` does not currently work with shot vectors. However, I do agree that using `broadcast_expand` makes more sense and it might not be worth the effort to implement a more "native" solution. I'll update `broadcast_expand` to work with shot vectors as well.
