### ISSUE TITLE
[BUG] Grouping of measurements is inconsistent between legacy and new opmath

### ISSUE THREAD

**Issue by lillian542** [PennyLaneAI/pennylane#5512]
### Expected behavior

That `measurements=[qml.expval(qml.PauliX(0)), qml.expval(qml.PauliY(0)@qml.PauliX(1)]` would be grouped the same and be tracked as requiring the same number of executions to measure regardless of whether the observables were `Tensor` or `Prod` instances.

### Actual behavior

There is a separate clause for grouping new opmath instances that causes mathematically identical measurements to be grouped differently. The legacy behaviour seems preferable and results in fewer executions.

### Additional information

The issue arises in `pennylane.device.qubit.sampling._group_measurements`. It was found in a test for the tracker that passes with Legacy opmath but not with the new opmath, but it appears to be genuinely increasing the number of executions run, not just incorrectly counting in the tracker. 

There is an xfailed test in `test_default_qubit_tracker.py` that should pass (i.e. fail due to strict xfail) once this is resolved.

### Source code

```shell
>>> from pennylane.devices.qubit.sampling import get_num_shots_and_executions, _group_measurements

>>> prod = qml.prod(qml.PauliX(0), qml.PauliY(1))
>>> tensor = qml.operation.Tensor(qml.PauliX(0), qml.PauliY(1))

>>> tape1 = qml.tape.QuantumScript([], measurements=[qml.expval(qml.PauliX(0)), qml.expval(prod)], shots=10)
>>> get_num_shots_and_executions(tape1)
(2, 20)

>>> all_mp_groups, all_indices = _group_measurements(tape1.measurements)
>>> all_mp_groups
[[expval(X(0))], [expval(X(0) @ Y(1))]]


>>> tape2 = qml.tape.QuantumScript([], measurements=[qml.expval(qml.PauliX(0)), qml.expval(tensor)], shots=10)
>>> get_num_shots_and_executions(tape2)
(1, 10)

>>> all_mp_groups, all_indices = _group_measurements(tape2.measurements)
>>> all_mp_groups
[[expval(X(0)), expval(X(0) @ Y(1))]]
```

### System information

```shell
pl-dev
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by trbromley** [comment]
Thanks @lillian542!

> The legacy behaviour seems preferable and results in fewer executions.
This looks like a priority to fix before the 0.36 release.
