### ISSUE TITLE
[BUG] `qml.counts` returns bad counts for measurements outcomes 

### ISSUE THREAD

**Issue by yokkon** [PennyLaneAI/pennylane#5537]
### Expected behavior

I expect the return value of `qml.counts` to return a dictionary with the amount of 2 to the power of 8 (wires) which is 256 keys which is the amount of computational states

### Actual behavior

Instead of 256 keys in the dictionary, I find more keys (300) with negative values in the returned dictionary:
{'00000000': 1,
 '00000001': 1,
 '00000010': 3,
 '00000011': 0,
 '00000100': 2,
 '00000101': 1,
 '00000110': 0,
 '00000111': 0,
 '00001000': 1,
 '00001001': 1,
 '00001010': 2,
 '00001011': 1,
 '00001100': 0,
 '00001101': 0,
 '00001110': 2,
 '00001111': 0,
 '00010000': 2,
 '00010001': 0,
 '00010010': 0,
 '00010011': 0,
 '00010100': 0,
 '00010101': 0,
 '00010110': 0,
 '00010111': 0,
 '00011000': 0,
 '00011001': 0,
 '00011010': 0,
 '00011011': 0,
 '00011100': 0,
 '00011101': 1,
 '00011110': 0,
 '00011111': 0,
 '00100000': 1,
 '00100001': 0,
 '00100010': 0,
 '00100011': 0,
 '00100100': 0,
 '00100101': 0,
 '00100110': 0,
 '00100111': 0,
 '00101000': 0,
 '00101001': 0,
 '00101010': 1,
 '00101011': 0,
 '00101100': 0,
 '00101101': 0,
 '00101110': 0,
 '00101111': 0,
 '00110000': 0,
 '00110001': 0,
 '00110010': 0,
 '00110011': 1,
 '00110100': 0,
 '00110101': 0,
 '00110110': 0,
 '00110111': 0,
 '00111000': 0,
 '00111001': 0,
 '00111010': 0,
 '00111011': 0,
 '00111100': 0,
 '00111101': 0,
 '00111110': 0,
 '00111111': 0,
 '01000000': 1,
 '01000001': 1,
 '01000010': 0,
 '01000011': 0,
 '01000100': 0,
 '01000101': 0,
 '01000110': 0,
 '01000111': 1,
 '01001000': 1,
 '01001001': 0,
 '01001010': 0,
 '01001011': 0,
 '01001100': 1,
 '01001101': 1,
 '01001110': 0,
 '01001111': 1,
 '01010000': 0,
 '01010001': 1,
 '01010010': 0,
 '01010011': 0,
 '01010100': 0,
 '01010101': 2,
 '01010110': 0,
 '01010111': 0,
 '01011000': 0,
 '01011001': 0,
 '01011010': 0,
 '01011011': 0,
 '01011100': 0,
 '01011101': 0,
 '01011110': 1,
 '01011111': 0,
 '01100000': 1,
 '01100001': 0,
 '01100010': 0,
 '01100011': 0,
 '01100100': 0,
 '01100101': 0,
 '01100110': 0,
 '01100111': 0,
 '01101000': 0,
 '01101001': 0,
 '01101010': 0,
 '01101011': 0,
 '01101100': 0,
 '01101101': 0,
 '01101110': 0,
 '01101111': 0,
 '01110000': 0,
 '01110001': 0,
 '01110010': 0,
 '01110011': 0,
 '01110100': 0,
 '01110101': 2,
 '01110110': 1,
 '01110111': 1,
 '01111000': 0,
 '01111001': 0,
 '01111010': 1,
 '01111011': 1,
 '01111100': 0,
 '01111101': 0,
 '01111110': 0,
 '01111111': 0,
 '10000000': 0,
 '10000001': 0,
 '10000010': 0,
 '10000011': 0,
 '10000100': 0,
 '10000101': 0,
 '10000110': 0,
 '10000111': 0,
 '10001000': 0,
 '10001001': 0,
 '10001010': 0,
 '10001011': 0,
 '10001100': 0,
 '10001101': 0,
 '10001110': 0,
 '10001111': 0,
 '10010000': 0,
 '10010001': 0,
 '10010010': 0,
 '10010011': 0,
 '10010100': 0,
 '10010101': 0,
 '10010110': 0,
 '10010111': 0,
 '10011000': 0,
 '10011001': 0,
 '10011010': 0,
 '10011011': 0,
 '10011100': 0,
 '10011101': 0,
 '10011110': 0,
 '10011111': 0,
 '10100000': 0,
 '10100001': 0,
 '10100010': 0,
 '10100011': 0,
 '10100100': 0,
 '10100101': 0,
 '10100110': 0,
 '10100111': 0,
 '10101000': 0,
 '10101001': 0,
 '10101010': 0,
 '10101011': 0,
 '10101100': 0,
 '10101101': 0,
 '10101110': 0,
 '10101111': 0,
 '10110000': 0,
 '10110001': 0,
 '10110010': 0,
 '10110011': 0,
 '10110100': 0,
 '10110101': 0,
 '10110110': 0,
 '10110111': 0,
 '10111000': 0,
 '10111001': 0,
 '10111010': 0,
 '10111011': 0,
 '10111100': 0,
 '10111101': 0,
 '10111110': 0,
 '10111111': 0,
 '11000000': 0,
 '11000001': 0,
 '11000010': 0,
 '11000011': 0,
 '11000100': 0,
 '11000101': 0,
 '11000110': 0,
 '11000111': 0,
 '11001000': 0,
 '11001001': 0,
 '11001010': 0,
 '11001011': 0,
 '11001100': 0,
 '11001101': 0,
 '11001110': 0,
 '11001111': 0,
 '11010000': 0,
 '11010001': 0,
 '11010010': 0,
 '11010011': 0,
 '11010100': 0,
 '11010101': 0,
 '11010110': 0,
 '11010111': 0,
 '11011000': 0,
 '11011001': 0,
 '11011010': 0,
 '11011011': 0,
 '11011100': 0,
 '11011101': 0,
 '11011110': 0,
 '11011111': 0,
 '11100000': 0,
 '11100001': 0,
 '11100010': 0,
 '11100011': 0,
 '11100100': 0,
 '11100101': 0,
 '11100110': 0,
 '11100111': 0,
 '11101000': 0,
 '11101001': 0,
 '11101010': 0,
 '11101011': 0,
 '11101100': 0,
 '11101101': 0,
 '11101110': 0,
 '11101111': 0,
 '11110000': 0,
 '11110001': 0,
 '11110010': 0,
 '11110011': 0,
 '11110100': 0,
 '11110101': 0,
 '11110110': 0,
 '11110111': 0,
 '11111000': 0,
 '11111001': 0,
 '11111010': 0,
 '11111011': 0,
 '11111100': 0,
 '11111101': 0,
 '11111110': 0,
 '11111111': 0,
 '-0000001': 3,
 '-0000010': 1,
 '-0000011': 3,
 '-0000101': 1,
 '-0000110': 1,
 '-0001001': 2,
 '-0001010': 3,
 '-0001011': 2,
 '-0001100': 1,
 '-0001110': 2,
 '-0010000': 1,
 '-0010110': 1,
 '-0010111': 1,
 '-0011011': 2,
 '-0011111': 1,
 '-0100010': 1,
 '-0100011': 1,
 '-0100100': 1,
 '-0100111': 1,
 '-0101100': 1,
 '-0110011': 1,
 '-0110100': 1,
 '-0110110': 1,
 '-0110111': 1,
 '-1000001': 2,
 '-1000100': 2,
 '-1000101': 1,
 '-1001001': 2,
 '-1001010': 1,
 '-1001100': 2,
 '-1001110': 2,
 '-1001111': 1,
 '-1010000': 1,
 '-1010101': 1,
 '-1010110': 2,
 '-1011110': 1,
 '-1100011': 1,
 '-1100110': 1,
 '-1110010': 2,
 '-1110101': 1,
 '-1110110': 1,
 '-1111011': 1,
 '-1111101': 1,
 '-1111111': 1}

### Source code

```shell
graphs = [(nx.Graph([(0, 1), (1, 2), (0, 2), (2, 3), (1,3), (0,3), (0,4), (1,4), (1,5), (2,6), (1,7), (5,7)]), -9)]
cost_h_list = list(map(lambda x : qml.qaoa.cost.maxcut(x[0])[0], graphs))
qaoa_hamiltonians = list(map(lambda x : qml.qaoa.cost.maxcut(x[0]), graphs))

def get_qaoa_sample_circuit_wrapper_according_to_graph(idx=0):
    assert(np.abs(idx) < len(qaoa_hamiltonians))
    cost_h, mixer_h = qaoa_hamiltonians[idx]

    def circuit_wrapper(dev):
        @qml.qnode(dev)
        def circuit(params):
            for w in dev.wires:
                qml.Hadamard(wires=w)
            # params[0] is gamma values for all layers
            # params[1] is beta values for all layers
            assert(len(params[0]) == len(params[1]))
            qml.layer(qaoa_layer, len(params[0]), params[0], params[1], cost_h=cost_h, mixer_h=mixer_h)
            return qml.counts(all_outcomes=True)

        return circuit
    return circuit_wrapper

def get_device(shots, wires=4):
    new_dev = qml.device('default.qubit', wires=wires, shots=shots)
    return new_dev

sample_circuit_wrapper = get_qaoa_sample_circuit_wrapper_according_to_graph()
dev_shots = get_device(shots=100, wires=len(graphs[0][0].nodes()))
sample_circuit_wrapper(dev_shots)(params)
```

### System information

```shell
Name: PennyLane
Version: 0.35.1
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane_Lightning

Platform info:           Linux-6.1.58+-x86_64-with-glibc2.35
Python version:          3.10.12
Numpy version:           1.25.2
Scipy version:           1.11.4
Installed devices:
- default.clifford (PennyLane-0.35.1)
- default.gaussian (PennyLane-0.35.1)
- default.mixed (PennyLane-0.35.1)
- default.qubit (PennyLane-0.35.1)
- default.qubit.autograd (PennyLane-0.35.1)
- default.qubit.jax (PennyLane-0.35.1)
- default.qubit.legacy (PennyLane-0.35.1)
- default.qubit.tf (PennyLane-0.35.1)
- default.qubit.torch (PennyLane-0.35.1)
- default.qutrit (PennyLane-0.35.1)
- null.qubit (PennyLane-0.35.1)
- lightning.qubit (PennyLane_Lightning-0.35.1)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by CatalinaAlbornoz** [comment]
Hi @yokkon, I'm not being able to replicate your code. You're missing the definition of params and the qaoa_layer function definition. Could you please post a minimal but self-contained version of your code which shows the issue? It helps a lot if you can strip this code to only the bare minimum.

Please let me know if you have any questions about this.

**Comment by CatalinaAlbornoz** [comment]
Hi @yokkon, my colleague Mudit is looking into this bug. He's already working on a fix so hopefully it can make it into the next PennyLane release which will be in about 2.5 weeks. In the meantime we'll let you know when the fix is in master so you can use the dev version at that time.

Thank you very much for reporting this bug here!

**Comment by yokkon** [comment]
Hi Catalina,

It’s great to hear from you.
I didn’t understand if the solution is already merged to dev? Or are you
still looking for the bug?
I will be happy to help if you still need, I have an idea to where is the
bug. I would also really appreciate if you can update me so I don’t need to
have workarounds in my code.

Thanks!

**Comment by mudit2812** [comment]
Hi @yokkon . We have a fix pushed already to the master branch, which should allow correct behavior for up to 63 wires. We're working on a fix to also allow using `qml.counts` with more than 64 wires, but you should already be able to install the latest PennyLane and work as usual since you're using 8 wires.

**Comment by CatalinaAlbornoz** [comment]
Hi @yokkon, @mudit2812 has now pushed the fix into master! You can now use the development version of PennyLane if you want to use it now, or wait two weeks for this to be in the next stable version of PennyLane.

You can learn how to install both versions at [pennylane.ai/install](https://pennylane.ai/install/).

Thanks again for reporting this bug and enjoy using PennyLane!
