### ISSUE TITLE
Three bugs with auxiliary args in immutable QNodes

### ISSUE THREAD

**Issue by smite** [PennyLaneAI/pennylane#557]
#### Issue description

The recent implementation of structured parameter names for the circuit drawer introduced the following three bugs that only affect auxiliary parameters of immutable QNodes.

* *Expected behavior:* All three code snippets below should work.

* *Actual behavior:* None of them do.

Bug 1: `qnodes/base.py:_make_variables` only converts `kwonlyargs` (it should convert all keyword args).

```python
import numpy as np
import pennylane as qml

dev = qml.device('default.qubit', wires=1)

@qml.qnode(dev, mutable=False)
def circuit(a, b=None):
    qml.ops.RX(a[0], wires=[0])
    qml.ops.RY(b[0], wires=[0])
    return qml.expval(qml.PauliZ(0))

a = [0.4]
b = [0.7]
circuit(a, b=b)   # TypeError: 'NoneType' object is not subscriptable 
```

Bug 2: `qnodes/base.py:_make_variables` can only handle `np.ndarrays`, not e.g. lists.

```python
import numpy as np
import pennylane as qml

dev = qml.device('default.qubit', wires=1)

@qml.qnode(dev, mutable=False)
def circuit(a, *, b=None):
    qml.ops.RX(a[0], wires=[0])
    qml.ops.RY(b[0], wires=[0])
    return qml.expval(qml.PauliZ(0))

a = [0.4]
b = [0.7] 
circuit(a, b=b)   # TypeError: 'Variable' object does not support indexing
```

Bug 3: `variable.py:Variable.val`: Structured name of the auxiliary parameter is not the correct the dict key, the base parameter name is.

```python
import numpy as np
import pennylane as qml

dev = qml.device('default.qubit', wires=1)

@qml.qnode(dev, mutable=False)
def circuit(a, *, b=None):
    qml.ops.RX(a[0], wires=[0])
    qml.ops.RY(b[0], wires=[0])
    return qml.expval(qml.PauliZ(0))


a = [0.4]
b = np.array([0.7])  
circuit(a, b=b)  # KeyError: 'b[0]'
```

**Comment by co9olguy** [comment]
@josh146 is this PR now out of sync, given the recent updates to the QNode variable processing?

**Comment by josh146** [comment]
No, these three bugs are still relevant. They relate to bugs in how we perform the function signature introspection, and extracting information from the variables. Now that the Variable refactor refactor is complete, it's time to go back and see if these can be resolved.

**Comment by josh146** [comment]
Note that they only apply to immutable QNodes, and aren't picked up as we don't have unit tests for immutable QNodes (fixed in #510)

**Comment by antalszava** [comment]
[ch323]

**Comment by josh146** [comment]
This is no longer a bug that needs fixing, it light of the [extensive tape-mode refactor](https://pennylane.readthedocs.io/en/latest/code/qml_tape.html). As a result:

* there are no longer any restrictions on QNode signatures; they follow the same logic and behave exactly as python functions.

* The `Variable` class has been marked for deprecation and removal.

Closing this for now.
