### ISSUE TITLE
Test 1-wire edge case in initialization function tests

### ISSUE THREAD

**Issue by mariaschuld** [PennyLaneAI/pennylane#561]
#### Issue description

The initialization function tests currently use 2 or 3 wires for most functions. But for most templates, 1 wire is some kind of edge case, because the parameter array may return empty. 

We should make a separate test that checks all cases for which an empty parameter array is expected (i.e. also 0 wires).

#### Additional information

The relevant tests can be found in ``test_init.py``, and some initialisation functions already include the ``n_wires=1`` case, which is why some tests check if ``shape != (0,)``. This could be removed if the no-parameter edge cases are tested separately.

**Comment by josh146** [comment]
@mariaschuld I believe this should have been closed when #606 was merged. If not, feel free to reopen.
