### ISSUE TITLE
Improve operator support for new `assert_equal` function: Group 1

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#5644]
### Context

PennyLane currently has a `qml.equal` function which can be used to check the equality of operators, measurements, and tapes. While this has been extremely useful in testing and validation, it can be difficult to figure out *why* two objects aren't equal.

This is why we are currently have added the framework for an `assert_equal` function:

https://github.com/PennyLaneAI/pennylane/blob/b6e96588f9e3d4236d1f31f73e22566298a22344/pennylane/ops/functions/equal.py#L179

```
>>> from pennylane.ops.functions.equal import assert_equal
>>> assert_equal(qml.S(0), qml.T(0))
AssertionError: op1 and op2 are of different types.  Got <class 'pennylane.ops.qubit.non_parametric_ops.S'> and <class 'pennylane.ops.qubit.non_parametric_ops.T'>.
```

The framework for this function was added in PR #5634 , but the implementation still needs to be updated.

### Implementation Details

Comparison currently relies on a `_equal` single dispatch function, with different "kernels" registered for different types of operators. Currently this function returns `True` or `False`.  We are changing it to return `True`, or a string that explains *why* the two operators are not equal.  This change has already been made for `BasisRotation`:

https://github.com/PennyLaneAI/pennylane/blob/b6e96588f9e3d4236d1f31f73e22566298a22344/pennylane/ops/functions/equal.py#L605

This task is to update `_equal` for

* Generic `Operator` classes: see [`_equal_operators`](https://github.com/PennyLaneAI/pennylane/blob/b6e96588f9e3d4236d1f31f73e22566298a22344/pennylane/ops/functions/equal.py#L317)
* `Controlled` classes: see [`_equal_controlled`](https://github.com/PennyLaneAI/pennylane/blob/b6e96588f9e3d4236d1f31f73e22566298a22344/pennylane/ops/functions/equal.py#L386)
* `Pow` classes: see [`_equal_pow`](https://github.com/PennyLaneAI/pennylane/blob/b6e96588f9e3d4236d1f31f73e22566298a22344/pennylane/ops/functions/equal.py#L418)
* `Adjoint` classes: see [`_equal_adjoint`](https://github.com/PennyLaneAI/pennylane/blob/b6e96588f9e3d4236d1f31f73e22566298a22344/pennylane/ops/functions/equal.py#L427)
* `Exp` classes: see [`_equal_exp`](https://github.com/PennyLaneAI/pennylane/blob/b6e96588f9e3d4236d1f31f73e22566298a22344/pennylane/ops/functions/equal.py#L435)

While more single dispatch kernels exist for `_equal`, they will be updated as part of separate tasks.

After this PR, we should be able to do something like:
```
>>> assert_equal(qml.adjoint(qml.RX(0.1, wires=0)), qml.adjoint(qml.RX(0.2, wires=0)))
AssertionError: op1 and op2 have different base operations because op1.data[0] is not equal to op2.data[0]. Got 0.1 and 0.2.
>>> assert_equal(qml.exp(qml.X(0), 0.5j), qml.exp(qml.X(0), 1.0j))
AssertionError: op1 and op2 have different coefficients. Got 0.5j and 1.0j.
```

Use your best judgement as to the contents of the string and we will help refine the message if needed.

### Additional Requirements

To fulfill this task, a PR should:

* Update `_equal` kernels for the above cases
* Update tests in [`test_equal.py`](https://github.com/PennyLaneAI/pennylane/blob/master/tests/ops/functions/test_equal.py). Existing tests like, `test_adjoint_comparison` can be extended, or new tests can be written.
* Add a changelog entry
* Pass black, pylint, and isort checks

**Comment by Tarun-Kumar07** [comment]
Hi @albi3ro and @trbromley,

I’ve submitted PR #5780. Once the PR is merged, could you please assign this issue to me before closing it?

Thank you!

**Comment by trbromley** [comment]
Thanks a lot @Tarun-Kumar07! Really excited to see some unitaryHACK contributions coming in :technologist:

It looks like @EuGig has also opened a PR for this issue:
- @Tarun-Kumar07's PR #5780 solves both issues #5644 and #5648
- @EuGig's PR #5778 was opened earlier and solves issue #5644

We like to encourage working together as much as possible if it works for both of you. Would it make sense for @Tarun-Kumar07 to take on #5648 and @EuGig to take on #5644?

**Comment by EuGig** [comment]
Sounds good to me!!

**Comment by Tarun-Kumar07** [comment]
Hi @trbromley and @EuGig,

I am open to collaboration. While working on #5644, I had to make some changes due to failing unit tests, which also addressed #5648. I attempted to separate the changes, but it seems they need to be in one PR. I have completed the changes for both issues and only waiting for the feedback.

If you feel there are still some gaps, @EuGig, I would be happy to collaborate further to address them.
Thanks !!

**Comment by Tarun-Kumar07** [comment]
@EuGig and @albi3ro, I noticed that the comments @albi3ro made about the tests in PR #5778 are similar to the changes I've implemented in my PR #5780. To avoid duplicating efforts, @EuGig and I could collaborate on PR #5780. 

What do you guys think?
@albi3ro, @trbromley and @EuGig

**Comment by trbromley** [comment]
> @EuGig and @albi3ro, I noticed that the comments @albi3ro made about the tests in PR #5778 are similar to the changes I've implemented in my PR #5780. To avoid duplicating efforts, @EuGig and I could collaborate on PR #5780.
> 
> What do you guys think? @albi3ro, @trbromley and @EuGig

Thanks @Tarun-Kumar07, that can work! So the proposal is:
- @Tarun-Kumar07 and @EuGig work together on #5780 
- Both bounties are completed with the merging of #5780 and you will both be tagged on each bounty
- You'd be equally sharing the $75 + $75 bounty

If that's good for both of you, then I think it's a great idea.

**Comment by Tarun-Kumar07** [comment]
@trbromley Sounds good to me!!

**Comment by Tarun-Kumar07** [comment]
Hi @albi3ro,

Could you please review PR #5780 when you have a moment?

Thank you!

**Comment by trbromley** [comment]
Thanks @Tarun-Kumar07 and sorry for the delay. We'll prioritize reviewing your PR.

**Comment by Tarun-Kumar07** [comment]
Hey @EuGig , there were minor comments in my PR #5780 which I have addressed. 
I am done with changes on my end. Please let me know if there any improvements which we can collaborate on.
Thanks !!
