### ISSUE TITLE
Improve measurement support in from_qasm

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#5646]
### Feature details

The `from_qasm` function allows users to convert a [QASM2](https://arxiv.org/abs/1707.03429) string into a PennyLane quantum function (see [docs](https://docs.pennylane.ai/en/stable/code/api/pennylane.from_qasm.html)). Internally, this is done via the converter in the [PennyLane-Qiskit plugin](https://docs.pennylane.ai/projects/qiskit/en/latest/).

Similar to the [recently-added improvement](https://pennylane.ai/blog/2024/03/pennylane-release-0.35#qiskit-10-integration-) to `from_qiskit`, we want `from_qasm` to be able to 

1. optionally append PL measurements to the end of the circuit and
2. faithfully convert measurements already present in the QASM2 string.

Currently, `from_qasm` ignores any measurements present in the QASM2 string.

### Implementation

For point 1, PennyLane supports a host of measurements (`MeasurementProcess`[objects](https://docs.pennylane.ai/en/stable/code/api/pennylane.measurements.MeasurementProcess.html?)) like expectation values that cannot be represented in QASM2. We would like for a user to be able to convert their QASM2 string with `from_qasm` and append their desired PennyLane measurement to the end of the circuit like so:

```python
>>> hadamard_qasm = 'OPENQASM 2.0;' \
...                 'include "qelib1.inc";' \
...                 'qreg q[1];' \
...                 'h q[0];'
>>> my_circuit = qml.from_qasm(hadamard_qasm, measurements=qml.expval(qml.Z(0)))
```

For point 2, a QASM2 string can contain simple `measure` primitives representing qubit measurement in the standard basis. This can in principle be mapped to PennyLane's [`qml.measure()`](https://docs.pennylane.ai/en/stable/code/api/pennylane.measure.html). We would like for any `measure` primitives in the input QASM2 string to be faithfully converted when using `from_qasm`, following the [same behaviour specified in `from_qiskit`](https://docs.pennylane.ai/en/stable/code/api/pennylane.from_qiskit.html#measurements-and-classical-control-flows).

A successful PR must include:

- The requested feature
- Comprehensive tests
- Relevant updates to the documentation
- An entry in the [release notes](https://github.com/PennyLaneAI/pennylane/blob/master/doc/releases/changelog-dev.md)
- Passing all CI tests

Check out our [development guide](https://docs.pennylane.ai/en/stable/development/guide.html) for more information, and don't hesitate to reach out to us if you need assistance.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

This issue will require work in both the [core PennyLane repo](https://github.com/PennyLaneAI/pennylane) and the [PennyLane-Qiskit plugin repo](https://github.com/PennyLaneAI/pennylane-qiskit) where the [existing conversion functionality lives](https://github.com/PennyLaneAI/pennylane-qiskit/blob/3b50fc525574893b94942c981c6dc0d0b669c45a/pennylane_qiskit/converter.py#L587). The solution to this issue can rely on existing QASM2 to Qiskit conversion support, e.g., via [`qiskit.qasm2`](https://docs.quantum.ibm.com/api/qiskit/qasm2).

**Comment by Coffee4MePlz** [comment]
Hi, I would like to tackle this issue as part of the UnitaryHack

**Comment by trbromley** [comment]
Hi @Coffee4MePlz! That would be great :rocket:

We're here to help with guidance if you need it. Is it clear how to get started?

**Comment by Coffee4MePlz** [comment]
Great. I'm studying the plugin first and `from_qiskit` to get a sense of how things were implemented . If any doubts arise I'll get in touch. Thank you.

**Comment by MashAliK** [comment]
Hello,

I've updated both the core library and the plugin to solve this issue. I've created a pull request in the plugin repo (https://github.com/PennyLaneAI/pennylane-qiskit/pull/555). How will the CI tests work if I create a PR in this repo since it will rely on the other PR? Please let me know what the process for developing on the two different repos simultaneously is. Thank you.

**Comment by trbromley** [comment]
Thanks @MashAliK! Great job with this, and congrats on completing this bounty :medal_military: 

Would you optionally like to be tagged in any of our announcements around unitaryHACK or the upcoming PennyLane 0.37 release at the start of July? This would be on LinkedIn and Twitter, so if you would like, please share your username(s).

**Comment by MashAliK** [comment]
@trbromley Thanks a lot to you and the PL team! I had a great time working on this.
Absolutely! I don't have Twitter but here is my [LinkedIn](www.linkedin.com/in/mashhood-ali-khan-b32a021b5).
Thanks again.
