### ISSUE TITLE
Support native measurement-based snapshots in Default Clifford

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#5647]
### Feature details

The [`default.clifford`](https://docs.pennylane.ai/en/stable/code/api/pennylane.devices.default_clifford.DefaultClifford.html) device allows PennyLane users to quickly simulate [Clifford circuits](https://en.wikipedia.org/wiki/Clifford_gates) in PennyLane using the [Stim](https://github.com/quantumlib/stim/tree/main) library as a backend. The device was [recently added in v0.35](https://pennylane.ai/blog/2024/03/pennylane-release-0.35#a-new-clifford-device-) and is not yet at feature parity with devices like `default.qubit`.

PennyLane provides support for [circuit snapshots](https://docs.pennylane.ai/en/stable/introduction/inspecting_circuits.html#debugging-with-mid-circuit-snapshots), allowing users to inspect circuits at different stages of execution on some simulator devices. Snapshots can can be placed in circuits using [`qml.Snapshot()`](https://docs.pennylane.ai/en/stable/code/api/pennylane.Snapshot.html), which defaults to providing the snapshot of the statevector at that point in the circuit. If a `measurement` argument is provided to `qml.Snapshot()`, then Pennylane [measurements](https://docs.pennylane.ai/en/stable/introduction/measurements.html) like [`qml.expval()`](https://docs.pennylane.ai/en/stable/code/api/pennylane.expval.html) can be inspected.

The `default.clifford` device only supports statevector-based snapshots. The objective of this feature request is to extend support to measurement-based snapshots.

### Implementation

It should be possible to execute the following code:

```python
import pennylane as qml

dev = qml.device("default.clifford")

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.Snapshot(measurement=qml.expval(qml.X(0)))
    qml.S(wires=0)
    return qml.expval(qml.X(0))

qml.snapshots(circuit)()
```

A successful PR must include:

- The requested feature
- Comprehensive tests
- Relevant updates to the documentation
- An entry in the [release notes](https://github.com/PennyLaneAI/pennylane/blob/master/doc/releases/changelog-dev.md)
- Passing all CI tests

Check out our [development guide](https://docs.pennylane.ai/en/stable/development/guide.html) for more information, and don't hesitate to reach out to us if you need assistance.

Additional requirements:

- Measurements done during `qml.Snapshot` shouldn't alter the state of the main execution workflow.
- Efficiency is important, the addition of snapshots should not come with much overhead.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

Support for measurement-based snapshots was provided in `default.mixed` in [this recent PR](https://github.com/PennyLaneAI/pennylane/pull/5552).

**Comment by king-p3nguin** [comment]
Hi, I would like to work on this issue for unitaryhack.

**Comment by king-p3nguin** [comment]
@trbromley Thank you for the reply! I think I have written the necessary code, so please let me know whether you are happy with it.

**Comment by trbromley** [comment]
It also looks like @EuGig has opened a PR :star_struck:

I just to clarify how things work in case of multiple contribution attempts for this bounty:
- We'll merge the first complete PR that solves the issue, which should include necessary updates to tests and documentation. The author(s) of that issue will jointly win the bounty and share the amount.
- It is possible to work together on a PR, but all of the PR authors should be on board with doing so.
- Even if a PR is already open, it might still be worthwhile to make your own attempt in case there are any gaps in the already-open PR.

@king-p3nguin opened their PR first and we're taking a look at that now. @EuGig how would you like to proceed?

Thanks!

**Comment by trbromley** [comment]
Thanks @EuGig! Yes you're welcome to have a go, but we could also recommend other projects to take on if you're interested? We're still waiting for an open PR on this bounty: https://github.com/PennyLaneAI/pennylane/issues/5646. Though there has been some interest already in the comments.

**Comment by trbromley** [comment]
Thanks so much @king-p3nguin! Great job on this bounty :medal_sports: 

Would you optionally like to be tagged in any of our announcements around unitaryHACK or the upcoming PennyLane 0.37 release at the start of July? This would be on LinkedIn and Twitter, so if you would like, please share your username(s).

**Comment by king-p3nguin** [comment]
@trbromley Thank you very much! Yes, I would like to be tagged. Since I only have a LinkedIn account, I will give you my LinkedIn username.
LinkedIn username: kazukitsuoka
