### ISSUE TITLE
Issue when using batched data on StronglyEntanglingLayers template.[BUG]

### ISSUE THREAD

**Issue by BenYyyyyy** [PennyLaneAI/pennylane#5695]
### Expected behavior

I want to use the StronglyEntanglingLayers template to process batched data. the shape of the data is like [batch_size, layers, wires, 3]. 

### Actual behavior

Some errors happened: 
```
.../pennylane/templates/layers/strongly_entangling.py", line 209, in compute_decomposition
    weights[..., l, i, 0],
IndexError: index 10 is out of bounds for dimension 1 with size 10
```

### Additional information

I check the strongly_entangling.py and find this bug may comes from this code:
```
201 line:  n_layers = qml.math.shape(weights)[0]
```

the correct code may be 

```
201 line:  n_layers = qml.math.shape(weights)[-3]
```

### System information

```shell
I run pennylane on the server, and the bug I think is not related to the system.
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by trbromley** [comment]
Thanks @BenYyyyyy for posting! This does sound like a bug, we'll take a look and get back to you.

Would you be able to share the output of `qml.about()` or at least `qml.version()` to help us troubleshoot?

**Comment by BenYyyyyy** [comment]
> Thanks @BenYyyyyy for posting! This does sound like a bug, we'll take a look and get back to you.
> 
> Would you be able to share the output of `qml.about()` or at least `qml.version()` to help us troubleshoot?

Platform info:           Linux-5.14.21-150400.24.81_12.0.75-cray_shasta_c-x86_64-with-glibc2.31
Python version:          3.9.16
Numpy version:           1.23.5
Scipy version:           1.12.0
Installed devices:
- default.gaussian (PennyLane-0.30.0)
- default.mixed (PennyLane-0.30.0)
- default.qubit (PennyLane-0.30.0)
- default.qubit.autograd (PennyLane-0.30.0)
- default.qubit.jax (PennyLane-0.30.0)
- default.qubit.tf (PennyLane-0.30.0)
- default.qubit.torch (PennyLane-0.30.0)
- default.qutrit (PennyLane-0.30.0)
- null.qubit (PennyLane-0.30.0)
- lightning.qubit (PennyLane-Lightning-0.31.0)

**Comment by CatalinaAlbornoz** [comment]
Thanks for sharing this info @BenYyyyyy . I see that you're not using the latest version of PennyLane. Are you able to update it to v0.36 which is our current version? My colleague David is working on a fix for your bug but you'll need to update PennyLane in order to be able to use it.

You can run `pip install pennylane --upgrade`
