### ISSUE TITLE
Define `BasisStateProjector.compute_sparse_matrix`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#5721]
The [`BasisStateProjector`](https://github.com/PennyLaneAI/pennylane/blob/0dcba4495af81890f8d76e6a5715f6994505f560/pennylane/ops/qubit/observables.py#L434) observable is inherently an extremely sparse object, but does not currently define a `compute_sparse_matrix` method.

This task would be to implement:
```
class BasisStateProjector(Observable):

    @staticmethod
    def compute_sparse_matrix(basis_state) -> scipy.sparse.csr_matrix:
        # add your implementation here
```

See [the SciPy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) for more information on the various ways to create a csr matrix.

Note that this task *does not* include implementing `StateVectorProjector.compute_sparse_matrix`, as that matrix is not going to be as sparse as the one for `BasisStateProjector`.

A PR should:

1) Implement `BasisStateProjector.compute_sparse_matrix`
2) Add unit tests to [`tests/ops/qubit/test_observable.py:TestProjector`](https://github.com/PennyLaneAI/pennylane/blob/0dcba4495af81890f8d76e6a5715f6994505f560/tests/ops/qubit/test_observables.py#L461)
3) Add a changelog entry to `doc/releases/changelog-dev.md`
4) Ensure the PR passes black, pylint, and isort checks.

**Comment by trbromley** [comment]
Closing this as it was completed in #5790
