### ISSUE TITLE
[BUG] No warnings or errors are being raised when `shots` argument is passed arbitrarily to `@qnode` with no applicable gradient method

### ISSUE THREAD

**Issue by Shiro-Raven** [PennyLaneAI/pennylane#5745]
### Expected behavior

When `shots` is passed to the `@qnode` function, it is typically considered a keyword argument for an underlying gradient transform. However, should this not be the case, a warning or an error should be raised, notifying the user to the fact that this value is not the actual being used for the execution. The user should be directed to supplying this value to the device instead.

### Actual behavior

Nothing happens. The code executes successfully with the shots configuration of the QNode's device

### Source code

```shell
@qml.qnode(qml.device('default.qubit'), shots=50)
def f():
    return qml.expval(qml.Z(0))

f()
```

### System information

```shell
Name: PennyLane
Version: 0.37.0.dev0
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane_Lightning

Platform info:           macOS-14.5-arm64-arm-64bit
Python version:          3.9.19
Numpy version:           1.26.4
Scipy version:           1.13.0
Installed devices:
- default.clifford (PennyLane-0.37.0.dev0)
- default.gaussian (PennyLane-0.37.0.dev0)
- default.mixed (PennyLane-0.37.0.dev0)
- default.qubit (PennyLane-0.37.0.dev0)
- default.qubit.autograd (PennyLane-0.37.0.dev0)
- default.qubit.jax (PennyLane-0.37.0.dev0)
- default.qubit.legacy (PennyLane-0.37.0.dev0)
- default.qubit.tf (PennyLane-0.37.0.dev0)
- default.qubit.torch (PennyLane-0.37.0.dev0)
- default.qutrit (PennyLane-0.37.0.dev0)
- default.qutrit.mixed (PennyLane-0.37.0.dev0)
- null.qubit (PennyLane-0.37.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.36.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by dwierichs** [comment]
I can take on this issue. My suggestion would be to 
1. test that the `SUPPORTED_GRADIENT_KWARGS` list is up to date (and does not include `"shots"`) using signature inspection, and 
2. [optionally] raise a dedicated warning or even error when `"shots"` is passed to `QNode`/`qnode`. 

Does that make sense? @trbromley @albi3ro @josh146

**Comment by albi3ro** [comment]
I wonder if we could keep `SUPPORTED_GRADIENT_KWARGS` update to date by using `inspect.signature` on all of our in-build gradient keyword arguments.

We could also add a check that ensures the provided gradient keyword arguments the used `gradient_fn`.  For example, if `backprop` is chosen as `"best"`, then we would warn if any gradient keyword arguments were specified.

**Comment by Shiro-Raven** [comment]
Is this issue already handled? Should I close it?

**Comment by dwierichs** [comment]
Oh ,yes good catch! This was handled in #5748
