### ISSUE TITLE
[BUG] qml.ThermalRelaxationError argument typo

### ISSUE THREAD

**Issue by CatalinaAlbornoz** [PennyLaneAI/pennylane#5988]
### Expected behavior

 The fourth parameter in [`qml.ThermalRelaxationError`](https://docs.pennylane.ai/en/stable/code/api/pennylane.ThermalRelaxationError.html) should be called `tg` (float): the gate time for relaxation error.

### Actual behavior

There's a typo so the parameter is mistakenly called `tq` instead of `tg`.

### Additional information

First reported [here](https://discuss.pennylane.ai/t/qml-thermalrelaxationerror-argument-typo/4799) in the Forum.

### System information

```shell
NA
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by Alex-Preciado** [comment]
Thank you so much for helping us fix this problem @SheepSeb!! Closing this issue now 😎
