### ISSUE TITLE
[BUG] `pattern_matching_optimization` eliminates all measurements

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#6088]
### Expected behavior

I expect `pattern_matching_optimization` to preserve the user's measurements.

### Actual behavior

The are all eliminated and the function simply returns a tuple

### Source code

```shell
from functools import partial

ops = [qml.S(0), qml.S(0), qml.Z(0)]
pattern = qml.tape.QuantumTape(ops)

@partial(qml.transforms.pattern_matching_optimization, pattern_tapes = [pattern])
@qml.qnode(device=qml.device('default.qubit'))
def circuit():
    qml.S(wires=0)
    qml.Z(0)
    qml.S(wires=1)
    qml.CZ(wires=[0, 1])
    qml.S(wires=1)
    qml.S(wires=2)
    qml.CZ(wires=[1, 2])
    qml.S(wires=2)
    return qml.expval(qml.X(0))

circuit()
```

### System information

```shell
PL master. But this issue has been around for at least a year.
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by tonmoy-b** [comment]
Hi, if no one's working on this right now maybe I can be assigned to it. Thanks.

**Comment by isaacdevlugt** [comment]
Hey @tonmoy-b! Thanks for your interest in fixing this 💪. We see this bug as _possibly_ straightforward to fix, but (of course 😅) it might be more complicated. Feel free to work on this and we can assist where possible. If it ends up being too demanding of a fix, we'll reassess 🙂. 

Make sure to read our contributing guidelines before getting started!

https://docs.pennylane.ai/en/stable/development/guide/contributing.html

**Comment by Alex-Preciado** [comment]
Hi @tonmoy-b 👋🏼 ,

Thank you for volunteering to work on this issue 💪🏼! I wanted to check in and see if you’ve had a chance to make any progress. We’re in the middle of our feature freeze, with the release of PennyLane v0.38 coming up next week, so it’s crucial that we complete this fix by Friday.

If you haven’t had time, no worries, please just let us know as soon as possible so we can decide if we need to take over to ensure the deadline is met—If that’s the case, we’ll be happy to find another good first issue for you to work on 😎.

Thank you again for your contribution!!

**Comment by tonmoy-b** [comment]
> Hi @tonmoy-b 👋🏼 ,
> 
> 
> 
> Thank you for volunteering to work on this issue 💪🏼! I wanted to check in and see if you’ve had a chance to make any progress. We’re in the middle of our feature freeze, with the release of PennyLane v0.38 coming up next week, so it’s crucial that we complete this fix by Friday.
> 
> 
> 
> If you haven’t had time, no worries, please just let us know as soon as possible so we can decide if we need to take over to ensure the deadline is met—If that’s the case, we’ll be happy to find another good first issue for you to work on 😎.
> 
> 
> 
> Thank you again for your contribution!!

Hi @Alex-Preciado, I haven't been able to put in much time on this yet. Kindly assign it to someone else so there's no delay. I will take up another task. Thanks

**Comment by Alex-Preciado** [comment]
Hi @tonmoy-b, thanks for letting me know! No worries at all—we’ve gone ahead and reassigned this to a member of our team to ensure we stay on track. We regularly have new good first issues, so feel free to let us know if you would like to take on another task when you’re ready. Thanks again for your help! 🚀
