### ISSUE TITLE
[BUG] Incorrect documentation in `mitigate_with_zne`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#6089]
### Expected behavior

I expect all documentation to reflect correct usage.

### Actual behavior

The docstring examples raise errors

### Additional information

This should be updated to `qml.transforms.insert(dev, qml.AmplitudeDamping, noise_strength)`. There may be other docstring issues as well.

### Source code

```shell
import pennylane as qml

noise_strength = 0.05

dev = qml.device("default.mixed", wires=2)
dev = qml.transforms.insert(qml.AmplitudeDamping, noise_strength)(dev)
```

### Tracebacks

```shell
TypeError: AmplitudeDamping.__init__() missing 1 required positional argument: 'wires'
```

### System information

```shell
PL master
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by lillian542** [comment]
Fixed in https://github.com/PennyLaneAI/pennylane/pull/6176
