### ISSUE TITLE
Remove side effects from BaseQNode._check_circuit

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#630]
**Expected behavior:**
`BaseQNode._check_circuit` **only** includes checks according to various criteria 

**Actual behavior:**
`BaseQNode._check_circuit` includes side-effects as it includes checks **and**:
* replaces operations in the `queue` with any decompositions if required
* sets `BaseQNode.ops` with the decomposed set of operations

This may lead to confusion in methods such as `BaseQNode._construct` and `PassthruQNode._construct` where `BaseQNode._check_circuit` is being used.

#### Source code

https://github.com/XanaduAI/pennylane/blob/f17ce4749416345c2ec172fb46f9b6c9cb839a85/pennylane/qnodes/base.py#L658

#### Additional information

The solution could be refactoring `BaseQNode._check_circuit` such that manipulations of the queue and observables are done in separate method(s).

**Comment by josh146** [comment]
Thanks @antalszava, the side effects in `_check_circuit` have always annoyed me!

**Comment by josh146** [comment]
With the queuing refactor and the new tape mode, `BaseQNode._check_circuit` has been deprecated and so this issue is outdated.
