### ISSUE TITLE
[BUG] Inconsistent qnode return behavior for list and tuple

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#6540]
### Expected behavior

I would expect identical behavior for both lists or tuples.

### Actual behavior

If we return a measurement process in a list, we add back in a dimension.  But if the measurement process is in a tuple, we do not add a tuple dimension back in.

### Source code

```shell
@qml.qnode(qml.device('default.qubit'))
def circuit(t):
    return t([qml.expval(qml.Z(0))])
>>> circuit(tuple)
1.0
>>> circuit(list)
[1.0]
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by andrijapau** [comment]
Fixed in https://github.com/PennyLaneAI/pennylane/pull/6568. 😄 Forgot to add the "Fixes" key word for automatic closure.
