### ISSUE TITLE
Add a method that calculates Von Neumann entropy

### ISSUE THREAD

**Issue by Lucaman99** [PennyLaneAI/pennylane#667]
It might be nice to have a method that can calculate the Von Neumann entropy of some arbitrary state. 

I've come across a few papers where a variant of "free energy" is used as a loss function for preparing Gibbs (or Gibbs-like) states [1-3]. This free energy loss function includes both energy expectation and entropy.

I don't think this would be too difficult to implement, we would just have to access `dev.state`, and return -Tr(p ln p).

[1] https://arxiv.org/abs/1910.02071
[2] https://arxiv.org/abs/1811.11756
[3] https://arxiv.org/abs/1912.11381

**Comment by co9olguy** [comment]
Thanks @Lucaman99!

We are currently thinking about how to implement more cost functions naturally, so this definitely fits. 

We're also thinking about whether it makes sense for `state` to be a property of the device, or a quantity that is returned (simulators only). In either case, the von Neumann entropy would be a nice candidate for a new cost function

**Comment by Lucaman99** [comment]
Awesome, I'd love to help out with the implementation of this feature! Is this something you would want to add into Pnnylane now, or would you rather wait until it is decided how `state` will be defined?

**Comment by Lucaman99** [comment]
@co9olguy Also, since you're interested in implementing new cost functions, would you be interested in implementing a free energy cost function (as well as the entropy). It would be a very simple extension since the free energy is given by L = 1/T <H> - S(p).

It also might be worth implementing relative entropy between two states as well! 🙂

**Comment by co9olguy** [comment]
All of these sound great. Before we add them though, we'll need to think ahead and plan how/where they fit

**Comment by Lucaman99** [comment]
@co9olguy Got it, I'm assuming this a change where more people need to be looped-in to the conversation?

**Comment by co9olguy** [comment]
Yep, it's on our radar currently

**Comment by Lucaman99** [comment]
Sounds good!

**Comment by josh146** [comment]
@Lucaman99 - now that we have `qml.state()`, this should pave the way for easily coding this up?

**Comment by antalszava** [comment]
This has been introduced as part of the quantum info module with https://github.com/PennyLaneAI/pennylane/pull/2617.
