### ISSUE TITLE
Customizability in BasicEntanglerLayers Template

### ISSUE THREAD

**Issue by Lucaman99** [PennyLaneAI/pennylane#680]
I have been working with PennyLane templates over the past couple of days, and I think more customizability (in terms of the placement of double-qubit gates) for the `BasicEntanglerLayers` might be nice:

- Instead of only being able to place CNOT gates in a ring-shaped pattern, this template could place gates according to an inputted list of pairs of wire indices.
- Allow for customizability of the multi-qubit gate used in the template, and allow for **parametrized** two-qubit gates as well (CRX, MultiRZ, etc).

**Comment by Lucaman99** [comment]
@josh146 Also, I actually already have the code written for the first point (I need this feature in order to create the VQT ansatz with the template, so I thought I would just try to implement it). If you want, I can open a PR so you can take a look/determine if it is useable. 🙂

**Comment by josh146** [comment]
> @josh146 Also, I actually already have the code written for the first point (I need this feature in order to create the VQT ansatz with the template, so I thought I would just try to implement it). If you want, I can open a PR so you can take a look/determine if it is useable. 🙂 

@Lucaman99 if you already have an implementation locally, sounds great!

**Comment by mariaschuld** [comment]
Hey @Lucaman99 , in general I think this is a great idea. The reason why this template is very restricted is that it is supposed to be a "beginners" template, which is extremely simple. Also to be used in tests and code development where we don't want a lot of fuss. 

Maybe it is worth making an ``EntanglerLayers`` instead with the more flexible architecture? One can use the ``broadcast`` function for this...

**Comment by Lucaman99** [comment]
@mariaschuld That makes more sense, so this new entangler would be able to take any `broadcast` value as an argument?

**Comment by mariaschuld** [comment]
See PR, if you like to extend this template it's also cool!

Yes, the template could take a pattern, which is directly fed to the broadcasting function for the entanglers...

**Comment by josh146** [comment]
@Lucaman99 @mariaschuld just checking to see if this issue is still valid?

**Comment by mariaschuld** [comment]
I think if we don't have user requests for this we should close it?

**Comment by josh146** [comment]
Yep, we can always re-open down the line.
