### ISSUE TITLE
Upgrade benchmarking tool

### ISSUE THREAD

**Issue by co9olguy** [PennyLaneAI/pennylane#691]
The benchmarking tool provided in the PennyLane repo is nice, but there are a few things we could consider doing to upgrade it.

- [ ] Better logic to determine which commit of PL is being tested, and make appropriate substitutions for different incompatible UIs (e.g., QNodes and the expval function come to mind). Right now it's done just by (possibly) overly generic try/except blocks.
- [ ] Add ability to specify additional args for devices or qnodes to the cli (right now done in an ad-hoc manner)
- [ ] Allow the `plot` function to scan over wires (the current architecture assumes the number of wires is fixed)

**Comment by trbromley** [comment]
Agreed! It would be nice to specify additional arguments for the benchmark and potentially for the `plot` function to vary over them. For example, this PR https://github.com/XanaduAI/pennylane/pull/697 looks at benchmarking optimizers - it would be very nice if we can define a custom `opt` flag for this benchmark to specify which optimizer to consider.

**Comment by josh146** [comment]
Agree @trbromley!

**Comment by josh146** [comment]
This issue is now superseded by https://github.com/PennyLaneAI/benchmark
