### ISSUE TITLE
outdated link in web documentation

### ISSUE THREAD

**Issue by WeileiZeng** [PennyLaneAI/pennylane#767]
#### Issue description

Description of the issue - 
outdated link in this webpage
https://pennylane.readthedocs.io/en/stable/development/guide/adr.html

quote: If you are unsure if a change requires an ADR proposal or not, please open a [GitHub issue](https://github.com/XanaduAI/pennylane/issue)

* *Expected behavior:* (What you expect to happen)
[GitHub issue] (https://github.com/PennyLaneAI/pennylane/issues)
* *Actual behavior:* (What actually happens)
[GitHub issue] (https://github.com/XanaduAI/pennylane/issue)

**Comment by josh146** [comment]
Thanks @WeileiZeng for catching this! `XanaduAI/pennylane` was the original location of the repository, so should redirect automatically to `PennyLaneAI/pennylane` 🙂 However, we should continue to make sure all links are updated.

**Comment by WeileiZeng** [comment]
the redirection doesn't work for issue page

**Comment by josh146** [comment]
Ah, then it should definitely be fixed ASAP. Thanks for letting us know!
