### ISSUE TITLE
Singular Matrix for qml.QNGOptimizer with dev analytic=False

### ISSUE THREAD

**Issue by milanleonard** [PennyLaneAI/pennylane#783]
#### Issue description

Description of the issue: When trying to optimize a non-analytic device using the quantum natural gradient optimizer I sometimes get a numpy LinAlgError of singular matrix. It will often work for some time before it runs into a problem

![image](https://user-images.githubusercontent.com/1357619/91522339-59f92b00-e93d-11ea-8683-ddaf7eefcc6c.png)
![image](https://user-images.githubusercontent.com/1357619/91522353-5f567580-e93d-11ea-8d02-572b4e6c0acc.png)

##### Full error message:
![image](https://user-images.githubusercontent.com/1357619/91522374-6aa9a100-e93d-11ea-8af8-755efac8b7cf.png)

* *Reproduces how often:* Depends on the number of shots, for shots=1000 couldn't get it to reproduce, for shots=20 happened every time I checked.

* *System information:* (post the output of `import pennylane as qml; qml.about()`)
This won't be part of the problem but here.

> Name: PennyLane
> Version: 0.11.0
> Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
> Home-page: https://github.com/XanaduAI/pennylane
> Author: None
> Author-email: None
> License: Apache License 2.0
> Location: f:\anaconda\envs\main\lib\site-packages
> Requires: scipy, appdirs, networkx, toml, autograd, numpy, semantic-version
> Required-by: 
> Platform info:           Windows-10-10.0.18362-SP0
> Python version:          3.8.5
> Numpy version:           1.19.1
> Scipy version:           1.5.2
> Installed devices:
> - default.gaussian (PennyLane-0.11.0)
> - default.qubit (PennyLane-0.11.0)
> - default.qubit.autograd (PennyLane-0.11.0)
> - default.qubit.tf (PennyLane-0.11.0)
> - default.tensor (PennyLane-0.11.0)
> - default.tensor.tf (PennyLane-0.11.0)

#### Source code and tracebacks
```
from pennylane import numpy as np # get pennylane's numpy wrapper
import pennylane as qml
from pennylane import expval, var
dev = qml.device("default.qubit", wires=3, analytic=False, shots=20)
@qml.qnode(dev)
def circuit(params):
    qml.RY(np.pi / 4, wires=0)
    qml.RY(np.pi / 3, wires=1)
    qml.RY(np.pi / 7, wires=2)
    qml.RZ(params[0], wires=0)
    qml.RZ(params[1], wires=1)
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    qml.RY(params[2], wires=1)
    qml.RX(params[3], wires=2)
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    return qml.expval(qml.PauliY(0))

init_params = np.array([0.432, -0.123, 0.543, 0.233])
opt = qml.QNGOptimizer(0.01)

thetaqng = init_params
for _ in range(100):
    thetaqng = opt.step(circuit, thetaqng)
    circuit(thetaqng)
    print(thetaqng)
```

**Comment by josh146** [comment]
Hi @milanleonard! Unfortunately, singular metric tensors are sometimes unavoidable when performing natural gradient descent; it is not guaranteed that the Fubini-Study metric tensor approximation calculated by PennyLane will not have singular values.

To avoid this, I suggest adding in a regularizer to the QNG optimizer, by passing the `lam` argument,

```python
opt = QNGOptimizer(stepsize=0.01, diag_approx=True, lam=0.01)
```

This will add a small identity matrix to the metric tensor to avoid singularities ($g\rightarrow g+\lambda I$). You may find that you need to increase the regularizer further, sometimes even values of 0.1 are needed.

**Comment by milanleonard** [comment]
Thanks @josh146! 

Is there any way to only invoke the regularizer conditionally on the Fubini-study metric being singular?

**Comment by josh146** [comment]
> Is there any way to only invoke the regularizer conditionally on the Fubini-study metric being singular?

Yes, there is actually! Note that the `QNGOptimizer.step()` method accepts a `metric_tensor_fn=None` argument. You could potentially wrap the metric tensor method like so:

```python
def metric_tensor_fn(params, diag_approx=False):
    metric_tensor = qnode.metric_tensor(params, diag_approx=diag_approx)

    if np.any(np.linalg.svd(metric_tensor, hermitian==True)[1] == 0):
        lam = 0.01
    else:
        lam = 0

    return metric_tensor + lam * np.identity(len(metric_tensor))
```

**Comment by josh146** [comment]
@milanleonard let me know if that works for you --- since this isn't explicitly a bug in PennyLane, I will close this issue for now. Feel free to reply here, or to use our discussion forum, which can be better suited for general PennyLane tips, questions, and discussion: discuss.pennylane.ai/

**Comment by milanleonard** [comment]
Thanks Josh, lambda worked wonderfully, as well as just wrapping it in a try except block and executing until it found an invertible Fubini-Study tensor. Cheers again for helping me sort it.
