### ISSUE TITLE
BasisEmbedding raising an unexpected ValueError

### ISSUE THREAD

**Issue by Zed-Is-Dead** [PennyLaneAI/pennylane#834]
#### Issue description

When executing a BasisEmbedding function with features=np.array([1, 0, 1]) I get a ValueError:
'basis_state' must only consist of 0s and 1s; got [<Variable(data[0]:0)> <Variable(data[1]:1)> <Variable(data[2]:2)>]
while I expect to get array([-1,1,-1])

* *System information:* (post the output of `import pennylane as qml; qml.about()`)
Name: PennyLane
Version: 0.11.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: c:\programdata\anaconda3\lib\site-packages
Requires: numpy, appdirs, toml, scipy, autograd, networkx, semantic-version
Required-by: 
Platform info:           Windows-10-10.0.17763-SP0
Python version:          3.7.6
Numpy version:           1.19.1
Scipy version:           1.4.1
Installed devices:
- default.gaussian (PennyLane-0.11.0)
- default.qubit (PennyLane-0.11.0)
- default.qubit.autograd (PennyLane-0.11.0)
- default.qubit.tf (PennyLane-0.11.0)
- default.tensor (PennyLane-0.11.0)
- default.tensor.tf (PennyLane-0.11.0)

#### Source code and tracebacks
**Code:**
import pennylane as qml
from pennylane import numpy as np
from pennylane.templates.embeddings import BasisEmbedding

data = np.array([1, 0, 1])
dev = qml.device('default.qubit', wires=3)

@qml.qnode(dev)
def circuit(data):
    BasisEmbedding(features=data, wires=range(3))
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1)), qml.expval(qml.PauliZ(2))

circuit(data)

**Traceback:**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-280c921d4aff> in <module>
----> 1 circuit(data)

C:\ProgramData\Anaconda3\lib\site-packages\pennylane\interfaces\autograd.py in __call__(self, *args, **kwargs)
     67             self.set_trainable(args)
     68             args = autograd.builtins.tuple(args)  # pylint: disable=no-member
---> 69             return self.evaluate(args, kwargs)
     70 
     71         @staticmethod

C:\ProgramData\Anaconda3\lib\site-packages\autograd\tracer.py in f_wrapped(*args, **kwargs)
     46             return new_box(ans, trace, node)
     47         else:
---> 48             return f_raw(*args, **kwargs)
     49     f_wrapped.fun = f_raw
     50     f_wrapped._is_autograd_primitive = True

C:\ProgramData\Anaconda3\lib\site-packages\pennylane\qnodes\base.py in evaluate(self, args, kwargs)
    819 
    820         if self.circuit is None or self.mutable:
--> 821             self._construct(args, kwargs)
    822 
    823         self.device.reset()

C:\ProgramData\Anaconda3\lib\site-packages\pennylane\qnodes\jacobian.py in _construct(self, args, kwargs)
     88         for each positional parameter.
     89         """
---> 90         super()._construct(args, kwargs)
     91         self.par_to_grad_method = {k: self._best_method(k) for k in self.variable_deps}
     92 

C:\ProgramData\Anaconda3\lib\site-packages\pennylane\qnodes\base.py in _construct(self, args, kwargs)
    564                     # it's ok to directly pass auxiliary arguments since the circuit is re-constructed each time
    565                     # (positional args must be replaced because parameter-shift differentiation requires Variables)
--> 566                     res = self.func(*self.arg_vars, **kwargs)
    567                 else:
    568                     # TODO: Maybe we should only convert the kwarg_vars that were actually given

<ipython-input-26-75ce97e7bbad> in circuit(data)
      6 @qml.qnode(dev)
      7 def circuit(data):
----> 8     BasisEmbedding(features=data, wires=range(3))
      9     return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1)), qml.expval(qml.PauliZ(2))

C:\ProgramData\Anaconda3\lib\site-packages\pennylane\templates\decorator.py in wrapper(*args, **kwargs)
     59     def wrapper(*args, **kwargs):
     60         with OperationRecorder() as rec:
---> 61             func(*args, **kwargs)
     62 
     63         return rec.queue

C:\ProgramData\Anaconda3\lib\site-packages\pennylane\templates\embeddings\basis.py in BasisEmbedding(features, wires)
     63 
     64     if any([b not in [0, 1] for b in features]):
---> 65         raise ValueError("'basis_state' must only consist of 0s and 1s; got {}".format(features))
     66 
     67     ###############

ValueError: 'basis_state' must only consist of 0s and 1s; got [<Variable(data[0]:0)> <Variable(data[1]:1)> <Variable(data[2]:2)>]

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by trbromley** [comment]
Hi @Zed-Is-Dead, thanks for sharing!

This error occurs because PennyLane is treating the `data` array as differentiable and replacing its contents with PennyLane's internal `Variable` object. For `BasisEmbedding`, however, the input features cannot be differentiated (they should be a simple binary vector).

One way to fix the above is to set `data = np.array([1, 0, 1], requires_grad=False)`. You could also check out the [relevant section](https://pennylane.readthedocs.io/en/stable/introduction/interfaces/numpy.html#differentiable-and-non-differentiable-arguments) of the documentation for more details.

We appreciate that this can be confusing and are actually working on a new (experimental) core that would mean your above code does not raise an error. You can check it out [here](https://pennylane.readthedocs.io/en/latest/code/qml_tape.html) (requires the `master` branch version of PennyLane).

**Comment by Zed-Is-Dead** [comment]
Hi,
Thank you for your quick reply. I was indeed confused because I saw the very code I was using in a webinar a few days ago and it worked fine...
