### ISSUE TITLE
Add the sqrt X gate to PennyLane

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#868]
It would be convenient to have access to the [the SqrtX gate](https://en.wikipedia.org/wiki/Quantum_logic_gate#Square_root_of_NOT_gate_(%E2%88%9ANOT)) in PennyLane. This could be represented by either  `qml.SX` or `qml.SqrtX`.

To add support for this gate to PennyLane, the following should be added/modified:

1. A new `SX` operation should be added to `pennylane/ops/qubit.py`. Matrix and eigenvalues should be defined, alongside a decomposition if possible. The operation should also be listed in the `ops` set at the bottom of the module.

2. The new operation should be added to the documentation page `doc/introduction/operations.rst`.

2. Native support for this gate should be added to our reference simulator, `default.qubit` in `pennylane/devices/default_qubit.py`.

4. Finally, a test should be added in `pennylane/devices/tests/test_gates.py`, to ensure that it is correctly applied and results in the correct output probability distribution.

**Comment by albi3ro** [comment]
Can I have this issue assigned to me? 

I have chosen this issue for my interview technical assessment.

**Comment by josh146** [comment]
@albi3ro done!

**Comment by albi3ro** [comment]
quick question about decompositions.

Do we need to specify the global phase on them?

Specifically, the `SX` gate is `RX(np.pi/2)` up to a phase of  exp(i pi/4) .

**Comment by josh146** [comment]
Hey @albi3ro - we don't currently have a way of specifying the global phase, however, I believe you should be able to construct the `SX` gate directly via the form `PhaseShift(theta) @ Rot(a, b, c)`, although I haven't calculated the parameters myself!

**Comment by josh146** [comment]
The combination `PhaseShift() @ Rot()` produces a universal single qubit gate (equivalent to the U3 gate, but better supported across hardware)
