### ISSUE TITLE
Inverses in default_qubit

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#870]
Several operations have hard coded implementations instead of simply using their unitary matrix.  These are specified at [default_qubit.py Line 130](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L130) such as `"PauliX"` or `"CNOT"`.  

These hard-coded functions like  [`dev._apply_phase`](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L328) can take in a boolean for the keyword `inverse` and apply the inverse operation instead.

**BUT** [`dev._apply_operation`](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L163) always sends inverse operations to the more general path using `dev._get_unitary_matrix` followed by something like `dev._apply_unitary`.

This happens because inverse operations have `.inv` appended to their name.  Thus the new name is no longer in the `dev._apply_ops` dictionary.

This can easily be fixed by changing `operation.name` to `operation.base_name` at [Line 179](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L179) and [Line 181](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L181)

**Comment by trbromley** [comment]
Thanks @albi3ro for the detailed report! I will take a look at this over the next few days.
