### ISSUE TITLE
Add the controlled U3 gate to PennyLane 

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#885]
It would be convenient to have access to the [controlled version](https://en.wikipedia.org/wiki/Quantum_logic_gate#Controlled_(cX_cY_cZ)_gates) of the [U3 gate](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.U3.html?highlight=u3#pennylane.U3) in PennyLane. This could be represented for example by `qml.CU3`.

To add support for this gate to PennyLane, the following should be added/modified:

1. A new `CU3` operation should be added to `pennylane/ops/qubit.py`. Matrix and eigenvalues should be defined, alongside a decomposition if possible. The operation should also be listed in the `ops` set at the bottom of the module.

2. The new operation should be added to the documentation page `doc/introduction/operations.rst`.

2. Native support for this gate should be added to our reference simulator, `default.qubit` in `pennylane/devices/default_qubit.py`.

4. Finally, a test should be added in `pennylane/devices/tests/test_gates.py`, to ensure that it is correctly applied and results in the correct output probability distribution.

**Comment by tehruhn** [comment]
Hi @antalszava ,

Could I have this be assigned to me?

**Comment by antalszava** [comment]
Hi @tehruhn, sure thing!

**Comment by tehruhn** [comment]
Regarding decomposition : 

I broke down the `CU3` gate into consecutive alternating `U3` and `CNOT` gates. Is that fundamental/ granular enough for our decomposition?

**Comment by josh146** [comment]
Hi @tehruhn, decomposing into U3 and CNOT should be fine 🙂 However, the main gate set in PennyLane for arbitrary single qubit rotations are the PhaseShift and Rot gates, so that would be even better!

**Comment by tehruhn** [comment]
Ah okay, will decompose further then!

**Comment by tehruhn** [comment]
Updates so far :

- Added a `CU3` class, added the matrix and decomposition, and added a test to check for correctness of decomposition.
- Updated documentation.
- Built docs and ran tests locally.

**Comment by antalszava** [comment]
Hi @tehruhn, that sounds great, seems like you're on track :slightly_smiling_face: Let us know if you'd like us to review it as a whole

**Comment by tehruhn** [comment]
Sure, will tag you in the PR when I'm done! I'm left with implementing the `_apply_CU3` method in the `default_qubit` device. Will open a PR after that.
