### ISSUE TITLE
Add generators to some operations

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#895]
PennyLane operations have a [generator](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.operation.Operation.html#pennylane.operation.Operation.generator) attribute, originally added in https://github.com/PennyLaneAI/pennylane/pull/295. This attribute contains the Hamiltonian used to generate the unitary gate. The use case for this attribute is the [QNGOptimizer](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.QNGOptimizer.html), which accesses the generator to construct the metric tensor.

However, some commonly-used gates in PennyLane do not yet have their generator defined. These include:
- [ ] `Rot`
- [x] `MultiRZ` (added in https://github.com/PennyLaneAI/pennylane/pull/912)
- [x] `PauliRot` (added in https://github.com/PennyLaneAI/pennylane/pull/963)
- [ ] `CRot`

Without a generator defined, these gates cannot be used within circuits with the QNG optimizer. This is a blocker for use of [StronglyEntanglingLayers](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.StronglyEntanglingLayers.html), which have `Rot` gates contained within.

This issue requests addition of generators for the above gates.

Update: `MultiRZ` and `PauliRot` have had their generators added. This leaves `Rot` and `CRot`, but it is not clear how to proceed since these gates are multiparameter gates, and perhaps best thought of as a composition of ZYZ rotations.

**Comment by JiahaoYao** [comment]
I find these gates all have its params `phi, theta, omega`, say for CRot. Then, how to define the generator for multi-variables?

**Comment by trbromley** [comment]
Hi @JiahaoYao, good point that `Rot` and `CRot` have multiple parameters. Maybe we could start with `MultiRZ` and `PauliRot`, which each have one differentiable parameter.

**Comment by josh146** [comment]
This is a good point though. I wonder the best way to generalize the generator logic to multi-parameter gates

**Comment by JiahaoYao** [comment]
Thanks for the merge, and what is the plan for other generators?

**Comment by trbromley** [comment]
Thanks @JiahaoYao for the PR! I've updated the description of this issue to highlight the remaining gates requiring a generator.
