### ISSUE TITLE
Error for pennylane.numpy.tensor with plugin devices using non-differentiable syntax

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#900]
#### Issue description
When a `pennylane.numpy.tensor` is passed to a QNode as a keyword argument, it is considered as a non-differentiable parameter. Unlike in the case when it is handled as a differentiable parameter, it is not cast into a `ndarray`.

When indexing into a `pennylane.numpy.tensor`, one can end up having a single element sequence. Certain devices (e.g., `qiskit.aer`, `forest.wavefunction`), are not capable of supporting the application of a gate taking this type of argument and raise an error. Gates can take such a `pennylane.numpy.tensor` as gate parameter, when passed as a non-differentiable parameter.

```python
import pennylane as qml
from pennylane.numpy import tensor

dev = qml.device("qiskit.aer", wires=4)

@qml.qnode(dev)
def circuit(phi=None):
    for y in phi:
        for idx, x in enumerate(y):
            qml.RX(x, wires=idx)
    return qml.expval(qml.PauliZ(0))

phi = tensor([[0.04439891, 0.14490549, 3.29725643, 2.51240058]])

circuit(phi=phi)
```

A special case using `RandomLayers` was tackled in PR #893. This is an example that is used in the  [Quanvolutional Neural Networks](https://pennylane.ai/qml/demos/tutorial_quanvolution.html) demonstration.

* *Expected behavior:*
The above snippet executes without errors.

* *Actual behavior:*
Error is raised (Qiskit case):
```
~/anaconda3/lib/python3.7/site-packages/qiskit/providers/aer/backends/backend_utils.py in cpp_execute(controller, qobj)
     49     qobj_dict['config']['library_dir'] = LIBRARY_DIR
     50 
---> 51     return controller(qobj_dict)
     52 
     53 

RuntimeError: Invalid number of dimensions!
```
Further errors may arise for other devices (see https://github.com/PennyLaneAI/pennylane/pull/893#issuecomment-726153779 for error messages that were thrown when using `RandomLayers`).

* *Reproduces how often:* (What percentage of the time does it reproduce?)
For certain plugin devices, each time a `pennylane.numpy.tensor` type sequence is passed as a gate parameter during execution.

* *System information:*

```
Name: PennyLane
Version: 0.13.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location:
Requires: numpy, scipy, networkx, autograd, toml, appdirs, semantic-version
Required-by: PennyLane-SF, PennyLane-Qchem, PennyLane-Forest, PennyLane-qsharp, pennylane-qulacs, PennyLane-lightning, PennyLane-qiskit, PennyLane-AQT, PennyLane-Cirq
Platform info:           Linux-4.19.11-041911-generic-x86_64-with-debian-buster-sid
Python version:          3.7.6
Numpy version:           1.18.5
Scipy version:           1.4.1
Installed devices:
- strawberryfields.fock (PennyLane-SF-0.12.0)
- strawberryfields.gaussian (PennyLane-SF-0.12.0)
- strawberryfields.gbs (PennyLane-SF-0.12.0)
- strawberryfields.remote (PennyLane-SF-0.12.0)
- strawberryfields.tf (PennyLane-SF-0.12.0)
- forest.numpy_wavefunction (PennyLane-Forest-0.13.0.dev0)
- forest.qpu (PennyLane-Forest-0.13.0.dev0)
- forest.qvm (PennyLane-Forest-0.13.0.dev0)
- forest.wavefunction (PennyLane-Forest-0.13.0.dev0)
- microsoft.QuantumSimulator (PennyLane-qsharp-0.9.0.dev0)
- qulacs.simulator (pennylane-qulacs-0.12.0.dev0)
- lightning.qubit (PennyLane-lightning-0.10.0.dev0)
- qiskit.aer (PennyLane-qiskit-0.13.0.dev0)
- qiskit.basicaer (PennyLane-qiskit-0.13.0.dev0)
- qiskit.ibmq (PennyLane-qiskit-0.13.0.dev0)
- default.gaussian (PennyLane-0.13.0.dev0)
- default.mixed (PennyLane-0.13.0.dev0)
- default.qubit (PennyLane-0.13.0.dev0)
- default.qubit.autograd (PennyLane-0.13.0.dev0)
- default.qubit.tf (PennyLane-0.13.0.dev0)
- default.tensor (PennyLane-0.13.0.dev0)
- default.tensor.tf (PennyLane-0.13.0.dev0)
- aqt.noisy_sim (PennyLane-AQT-0.10.0.dev0)
- aqt.sim (PennyLane-AQT-0.10.0.dev0)
- cirq.mixedsimulator (PennyLane-Cirq-0.12.0.dev0)
- cirq.simulator (PennyLane-Cirq-0.12.0.dev0)
```

#### Additional information

A solution could be to create a case for `pennylane.numpy.tensor` type sequence parameters in each plugin device implementation (see https://github.com/PennyLaneAI/pennylane/pull/893#issuecomment-725935113 containing a suggestion).

Seems that this problem does not arise in tape mode.

**Comment by josh146** [comment]
Thanks for catching this @antalszava @mariaschuld.

I think this is a result of the old + new QNode variable marking system clashing.

* Keyword arguments being non-differentiable is only assumed in the old core; PennyLane NumPy tensors are passed as-is to the device if passed as a keyword argument.

* In tape mode, however, positional vs. keyword arg makes no difference. Any argument can be differentiable, if marked as so.

As a result, when tape-mode is default this issue should disappear. However, in the meantime, I suggest we add

```python
if isinstance(x, qml.numpy.tensor) and x.ndim == 0:
    x = x.unwrap()
```

either to the (old) autograd interface, the (old) `BaseQNode`, or `QubitDevice`, depending on which one makes more sense; this way we don't have to update all plugins.

My gut feeling is that it makes more sense to fix this in `BaseQNode`, since it will be deleted anyway when tape mode is default.
