### ISSUE TITLE
Add support for calculating the Hessian

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#948]
In tape-mode, the new core of PennyLane, quantum circuits are represented by `QuantumTape` objects. Furthermore, the *gradient* of quantum tapes can be computed via the parameter-shift rule:

```
∂f(x) = [f(x+s) - f(x-s)] / (2 sin(s))
```

That is, the tape is executed twice, with shifted values, and the gradient is a linear combination of the evaluated shifted tapes.

The parameter-shift method is available [here](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/tape/tapes/qubit_param_shift.py#L124), and has the following general form:

```python
  def gradient_method(idx, param, **options):
      # generate the quantum tapes that must be computed
      # to determine the quantum gradient
      tapes = quantum_gradient_tapes(self)

      def processing_fn(results):
          # perform classical processing on the evaluated tapes
          # returning the evaluated quantum gradient
          return classical_processing(results)

      return tapes, processing_fn
  ```

where `processing_fn(results)` processes the results of the evaluated tapes, e.g., applying the required linear combination.

In the recently released https://arxiv.org/abs/2008.06517, a formula is given for computing the _hessian_ on quantum hardware (eqns 11 - 13). It would be great to add a `QubitParamShift.hessian(i, j, params, **options)` method that returns the second derivative with respect to tape parameters `i` and `j` using this second-order shift formula.

**Comment by alejomonbar** [comment]
Can I try this one? @josh146

**Comment by co9olguy** [comment]
@alejomonbar Thanks for offering! For this particular issue, we had already discussed with @soudy to tackle it (you can see the PR came in today), so unfortunately it's already spoken for :smile:. If you're eager to contribute, we can set up a dedicated discussion to see what issues (possibly not yet listed on our github repo) you might be most interested in. Let us know!

**Comment by alejomonbar** [comment]
> @alejomonbar Thanks for offering! For this particular issue, we had already discussed with @soudy to tackle it (you can see the PR came in today), so unfortunately it's already spoken for 😄. If you're eager to contribute, we can set up a dedicated discussion to see what issues (possibly not yet listed on our github repo) you might be most interested in. Let us know!

Sure, I'd like to see what else is open for me to work. So let me know how we can set that discussion. Thank you!

**Comment by co9olguy** [comment]
@alejomonbar How about this issue? https://github.com/PennyLaneAI/pennylane/issues/958

We might need to update the issue comment based on the subsequent discussion below it, but the basic idea is to allow support for more stochastic versions of existing gradient estimators

**Comment by josh146** [comment]
I've just updated the issue comment in #958 to provide more info :)

**Comment by alejomonbar** [comment]
> @alejomonbar How about this issue? #958
> 
> We might need to update the issue comment based on the subsequent discussion below it, but the basic idea is to allow support for more stochastic versions of existing gradient estimators

Sure! I'll take a look at this. Thank you.
