### ISSUE TITLE
Allow tape.jacobian to estimate the jacobian by computing the gradients of a subset of parameters chosen stochastically

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#958]
Currently, in PennyLane, the `tape.jacobian` method will loop over all parameters in the circuit to construct the Jacobian. If utilizing the parameter-shift rule method of differentiation, for example, this will execute the variational circuit `2*num_parameter` times in order to compute the gradient.

However, a recent result by [Ryan Sweke et al. (2019)](https://arxiv.org/abs/1910.01155) showed that you can randomly sample the parameters to shift at each optimization step. Even in the extreme case where only one parameter is shifted per step, gradient descent convergence remains guaranteed.

This would be a nice feature to add to PennyLane. This could be done as follows:

* Allow a new keyword argument option to be passed to `JacobianTape.jacobian`, for example `k_params` (this is just a placeholder name, final name to be determined).

* Then, modify the internal for loop over all parameters,

  ```python
  for trainable_idx, param_method in enumerate(diff_methods):
  ```

  so that gradient rules are generated by randomly sampling only the specified number of parameters, *if the new keyword argument is provided*:

  ```python
  k_params = options.get("k_params", None)

  params_and_methods = enumerate(diff_methods)
  if stochastic_params is not None:
      params_and_methods = set(random.choices(list(enumerate(diff_methods)), k=k_params))
  
  for trainable_idx, param_method in params_and_methods:
  ```

**Comment by co9olguy** [comment]
Not to be confused with the "Stochastic Parameter-shift Rule" of Banchi & Crooks? :thinking:

**Comment by josh146** [comment]
Yes, not to be confused! I was thinking about that while writing this issue. Is there a better name for this ‘stochastic’ parameter shift rule?

**Comment by co9olguy** [comment]
maybe have a "stochastic gradient" mixin that applies to finite diff, PSR, etc? i.e., the stochasticity is independent of the actual method?

**Comment by josh146** [comment]
Great idea! It wouldn't even need to be a mixin, we can just add support directly to the `tape.jacobian()` method, which is diff method agnostic.

**Comment by alejomonbar** [comment]
Hi @josh146,

Then, is it only adding the code that you provide above indicating that the number of k_params should be between 1 and the number of parameters? (like the code below)
```Python
        k_params = options.get("k_params", None)
        
        params_and_methods = enumerate(diff_methods)
        if k_params is not None:
            if not 1 <= k_params <= self.num_params:
                raise ValueError(f"The number of k_params: {k_params} is not between the range 1 and {self.num_params}")

            params_and_methods = set(random.choices(list(enumerate(diff_methods)), k=k_params))
            
        for trainable_idx, param_method in params_and_methods:
            if (method == "best" and param_method[0] == "F") or (method == "numeric"):
                # numeric method
                tapes, processing_fn = self.numeric_pd(trainable_idx, params=params, **options)

            elif (method == "best" and param_method[0] == "A") or (method == "analytic"):
                # analytic method
                tapes, processing_fn = self.analytic_pd(trainable_idx, params=params, **options)

            processing_fns.append(processing_fn)

            # we create a flat list here to feed at once to the device
            all_tapes.extend(tapes)

            # to extract the correct result for this parameter later, remember the number of tapes
            reshape_info.append(len(tapes))
```
I found a problem with this approach. It could select the following case for `param_method = '0'` which is the case for the param ` qml.RX(0.133, wires='a')`. Therefore, neither the case (method == "best" and param_method[0] == "F")  or (method == "best" and param_method[0] == "A") is selected.

```Python
import pennylane as qml
import pennylane.tape

qml.enable_tape()
dev = qml.device("default.qubit", wires=[0,'a'])

with qml.tape.JacobianTape() as tape:
    qml.RX(0.432, wires=0)
    qml.RY(0.543, wires=0)
    qml.RX(0.133, wires=0)
    qml.CNOT(wires=[0,'a'])
    qml.RX(0.133, wires='a')
    qml.expval(qml.PauliZ(wires=[0]))

opt = {'k_params':1}
tape.jacobian(dev, **opt)

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-15-ae622e5dc974> in <module>
      1 opt = {'k_params':1}
      2 # tape.trainable_params = {3}
----> 3 tape.jacobian(dev, **opt)

~/pennylane/pennylane/tape/tapes/jacobian_tape.py in jacobian(self, device, params, **options)
    517                 tapes, processing_fn = self.analytic_pd(trainable_idx, params=params, **options)
    518 
--> 519             processing_fns.append(processing_fn)
    520 
    521             # we create a flat list here to feed at once to the device

UnboundLocalError: local variable 'processing_fn' referenced before assignment
```

**Comment by josh146** [comment]
Hi @alejomonbar! Would the following continue statement (I believe in the `master` branch) fix this?

```python
        for trainable_idx, param_method in params_and_methods:
            if param_method == "0":
                continue
```
