### ISSUE TITLE
Add support of more noise channels present to pennylane

### ISSUE THREAD

**Issue by hrushikesh890** [PennyLaneAI/pennylane#971]
#### Issue description

Description of the issue - Currently pennylane supports only following noise channels 

AmplitudeDamping 
GeneralizedAmplitudeDamping 
PhaseDamping
DepolarizingChannel
QubitChannel.

While using these channels variety of other noise channels can be created, however for the user it would be more convenient if there is direct support for Thermal relaxation error, pauli error, readout error and reset error in pennylane. Such noisy simulations are supported in qiskit and will be valuable to have it in pennylane

* *Expected behavior:* (What you expect to happen) APIs able to simulate thermal relaxation error, pauli error, readout error and reset error.

**Comment by co9olguy** [comment]
Thanks for the feature request @hrushikesh890! We will add it to our to-do list. 

If you're so-inclined, adding new noise channels is actually a relatively straightforward task that might be a good task for a new contributor. Let us know if you might be interested in contributing to the library in this way :smile:

**Comment by hrushikesh890** [comment]
@co9olguy  Hi, 
I am very much willing to contribute to pennylane. Me and @yulunwang (Teammate of mine in our research group) are looking to contribute to pennylane as we use it a lot in our research. If possible we would like to try our hands at this task.

**Comment by co9olguy** [comment]
Awesome :tada:, glad to hear that @hrushikesh890!

If you want a particular contribution to start with, as I said, this particular issue is actually a really good one, and would be a valued addition. Feel free to also browse other issues for the `good first issue` tag. 

Note that the PennyLane dev team will be taking a bit of a holiday to end the year, so if you want/need our feedback or advice, you might have to wait until we're back in the office in early Jan :smiley:

**Comment by ixfoduap** [comment]
Hi @hrushikesh890,

This is awesome! I'm the PennyLane developer that has been championing noisy simulations and quantum channels. Adding new noisy channels is relatively straightforward once you know its Kraus operators. Testing is a bit trickier, but you can just follow what has been done in previous cases. Finally, if all the Kraus operators are themselves valid channels, e.g., they are unitaries up to rescaling, then we know how construct analytical gradients. 

Please let me know of any way that I can help!

Best,

Juan Miguel

**Comment by alejomonbar** [comment]
is someone working on this or can I try it? @josh146 @ixfoduap @antalszava

**Comment by meenu-kri** [comment]
Regarding adding readout error to pennylane, I am wondering what would be the best way to add it. As far as I understand, simulating the readout error in measurement is like applying a BitFlip channel (with a nonzero probability) to the quantum state just before reading out the diagonal entries of the density matrix corresponding to the quantum state for the required probabilities. If expectation value of any observable needs to be calculated, then the BitFlip channel (for the readout error) should be applied after applying diagonalizing_gates (corresponding to the observable) to the quantum state. 

Application of BitFlip channel can be simulated on the mixed device and not on the qubit device I think. Ideally, it would have been good to have readout error as an attribute to measurements. Nonetheless, since it can be simulated on the mixed device only, it makes sense to add it as an attribute to the mixed device currently. Any thoughts?

**Comment by antalszava** [comment]
Hi @meenu-kri,

> Nonetheless, since it can be simulated on the qml.devices.default_mixed only, it makes sense to add it as an attribute to the qml.devices.default_mixed currently. 

Agreed! :slightly_smiling_face: 

Posting steps from our chat just now:
1. Updating the `DefaultMixed.__init__` method:

Could be done, for example, by introducing a new `readout_prob` argument (or one with comparable name) and using it to store the readout error probability as an attribute:
```py
    def __init__(
        self, wires, *, r_dtype=np.float64, c_dtype=np.complex128, shots=None, analytic=None, readout_prob=None
    ):
        if isinstance(wires, int) and wires > 23:
            raise ValueError(
                "This device does not currently support computations on more than 23 wires"
            )

        # call QubitDevice init
        super().__init__(wires, shots, r_dtype=r_dtype, c_dtype=c_dtype, analytic=analytic)
        self._debugger = None

        # Create the initial state.
        self._state = self._create_basis_state(0)
        self._pre_rotated_state = self._state

        # TODO: check that if readout_prob is not None, then it is float and between 0 and 1
        self.readout_err = readout_prob
```
Note that if the user doesn't explicitly pass in `readout_prob` on the device creation, then no readout error is added to the simulation.
2. Inserting the following snippet into the `DefaultMixed.apply` method:
```py
        if self.readout_err:
            bitflips = [qml.BitFlip(self.readout_err,wires=k) for k in self.num_wires]
            for bf in bitflips:
                self._apply_operation(bf)
```

**Comment by meenu-kri** [comment]
Hi @antalszava,

Thanks for the response 🙂. It's quite helpful. 

I made the changes we talked about in `default_mixed.py`. I have also written tests in `test_default_mixed.py`. Link to the PR https://github.com/PennyLaneAI/pennylane/pull/2786 that I have created with these changes.

**Comment by antalszava** [comment]
With #2786 merged, we have added all 4 originally mentioned noise channel types mentioned (Thermal relaxation error, pauli error, readout error and reset error).
