### ISSUE TITLE
Improve efficiency of `Wires.map` (and `Wires` overall)

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#975]
**Context**

The Wires class produces relevant overhead (see for example #967). Here I'd like to consider the class method `Wires.map` which allows for mapping existing `Wires` to new ones via a dictionary. I also make a comment addressing the `Wires` class on a higher level at _Generalization_ 

**Concrete Issue / Example**

As an example, calling `Wires.map` on a dictionary of N one-to-one identifications of single wires in the Wires instance, e.g.
```
wires = Wires(range(N))
wires.map( {i : str(i) for i in range(N)} )
```
will lead to 3N new instances of single-entry `Wires` (and the desired new instance of an N-entry `Wires`):
- 2N in `wire_map = {Wires(k): Wires(v) for k, v in wire_map.items()}`
- N in `for w in self` because `__iter__` calls `__getitem__` N times, which in turn creates a one-wire instance of `Wires`.

**Discussion / Solution Attempt**

It is not entirely clear to me why the `Wires` class has the structure it does and would have general questions on design choices of this class/concept throughout pennylane. Therefore I am not sure what would be the best fix to reduce the overhead, because my intuitive reaction is to change the overall structure of `Wires`. 
One quick fix addressing the scenarios where the dictionary already contains `Wires` instances would be to replace 
```python
wire_map = {Wires(k): Wires(v) for k, v in wire_map.items()}
```
by
```python
for k, v in wire_map.items():
    if not isinstance(k, Wires):
        k = Wires(k)
    if not isinstance(v, Wires):
        v = Wires(v)
    wire_map[k] = v
```
This is not a very elegant solution and does not give improvement (but actually slows down) in the scenario when none of the `wire_map` keys and values are `Wires` already.

**Generalization**
The overhead of `Wires` seems to me to be due to the switching back and forth between `Wires.labels`, `Wires` instances and the various allowed input types to create `Wires`. 
One possibility of making the class more efficient could be to subclass `dict` and use corresponding methods, the details of this are a bit of work I think.

**Comment by dwierichs** [comment]
I will make an attempt to use built-in dictionary methods and if successful create a PR.

**Comment by mariaschuld** [comment]
Thanks @dwierichs, this is an important issue! Just a comment about the solution with subclassing built-in dictionaries, one needs to make sure that the wires remain ordered (so you may want to look at `OrderedDict`).

To assess the best way forward, it would be useful to systematically profile the slowdown from creating instances of the wires class. If most of this slowdown happens from one workflow only, we may be better off just changing that workflow. 

Am happy to help with this after the Christmas break!

**Comment by dwierichs** [comment]
Thanks, that's a good point! 
Yes, I agree that it's a good idea to profile the workflow in more detail, will certainly do so to understand the overall issue.

**Comment by mariaschuld** [comment]
@dwierichs this is not solved by #983, right? I have a prototype of making the wire map (and then the device) only use labels, but this may require refactoring devices. I propose we tackle this if there is another necessary breaking change for devices...

**Comment by dwierichs** [comment]
I think the original intention of this issue is covered by #983 because we got rid of the recasting of the dictionary into new Wires instances. However, the general logic flow of when and therefore how often mappings of wires are invoked is still to be improved, I agree. I'm excited to see progress on this, let me know if you want to share your work on the labels-only approach!
One could make a new issue that makes this change more concrete than "Imporve Wires overall"...

**Comment by mariaschuld** [comment]
Cool, let me close this and open another one and maybe a PR. 

The reason why I didn't push the prototype is that I didn't see any speedup from it, but that is still puzzling me!
