### ISSUE TITLE
Test suite refactor

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#99]
**Suggestion**

We should move away from this sort of testing style, where we loop over all imported objects, and use branches to overwrite attributes:
```python
# wrong parameter types
if cls.par_domain == 'A':
    # params must be arrays
    with self.assertRaisesRegex(TypeError, 'Array parameter expected'):
        cls(*n*[0.0], wires=ww, do_queue=False)
    # params must not be Variables
    with self.assertRaisesRegex(TypeError, 'Array parameter expected'):
        cls(*n*[ov.Variable(0)], wires=ww, do_queue=False)
elif cls.par_domain == 'N':
    # params must be natural numbers
    with self.assertRaisesRegex(TypeError, 'Natural number'):
        cls(*n*[0.7], wires=ww, do_queue=False)
    with self.assertRaisesRegex(TypeError, 'Natural number'):
        cls(*n*[-1], wires=ww, do_queue=False)
elif cls.par_domain == 'R':
    # params must be real numbers
    with self.assertRaisesRegex(TypeError, 'Real scalar parameter expected'):
        cls(*n*[1j], wires=ww, do_queue=False)

# exception if par_domain ever gets overridden to an unsupported value
tmp = cls.par_domain
with self.assertRaisesRegex(ValueError, 'Unknown parameter domain'):
    cls.par_domain = 'junk'
    cls(*n*[0.0], wires=ww, do_queue=False)
    cls.par_domain = 7
    cls(*n*[0.0], wires=ww, do_queue=False)

cls.par_domain = tmp
```

and move towards this style of test (ignore the actual content), where there are no loops, and everything is as minimal and as explicit as possible:
```python
def test_incorrect_num_wires(self):
    """Test that an exception is raised if called with wrong number of wires"""

    class DummyOp(oo.Operation):
        r"""Dummy custom operation"""
        num_wires = 1
        num_params = 1
        par_domain = 'R'
        grad_method = 'A'

    with self.assertRaisesRegex(ValueError, "wrong number of wires"):
        DummyOp(0.5, wires=[0, 1], do_queue=False)

def test_incorrect_num_params(self):
    """Test that an exception is raised if called with wrong number of parameters"""

    class DummyOp(oo.Operation):
        r"""Dummy custom operation"""
        num_wires = 1
        num_params = 1
        par_domain = 'R'
        grad_method = 'A'

    with self.assertRaisesRegex(ValueError, "wrong number of parameters"):
        DummyOp(0.5, 0.6, wires=0, do_queue=False)
```

While it removes some of the 'automation' from the test-suite, this is a good thing imo:
* It makes the test suite much more readable and maintainable
* When a failure occurs, it is **MUCH** easier to determine exactly where, as each test method contains (at most) 2-3 *explicit* assert statements.
* It forces you to create a new test when a new object/feature is added, rather than hoping it gets caught by an existing loop
* Currently, if a new feature/object breaks the existing 'loop' structure of the test, it is difficult and time-consuming to fix

**Comment by josh146** [comment]
A quick update. We should aim for the following:

* Replace unittest with pytest, which is much more flexible, more maintained, and the preferred python testing tool

* Each test is a single function, which is explicit and only tests a single thing, no loops.

* For tests that do need to be parameterized, the pytest parameterize decorator is used.

For an example of what I consider a clearer and more explicit test suite, see the Hafnian++ tests:

https://github.com/XanaduAI/hafnian/blob/hafnian%2B%2B/hafnian/tests/test_hafnian.py

**Comment by quantshah** [comment]
Hi, I am trying to re-write some of the tests with pytest and numpy testing. Is there a reason why we should not be using things such as `numpy.testing.assert_array_almost_equal` ? E.g.,

This runs with any test module and independently as a python file too. The `BaseTest`class is also implementing this check with loop and `np.all` anyways in this [line](https://github.com/XanaduAI/pennylane/blob/master/tests/defaults.py#L61)
```
from pennylane.ops import cv

import numpy as np
from numpy.testing import assert_array_almost_equal, assert_
from numpy.testing import run_module_suite


def test_rotation_heisenberg():
    """
    ops: Tests the Heisenberg representation of the Rotation gate.
    """
    phis = np.linspace(-2 * np.pi, 2 * np.pi, 11)
    for phi in phis:
        matrix = cv.Rotation._heisenberg_rep([phi])
        true_matrix = np.array([[1, 0, 0],
                                [0, np.cos(phi), -np.sin(phi)],
                                [0, np.sin(phi), np.cos(phi)]])
        assert_array_almost_equal(matrix, true_matrix)


class TestNonGaussian(object):
    """Tests that non-Gaussian gates are properly handled."""
    def test_heisenberg_rep_nonguassian(self):
        """
        op: Tests that the `_heisenberg_rep` for a non-Gaussian gates is None
        """
        nongaussian_gates = [cv.Kerr, cv.CrossKerr, cv.CubicPhase]
        for op in nongaussian_gates:
            assert_(op._heisenberg_rep(*[0.1] * op.num_params) is None)


if __name__ == '__main__':
    run_module_suite()
```

**Comment by josh146** [comment]
We have been slowing porting over the Strawberry Fields tests to pytest, see https://github.com/XanaduAI/strawberryfields/tree/master/strawberryfields/backends/fockbackend/tests for some examples.

Since pytest enforces the idea that tests functions should be short, clear, and simply use `assert` for testing, we have settled on the pattern of using `assert np.allclose(a, b, atol=tol)` to test arrays using floating point values (`allclose` is also mentioned as a preferred function to `assert_array_almost_equal` in the NumPy documentation).

For example, the following test in the ported `test_displacement_operation.py` file:
```python
@pytest.mark.parametrize("r", MAG_ALPHAS)
@pytest.mark.parametrize("p", PHASE_ALPHAS)
def test_normalized_displaced_state(self, setup_backend, r, p, tol):
    """Tests if a range of displaced states are normalized."""
    alpha = r*np.exp(1j*p)

    backend = setup_backend(1)
    backend.displacement(alpha, 0)
    state = backend.state()

    assert np.allclose(state.trace(), 1, atol=tol, rtol=0)
```

**Comment by quantshah** [comment]
This is great. I will continue with the refactoring then. I need to update my knowledge of pytest though. Seems pretty neat with the different decorators. 

Thanks.

**Comment by josh146** [comment]
Useful ones I've found so far:

* `@pytest.fixture` - fixtures are great!
* `@pytest.mark.parametrize` - for looping the same test with lots of different test data/parameters, without needing to create specific loops/duplicate the test
* `@pytest.skip("message")` to skip a certain test from within the test itself
* `@pytest.mark.skipif(condition, reason="message")` - to skip a test given a certain condition, i.e. wrong OS

**Comment by johannesjmeyer** [comment]
A note on the files that are still due to refactor:
* `test_default_gaussian.py`
* `test_default_qubit.py`
* `test_operation.py`
* `test_optimize.py`
* `test_quantum_gradients.py`

**Comment by co9olguy** [comment]
This is quite an old issue, but I feel like it is close to being closed. @josh146 What work is remaining here? Just removing the `for` loops in the tests that are mentioned above by @johannesjmeyer?

**Comment by josh146** [comment]
Yep! We could make it a new issue, and close this one.
