### ISSUE TITLE
Support broadcasting in KerasLayer and TorchLayer

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#991]
Following the discussion [here](https://discuss.pennylane.ai/t/broadcast-keras-layer-to-sequence/759), most layers in Keras support broadcasting, i.e.,
```python
import tensorflow as tf

x = tf.ones((5, 4, 4))

layer = tf.keras.layers.Dense(10)
out = layer(x)

print(out.shape)
```
The result is `(5, 4, 10)`. Here, the batch size is `5` and the dense layer converts from a size-`4` input to a size `10` output. However, the middle `4` is simply broadcasted over.

This is not possible using PennyLane's `KerasLayer`:
```python
import pennylane as qml

dev = qml.device("default.qubit", wires=4)

@qml.qnode(dev)
def layer(weights, inputs):
    qml.templates.AngleEmbedding(inputs, wires=range(4))
    qml.templates.StronglyEntanglingLayers(weights, wires=range(4))
    return [qml.expval(qml.PauliZ(i)) for i in range(4)]

qlayer = qml.qnn.KerasLayer(layer, {"weights": (4, 4, 3)}, output_dim=4)

qlayer(x)
```
The above results in an error.

This issue requests addition of this feature for `KerasLayer` and `TorchLayer`. Practically, this would require updating the `call()` method of `KerasLayer` and the `forward()` method of `TorchLayer`.

**Comment by DanielPolatajko** [comment]
Hi, I'm interested in contributing by tackling this issue, and I've written support for this feature on my fork. May I go ahead and submit a PR?

**Comment by co9olguy** [comment]
Thanks @DanielPolatajko, we'd love to have your contribution. Feel free to make a PR at your convenience :smiley:
