### ISSUE TITLE
[BUG] Differentiating QNodes with respect to a ragged array is not supported in tape mode

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#997]
Consider a variable `params = [np.ones(2), 0.5]` composed of differently-sized objects. Differentiating a QNode with respect to `params` is not supported in tape mode (but does work in non-tape mode):
```python
import pennylane as qml
from pennylane import numpy as np

# qml.enable_tape()  # uncommenting this line results in an error

dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def f(params):
    qml.Rot(*params[0], 0, wires=0)
    qml.RX(params[1], wires=0)
    return qml.expval(qml.PauliZ(0))

params = [np.ones(2), 0.5]

df = qml.grad(f)

df(params)
```
The error is `ValueError: array is not broadcastable to correct shape`.

**Comment by josh146** [comment]
@trbromley I might close this issue for now, as we made the decision not to support ragged input arrays for differentiation going forward.
